### ISSUE TITLE
Wrong Currency on Reports

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#10182]
OpenCart v3.0.3.8

Sales reports show wrong currency on multi currency (USD, EUR,...) stores.

How to reproduce?
1. Set multi stores with different currencies
2. Add order on first store with example USD currency
3. Add order on second store with EUR currency
4. Go in admin and select Reports
5. All sales reports show all values ONLY in CONFIG CURRENCY and not in correct one

**Comment by mathsolutions** [comment]
The indicated files do not exist probably you were referring to admin/controller/extension/report/sale_order.php and admin/model/extension/report/sale.php
Moreover when an order uses a currency different from the default one, values in the order_total table are stored in values converted to default currency. Ultimately the report reports correct values.

**Comment by Jawahar1994** [comment]
@mathsolutions Thanks, we will re-check the same and close this issue after verifying the same from our end

**Comment by prabhatkumaroc082** [comment]
@faca5 
You must have checked on the previous versions because there is no such issue with 3.0.3.8.

> 5\. All sales reports show all values ONLY in CONFIG CURRENCY and not in correct one

v3.0.3.8 is also working as per default currency but there is no such issue on calculation.

You can check the order table entry, it doesn't save converted price so there will not be any calculation issue.

Please check the latest version v3.0.3.8 and test.
