### ISSUE TITLE
The brand should be used instead of the manufacturer.

### ISSUE THREAD

**Issue by eturerer** [opencart/opencart#10200]
https://github.com/opencart/opencart/blob/07ab2d4e5fa2696fad0fe8b98f1dba7ee837dace/upload/admin/controller/catalog/manufacturer.php#L3

**Comment by stalker780** [comment]
Looks fine. Why do you think it must be brand here?

**Comment by TheCartpenter** [comment]
```A brand (brand name) may be name, term, symbol, design or any other combination that identifies a seller product. Manufacturer (or producer) brand is the brand which is owned by the manufacturer examples are LG and SONY.```

Source: Google .

**Comment by TheCartpenter** [comment]
In this scenario, perhaps the brands should be created as the groups of the manufacturers.

**Comment by eturerer** [comment]
Products are sold by brand. manufacturer can make contract manufacturing. The brand used by the manufacturer may be different. playstation and xbox these were the brand. manufacturer microsoft and sony. iPhone is the brand. iphone is brand Apple Inc. is the manufacturer.

**Comment by stalker780** [comment]
It's a historical feature of OC. Don't think anyone will rename controllers, tables, fields.
Just edit your language file if you want to see brands :)

**Comment by TheCartpenter** [comment]
The problem with this request is that, not only it's been requested before on this repository, but also because of the manufacturer ID that would loose its data relationship once the conventional names converted since tables cannot be renamed without removing the auto-incrementation from the PRI key and re-enable it without proper permissions from the hosts. Otherwise, tables needs to be created fresh but all manufacturer IDs, as auto-incremented values, may be unrelated afterwards.

Therefore, this commit can now be closed.

**Comment by danielkerr** [comment]
its not worth the change.
