### ISSUE TITLE
Wrong formatting in catalog/controller/product/compare.php

### ISSUE THREAD

**Issue by amaco596** [opencart/opencart#10213]
**What version of OpenCart are you reporting this for?**
3.0.3.8

**Describe the bug**
There is wrong formatting for product weight, length, width and height in:
catalog/controller/product/compare.php line 107 to 110.

The "format" function takes four parameters, where the last two are optional and default to "$decimal_point = '.'" and "$thousand_point = ','". While this is Ok for English language there are many languages that use "," for decimal point, so weight, length, width and height are not proper formatted when the last two parameters are omitted.

So, there should be:
'weight'       => $this->weight->format($product_info['weight'], $product_info['weight_class_id'], $this->language->get('decimal_point'), $this->language->get('thousand_point')), in line 107,

'length'       => $this->length->format($product_info['length'], $product_info['length_class_id'], $this->language->get('decimal_point'), $this->language->get('thousand_point')), in line 108,

'width'        => $this->length->format($product_info['width'], $product_info['length_class_id'], $this->language->get('decimal_point'), $this->language->get('thousand_point')), in line 109 and

'height'       => $this->length->format($product_info['height'], $product_info['length_class_id'], $this->language->get('decimal_point'), $this->language->get('thousand_point')), in line 110.

**Comment by amaco596** [comment]
There are more files where "format" function ($this->weight->format) is used with two parameters, which can lead to wrong formatting in other languages where the decimal point is ",":

catalog/controller/extension/feed/google_base.php
catalog/model/extension/shipping/fedex.php
catalog/model/extension/shipping/parcelforce_48.php
catalog/model/extension/shipping/royal_mail.php
catalog/model/extension/shipping/ups.php
catalog/model/extension/shipping/usps.php
catalog/model/extension/shipping/weight.php

**Comment by TheCartpenter** [comment]
@amaco596: Normally, language packages are handled by codes. Are you saying that even by using the same language codes, either decimal points and thousand points, may differ as opposed to the en-gb language code?

**Comment by amaco596** [comment]
@TheCartpenter, in Romanian for example the decimal point is "," whereas in English is ".". So if you don't provide the optional parameter "$decimal_point" to function "format" it will default to ".". When the length is formatted in a site in Romanian it will be for example 10.00 instead of 10,00, even though the $decimal_point variable in the language file is ",". So it's formatted wrong.

**Comment by TheCartpenter** [comment]
@amaco596: The problem is that even by adding the decimal points and the thousand points in the length class model in the OC admin, the store owner would still need to define each length class additionally along those that can be already selected from each admin products in order to know which class represent the decimal and thousand point one and that may require product duplication by using the 'copy product' feature that is already built-in. Otherwise, with one length class library, how would store owners be able to know which decimal points and thousand points needs to be showed while formatting the length class in the controllers?

**Comment by amaco596** [comment]
@TheCartpenter, the decimal point and the thousand point are defined in language files, catalog/language/en-gb/en-gb.php and for example catalog/language/ro-ro/ro-ro.php, $_['decimal_point'] and $_['thousand_point']. These are optional parameters for "$this->length->format" function and they default to English values which are "." for decimal point and "," for thousand point.

So, even if I have for example "," for decimal point in catalog/language/ro-ro/ro-ro.php it will not be used if I don't provide it to "$this->length->format" function which then defaults to ".". That's wrong in Romanian.

I have already tried the suggested solution, and it works.

**Comment by TheCartpenter** [comment]
```I have already tried the suggested solution, and it works.```

Excellent. Since you claim the solution on the above is working, and that the system/library/cart/length.php file also uses the $this->language->get in the number_format, can you please post the solution on how you accomplished this 'in codes'?

**Comment by amaco596** [comment]
@TheCartpenter, I did post the solution in my bug report. Please read my bug report!

**Comment by amaco596** [comment]
@TheCartpenter, my bug report is the first post in this thread.

**Comment by TheCartpenter** [comment]
You're referring to a package where the en-gb does not include this issue. Which means, the language pack is where this issue is occurring since the cart\length.php file from the library already calls for the default decimal point and language point regardless if the parameters are entered or not from the compare page. Therefore, what you are reporting is not a bug.

**Comment by amaco596** [comment]
In my bug report I am referring to catalog/controller/product/compare.php file, where in line 107 to 110 the "format" function is using only two parameters instead og four, so the last two parameters default to English values, which is wrong in Romanian language.

If I use the suggested solution, $this->language->get('decimal_point') will use the right decimal point which is "," for Romanian language and not default to "." which is for English language.

I mean it's a bug since the "format" function is not using four parameters in catalog/controller/product/compare.php file.

**Comment by amaco596** [comment]
@TheCartpenter, probably I didn't explain well, but the point is that the "format" function should use four parameters in catalog/controller/product/compare.php (instead of two), so no matter whichever language package is installed, the right decimal point will be used.

**Comment by TheCartpenter** [comment]
```If I use the suggested solution, $this->language->get('decimal_point') will use the right decimal point which is "," for Romanian language and not default to "." which is for English language.```

Exactly. Which means that, since the en-gb language have no issues as it has been originally delivered out-of-the-box, then the issue is with the Romanian language package, not with the en-gb package. Unless you're saying there are additional language keys used in other languages that should be handled politically, including the en-gb language's original language pack, then please post these changes which includes each language pack changes.

> @TheCartpenter, probably I didn't explain well, but the point is that the "format" function should use four parameters in catalog/controller/product/compare.php (instead of two), so no matter whichever language package is installed, the right decimal point will be used.

The explanation was well understood. As mentioned on the above, what you're reporting is not a bug originating from the core.

**Comment by amaco596** [comment]
@TheCartpenter, I might have misunderstood what a bug is, but the changes must be done to OpenCart files which we download from opencart.com.

Isn't catalog/controller/product/compare.php file an OpenCart file?

And the other files mentioned:
catalog/controller/extension/feed/google_base.php
catalog/model/extension/shipping/fedex.php
catalog/model/extension/shipping/parcelforce_48.php
catalog/model/extension/shipping/royal_mail.php
catalog/model/extension/shipping/ups.php
catalog/model/extension/shipping/usps.php
catalog/model/extension/shipping/weight.php

In all these files the "format" function is using two parameters instead of four, which can lead to wrong formatting depending on which language package one might use.

I thought that by reporting this here the OpenCart developers will fix this issue in the next version of OpenCart. Where should I report problems with these files?

**Comment by TheCartpenter** [comment]
```depending on which language package one might use.```

For this OC version, still on this day, it would be the right location to submit issues. However, what you are submitting on this commit is not one of them.

**Comment by amaco596** [comment]
@TheCartpenter, I am not reporting a problem with language packages.

The problem is that the "format" function is using two parameters in catalog/controller/product/compare.php file, and I mean it should use four, so the right decimal point from the right language file is used instead of using "." as a decimal point for all the languages. Even if the decimal point is "," in my language file it will never be used if the $decimal_point parameter used by "format" function is always ".". Formatting for example 10.00 kg is wrong in Romanian, where it should be 10,00 kg. What you call decimal point in English is a decimal comma in Romanian.

Since catalog/controller/product/compare.php is an OpenCart file, I mean it's a bug.

I don't know how to explain otherwise.

**Comment by mhcwebdesign** [comment]
@amaco596: Yes, of course you are right to report it here as a bug, thank you for this. Decimal values presented on frontend pages should indeed use the language-dependent correct values for the decimal and the thousands-separator. I don't know what TheCartpenter is all on about.

**Comment by TheCartpenter** [comment]
If the case, then the master branch also has this bug and nobody reported it prior since the library/cart/length.php still uses the default language inside its method when no parameters are defined. If all languages would need to use all four parameters, then there would also be an issue with the en-gb package which isn't the case here.

**Comment by amaco596** [comment]
@TheCartpenter, the languages don't need to use all four parameters. The "format" function in catalog/controller/product/compare.php and the other files needs to do that. The format function has nothing to do with the languages. It only gets some parameters and return a formatted string.

**Comment by TheCartpenter** [comment]
This is what I am saying. In the $this->length->format, there are currently two parameters instead four right now, including the master branch. How can one, or two, define this as a bug if the en-gb package does work normally even with the first two parameters on both branches?

**Comment by cataistoc** [comment]
@TheCartpenter 
This is the declaration of format method in length.php : 
public function format($value, $length_class_id, $decimal_point = '.', $thousand_point = ',') { ... }
So, when this method will be called without the last 2 parameters they will be defaulted at values for en-gb. It will be fine for en-gb language but not for other languages which use different separators (e.g. ro-ro).
In order to solve these issue for other languages it is needed to call this method  with all 4 parameters, like @amaco596 said.

**Comment by TheCartpenter** [comment]
```In order to solve these issue for other languages it is needed to call this method with all 4 parameters, like @amaco596 said.```

By doing that, it will override the default en-gb language in the method when, normally, the last two parameters are not entered.

**Comment by cataistoc** [comment]
Yes, but what's wrong in this case? In case of en-gb language, the separators are the same as defaulted.. So, functionally, everything is fine. 
In my opinion, the main cause of this problem is that these parameters are optional and should not be if other languages different than en-gb are accepted. If these parameters were necessary, then this problem would have been found a few years ago.

**Comment by TheCartpenter** [comment]
By considering that, it would also mean that mandating the last two parameters would allow any decimal point and any thousand point to be entered by countless extensions whereas the en-gb won't be possible to troubleshoot even by switching the language back to its default state since the number_format would no longer use the default language keys but rather the two last parameters being entered. In a library, I fail to see how such method could be used by reflecting the change globally in the platform each times the $this->length->format would be called.

**Comment by cataistoc** [comment]
If an extension don't use the correct separators (related to the active language), then the issue is in that extension and not in Opencart code. Currently, there is an issue in Opencart, in case of using different language than en-gb.
Also, if there is a fair about what extensions could set as separators, then these parameters can be validated, and to accept only point, comma and apostrophe  (for Switzerland). If everything else is received than you can switch to en-gb values.

see below from internet, after a quick search:
"The majority of European countries use the decimal comma. Among them are Spain, France, Norway, the Czech Republic, Denmark, and more. However, it’s important to note that the **United Kingdom is an exception** because they tend to follow the Imperial System, which uses the decimal point. Curiously, Switzerland and Liechtenstein are different, as they use a point as a decimal separator, and an apostrophe (‘) for thousands."
link: https://www.smartick.com/blog/math/learning-resources/decimal-separators/#America

Also, If I have a site in a different language than en-gb, I want to work properly in my language. I don't care about en-gb, because is useless for me.

**Comment by TheCartpenter** [comment]
```and to accept only point, comma and apostrophe (for Switzerland). If everything else is received than you can switch to en-gb values.```

While the posted URL originates from a blog, what would then be the difference to change the decimal point and the thousand point in each of these language packs instead of using free-for-all parameters in the format methods of the libraries? By editing each language main PHP files, won't these provide the same results once switching the language over a custom language pack already?

**Comment by amaco596** [comment]
@TheCartpenter, my point was exactly that it wouldn't make any difference if you had "," as a decimal point in the language file since it will never be used because the "format" method will always default to "." if you only use two parameters.

**Comment by TheCartpenter** [comment]
Then, there is no point to modify the compare controller since the decimal point and the thousand point can already be edited from each main language files.

**Comment by amaco596** [comment]
@TheCartpenter, they can be edited but never used, if you only use two parameters. That's why you should modify the controller to use four parameters.

**Comment by cataistoc** [comment]
@TheCartpenter 
The length.php which contains defaulted en-gb sepatators is not in language package. Is in system/library directory.

**Comment by amaco596** [comment]
@TheCartpenter, let's take the line 108 in catalog/controller/product/compare.php

'length'       => $this->length->format($product_info['length'], $product_info['length_class_id']),

In this case it doesn't matter what you have as decimal point in the language file, because it will always default to "." since you only have two parameters.

And my suggested solution:
'length' => $this->length->format($product_info['length'], $product_info['length_class_id'], $this->language->get('decimal_point'), $this->language->get('thousand_point')),

In this case the $this->language->get('decimal_point') will fetch the decimal point from the language file.

**Comment by osworx** [comment]
Maybe there is still a 'simple" misunderstanding .. ?

Code (as an example):
https://github.com/opencart/opencart/blob/4ec75265d6789d2ab3de64a7e021affe1643ed68/upload/catalog/controller/product/compare.php#L107

Leads to:
https://github.com/opencart/opencart/blob/4ec75265d6789d2ab3de64a7e021affe1643ed68/upload/system/library/cart/length.php#L42

which means: the compare controller is calling the format function, but does NOT hand over the correct decimal and thousand values as defined in each language master file (here en-gb):
https://github.com/opencart/opencart/blob/4ec75265d6789d2ab3de64a7e021affe1643ed68/upload/catalog/language/en-gb/en-gb.php#L9
and
https://github.com/opencart/opencart/blob/4ec75265d6789d2ab3de64a7e021affe1643ed68/upload/catalog/language/en-gb/en-gb.php#L10

Summary; as long as the controllers are not submitting the correct - language depending - values, each output (display) is based on the English (or whatever) driven format only - but not the correct for many Countries (like many in Europe as Austria, Germany, etc.)

**Comment by TheCartpenter** [comment]
I do have to give that it's a bit odd that the $decimal_point and the $thousand_point is defined but that the currency library uses the default language with the number_format function. To short things up, I'll create a commit that will simplify all these changes and post the commit link afterwards. It doesn't require modifications to all these PHP files as there's a way to do it without interfering with other extensions in the mean time.

**Comment by TheCartpenter** [comment]
Alright folks see if this solution is working: https://github.com/TheCartpenter/opencart/pull/10214/commits/c254816206e270014b3011586e539e0e0401579a .

**Comment by osworx** [comment]
Simplier then aditng various files, would be to add the decimal and thousand value to the config.
Inside the library controllers $this->config is already assigned:

https://github.com/opencart/opencart/blob/4ec75265d6789d2ab3de64a7e021affe1643ed68/upload/system/library/cart/length.php#L8

https://github.com/opencart/opencart/blob/4ec75265d6789d2ab3de64a7e021affe1643ed68/upload/system/library/cart/length.php#L42

So, the solution could be:
```php 
public function format($value, $length_class_id, $this->config->get('decimal_point), $this->config->get('thousand_point'))```

**Comment by osworx** [comment]
> 
> 
> Alright folks see if this solution is working: https://github.com/opencart/opencart/pull/10214/files

Could be also a solution.

**Comment by amaco596** [comment]
@TheCartpenter, remember that the "format" function in system/library/cart/weight.php must be changed as well.

**Comment by TheCartpenter** [comment]
> @TheCartpenter, remember that the "format" function in system/library/cart/weight.php must be changed as well.

This commit is about the length. Please stay on topic!

**Comment by amaco596** [comment]
@TheCartpenter, the bug report is about catalog/controller/product/compare.php which include both weight and length. And there is the same problem with both of them.

**Comment by TheCartpenter** [comment]
Right. Weight is also in there. Commit: https://github.com/opencart/opencart/pull/10215/files .

**Comment by TheCartpenter** [comment]
@WebkulOpencart: Maintenance branch.

**Comment by cataistoc** [comment]
@TheCartpenter 
I don't fully agree with your solution because it implies more code to execute  (the if's) and with the current implementation of  method calls this code is executed very frequent. This could impact the performance. But, yeah, may be I am paranoid. :)
On the other hand, I think is the easiest and quickest solution to solve the issue.

**Comment by TheCartpenter** [comment]
@cataistoc: The registry object is still a single feed object that propagates throughout the platform which means the same arrays from the object is being recalled. The default language definition will be loaded each times but this is no different than the TWIG engine loading the language files each times the $data array is being used from the Engine. If you're worried about the language text being recalled, I would worry more about the times the TWIG engine rather makes these calls.

**Comment by TheCartpenter** [comment]
So to add, the currency format method has been running its default language text since almost the beginning of time and I don't recall anyone complaining about that regarding performance issues.

**Comment by mhcwebdesign** [comment]
Can you try this solution for the **system/library/cart/length.php** please and let me know:

```
	public function __construct($registry) {
		$this->db = $registry->get('db');
		$this->config = $registry->get('config');
		$this->language = $registry->get('language');
		......
```

```
	public function format($value, $length_class_id, $decimal_point = null, $thousand_point = null) {
		if ($decimal_point==null) {
			$decimal_point = $this->language->get('decimal_point');
		}
		if ($thousand_point==null) {
			$thousand_point = $this->language->get('thousand_point');
		}
		if (isset($this->lengths[$length_class_id])) {
			return number_format($value, 2, $decimal_point, $thousand_point) . $this->lengths[$length_class_id]['unit'];
		} else {
			return number_format($value, 2, $decimal_point, $thousand_point);
		}
	}

```

**Comment by TheCartpenter** [comment]
> Can you try this solution for the **system/library/cart/length.php** please and let me know if it works:
> 
> ```
> 	public function __construct($registry) {
> 		$this->db = $registry->get('db');
> 		$this->config = $registry->get('config');
> 		$this->language = $registry->get('language');
> 		......
> ```
> 
> ```
> 	public function format($value, $length_class_id, $decimal_point = null, $thousand_point = null) {
> 		if ($decimal_point==null) {
> 			$decimal_point = $this->language->get('decimal_point');
> 		}
> 		if ($thousand_point==null) {
> 			$thousand_point = $this->language->get('thousand_point');
> 		}
> 		if (isset($this->lengths[$length_class_id])) {
> 			return number_format($value, 2, $decimal_point, $thousand_point) . $this->lengths[$length_class_id]['unit'];
> 		} else {
> 			return number_format($value, 2, $decimal_point, $thousand_point);
> 		}
> 	}
> ```

```if (is_null($decimal_point)) {
			$decimal_point = $this->language->get('decimal_point');
		}
		if (is_null($thousand_point)) {
			$thousand_point = $this->language->get('thousand_point');
		}```

**Comment by TheCartpenter** [comment]
The null types validation may not be accepted since even the zone_id array key validation ends with == '' in the validate() or validateForm() methods. Which means, the empty string parameters might be the right course of action in this scenario since Opencart does not commonly use null types as an empty parameter in the maintenance branch. Not sure, yet, regarding the master branch, however.

**Comment by TheCartpenter** [comment]
For the master branch, I added the null types in the Pull Requests.

**Comment by danielkerr** [comment]
i added it to master
