### ISSUE TITLE
Status to be released oc4

### ISSUE THREAD

**Issue by rsuchovsky** [opencart/opencart#10235]
Please could you give information on the release of a new version of oc4? Whether it is realistic for her to be out by the end of the year. 

Thank you.

**Comment by TheCartpenter** [comment]
The Projects tab on this repository helps providing information based on the status of the release at this time.

**Comment by rsuchovsky** [comment]
Thank you for the info, I'm watching the project card. 
I just don't know if it is realistic for developers to release oc4 by the end of this year. Or until next year. 
Because the project card doesn't update much.

**Comment by chongshengdz** [comment]
it could be years, or maybe next year.
this year is impossible.

**Comment by yvonn** [comment]
3.0.3.8 is the latest release at August 27, 2021 
You can check https://www.opencart.com/index.php?route=cms/download/history

**Comment by yvonn** [comment]
Repairs and fixes are also important.

**Comment by stalker780** [comment]
> Repairs and fixes are also important.
Absolutely. But using a framework from 2013 in 2021... is a bit absurdly.

**Comment by stalker780** [comment]
Anyway, Daniel is doing a lot of work now for OC4. And doing it really fast comparing to OC3. Hope we will see a release soon.

**Comment by mhcwebdesign** [comment]
@stalker780: 

> Absolutely. But using a framework from 2013 in 2021... is a bit absurdly.

What a stupid comment. I suggest you study up on MVC design of software, or use a different ecommerce software.

**Comment by dabbmedia** [comment]
Updating BS3 to BS5 in OpenCart 3 is non-trivial, finishing up a project now.

- BS5 uses different class and data attribute names for the components; so the accordions in product/product.twig and checkout/checkout.twig, for example, needed some find and replace (not too much work)
- BS5 does not use jQuery, but BS5 and jQuery work together in no-conflict mode
- replacing jQuery on the checkout page is a massive amount of work, due to the use of jQuery's delegate and HTML containing inline JS loaded asynchronously (my vote is moving to ES6 transpiled with Babel, or ViewJS)

**Comment by danielkerr** [comment]
its getting close. 

i just got a bit stuck with the new one page checkout system but am managing to fix it.

https://github.com/opencart/opencart/projects/5

**Comment by mrteray** [comment]
> I beleive it will be released by the end of the year. my team currently are testing the cloud system. we plan to launch the a subscription version of opencart on cloud hosting this year. for it to work i need 4.0 fully working.

**well well well) you have 6 days)**

**Comment by danielkerr** [comment]
The order editor is a pain to finish

**Comment by danielkerr** [comment]
very soon.
