### ISSUE TITLE
Community Necessity - feature: Sale tab

### ISSUE THREAD

**Issue by ericklb84** [opencart/opencart#10232]
## Create a promotion tab what the people create sale for a category and all products recipe the discount [Percent or Value]
* Crate a sale method when categories recipe a fixed value of discount or a percent
* Create a label for product card

**Comment by mhcwebdesign** [comment]
This is not an OpenCart bug, please re-post your suggestion with more details on the OpenCart forum at https://forum.opencart.com/viewforum.php?f=110 as a feature request.

**Comment by TheCartpenter** [comment]
Creating labels are already handled by shipping providers upon delivery. Which means, even though a product card label could be created from the store, it won't provide any guarantee that this labeled product card can be used prior to the sale being shipped / completed especially when the label_id would need to be handled for guests customers rather than the registered ones.
