### ISSUE TITLE
Why is OpenCart generating a Permission Problem?

### ISSUE THREAD

**Issue by noorbakerally** [opencart/opencart#10244]
I have an opencart system that is not loading due to permission issues. The HTTP Server is Apache HTTP running on Centos 8.

```
Warning: fopen(/var/www/html/system/storage/logs/error.log): failed to open stream: Permission denied in /var/www/html/system/library/log.php on line 22
RuntimeException: Unable to create the cache directory (/var/www/html/system/storage/cache/template/b7). in /var/www/html/system/storage/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 55
Warning: fwrite() expects parameter 1 to be resource, bool given in /var/www/html/system/library/log.php on line 31
Warning: fclose() expects parameter 1 to be resource, bool given in /var/www/html/system/library/log.php on line 39
Warning: fclose() expects parameter 1 to be resource, bool given in /var/www/html/system/library/log.php on line 39
```

I have tried different of type of permissions. For test purposes, i've set chmod -R 777 to the complete storage directory and its subdirectories but still no success.

**Comment by eka7a** [comment]
Please use the opencart forum for this.
https://forum.opencart.com/viewforum.php?f=199

**Comment by dabbmedia** [comment]
@noorbakerally 

Run the commands below as root, su - or sudo:

Verify the permissions of the file being written and its parent directory:
`ls -lah /var/www/html/system/storage/logs/error.log` and
`ls -lah /var/www/html/system/storage/logs/`

Verify the permissions of the file doing the writing:
`ls -lah /var/www/html/system/library/log.php`

Verify the apache user:
`ps axfu | grep http`

If some files are not changing permissions with chmod as verified with the above, try the force option:
`chmod -Rf 0777 /var/www/html`

Since the error message in the first message mentions not being able to write to the logs or the Twig template cache, it may be an issue of the location of the 'storage' folder. If you used a custom location during the install, make sure the OpenCart install is trying to use the correct 'storage' folder with the correct permissions.

Log errors think the storage folder is here:
`/var/www/html/system/storage`
Security best practice may prefer the file here:
`/var/www/storage`

**Comment by lishuai0214** [comment]
check SELinux and try again, [](https://blog.lysender.com/2015/07/centos-7-selinux-php-apache-cannot-writeaccess-file-no-matter-what/)
