### ISSUE TITLE
Edit order does not change currency selected on step 1

### ISSUE THREAD

**Issue by Bary** [opencart/opencart#10432]
**What version of OpenCart are you reporting this for?**

3.0.3.8

**Describe the bug**
There is 5 steps of edit order: on first one change currency, on step 2 you see product(s) with correct new currency and on final step 5 is all visible in new currency (no problem) but clicking save opencart confirm saving on green background but email comes with previous currency, in databse there are not updated columns: currency_id, currency_code, currency_value.

**To Reproduce**
1. Go to any order and choose edit ( I did fresh install of 3.0.3.8 made one order in default USD and tried to change that into EUR)
2. on Step 1 change currency into whatever (EUR on my case)
3. Save on step 5
4. See error - no error, but return to that order, still in previous currency

**Expected behavior**
order in new currency

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? - local docker + web server
 - Operating system - linux
 - PHP version - 7.3.32
 - Apache version - 2.4.51 debian
 - Browser(s) tested with [e.g. chrome, safari - if applicable] - opera, chrome, edge

**Additional context**
in the API edit function in catalog/controller/api/order.php and model_checkout_order->editOrder there is nothing that sets the currency when updating an order.

**Comment by TheCartpenter** [comment]
That's because the catalog/controller/api/currency.php file adds a session data to the posted currency but does not redirect from the browser once the order has been saved on step 5. Which means, the previous currency will be tracked in from the currency library rather than the selected one from the admin order form.

As for the edit order model in checkout, that is also confirmed. Only the addOrder method seem to have the currency ID, code and value.

**Comment by danielkerr** [comment]
please open issue here:

https://github.com/opencart/opencart-3/issues

**Comment by Bary** [comment]
done, thx
