### ISSUE TITLE
Add cart issuce application CSRF token not working 

### ISSUE THREAD

**Issue by selvarajRaja31082018** [opencart/opencart#10447]
What version of OpenCart are you reporting this for?

3.0.3.8

Describe the bug
The VAPT Auditing Team found one more issue in Opencart 3.0.3.8. In the current scenario, If I take the source code for the Add to Cart section and save in a new html file, the product item has been automatically added in the cart. Already, I tried with your CSRF Protection Form (VQMod) but unable to resolve. So I need your support to overcome this issue in the proper way.

Server / Test environment (please complete the following information):

Local development
Operating system - linux
PHP version - 7.3.32
Apache version - 2.4.51 debian
Browser(s) tested with [e.g. chrome, safari - if applicable] - opera, chrome, edge
![image_2022_02_28T04_20_34_191Z](https://user-images.githubusercontent.com/46552995/156107920-9539623d-612e-47ca-acbb-5abaa2882565.png)
![image_2022_02_28T04_15_46_501Z](https://user-images.githubusercontent.com/46552995/156107925-3c767e36-9aa0-4ea8-bb95-8bd82cd47578.png)
![image_2022_02_28T04_15_27_775Z](https://user-images.githubusercontent.com/46552995/156107929-6eb6924d-f2dd-477b-829b-76927d31c2db.png)
![image_2022_02_28T04_15_59_641Z](https://user-images.githubusercontent.com/46552995/156107932-170e8ad3-078b-412a-a523-377f63c3d12f.png)

**Comment by TheCartpenter** [comment]
WTH is this posted in here??? Extensions are NOT supported on this repository!

**Comment by vestigegroup** [comment]
thanks

**Comment by mhcwebdesign** [comment]
Please re-post on the OpenCart forum for help with the CSRF Protection Form.

**Comment by selvarajRaja31082018** [comment]
WTH is this posted in here??? Extensions are NOT supported on this repository!-Pls explain this briefly.

**Comment by ADDCreative** [comment]
The extension you referred to is third party extension, you need to contact the developer of the extension for support.

If your issue is about general lack of CSRF protection. This has been mentioned many times before and the developers response has alway been it's not an issue.
https://github.com/opencart/opencart/search?q=csrf&type=issues

However, it looks like the yet to be released development version may change things, but nothing on the add to cart as yet.
https://github.com/opencart/opencart/search?p=1&q=customer_token&type=code
