### ISSUE TITLE
Session Not Expire After New Password Reset

### ISSUE THREAD

**Issue by selvarajRaja31082018** [opencart/opencart#10460]
Description:

During the assessment, the consultant found the application does not expire the session after password reset or password change functionality.

Attack Scenario:

If the attacker has compromised the victim user's account due to any weak credentials or method. Here now the victim wants to change the password because he knows his account was compromised. Now the victim is changed the password of his account using password reset or password change functionality. But after changing the password of victim account doesn't protect his account from the attacker due to insufficient session expiration protection on the other active sessions. Here the application doesn't have the active session list to view the active session of any user's account to verify the number of sessions available for his account.

So here the attacker has full control over the victim's account even the victim is changed the password.

Remediation:

Kindly inactive all active sessions once the password change or password reset has been done from the user.

In other words we can list all of the active sessions to the users to terminate the sessions if they are not using them.

Reference

Kindly find the below few public reports and the severity is set to Medium which is from hackerone and they have fixed this vulnerability

https://hackerone.com/reports/1069392
https://hackerone.com/reports/514577
https://hackerone.com/reports/737039

**Comment by mhcwebdesign** [comment]
Rather than repeatedly spamming the github issues section with your comments, how about you start out with a clearer problem description and offer a realistic solution, otherwise you'd just waste everybody's time here.

For a start: Are you talking about OpenCart admin users, or frontend account users?

Also, your suggested solution won't work. E.g. in the same scenario, if the unwanted logged-in user (hacker) initiated a password change and subsequently all sessions related to this account were forcefully expired, then the genuine account holder (or admin user) would be cut off!

The bottom line is this: Once logged in OpenCart has no way to know whether the user or customer is genuine or not.

There are possible solutions, such as better passwords, 2-factor authentication, anti-spambot tools, anti-bruteforce WAFs, etc, but yours isn't one of them.
