### ISSUE TITLE
payment token? payment_method_data 'name' is obscure

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#10475]
https://github.com/opencart/opencart/blob/a8b6e9f1537d4a15199fc2f06812e23c6787fb13/upload/extension/opencart/catalog/controller/payment/credit_card.php#L80

**Comment by TheCartpenter** [comment]
Already pulled request.

**Comment by danielkerr** [comment]
can i get a link to pull request?

**Comment by TheCartpenter** [comment]
Not sure I would agree on this one, since there are also account security reasons to why customers are using sessions prior to get redirected to the payment service provider's website to complete their transactions as opposed to store credit card payments even though the CC numbers are being replaced with stars (*) or Xs.

**Comment by danielkerr** [comment]
the card extension is only for developers to know where to put stuff for setting up payment methods.
