### ISSUE TITLE
OC4 Database custom charset

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#10833]
Please add customizable MySQL charset during installation.

https://github.com/opencart/opencart/blob/470c7a218c36f1bb15226d97053f60897b8ed140/upload/system/library/db/mysqli.php#L16

It should not be hardcoded inside DB library.

utf8 is outdated nowadays and most installations require utf8mb4 to be able to store unicode chars in DB.

**Comment by TheCartpenter** [comment]
Then the utf8mb4 should be hardcoded instead of the previous utf8 since most installations uses this charset ...

**Comment by stalker780** [comment]
@danielkerr 
Tell this to our customers, who want to store emoji in DB.
For different reasons (SMS/Emails/Telegram bot API/Comments/etc.)

99% of our websites use utf8mb4. And this requires to modify mysqli library in every single website.

It is not difficult for me to modify mysqli library. But this is the most frequently asked question for my HTML description (ckeditor/summernote) extensions: Why I cannot store emoji in product name/description and get ??? instead of heart/dog/smiley icon?

Well, as always. OpenCart developers will always have a job to do :)

**Comment by osworx** [comment]
Just for reading:
1. https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci
2. https://drupal.stackexchange.com/questions/166405/why-are-we-using-utf8mb4-general-ci-and-not-utf8mb4-unicode-ci

Beside this, using **utf8mb4_unicode_ci** should be at least THE choice for all installations.
Why?
For example (beside the fact for those useless emojis .. ), I use this collation always since a few years (wherever supported).
Reason: better support for German -  and this as valid basically for all languages if NOT English!
