### ISSUE TITLE
[4.0.0.0] Checkout - Registered >> sometimes Shipping / Payment Options not selectable

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#10935]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
1. logged in as registered user
2. adding item to cart
3. call Checkout
4. Shipping / Payment options are sometimes not selectable:
![OC-4000-Checkout-as-registered](https://user-images.githubusercontent.com/1905204/170865423-b92f9996-e749-4257-9884-e659e5da6fd7.png)

Selected a shipping method, the payment option is displayed:
![OC-4000-Checkout-as-registered-after-select-shipping](https://user-images.githubusercontent.com/1905204/170865517-6f87a9e5-dd8e-44c9-a9bf-b67d13809923.png)

But when I deselect the shipping method, the payment option is still visible > inconsistent!
![OC-4000-Checkout-as-registered-after-deselect-shipping](https://user-images.githubusercontent.com/1905204/170865568-b39f3e83-375d-431d-a907-bc59037095ef.png)

And finally - the most strange issue: checkout as guest, provided all details, but no shipping and payment methods as selectable:
![OC-4000-Checkout-as-guest-no-shipping-payment](https://user-images.githubusercontent.com/1905204/170865742-d5dc44cd-aa75-4250-a6f8-be47e42863ad.png)

A "strange" checkout like this, is simply not useable!

**Comment by TheCartpenter** [comment]
That's what I tried to explain regarding the terms and agreement vs. the payment and shipping service providers selected during checkout previously. Otherwise, that's what happens. One could identify GDPR issues and notices the results where each laws would not be designated to their service providers' agreement. Instead, the checkout checkboxes are running on its own terms.

**Comment by osworx** [comment]
Privacy & other Terms (e.g. TOS) during the checkout process are independent from shipping and/or payment service providers!
They are only here to get users consent and fullfill legal requirements (depending on each country the webshop is selling the products) because they are required (again: in some countries).

Or am I misunderstanding you?

**Comment by TheCartpenter** [comment]
> Privacy & other Terms (e.g. TOS) during the checkout process are independent from shipping and/or payment service providers! They are only here to get users consent and fullfill legal requirements (depending on each country the webshop is selling the products) because they are required (again: in some countries).
> 
> Or am I misunderstanding you?

You did not misunderstood. In fact, you're right to the point. Which is why, the current way the checkout process is handle is also problematic based on the independency of these laws vs. the Privacy & other terms as a matter of fact.

Since V4, catalog/view/javascript/common.js uses a dynamic post validations from the HTML forms being submitted. Which means, a toggled strategy 'could' be used similarly as the OC admin custom fields whenever a dropdown menu is being used, an associated content is loaded, where this time, the checkout could do the same in order to rectify those situations by law.

**Comment by danielkerr** [comment]
there is also a gdpr and accept cookies if u enable on settings

**Comment by TheCartpenter** [comment]
Yes, this option is based on cookies. However, this commit is also about terms & conditions reflected by the use of service during checkout depending on the payment and shipping extension modules selected during process since these regulations are, indeed, based country-wise.

**Comment by osworx** [comment]
Sorry, but what has this buggy checkout (placement of the checkboxes, the prechecked checkbox, displaying once shipping/payment and once not displaying) to do with a GDPR and/ or Cookies??

It' s a good idea to add a one-page-checkout after so many years, but it should work and has to meet the minimum requirements!
Also when buying as guest, the Privacy Terms have also to be agreed - no matter which shipping and/or payment option maybe be chosed later or sooner.
**Guests have the same rights as Registered customers - or not?**

**Comment by TheCartpenter** [comment]
Correct. Guests do normally have the same rights as customers. However, placement of checkboxes does also have something to do with GDPR when using payment and shipping as a service. Which is why, cookies, while it's still valid through the GDPR process, is simply insufficient on that end for store owners to maintain their mutual agreement with their service providers as for customers to agree with store owners prior to confirm the order during checkout.

**Comment by wakson** [comment]
I am seeing the exact same issue above. Not sure why shipping and payment are gray out been stuck googling around and no solution at all any solution or is this a bug currently being resolved?

**Comment by danielkerr** [comment]
cookies and gdpr have noting to do with checkout. stop imagining things.

when buying as guest, the Privacy Terms have also to be agreed

no it does not! use ur brain!

**Comment by OlehOnyshchuk** [comment]
So how to solve this problem. Payment method still not active. Can anyone help?
