### ISSUE TITLE
Wrong date format and localization in DATE, DATETIME and TIME form fields

### ISSUE THREAD

**Issue by amaco596** [opencart/opencart#10964]
**What version of OpenCart are you reporting this for?**
4.0.0.0

**Describe the bug**
I installed Romanian language, but there is wrong date format and localization in all DATE, DATETIME and TIME form fields. For example the date should be formated like 28.05.2022, and calendar should be in Romanian not in English (see the screenshoot).

**Expected behavior**
Date format and localization depending on the language used.

**Screenshots / Screen recordings**
![localization](https://user-images.githubusercontent.com/51860627/171175220-cf4198cb-a158-4b16-98cf-bafaabd4917d.jpg)

**Comment by BuslikDrev** [comment]
## Reporting a bug

Read the instructions below before you create a bug report.

 1. Search the [OpenCart forum](https://forum.opencart.com/viewforum.php?f=201), ask the community if they have seen the bug or know how to fix it.
 2. Check all open and closed issues on the [GitHub bug tracker](https://github.com/opencart/opencart/issues).
 3. If your bug is related to the OpenCart core code then please create a bug report on GitHub.
 4. READ the [changelog for the master branch](https://github.com/opencart/opencart/blob/master/CHANGELOG.md)
 5. Use [Google](https://www.google.com) to search for your issue.
 6. Make sure that your bug/issue is not related to your hosting environment.

If you are not sure about your issue, it is always best to ask the community on our [bug forum thread](https://forum.opencart.com/viewforum.php?f=201)

**Important!**
- If your bug report is not related to the core code (such as a 3rd party module or your server configuration) then the issue will be closed without a reason. You must contact the extension developer, use the forum or find a commercial partner to resolve a 3rd party code issue.
- If you would like to report a serious security bug please PM an OpenCart moderator/administrator on the forum. Please do not report concept/ideas/unproven security flaws - all security reports are taken seriously but you must include the EXACT details steps to reproduce it. Please DO NOT post security flaws in a public location.

**Comment by amaco596** [comment]
@BuslikDrev I mean it is related to the core code, since it is a problem with the DATE, DATETIME and TIME form fields in .twig file. As I can see in the template file, the type of form field is "text". If I change it to "date", the date will be formated right, and there is a new calendar icon inside the DATE field (see the screenshoot). If I click on the calendar icon inside the DATE field the calendar is in Romanian, but there is also the english calendar popping up, which should't.

![localisation1](https://user-images.githubusercontent.com/51860627/171186248-9763da2a-9d74-45a5-851a-f352b4c0382d.jpg)

As long as it is a problem with the form field in .twig file, I mean it is related to the core code, and something the developers should fix. Opencart is multilanguage, so it should display the calendar and format the date depending on the language used, not only in English.

**Comment by BuslikDrev** [comment]
>Also, the date range picker got broken. Eg. store > Product Returns.

https://github.com/opencart/opencart/pull/10955 ?

**Comment by danielkerr** [comment]
[amaco596](https://github.com/amaco596) your wasting everyones time. the date format is sql format. 

@[anytizer](https://github.com/anytizer) already fixed
