### ISSUE TITLE
OC 4.0: Events - provide function to get twig file content in .../view/route/before

### ISSUE THREAD

**Issue by nmpetkov** [opencart/opencart#10985]
As far as I know, the only place where events can handle the contents of the twig file before it is rendered, is in the View, before events. There the third parameter is $code.

The problem is that it is empty unless the user has edited the twig file. Then the code is stored in the database, and in the third parameter $code the code is really available.

In order to be able to process the code in before event, especially since Ocmod is no longer available, we need an easy and quick way to load the $code parameter with the contents of the twig file, which is generally the subject of rendering.

So: please provide function to get twig file content (it is not obvious, becausse of the theme selected for the store).

**Comment by BuslikDrev** [comment]
When installing the module, create this file.

**Comment by nmpetkov** [comment]
@danielkerr View after event can access RENDERD code, it is not the same.

**Comment by nmpetkov** [comment]
@TheCartpenter In rendered code it is like in browser - for example:
Instead of `<td>{{ product.nme }}</td>` you have `<td>iPod</td`.
In other words, in first case you have possibility to handle with known keywords.

Rendered code is also nice to have in after events. I do not want to compare which is better, but I want to have more options, otherwise Ocmod will be indispensable.

By the way, Ocmod is indispensable in one thing: It works at the level of code processing during Ocmod refresh (1 time, and during which it is not associated with delays in generating pages for the client). While the Events system takes time to generate the pages and this slows down the delivery of the code to the client too much. Both have advantages and disadvantages and should work in sync, not eliminate one or the other possibility.

**Comment by BuslikDrev** [comment]
> @TheCartpenter In rendered code it is like in browser - for example: Instead of `<td>{{ product.nme }}</td>` you have `<td>iPod</td`. In other words, in first case you have possibility to handle with known keywords.
> 
> Rendered code is also nice to have in after events. I do not want to compare which is better, but I want to have more options, otherwise Ocmod will be indispensable.
> 
> By the way, Ocmod is indispensable in one thing: It works at the level of code processing during Ocmod refresh (1 time, and during which it is not associated with delays in generating pages for the client). While the Events system takes time to generate the pages and this slows down the delivery of the code to the client too much. Both have advantages and disadvantages and should work in sync, not eliminate one or the other possibility.

Use the theme editor to edit the template (maximum speed).

**Comment by TheCartpenter** [comment]
Creating Event Triggers should not involve any delays after clearing the OC cache from dashboard and extensions' modification page. If further delays are encountered, it is due to either server cache delays or you are using core folders to add your extensions rather than using both extension/module folders which may take up to one hour for the library cache to refresh the data by default.

**Comment by FelipoAntonoff** [comment]
@BuslikDrev create a module and ask the client to edit it through the theme editor I consider it a bad experience and the performance should be the same as it was in OCMOD and the worst thing is there is no way for us to know the location that was changed, it would take a type of diff to this by comparing the original and the one that has been altered.

@nmpetkov I agree, I'm curious to know how Events will replace the OCMOD resources, they should be treated as complete, the use of both is more advantage than trying to use Events for everything, because there is a case that seems to have not been resolved in Events which is how we can change PHP files, as it runs before or after a trigger, whereas before we could work at line level and with cache.

It would be better to focus on better the tools that already exist, than trying to make one replace the other, not to mention the thousands of modules that don't use Events, but need to be able to change native files safely and with performance
