### ISSUE TITLE
How I can add css and style to my extension?

### ISSUE THREAD

**Issue by Aks8578** [opencart/opencart#11012]
How I can use $this->document->addStyle() for loading css file in the directory (upload/extension/[my extension name]/admin/view/asset/style.css).Because we can only write to extension folder.

**Comment by danielkerr** [comment]
u can put any location u want. 

extension/[my extension name]/admin/view/asset/style.css

will work.

**Comment by danielkerr** [comment]
@[cgcmart](https://github.com/cgcmart) what u posted fixes nothing.

**Comment by chufrog** [comment]
For opencart v4.x (4.0.2.1), backend control panel situation.

is it correct to use this **ugly** statement to add my own asset to support my extension?

_$this->document->addStyle('../extension/' . $ext_name . '/admin/view/stylesheet/' . $ext_name . '/asset.css');_

Or any more elegant way to include my asset (js/css)?

e.g. 
_$this->document->addStyle('/admin/view/stylesheet/' . $ext_name . '/asset.css');_

Thank you.

**Comment by mavelo-llc** [comment]
We go up one directory for our style href in 4.0.2.3...

`$this->document->addStyle('../extension/my_extension_name/admin/view/stylesheet/style.css');`

You already know "my_extension_name" since this would be added to the extension's controller. Plus you know the path from there, so there's no need for variables.
