### ISSUE TITLE
[master] Register form - First name has wrong position

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11323]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

**To Reproduce**
1. Go to 'Register Account' in the frontend
2. Try to enter 'First name'

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/174150891-318c318b-a5c8-417a-a56a-618093bf21ea.png)

**Comment by pemaier** [comment]
Also a password confirmation is not present (e.g. typo mistakes)
![image](https://user-images.githubusercontent.com/10166095/174151488-bfbb8a84-54cd-4c48-979b-40897be990fc.png)

**Comment by pemaier** [comment]
... and after clicking 'Continue' for save the form ... noting happens.

**Comment by danielkerr** [comment]
can not replicate ur firstname missing go away!

![image](https://user-images.githubusercontent.com/5079756/174240904-62f249bb-eeb3-4590-a1f6-f8b0edc80697.png)

![image](https://user-images.githubusercontent.com/5079756/174240925-fa6e69d0-5105-46e7-8a8b-070e7aeb2534.png)

**Comment by picsouds** [comment]
the problem is reproducible on firefox only (ok for chrome) and there is an alignment problem on the newsletter acceptance form.

Just add a class="float-none" in the legend
https://github.com/opencart/opencart/blob/1a42eddf5c1dc56ce3f3ef1e1d76fd67aa8255db/upload/catalog/view/template/account/register.twig#L14

and add a col-form-label in the 2 form-check of the newsletter (196 and 199)

https://github.com/opencart/opencart/blob/1a42eddf5c1dc56ce3f3ef1e1d76fd67aa8255db/upload/catalog/view/template/account/register.twig#L196-L200

**Comment by danielkerr** [comment]
ok found
