### ISSUE TITLE
Product Filters

### ISSUE THREAD

**Issue by ProjectMyst** [opencart/opencart#11451]
![image](https://user-images.githubusercontent.com/5079756/178012602-38e2e34c-cddd-4b02-861c-2316adbfeae4.png)

wasting my time entering the products to test

__Originally posted by @danielkerr in https://github.com/opencart/opencart/issues/11449#issuecomment-1179055181__

I've set up a demo site for you with one product and 7 filters.

Please try to add filers "PlayStation 4" or "PlayStation 5" to the product. Ignore the first 5 filters, only try to add the 2 filters "PlayStation 4" or "PlayStation 5" and let me know the out come.

https://projectmyst.com/demo/admin/

Username: admin
Password: demo

**Comment by danielkerr** [comment]
it works fine if u type sony first! u want to just type in playstation.

**Comment by ProjectMyst** [comment]
You are a very ignorant person, if you want to ignore the problem, that's up to you, it's your script but at some point, you realise you will have to change for it to work properly.

From:
$sql .= " AND fd.name LIKE '" . $this->db->escape((string)$data['filter_name'] . '%') . "'";

To: $sql .= " AND fd.name LIKE '" . $this->db->escape('%' . (string)$data['filter_name'] . '%') . "'";

I've never come across a more toxic environment then this, you are not a nice person at all, you need some happiness in your life.

**Comment by danielkerr** [comment]
u have created this issue when u cant use the autocomplete properly! it works fine!

you are typing playstation when the product u are search for, that you have called: sony playstation! you type son and you will get the list of playstations coming up. if you want playstation to come up then name the product paystation!

I called u a dick because u have created multiple issues where the was no issue and it was your own hosting or some other stupid thing.  

only in your mind is this system supposed to work ytou want it to work! only you reporting this issue!

**Comment by stalker780** [comment]
@danielkerr This issue is raised with every new OC version. Why not make it as customers want?

It's not only about Sony Playstation.

A shop may have hundreds of Sony products. And to find Playstations you need to type full brand name + product name. Instead of just typing "playstation".

Another example:
You may have hundreds of bicycles of different brands and if you want to find mountain bicycles among them it is not possible without typing the whole product name.

![image](https://user-images.githubusercontent.com/6297070/178103310-2562e55e-8a9a-4772-8b42-9d4b4d9b73cd.png)

Moreover autocomplete should work like search in frontend. Split words and search all their matches. So searching "mountain polygon" would return all mountain bikes of that brand. Otherwise this autocomplete is useless in real life and must be replaced with 3d-party extension.

https://github.com/opencart/opencart/blob/496b27342adc8afc7bc25ba1eb547c28da31bc38/upload/catalog/model/catalog/product.php#L69

Same for autocomplete products, categories, attributes, options, customers, etc.

Ignoring and insulting people who propose good things is not a best way to build a good product.
 
But as always. This will be ignored.

**Comment by danielkerr** [comment]
u type playstATION U COULD HAVE MILLION MORE PRODUCTS including gamepads, etc..

**Comment by mhcwebdesign** [comment]
I actually have to agree with stalker780 on this. We have modified the autocomplete on a number of our clients' websites to make it more user friendly, even if nothing more than changing it to using something like `LIKE '%xxxx%'` for the SQL.
