### ISSUE TITLE
[master] Frontend Checkout - Customer comment is missing

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#11519]
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
Make an order enter a comment and click Confirm Order
The comment is not getting processed and missing in a new order
(Enter a comment in the Administration is no problem.)

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/10166095/184006924-30a10b0e-8e70-443d-b286-b882240ea08a.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? server
 - Operating system linux
 - PHP version 8.1
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 103.0

**Additional context**

**Comment by mhcwebdesign** [comment]
I can confirm this error still exists for the newly released OC 4.0.1.0. Just tested it, using the 'Cash on Delivery' payment method.

**Comment by phpscript3** [comment]
i check now exists error

**Comment by tinnielam** [comment]
I'm sorry to comment on this ticket, but this problem still exists in the latest version in the master branch of opencart.

Whenever I pick a shipping method first, then pick a payment method and finally fill in the comment form and submit the form. I won't see any comments in my order history or my order details on the back-end side. I've attached an image just to show you which steps I took in order to get this problem.

![image](https://user-images.githubusercontent.com/2794232/206417590-0dec3a33-50c4-415b-a72f-d3009b166490.png)

The only workaround I discovered is that when I fill in the comment form first, then select a shipping method and finally select a payment method. I will get the correct results in my order history and order details on the back-end side.

I have noticed that whenever I select a payment method, it triggers checkout/confirm.confirm and this is what I have been missing after I successfully fill in the comments form.

So whenever I comment something I have to trigger : 
$('#checkout-confirm').load('index.php?route=checkout/confirm.confirm&language={{ language }}');

The success function in : "$('#input-comment').on('keydown', function () { }" lacks this : 

$('#checkout-confirm').load('index.php?route=checkout/confirm.confirm&language={{ language }}');

This actually fixed all my problems :)
