### ISSUE TITLE
PayPal Express not sending State.

### ISSUE THREAD

**Issue by tintoyarcade** [opencart/opencart#1152]
PayPal Express does not appear to send the State for a completed order that originates with the PayPal Express Checkout button.

I checked my database and I see payment_zone_id = 0 and the shipping_zone_id = 0 for completed orders.  The payment_zone and shipping_zone are empty.

If the customer goes to PayPal directly, bypassing checkout, then the State (zone_id) does not appear with the order.

If the State is entered at checkout, then the State is correctly sent to the completed order.

Is this a known bug in the pp_express in 1.5.6?

**Comment by samaraki** [comment]
I have the same problem as others have mentioned, the state is not coming through, I am in the UK, so really it would be called the "County" not "State", but that doesn't really matter...
It works fine with PP Pro and PP standard, just not PP Express, I am of course using a newer version of OC to what you guys must of been using, as this thread is pretty old, I'm still using an old version though 1.5.6.4 as my file already has those "changes" you mentioned put in by default, albeit on different lines.
Anyway, the problem still occurs, so it must be something else.

I don't think the state not coming through effects most orders, most of them come through just fine, but with the state missing, (which doesn't matter to me as long as the payment works), but occasionally the buyer won't be able to order because of it, as it says there is the state missing on the front end, (I'm not sure what triggers that, if it's working for most orders, maybe it's country related, but I'll never know as PP Express doesn't show "missing orders" in the admin), when this happens, it causes an error in the error log, so I'm not sure what to make of it, if anyone has a fix, I'd like to know.

Thanks.
