### ISSUE TITLE
Undefined array key issue on checkout page when buy product with subscription plan

### ISSUE THREAD

**Issue by punitkumar** [opencart/opencart#11555]
**What version of OpenCart are you reporting this for?**
4.0.1.0

**Describe the bug**
Unable to complete checkout a product, product with subscription plan

**To Reproduce**
Step 1. Login in admin panel then go to Catalog > Subscription plans
		Create a new plan with details
		Subscription Plan Name - Fitness OR Any
		Trial Price - 100
		Trial Duration - 1
		Trial Cycle - 1
		Trial Frequency - Day
		Trial Status - Enabled
 		Subscription
		Price - 1200
		Duration - 0
		Cycle - 1
		Frequency - Year
		Status - Enabled
		Sort Order - 1
	Step 2: Create a New Product Fitness Gym OR Any Name, fill required information
		I.e: Name, Meta Title, Model, Seo Url, Choose Subscription Plan - Fitness
	Step 3: Go to Website Front Create a New Account with Address Details or Login into Existing one, if address details are missing then add them first
	Step 4: Search Product created in Step 2, i.e: Fitness Gym
	Step 5: Goto product page then choose Subscription plan and add product into cart.
		After adding product into cart then go to checkout page
		Choose shippng method (Shows Flat Rate instead of shipping method) Flat Shipping Rate 
		Choose Payment Method: Credit Card Payment or Any other available 
		As soon as you choose given payment method you will see an errors

**Expected behavior**
User/Customer should able to complete the checkout

**Screenshots / Screen recordings**
![oc_4010_checkout_error](https://user-images.githubusercontent.com/1077829/185308341-f580fd12-64e7-43da-885a-2358c9ed9c73.png)

**Server / Test environment (please complete the following information):**
 - Local development? Yes Deployed to a web server? No
 - Operating system - Window 10 Home Single Language
 - PHP version - 8.1.6
 - Apache version -  XAMPP Control Panel V3.3.0
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Chrome 
 - Version 104.0.5112.81 (Official Build) (64-bit)

**Comment by TheCartpenter** [comment]
See if these solutions will reduce the errors:

https://github.com/opencart/opencart/pull/11558
https://github.com/opencart/opencart/pull/11557
https://github.com/opencart/opencart/pull/11556

The third link is optional but simply contains whitespace. However, this solution is also valid, since the customer ID in the subscription checkout model is also required as per my solution for adding new subscriptions:

https://github.com/opencart/opencart/issues/11458

As for the reference field, of course, catalog/controller/checkout/order.php file calls for the addOrder() method during checkout via mandatory fields which is why, as much as the custom fields, the reference field needed to be validated while inserting the data during the INSERT INTO query. See if these solutions solves the issue.

**Comment by TheCartpenter** [comment]
It's either that for the reference field or this field from the addSubscription() method needs to add an empty value by default and the duplicated one was added there by mistake.

**Comment by danielkerr** [comment]
duplicate 

https://github.com/opencart/opencart/issues/11458
