### ISSUE TITLE
[4.0.1.1] Order products are pulled from the database, not the "order_product" table

### ISSUE THREAD

**Issue by ClearThinking** [opencart/opencart#11863]
When you view an order in the admin panel (route=sale/order|info) the product data is being pulled directly from the database, and does not reflect the information at the time the order was placed. It needs to read from the "order_product" table instead of the current product table. 

It looks like some changes will need to be made to this file:

/catalog/controller/api/sale/cart.php

or to the file that calls it from the admin side:

/admin/controller/sale/order.php

**Comment by ADDCreative** [comment]
This does seem to affect the tax calculation for the products. With a default install, if you place a guest order with a shipping address other than the United Kingdom, when you view it in the admin the product prices have the wrong United Kingdom tax added, even though the total is correct. Whereas it should have the tax for the country of the order.

There is an example on the forum.
https://forum.opencart.com/viewtopic.php?p=849777#p849386

**Comment by TheCartpenter** [comment]
I have reviewed the shipping() method in the sale/order controller file as the first post seem to address a good point. Since subscription data is involved with an order ID, the catalog/product model should not be involved in regard to stocks since the catalog-end side already allows customers to keep shopping within the hour, by default, regardless of the stock status once the products have been added into the cart.

Therefore, by validating the store products, along with the order products, it will also affect the subscriptions as well as their transactions since a transaction does not involve any product ID in its parameters with the use of addTransaction() method whereas the addTransaction() method implicits the order ID in each second parameters. The stock products should then be disregarded on that end. 

However, by removing the getProduct() lookup, store owners would still need to improvise to get their stocks since, in the shipping() method, a loop is being used which means it would also become quite impossible to lookup the stocks with a service provider as well.

Order products don't have any stocks nor should it be included. The problematic, still, is with the subscriptions at the same time the store products are being validated overall.

**Comment by TheCartpenter** [comment]
Solved the issue for the subscriptions lookup in sale/order: https://github.com/opencart/opencart/pull/11978 .

**Comment by TheCartpenter** [comment]
I am still reflecting a bit on this one, since we don't have a product transaction table but may also not be needed since the core already contains a ```stock_status``` table. Perhaps adding a dynamic method where an extension could associate the stock status ID could do it but even there the ```getProduct()``` method still pulls the ```stock_status``` table in the query whether it's from the admin or from the catalog in the end.

So far, what it looks like is the stock status query should specifically reflect on extensions, since the ```addSubscription()``` also specifically require an extension to do it.

**Comment by mhcwebdesign** [comment]
@ClearThinking: Agree, this issue has to be fixed. More details on what causes it can be found here: https://github.com/opencart/opencart/issues/12057

**Comment by TheCartpenter** [comment]
The ```getProduct()``` method is fine in there. However, it's something I overlooked when adding the filters in the ```getSubscriptions()``` method for the sale/subscription. Since the order product ID is indeed unique, then the stock status can also be checked and re-validated with the ```product_info``` from the ```shipping()``` method of the sale/order by using an event.

At least, as a subscription-based information, store owners can be informed of their stock statuses in regard to subscriptions while using the order ID that's already built-in. I will post pull requests about these.

**Comment by TheCartpenter** [comment]
The ```getProduct()``` in sale/order from the ```shipping``` method is fine. This will allow events with /before to verify the stocks as opposed to not having it like previous OC releases.

**Comment by TheCartpenter** [comment]
However, that is correct. We still need to wait for the order editor to see how this goes later on.

**Comment by danielkerr** [comment]
should be fixed now

https://github.com/opencart/opencart/issues/12019

**Comment by ClearThinking** [comment]
Thanks!
