### ISSUE TITLE
UX issue with address dropdown on checkout page

### ISSUE THREAD

**Issue by marcelstoer** [opencart/opencart#12001]
I am sorry I cannot provide specific information about the shop installation or the OpenCart version. I don't _run_ an OpenCart shop, I just use one as a customer.

**Describe the bug**
The address dropdown on checkout page suffers from a UX issue if you have multiple addresses which only differ in their optional fields.

![opencart-select-address](https://user-images.githubusercontent.com/624195/202876089-354f293b-f42f-43ee-a362-d0a02c6a999c.jpg)

For privacy reasons I redacted the full address but in my case it looks like OpenCart is listing the exact same address twice. Instead what's happening is that the "Company" field is omitted in the dropdown entries. I have two addresses stored, one with and one without the company name (I run my company from home and, hence, they have the same address except that one also has a company name).

**Expected behavior**
The dropdown entries to include all/nearly-all address fields such that I can pick the right one easily.

**Screenshots / Screen recordings**
The current workaround is to _first_ 
- go to the "manage addresses" page
- hover over the "Edit" button
- take note of the address id shown in the status bar

Then on checkout, inspect the source code and look for the address id to find out at which position in the dropdown it is showing.

![opencart-edit-addresses](https://user-images.githubusercontent.com/624195/202876271-bdad6b1d-06b6-4280-be4f-857af9e3355b.jpg)

**Comment by marcelstoer** [comment]
@danielkerr Thanks for looking into this. Could you please explain how this issue is now "completed"? (How) Did you fix it?

**Comment by danielkerr** [comment]
i dont think it needs fixing.

**Comment by ADDCreative** [comment]
@danielkerr It would be nice to have a least the company name shown. You can find business customers sometimes the same address multiple times. They don't see the company name in the drop down so they add the same address again trying to get the company name to show.

We have even had customers contact us to say they can't checkout because they can't add their company name to the address. It was easy enough to to add a change to show the company name, but I suspect others may have the same issue.

**Comment by danielkerr** [comment]
Ffs
