### ISSUE TITLE
Menu partially loading after translation.

### ISSUE THREAD

**Issue by Y-Kilic** [opencart/opencart#12171]
**What version of OpenCart are you reporting this for?**
Version 4.0.1.1

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
The modules menu on the register & login pages.

Expected behaviour
![image](https://user-images.githubusercontent.com/28715936/216791205-df02ce3e-e7a9-491f-94ff-070cbd49cb45.png)
Behaviour after I translated everything to dutch. To be sure I did nothing wrong in the translation files, I also downloaded a pre made dutch language pack. Both having the same issue.

The issue (menu partially loading?):

![image](https://user-images.githubusercontent.com/28715936/216791296-f8653a4c-c24d-4d27-9852-7b4fff532794.png)

**To Reproduce**
Install dutch language pack.
Navigate to https://demodemo/index.php?route=account/register&language=nl-nl

**Expected behavior**
Menu fully loading
![image](https://user-images.githubusercontent.com/28715936/216791205-df02ce3e-e7a9-491f-94ff-070cbd49cb45.png)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system: Centos 7, cPanel
 - PHP version: 8
 - Apache version cPanel latest
 - Browser(s) Edge

**Additional context**

dutch client side language pack:
[backup nl-nl.zip](https://github.com/opencart/opencart/files/10609751/backup.nl-nl.zip)

**Comment by condor2** [comment]
@opencartbot it work only translations is in extension/opencart and not in language_pack/extension. When you delete from extension/opencart that bug happen.

OC 4.0.2.0

**Comment by rsepulvedacl** [comment]
Same problem here. I tried to install a translation as a module, then some phrases disappear or appear in English, but everything works fine when files are manually merged (old method).
It seems that nothing is translated whenever files are called from `[web_root]/extension/opencart/`. I tried with versions 4.0.1.1 and 4.0.2.0 (preview, from master).

[opencart_spanish.ocmod.zip](https://github.com/opencart/opencart/files/10976343/opencart_spanish.ocmod.zip)

**Comment by rsepulvedacl** [comment]
I modified the `addPath` method like this and it worked:

```php
	public function addPath(string $namespace, string $directory = ''): void {
		if (!$directory) {
			$this->directory = $namespace;
		} elseif (is_dir(DIR_EXTENSION . 'opencart_spanish/' . substr($directory, strlen(DIR_OPENCART)))) {
			$this->path[$namespace] = DIR_EXTENSION . 'opencart_spanish/' . substr($directory, strlen(DIR_OPENCART));
		} else {
			$this->path[$namespace] = $directory;
		}
	}
```

But I need to replace the `'opencart_spanish/'` part with a variable.

**Comment by rsepulvedacl** [comment]
Still not working on 4.0.2.0.

[opencart_spanish.ocmod.zip](https://github.com/opencart/opencart/files/11256440/opencart_spanish.ocmod.zip)

**Comment by rsepulvedacl** [comment]
It still doesn't work on 4.0.2.2.

[opencart_spanish.ocmod.zip](https://github.com/opencart/opencart/files/12138062/opencart_spanish.ocmod.zip)

Install it, activate it, set it up on System → Settings→ Edit → Local.

Run:
`ps aux | grep apache2 | grep -v grep | grep -v root | cut -d ' ' -f3 | awk '{print " -p " $1}' | xargs sudo strace -f -t -e trace=file -o opencart-strace.txt`

Load a page and then run:
`grep 'es-cl' opencart-strace.txt`

When you're browsing catalog, you'll see that there are times where it tries to load translations from:
`/var/www/html/opencart/extension/opencart_spanish/catalog/language/es-cl/extension/opencart/total/credit.php`
instead of:
`/var/www/html/opencart/extension/opencart_spanish/extension/opencart/catalog/language/es-cl/total/credit.php`.

When you're browsing admin, you'll see that there is no translation loaded, then run:
`grep 'en-gb' opencart-strace.txt`
and you'll find that it only loads the original phrases.

Thanks for reading!
