### ISSUE TITLE
SEO URLs Error: Incorrect URLs not returning HTTP Status 404 when 'SEO URLs' setting is enabled

### ISSUE THREAD

**Issue by manasgain** [opencart/opencart#12228]
**What version of OpenCart are you reporting this for?**
**Master**

**Describe the bug**
After enabling `"Use SEO URLs"` with proper configuration, SEO URLs are working perfectly fine.
But when anyone types an incorrect URL, instead of returning a _404 page_ & _HTTP Status Code_ **404 Not Found**, it is fetching **_Route:_ "common/home"**, which is great - users no longer see boring 404 pages.

However, there is one issue: browsers & search engine crawlers no longer get the HTTP **"404 Not Found"** Status Code in _Response_ and treat _incorrect URLs as valid URLs._
Eventually, _search engines_ are _indexing the incorrect links_ & placing it at top, while valid links are either placed at the bottom or getting deindexed.

_Incorrect URLs must return a **"404 Not Found"** header in response._

**To Reproduce**
1. Enable **"Use SEO URLs"** in Settings->Server and also configure `".htaccess"` properly.
2. Type the incorrect OpenCart site URL and notice the page.

Eg. `https://yourwebsite.com/this-wrong-url`

You will notice that the **incorrect URL** is fetching the view related to the _home page_ `(route: common/home)`

**Expected behavior**
This incorrect URL should have returned a **"404 Not Found"** `HTTP Error status code` in the _header response._
For users, it is great to see _HomePage_ instead of boring _404 page_, however Search Engines are penalising by _deindexing valid urls_ (as per report in Google Search Console & Bing Webmaster Tools).

If the **"Use SEO URLs"** setting is **disabled,** then this is working **well**.
_"404 Not Found" error code is being thrown with the wrong route or incorrect URL._
However, the URLs are very bad in appearance, and no one wants to have such a dirty URL in production.

### HOW to throw "404 Not Found" for incorrect url with "Use SEO URLs" enabled???

**Server / Test environment (please complete the following information):**
 - Local development as well as Deployed to a web server?
 - PHP version - 8.1.6
 - Browser(s) tested with latest Chrome, Brave

**Additional context**
I hired an SEO consultant, and he suggested returning "404 Not Found" in the header response for incorrect URLs.

_(This issue [https://github.com/opencart/opencart/issues/12208](https://github.com/opencart/opencart/issues/12208) was already posted by another user (@florin-botea), but that person failed to explain the issue properly. As a result, it has been closed.)_

**Comment by nexadomain** [comment]
I can confirm this issue with the latest master.

On entering an incorrect URL, a **200 OK** header is being sent with the homepage view.

![image-min](https://user-images.githubusercontent.com/77724079/229384591-53a82883-9b39-4711-acba-9f676e4f1868.jpg)

**Comment by danielkerr** [comment]
u need to put the base url in .htaccess

RewriteBase /opencart-master/upload/

should be 

RewriteBase /OC/opencart/

**Comment by SDG1212** [comment]
Hello!
The issue is still exist (4.2.1 version). Let me explain more technical details.

1. In framework.php file we have a code:
```
// Route
if (!$action) {
	if (!empty($request->get['route'])) {
		$action = new \Opencart\System\Engine\Action((string)$request->get['route']);
	} else {
		$action = new \Opencart\System\Engine\Action($config->get('action_default'));
	}
}
```
The question is why do we try to return home page when the route variable is empty? 
Instead it should return 404 error. The code below:
```
// Route
if (!$action) {
	if (!empty($request->get['route'])) {
		$action = new \Opencart\System\Engine\Action((string)$request->get['route']);
	} else {
		$action = new \Opencart\System\Engine\Action($config->get('action_error'));
	}
}
```
Okey. We have solved half of the issue. Now we don't have possibility to return the home page. Lets try to fix it in a quick (not quality enough) way.

```
// Route
if (!$action) {
	if (!empty($request->get['route'])) {
		$action = new \Opencart\System\Engine\Action((string)$request->get['route']);
	}

	if (!$action) {
		$isHomePageWithoutLanguageCode = empty($request->get['_route_']);

		if ($isHomePageWithoutLanguageCode) {
			$action = new \Opencart\System\Engine\Action($config->get('action_default'));
		}
	}

	if (!$action) {
		$routeWithoutSlashes = str_replace('/', '', $request->get['_route_']);
		$isHomePageWithLanguageCode = isset($request->get['language']) && $routeWithoutSlashes == $request->get['language'];

		if ($isHomePageWithLanguageCode) {
			$action = new \Opencart\System\Engine\Action($config->get('action_default'));
		}
	}

	if (!$action) {
		$action = new \Opencart\System\Engine\Action($config->get('action_error'));
	}
}
```

Finally. Something work as it should. But the main problem that we need to improve is SEO URL Controller decode function. That's why I think this problem should have more complex and quality solution. It will be better to take some time to analyze the issue.

Let's go to next problem.

2. ContentTop, ContentRight, ContentBottom & ContentLeft Controllers always return Home Page Modules When the Route Variable doesn't exist. Why? It should return modules for 404 route and only in some cases Home Page Modules. Again the problem is mostly in SEO URL Controller decode function.

Hope my information will be useful.

**Comment by manasgain** [comment]
@danielkerr 
This issue needs to be reopened

**Comment by qaharmdz** [comment]
@danielkerr please consider checking the issue again.

The issue happens when `config_seo_url` is enabled and `catalog/controller/startup/seo_url.php` doesn't set a fallback for the `route` value. Thus the `framework.php` will set the route to `action_default` due to the request `route` is not available.

In the case of `example.com/en` it is expected behavior to return header status 200 and show the homepage. 
But it introduces another issue:

- example.com/xyz - 200 homepage
- example.com/en/xyz - 200 homepage

Expected behavior:

- example.com/xyz - 404 not found
- example.com/en/xyz - 404 not found

My patch proposal is to set a fallback `route` to `action_error` on the `catalog/controller/startup/seo_url.php`.

```php
public function index(): void 
{
    // Add rewrite to URL class
    if ($this->config->get('config_seo_url')) {
        // ...

        // Decode URL
        if (isset($this->request->get['_route_'])) {
            // ...

            foreach ($parts as $part) {
                // ...
            }

            // Patch https://github.com/opencart/opencart/issues/12228
            if (
                empty($seo_url_info)   // validate last `_route_` parts, example.com/en/xyz should show 404
                && !isset($this->request->get['route'])   // validate `route` key is not yet available
            ) {
                $this->request->get['route'] = $this->config->get('action_error');
            }
        }
    }
}
```

Patch result:

- example.com/en - 200 homepage, `route=common/home`
- example.com/xyz - 404 error not found, `route=error/not_found`
- example.com/en/xyz - 404 error not found, `route=error/not_found`
- example.com/en/product/not-exist - 404 products not found, `route=product/product`
- example.com/en/catalog/not-exist - 404 categories not found, `route=product/category`

Also the assigned modules to `Design > Layout` with route `error/not_found` correctly appear on the 404 error not-found page.
