### ISSUE TITLE
ecb.php throws error (Division by zero) if the default currency is not in the fetched list

### ISSUE THREAD

**Issue by ahmed-fad** [opencart/opencart#12359]
Version: Opencart 4.0.2.1

this line:
`							$this->model_localisation_currency->editValueByCode($result['code'], 1 / ($currencies[$default] * ($from / $to)));
`
throws an exception: divide by zero
if the default currency is not in the list.

**To Reproduce**
- add a currency, e.g. BHD
- make it default
- once ecb.php is called (e.g. if installing a new language extension) it will throw `divide by zero`

**Comment by pemaier** [comment]
I have a similar problem.
**What version of OpenCart are you reporting this for?**
master
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?
I want use Russian Ruble as main currency. But the settings are not working right and the update isn't working.

**To Reproduce**
Steps to reproduce the behavior:
1.Go to Settings / Localization / Currencies and activate Russian Ruble
2. Go to 'settings / your store'
3. Click on 'tab local'
4. Scroll down to 'Currency and choose Russian Ruble'
5. Go back to Settings / Localization / Currencies 
6. See error that Russian Ruble is not set to 1.00000000
7. After click to update noting happens

**Expected behavior**
A clear and concise description of what you expected to happen.

The same if I choose Euro. That the currency rate is calculated well also for Russian Ruble.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app
![image](https://github.com/opencart/opencart/assets/10166095/b6fdc92a-fd9c-4c2e-a3c3-5675c468a4c5)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? localhost and external server
 - Operating system Linux
 - PHP version 8.2
 - Apache version 2.4
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox
 - Version [e.g. 22] 114.0
