### ISSUE TITLE
More possible issues to take a look at

### ISSUE THREAD

**Issue by TheCartpenter** [opencart/opencart#12425]
OC v4.0.2.2.

On the OC forum, there were reported, but not yet officially identified, issues about the admin upgrade controller and the upgrade TWIG file: https://forum.opencart.com/viewtopic.php?p=858799#p858799 . Might be something that requires to be looked at.

**Comment by danielkerr** [comment]
not sure what the issue is they are describing. the back up had a issue that was fixed. 

"Current update implementation has super-slow zip extraction way - it actually opens zip for each file, extracts single file, and closes it. Fixing this increased unzip speed 10x at least. After that the limit to extract 200 files per request is very low, so it is raised. Even with limit 1000 single request takes like 2 seconds."\

this ios not try it extracts 200 files at a time. i can not see any issue

**Comment by MaxD2** [comment]
I'm the author of this fix. Exracting file from zip by acessing "zip://archieve.zip#filename" wrapper actually opens zip and analyses it from the scratch for each operation. Sure, this procedure time is proportional to zip size. Currently extracting 200 files this way takes approximately 5 minutes. Whole destribution extraction takes ages.

Proper file extraction should utilize already created **ZipArchive** object for extraction.

Beside that the built-in upgrade code contains numerous errors and there is no conditions it can complete successfully.
That means that no one tested it even single time.

For example, in all versions starting from 4.0.0.0 till current in **install/controller/upgrade/upgrade_1.php** such a line with missing quotes is present:
`$output .= 'define(\'DIR_STORAGE\', ' . $config['DIR_STORAGE'] . ');' . "\n";`

It produces such an output, making syntax error in **admin/config.php**:
`define('DIR_STORAGE', /Users/maxd/Web/test/402/storage/);`

**Comment by danielkerr** [comment]
Master branch it works
