### ISSUE TITLE
Opencart maintenance mode not showing the frontend when logon as admin

### ISSUE THREAD

**Issue by bpcheramie** [opencart/opencart#12494]
4.0.1.1

When you have the site set in maintenance mode and you are login as the admin and you try to view the front-end of the site it will only show you the maintenance mode screen when it should be showing the site.

1. Open admin panel and log on as admin
2. Go to system
3. Go to settings 
4. Center screen click on action to the right hand side of the screen.
5. click on the tab that has server on it.
6. turn on maintenance mode
7. click on the save button.
8. click the down arrow by your user name and select your store. 
9. it will open your website but it will only show you the maintenance page and it should be showing you the store withouy the maintenance page 

when you are logon as the admin of the store and the store is in maintenance mode you should not see the maintenance mode screen but the store.

**Comment by mhcwebdesign** [comment]
OC 4.0.1.1 was never suitable for production site. Please try it again with 4.0.2.2, or the master branch.

**Comment by ADDCreative** [comment]
I can confirm this affects 4.0.2.2 as well. It depends on whether the admin or catalog side creates the session cookie. See. https://forum.opencart.com/viewtopic.php?p=859249#p859203

**Comment by mhcwebdesign** [comment]
@ADDCreative : I am not able to reproduce this issue in OC 4.0.2.2. Can you post the precise steps on ho0w to reproduce this error?

**Comment by ADDCreative** [comment]
@mhcwebdesign This is how I could recreate it in 4.0.2.2. OpenCart was installed in a subdirectory on a domain, not local.

1. Use a totally clean browser with no cookies already set
2. Go directly to the admin URL such as `https://example.com/opencart4/admin/`
3. Login
4. Switch on Maintenance Mode if not already on
5. Click on Your Store in the Profile drop down menu. Which would take to to `https://example.com/opencart4/`

I then see the maintenance message, when I should see the store.

As I said in the forum post. If you go to in a totally clean browser to `https://example.com/opencart4/` first and then `https://example.com/opencart4/admin/` it works fine. It's because of how the path is set on the session cookie.
https://github.com/opencart/opencart/blob/f27a8e206ecb248e015a909b2fd29ea129029793/upload/system/config/default.php#L42

You end up with two session cookies /opencart4/ and /opencart4/admin/. If you go to the samin first the catalog will have a different ID as it can't read the  /opencart4/admin/ cookie.

**Comment by danielkerr** [comment]
it works. just tested it.

**Comment by mavelo-llc** [comment]
Had same issue in clean 4.0.2.3 install. Front-end cannot see cookie created with '/admin-folder/' session path. Resolved issue by editing...

system/config/default.php
`$_['session_path'] = '/';`


See https://www.php.net/manual/en/function.setcookie.php#:~:text=If%20set%20to%20%27/%27%2C%20the%20cookie%20will%20be%20available%20within%20the%20entire%20domain.%20If%20set%20to%20%27/foo/%27%2C%20the%20cookie%20will%20only%20be%20available%20within%20the%20/foo/%20directory%20and%20all%20sub%2Ddirectories%20such%20as%20/foo/bar/%20of%20domain.

**Comment by alaplap** [comment]
I noticed the same problem. As [ADDCreative](https://github.com/ADDCreative) mentioned, cookies example.com/ and ecample.com/admin/ existed, and as I renamed "admin" to something else, a third cookie existed as well. I removed the cookies and that solved the problem.
