### ISSUE TITLE
Cart shows 0

### ISSUE THREAD

**Issue by hqasraful** [opencart/opencart#12662]
Version 4.0.2.2
If I "Add to cart" a product from "home page" it  is added to "Cart" and shows fine even I refresh the home page. But when I click on product from the home page and try to "Add to cart " a product  from product page, it also works fine but on refresh the product page Cart shows 0.  I discovered the problem occurs when I just want only one currency disabled the others currencies.

![home page cart](https://github.com/opencart/opencart/assets/7779509/74e29325-84ac-4be4-86fd-a1b864a0a88d)
![product page cart](https://github.com/opencart/opencart/assets/7779509/2237f1d7-0b95-4f9e-8707-ef90ba2890da)

**Comment by danielkerr** [comment]
because u have set login to view prices. already fixed prices still appearing

**Comment by pemaier** [comment]
Sorry you are right with my settings.
![image](https://github.com/opencart/opencart/assets/10166095/39442418-a52d-4c4b-b464-65202902be91)

JFI: With the 1st opening today i saw prices in the cat as i remember (this was the reason I started the video again because the result was not like the result of hqasraful's) ... but now I can't reproduce it again. 
(The new install and settings are from yesterday.)
