### ISSUE TITLE
[4.0.2.3] Error after deleting a language

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#12766]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Describe the bug**
Order statuses disappeared after removing an additional language
What section does it affect?
setting/setting

**To Reproduce**
1. Install an additional language
2. Set the language status to enabled
3. In the settings, select the newly installed language
4. Remove the language in extensions
5. Order statuses are missing in the settings

**Expected behavior**
The statuses must remain or when deleting a language, it cannot be deleted if it is active and selected by default.

**Screenshots / Screen recordings**
![order_statuses](https://github.com/opencart/opencart/assets/12296392/48ad9a45-1a06-42d0-9da2-e337a8061abb)

**Server / Test environment (please complete the following information):**
![image](https://github.com/opencart/opencart/assets/12296392/846797fc-fb24-498d-9509-7a61d6e43b47)

I understand that you shouldn’t do this, but I think that there may be problems if someone suddenly does this.

**Comment by danielkerr** [comment]
"[4.0.2.3] Error after deleting a language"

and yet theissue is completely different from what u are describing

**Comment by danielkerr** [comment]
i gave no idea i think it only happens to u!

**Comment by danielkerr** [comment]
maybe change the language back to default

**Comment by Hkr32** [comment]
> maybe change the language back to default

It doesn't allow you to change it because all the fields are not filled in.



> i gave no idea i think it only happens to u!

Great approach to development.

**Comment by stalker780** [comment]
@Hkr32 give a link to this language extension.
Are you sure it's not an extension issue?

**Comment by Hkr32** [comment]
> @Hkr32 give a link to this language extension if it is free.

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=45362

> Are you sure it's not an extension issue?

I haven't tested other languages, but I just understand the reason for all this. At least it seems so to me)

**Comment by stalker780** [comment]
@Hkr32 

This happens because your language code is stored in your browsers cookies.
After deleting the language extension your browser still have language cookie set `ru-ru`

![image](https://github.com/opencart/opencart/assets/6297070/aa750cd1-b3e1-42ea-a7f5-a8486580a3cb)

OC tries to select rows with absent language when selecting order_status list.

First you need to set any other language. Then delete your default language extension.

Or you need to clear browser cookies to reset your language code.

Extension developer can add this functionality to extension `uninstall` function to avoid such behavior.
So it is not an OC bug really.

**Comment by Hkr32** [comment]
So opencart allows you to delete the active language and after that everything starts working incorrectly, but it’s not opencart’s fault? Fine)

**Comment by stalker780** [comment]
I agree that OC should have some checks. 
But as I have stated earlier this can be easily fixed be extension developer. If russian was not your only language :)


Here is an example. I did not check it, but you understand my idea.
File extension\ocn_language_russian\admin\controller\language\russian.php:
```
	public function uninstall(): void {
		if ($this->user->hasPermission('modify', 'extension/language')) {
			$this->load->model('localisation/language');
			
			$language_info = $this->model_localisation_language->getLanguageByCode('ru-ru');

			if ($language_info) {
				$this->model_localisation_language->deleteLanguage($language_info['language_id']);
			}
			
			// START Check active language and reset cookies to the first available language
			if ($this->request->cookie['language'] == 'ru-ru') {
				$results = $this->model_localisation_language->getLanguages();
				
				$language = [];

				foreach ($results as $result) {
					$language = $result; 
					
					break;
				}
				
				if ($language) {
					setcookie('language', $language['code'], time() + 60 * 60 * 24 * 365 * 10);
				}
			}
			// END
		}
	}
```

**Comment by Hkr32** [comment]
What if, after uninstalling, search for English and set it as the default?

**Comment by stalker780** [comment]
What if there is no English language?
Not all stores use english.

In my country is often used combination of ukrainian + russian. 
English is usually deleted, because it is not possible to hide english language and users are required to fill english product titles even if this language is disabled.
