### ISSUE TITLE
damianb

### ISSUE THREAD

**Issue by katanacrimson** [opencart/opencart#1286]
thread removed for abuse

**Comment by danielkerr** [comment]
A another comment in because maybe my original point was not taken the right way but what sort of reaction do you expect when somebody comes to your issue tracker and posts "Opencart illegally stripping license & attribution from reused code"!

1. No attribution was striped out or any files! OpenCart includes many other open source scripts such as jquery, bootstrap, font-awesome, summernote, ckeditor, etc.. none of those projects have had attribution or licenses removed.

2. Both license for OpenCart are the same GPL license so no additional license was required. No copyright violation occurred.

3. The code in question was 28 lines code that was copied and pasted into a file that contain 590 lines of code. Even if the code was not GPL it would still come under fair use for a number of reasons.

4. GitHub is for coding and development, not dipsticks who troll repositories to cause trouble, which if you hadn't noticed from the title of the issue, was what damianb had set out to do!

**Comment by aequasi** [comment]
Why did you necro an issue from almost 2 years ago.
