### ISSUE TITLE
Additional language fallback to english/default

### ISSUE THREAD

**Issue by i2Paq** [opencart/opencart#1366]
Latest 2.x version from github.

Adding a second language via Admin = successful.
Selecting this new language in Storefront or Admin results in a blanc page.

Swapping second language files for English language files ends up with the same result.

**Comment by deepvision7** [comment]
After upgrade from OC 2.0.1.x to the latest OC 2.0.2.0 it is broken again.

text_home, button_continue, button_login strings, etc. messages are all over front end and back end.
It is because the local language resources (russian) are no longer taken from the default.php file in the russian folder . If I rename the the default.php to the russian.php it all works fine and text_home, button_continue, button_login strings, etc. are gone.

And BTW after uploading the OC 2.0.2.0 over the previous version there are two files now:
default.php and english.php with the same content in the catalog/language/english and admin/language/english .

The following may be helpful:
http://www.opencartjazz.com/en/opencart-module/oc2011/oc2011-bugfix-default-language-fallback

**Comment by osworx** [comment]
This behaviour is normal.
Because (!): Mr. Kerr changed the standard name of the main language file from default.php back to LANGUAGE_NAME.php
So, if you are upgrading, the default.php ist still present - but useless.
And if the language pack - here russian - has not changed to the new, the main language vars are not loaded.
Say thank you to Mr. Super.
