### ISSUE TITLE
subcategories data not showing

### ISSUE THREAD

**Issue by vsadoug** [opencart/opencart#13777]
**What version of OpenCart are you reporting this for?**
4.0.2.3
**Describe the bug**
When creating a subcategory, the title and description of that subcat do not show on the storefront page. Only the parent category title and description show.
**To Reproduce**
default install. 
1. install default store
2. go to storefront, Click on components category, 
3. click on Mice/Trackballs 
4. Components still shows at top of page, it should read Mice/Trackballs  and show the description and photo for Mice/Trackballs from admin side.

**Expected behavior**
It should show the category you are in, not the parent. this makes the descriptions of subcategories useless. Any description you put on the admin side into a subcategory is not shown. 

**Screenshots / Screen recordings**
http://vstraining.com/oc1.png

**Server / Test environment (please complete the following information):**
 - OC 4.0.2.3 stock install
 - alma linux 
 - PHP version 8.2
 - Apache version - latest
 - Browser(s) tested with all. 

**Additional context**
I tried using {{ child.name }} but it doesnt pull it for some reason.

**Comment by styudbl** [comment]
I also wanted to write about this error, but I was beaten to it :)

But what is also important to add is the issue with breadcrumbs. They are also not working correctly. In the screenshot, it can be seen that it shows Components>Components instead of Components>Mice and Trackballs.

By the way, it works correctly in version 4.0.0.0.

I checked upload\catalog\controller\product\category.php and they are different. I have not tried replacing from 4.0.0.0 to 4.0.2.3 yet. But I would like to receive a fix from Daniel.

Please release some patch that will fix this.

**Comment by styudbl** [comment]
If you add a third subcategory, it will display the description of the second subcategory, and also "?route=product/category&language=en-gb" is added to the links in the breadcrumb path.

**Comment by danielkerr** [comment]
already fixed in master if there waas an issue

**Comment by tslsundry** [comment]
So what's the resolution ?

Has any patch been released ?

For me, subcategories data not showing #13777, is wide open

Kindly respond.

**Comment by grahamstoker** [comment]
Also Have the same issue and cannot find the fix.

What is the master ?

**Comment by tslsundry** [comment]
You can experiment with the **forked** repository from https://github.com/opencart/opencart or else you have two options.

1. Wait "PATIENLTY" for upgrade to roll out - don't know when. **OR**
2. Revert to a suitable version (Version 3 Series ...)

Honestly 4.0.2.3 is a lot buggy and grumpy in it's present form.
