### ISSUE TITLE
CKEditor 4.22.1 version is not secure.

### ISSUE THREAD

**Issue by icainc-alan** [opencart/opencart#14032]
**What version of OpenCart are you reporting this for?**
4.0.2.3
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Getting this new message.  Did not have it before.  "This CKEditor 4.22.1 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.24.0-lts."

**To Reproduce**
1. Go to 'Category'

4. See error - This CKEditor 4.22.1 version is not secure. Consider [upgrading to the latest one](https://ckeditor.com/ckeditor-4-support/), 4.24.0-lts.

**Expected behavior**
No message in red.

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

![image](https://github.com/opencart/opencart/assets/174690760/da4cabcb-b56c-4a45-9d11-53313fa265ef)

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

After this message started to pop-up today, I started having an issue of using the store customer interface while in administrator mode and having the server in Maintenance Mode. (it will no longer allow me in the store while the maintenance mode is on.

**Comment by stalker780** [comment]
fixed in OC 4.1.

CKEditor 4.22.1 is the latest free version.

https://github.com/opencart/opencart/commit/b777bf3a45c1c993ff225c0e8348d9c9ef491cf2

**Comment by osworx** [comment]
Hmmm .. only disabling the check is not really a secure solution .. isn't it?

While, the insecure version might not affect OpenCart Admins, because as long the editor is only available at the administration side, the issues are these: https://github.com/ckeditor/ckeditor4/security/advisories/GHSA-fq6h-4g8v-qqvm

Should be considered either to buy a license or use another (free) editor.

**Comment by stalker780** [comment]
@osworx The solution is to remove an annoying popup message which is not related to security as it claims.
There are no any known security issues with CKEditor 4.22.1 for now.

I do not see any problems in homecalls when checking for updates. But how it was implemented in CKEditor 4.22.1 I would rather call this a bug or a sort of spam advertising to make users move to the payed version frightening them with such a message.

**Comment by stalker780** [comment]
@mhcwebdesign Why?

Just add `config.versionCheck = false;` to config.js
https://github.com/opencart/opencart/commit/b777bf3a45c1c993ff225c0e8348d9c9ef491cf2

**Comment by mhcwebdesign** [comment]
> @mhcwebdesign Why?
> 
> Just add `config.versionCheck = false;` to config.js [b777bf3](https://github.com/opencart/opencart/commit/b777bf3a45c1c993ff225c0e8348d9c9ef491cf2)

Yes, you are right. Or this will work in the admin twig files, too:

```
$('textarea[data-oc-toggle=\'ckeditor\']').ckeditor({
    language: '{{ ckeditor }}',
    'versionCheck': false
})

```

**Comment by ADDCreative** [comment]
> @osworx The solution is to remove an annoying popup message which is not related to security as it claims. There are no any known security issues with CKEditor 4.22.1 for now.

@stalker780 There are actually 3 known security issues that affect CKEditor 4.22.1. However, none would affect OpenCart as it does not use the features that are vulnerable.

**Comment by osworx** [comment]
> @osworx The solution is to remove an annoying popup message which is not related to security as it claims. There are no any known security issues with CKEditor 4.22.1 for now.
> 
> I do not see any problems in homecalls when checking for updates. But how it was implemented in CKEditor 4.22.1 I would rather call this a bug or a sort of spam advertising to make users move to the payed version frightening them with such a message.

Practices like that will lead to add "checks" like that into all extensions ..
Finally "just to buy" the commercial version ..

I see many problems with homecalls like that.
I could live with it, when such will be made once every 24 hours or a longer period.
Or on a"subscription" base when I decide to get such notifications!

Reg. the security issue: it is security issue:

> Affected packages

The vulnerability has been discovered in the core HTML parsing module and may affect all editor instances that:

    Enabled [full-page editing](https://ckeditor.com/docs/ckeditor4/latest/features/fullpage.html) mode,
    or enabled [CDATA](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dtd.html#property-S-cdata) elements in [Advanced Content Filtering](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_content_filter.html) configuration (defaults to script and style elements).

Impact

A potential vulnerability has been discovered in CKEditor 4 HTML processing core module. The vulnerability allowed to inject malformed HTML content bypassing Advanced Content Filtering mechanism, which could result in executing JavaScript code. An attacker could abuse faulty CDATA content detection and use it to prepare an intentional attack on the editor. It affects all users using the CKEditor 4 at version < 4.24.0-lts.

But as also written above: as long as only the admins work with that editor, the security issue will be no one.
So, never enable this editor for the shop itself and you are fine.

**Comment by mradilamin** [comment]
https://github.com/opencart/opencart/issues/14032 


isusse solved ..

**Comment by danielkerr** [comment]
it only needs to be updated if it was open to the public

**Comment by woolvey** [comment]
Can someone tell me where the version is actually checked? When I add config.versionCheck = false; to config.js, I still get the warning error.

**Comment by stalker780** [comment]
@woolvey config.js gets cached. Clear your browser cache.

**Comment by woolvey** [comment]
Thanks!! Can't believe I didn't try that before posting. doh!

**Comment by DeveloperMuvu** [comment]
Hi Team,

In ruby rails how to desactivate message....version "ckeditor", "~> 4.2.4"

Thanks you

**Comment by mhcwebdesign** [comment]
@DeveloperMuvu : This is an OpenCart forum, for ruby rails please use their forum at https://discuss.rubyonrails.org/

**Comment by fernandovaller** [comment]
Working!

```
<script src="//cdn.ckeditor.com/4.22.1/full/ckeditor.js"></script>
<script>
    CKEDITOR.replace('ckeditor', { 'versionCheck': false });
</script>
```

**Comment by perlsol** [comment]
I can't believe that you find it acceptable to use this CKEditor 4.22.1 and just rely on it not being found by a renamed admin panel, the fact it is still public facing is enough to not use it. your approach to security measures of simply hiding the warning leaves a lot to be desired. Instead of hiding such warning why not replace it!

**Comment by stalker780** [comment]
@perlsol stop this panic and paranoia. There are lots of ways to find your renamed admin folder even without js requests.
`config.versionCheck = false;` not only removes the warning message, it disables http request in ckeditor code.
Check sources before posting.
https://github.com/ckeditor/ckeditor4/blob/3fd8eafd8d805024ca3280fd95899833bb16b163/core/ckeditor_version-check.js#L27-L29

You really think there is someone monitoring CKEditor server for incoming requests to find your admin folder?
Renaming admin folder is only one of the security measures.

**Comment by perlsol** [comment]
If there are lots of ways to find your renamed admin folder then hacker's can easily leverage a bot to find the still used editor.
Why even use v4! I came to opencart looking for a secure solution for a customer, the fact I am straight away presented with a security issue that has been swept under the carpet has prompted me to turn away and keep looking

**Comment by stalker780** [comment]
OMG 🤦‍♂️
Just cut off your internet cable and burn your wifi router

**Comment by perlsol** [comment]
awesome attitude!

**Comment by stalker780** [comment]
Let's talk about attitude.

You came to the developers portal, to the solved issue, reporting nothing, blaming everyone that we are using wrong editor, blaming it is unsafe and the whole oc4 is unsafe too... while showing that you don't understand how things work...
Instead of using the proposed solution or using your own html editor.
Ok... awesome attitude.

Now you are offended you did not achieve... By the way, what did you plan to achieve with you messages?
You proposed no solutions, no problems were reported.

**Comment by stalker780** [comment]
> This lax attitude is exactly why server's get hacked.

Servers are hacked because of unwise administrators.
You still did not provide any test cases how your server can be hacked with CKEditor update request. Even if an imaginary hacker from CKEditor team knows your admin folder name. 
I understand that this red popup message maddened/frightened you, but it has nothing related to security or OC4.

You were given the solution how to disable this request with just one line of code in config.js file.
I don't understand what we are still discussing here.

**Comment by cssesq** [comment]
> Working!
> 
> ```
> <script src="//cdn.ckeditor.com/4.22.1/full/ckeditor.js"></script>
> <script>
>     CKEDITOR.replace('ckeditor', { 'versionCheck': false });
> </script>
> ```

Where exactly in config.js is this code placed? 
I get the same message even after clearing browser cache.

**Comment by ADDCreative** [comment]
@cssesq See https://github.com/opencart/opencart/commit/b777bf3a45c1c993ff225c0e8348d9c9ef491cf2.
