### ISSUE TITLE
Checkout - Default Payment Method and shipping method not automatically selected on checkout page.

### ISSUE THREAD

**Issue by qfx007** [opencart/opencart#14051]
**What version of OpenCart are you reporting this for?**
4.0.2.3

**Describe the bug**
Default Payment Method and shipping method not automatically selected on checkout page. Even if there is only 1 payment method and 1 shipping method available on the store.

What section does it affect?
Checkout page

**To Reproduce**
1. Create a shop with only 1 payment method and 1 shipping method enabled.
2. Add a product to cart.
3. Go to checkout page.
4. The buyer needs to manually select the payment and shipping method to successfully checkout.

**Expected behavior**
When there is only one payment and shipping method available it should be automatically assigned with checkout. And if multiple payment and shipping methods are available, the first method as per the sort order should be automatically assigned on checkout.

**Comment by danielkerr** [comment]
why would they need to click continue if already selected

**Comment by TheCartpenter** [comment]
That would be unregulated, since store owners would take ownership of their guests / customers based on their account preferences and overwritten by the stores' settings. Opencart does provide subscription plans from the core but only based on products; not based on the customers' profiles. In order for the customer to be consent to default payment options during checkout, a subscription plan would be needed without affecting PCI regulations. Take note that PCI regulations does not reflect on payment sort orders but only to what it's being prioritized as a default option without the customer's preferences. 

As for the continue button, it has no relevance to this type of feature, since whether the payment sort order is being used with or without a continue button, it does not impact the customer in any way. The real deal is the fact that an identity provider is required when the need for customers to choose their payment options. Take a look as an example like PayPal and Stripe with the card options, for instance. Both identity providers provide those options directly to the customers by using those accounts. 

Therefore, this could be easily achieved with a payment extension.

**Comment by qfx007** [comment]
I still fail to understand the relevance of PCI regulations here. As per my understanding PCI regulations are applicable when the merchant is accepting and/or storing credit/debit cards on their system and the security of the communication between the servers handling card information. The video shown above utilises COD payment option for demonstration. And, even if we use PayPal as the payment gateway, the customer gets redirected to the PayPal's gateway and we aren't storing any card data with us. 

My concern here is just to make the user-interface of checkout page more customer friendly wherein they don't have to manually select the addresses(whats the purpose of marking an address as DEFAULT by the customer) and shipping method / payment method when there is NO other alternative available for the customer to select one.

On the checkout page, if the default addresses(based on buyer assigned default address) and the available methods(based on default or sort order) get auto populated that will save lot of unnecessary steps and enhance the buyer experience. Please understand here that the buyer still possess the ability to change them through drop-down list. Only thing required is to auto populate the fields so that once verified by the buyer, all it requires is to press checkout if no deliberate change is required by them.

**Comment by TheCartpenter** [comment]
> > why would they need to click continue if already selected
> 
> Hi Daniel, sorry it seems i am not able to properly explain the issue. For the better understanding of it please find the attached video herewith.
> 
>  OC-issue.mp4

> I still fail to understand the relevance of PCI regulations here. 

Yes, as it seem. You are still failing to understand the purpose on why only identity providers provides those options and not store owners. As per my previous reply, it clearly explains on why this feature is normally restricted to guests users since it requires a subscription reflecting on customers' accounts to achieve this. As you mentioned, in regard to redirecting to customers to PayPal without the need of choosing a card to purchase their goods, that is one of the reasons as well customers are not being asked is because they may not be acquired to authenticate to an account with PayPal Checkout, since it is the reason why PayPal acquires customers to have an account, like any other identity payment providers, in order to select a default payment option. Therefore, it is not up to store owners to override this option for their customers as part of their stores without an extension involving a subscription payment that reflects to customers' accounts.

As for PCI compliance, doing more research online, you may notice a larger scale on what involves the details of the use for PCI which is also one of the reasons why the GDPR law came along years afterwards. As for the customers' addresses, you'd be typically correct. However, this feature was implemented way long before the GDPR law got released as this feature has also been modified in OC v4.x releases as opposed to previous OC series during checkout and with the API.

**Comment by TheCartpenter** [comment]
By making this change to JS, when customers will be redirected to the payment identity provider, the default payment option may not remain there.

**Comment by danielkerr** [comment]
> I still fail to understand the relevance of PCI regulations here. As per my understanding PCI regulations are applicable when the merchant is accepting and/or storing credit/debit cards on their system and the security of the communication between the servers handling card information. The video shown above utilises COD payment option for demonstration. And, even if we use PayPal as the payment gateway, the customer gets redirected to the PayPal's gateway and we aren't storing any card data with us.
> 
> My concern here is just to make the user-interface of checkout page more customer friendly wherein they don't have to manually select the addresses(whats the purpose of marking an address as DEFAULT by the customer) and shipping method / payment method when there is NO OTHER ALTERNATIVE available for the customer to select one.
> 
> On the checkout page, if the default addresses(based on buyer assigned default address) and the available methods(based on default or sort order) get auto populated that will save lot of unnecessary steps and enhance the buyer experience. Please understand here that the buyer still possess the ability to change them through drop-down list. Only thing required is to auto populate the fields so that once verified by the buyer, all it requires is to press checkout if no deliberate change is intended by them.

dont listen to him. its nothing to do with PCI

**Comment by TheCartpenter** [comment]
> > I still fail to understand the relevance of PCI regulations here. As per my understanding PCI regulations are applicable when the merchant is accepting and/or storing credit/debit cards on their system and the security of the communication between the servers handling card information. The video shown above utilises COD payment option for demonstration. And, even if we use PayPal as the payment gateway, the customer gets redirected to the PayPal's gateway and we aren't storing any card data with us.
> > My concern here is just to make the user-interface of checkout page more customer friendly wherein they don't have to manually select the addresses(whats the purpose of marking an address as DEFAULT by the customer) and shipping method / payment method when there is NO OTHER ALTERNATIVE available for the customer to select one.
> > On the checkout page, if the default addresses(based on buyer assigned default address) and the available methods(based on default or sort order) get auto populated that will save lot of unnecessary steps and enhance the buyer experience. Please understand here that the buyer still possess the ability to change them through drop-down list. Only thing required is to auto populate the fields so that once verified by the buyer, all it requires is to press checkout if no deliberate change is intended by them.
> 
> dont listen to him. its nothing to do with PCI

Have it your way. The bottom line is that you're still leaving the source code in the browser upon redirections to a payment identity provider where the default payment option may not be used.

**Comment by TheCartpenter** [comment]
https://community.shopify.com/c/payments-shipping-and/can-we-alter-the-sequence-of-payment-options-in-settings/m-p/1692320/highlight/true#M62682

**Comment by qfx007** [comment]
> https://community.shopify.com/c/payments-shipping-and/can-we-alter-the-sequence-of-payment-options-in-settings/m-p/1692320/highlight/true#M62682

![Re-Change-Order-of-Payment-Options-Shopify-Community](https://github.com/user-attachments/assets/bdbc176c-39af-4ad0-9eaf-599308a0093d)

Oh.. so shopify has monetized this feature. Thank God, Daniel is not thinking about OpenCart Plus Plan.

**Comment by TheCartpenter** [comment]
> > https://community.shopify.com/c/payments-shipping-and/can-we-alter-the-sequence-of-payment-options-in-settings/m-p/1692320/highlight/true#M62682
> 
> ![Re-Change-Order-of-Payment-Options-Shopify-Community](https://private-user-images.githubusercontent.com/159226414/350719385-bdbc176c-39af-4ad0-9eaf-599308a0093d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MDQwMzksIm5iZiI6MTcyMTUwMzczOSwicGF0aCI6Ii8xNTkyMjY0MTQvMzUwNzE5Mzg1LWJkYmMxNzZjLTM5YWYtNGFkMC05ZWFmLTU5OTMwOGEwMDkzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQxOTI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTRhZmNlNzZlNDIzYTA0NjYyZjcyM2JiMzA5N2Y5NzVjYmI5ODczZmI2MDBjOWUyNGJmMTM3YzMzNDgzNWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eC4idVfJaSTebrBTYmsF-VHZO4QfT-5TxHYnId54ujQ)
> 
> Oh.. so shopify has monetized this feature. Thank God, Daniel is not thinking about OpenCart Plus Plan.

May be not. However, he's not relying on a payment identity provider but rather to provide ownership to store owners over their customers to select their default payment which, normally, would require a payment extension to achieve this.

**Comment by danielkerr** [comment]
[TheCartpenter](https://github.com/TheCartpenter)ur in the wrong. stop posting this rubish.
