### ISSUE TITLE
New loader.php memory leakage

### ISSUE THREAD

**Issue by stalker780** [opencart/opencart#14218]
After latest loader.php modifications there is a memory leakage in PHP8.0-8.3

https://github.com/opencart/opencart/blob/dd380efa6073aad6f1e0a18d85a75af63db9cc0a/upload/system/engine/factory.php#L47

https://github.com/opencart/opencart/blob/dd380efa6073aad6f1e0a18d85a75af63db9cc0a/upload/system/engine/loader.php#L106

https://github.com/opencart/opencart/blob/dd380efa6073aad6f1e0a18d85a75af63db9cc0a/upload/system/engine/loader.php#L115

Every time you call nonexistent controller method PHP memory usage doubles.

This is a critical issue for the events and extension systems.

After 20 calls OpenCart consumes more than 1.5Gb memory. Tested on a newly installed latest master.

It should either throw an error for developer to react, or use another exception approach. 
Cause every new exception contains all previous exceptions inside it.

```
echo '<pre>'.__METHOD__.' ['.__LINE__.']: '; print_r(memory_get_peak_usage(true)); echo '</pre>';

for ($i=0; $i < 18; $i++) {
	$this->load->controller('extension/my_extension/fake_controller/fake_method');
}

echo '<pre>'.__METHOD__.' ['.__LINE__.']: '; print_r(memory_get_peak_usage(true)); echo '</pre>';
```

Result:
```
Opencart\Catalog\Controller\Common\Home::index [24]: 8388608

Opencart\Catalog\Controller\Common\Home::index [30]: 452984832
```

**Comment by stalker780** [comment]
It is also hard to debug this issue. You get no error messages, no logs, just a frozen script and after that an error you ran out of memory.

IMHO the loader should throw an error that controller/method cannot be executed and script aborted. Just as it happens when tying to load nonexistent models. This makes script behavior strait and understandable for developers and users.

**Comment by mhcwebdesign** [comment]
Well spotted, I hope Daniel will accept it.

**Comment by farshadfmr** [comment]
The current edit on this file has an issue. At the moment creating an event to replace a controller wont trigger the new one. This is because of moving the "before" trigger down, which affects the $route to remain the same as original.

For example:

Following event wont load the modifiedHeaderController **controller** and instead loads the default header controller (php file, I'm not talking about the twig file). 

`$this->event->register('**controller**/common/header/before', new \Opencart\System\Engine\Action('extension/something/startup/something.event'));`

```
class Something extends \Opencart\System\Engine\Controller {
  public function event(string &$route, array &$data) {
  
        $route = 'extension/something/startup/something.modifiedHeaderController';
  
        return new \Opencart\System\Engine\Action($route);
  }
  
  public function modifiedHeaderController() {
  
        echo 'hi';
  
        return "";
  }
}
```

**Comment by danijelGombac** [comment]
@stalker780 I don’t think the memory limit issue is caused by the wrong route, but by the code in https://github.com/opencart/opencart/blob/c34e96a1d139b83c5f33e4330636171cf4f8ddf8/upload/admin/controller/event/language.php#L79

With each call to the controller, json_encode($data) grows because it includes the previous backup.
I added the following before $this->language->set('backup', json_encode($data));:

```
if (array_key_exists('backup', $data)) {
    unset($data['backup']);
}
```
and I no longer get the memory limit error. It would be better to fix this directly in controller/event/language.php and move the before event back to the top of the controller loader, so the event is able to modify the route correctly.

**Comment by danijelGombac** [comment]
@stalker780 ok, I made a PR #15207
