### ISSUE TITLE
SyntaxError: Unexpected end of input OK

### ISSUE THREAD

**Issue by indesign1** [opencart/opencart#1825]
When updating order history, getting the error in an alert, cant change it to completed:

SyntaxError: Unexpected end of input
OK

**Comment by salmanindia** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6432239/6037530/61210898-ac09-11e4-9ded-c3bc345cf50f.png)



![untitled1](https://cloud.githubusercontent.com/assets/6432239/6037545/9af275c0-ac09-11e4-902a-34c9024fa713.png)


![untitled1](https://cloud.githubusercontent.com/assets/6432239/6037563/e394f30c-ac09-11e4-9c8a-56d4f0898ce6.png)

**Comment by tdss** [comment]
In my case it was caused by error in OC configuration. If you think you've tried everything and it still doesn't work, turn on error displaying in store settings and check for errors displayed in pages like admin/index.php?route=sale/order/edit.
My case was: "Notice: Use of undefined constant HTTPS_CATALOG - assumed 'HTTPS_CATALOG' " - I've had to define HTTPS_CATALOG in admin config. After fixing this issue, it all started to work.

**Comment by RonaldoSantana** [comment]
This error persists. Looks like the fix is something else for each person.

**Comment by tdss** [comment]
Unfortunately I am on vacation right now wothout access to pc. Will be back 27.april.

Thanks,
Dariusz

Wysłane z iPhone'a

Dnia 19 kwi 2015 o godz. 23:06 Ronaldo Santana <notifications@github.com> napisał(a):

**Comment by stockmaster** [comment]
For all having this issue, do you guys use CloudFlare?

**Comment by salmanindia** [comment]
no

**Comment by daniel-fastcomet** [comment]
Hello,

The error is not fixed after creating an API user and assigning it for the checkout. As it is 2 days after the 27th, is there a solution to the matter in question already?

**Comment by imdevlper18** [comment]
I had my store on maintenance mode. So order details were failing.
Removing from maintenance mode fixed the issue and i was able to edit the orders.
