### ISSUE TITLE
FedEx shipping module issues

### ISSUE THREAD

**Issue by pifiu** [opencart/opencart#2269]
When using the fedex plugin and selecting "Your packaging" under the packaging type, it seems the size is set to 20x20x20 no matter what.

For now I am selecting "fedex box" and it seems to provide a somewhat close estimate, however then this does not work for Ground service.

Also list rate and account rate return the same when in fact they are not.

**Comment by dhaupin** [comment]
Ran into this today as well -- due to the Jan 2015 rate increase, compounded with their DIM tweaks, stacked on the fixed box size, the minimum rate fedex returns is like 33% higher. Example, a rate in 2014 that used to be $7.50 to Cali is now $25 in 2015 due to the fixed 20x20x10 box dimensions on top of their ~5% increases.

A 3d script would be very hard indeed, especially calculating dimensionals. Luckily there are box/pallet-builder hookins that do that such as Pacejet. They would prob work great in OC2 if there was a product or ship est API... but they are expensive (thousands of dollars). If folks are serious about accuracy and they have enough volume this would work, otherwise they must est (or fudge) it all.

Perhaps a shortcut solution would just be to spool through the length classes + boxes + weight classes + weights to rough it out from the hip. If they find that Fedex is returning too high because it sees 15 small boxes, they could adjust weight to lower it. Its lose lose, but there is no win win in this situation without someone spending a week trying to make a package prediction-calculator class. Or maybe one exists :)

I dunno, just thoughts. The fixed dimension thing needs to go though, especially considering 2015 rates are jacked up. Thanks for your time in this platform regardless man

**Comment by garudacrafts** [comment]
I have a "shoot-from-the-hip" multi-package 3D shipping rate calculation on my site. Hopefully this rabbit hole may help someone...

I modified my USPS shipping extension to split an order in to **multiple packages** to calculate a shipping rate for each package individually. I record them in a database table and then add them up to return a single rate to the customer on the front-end. I did this because **my website has members**  who sell products and I needed to track how much to charge for shipping for each member's group of products on each order.

## How to get approx dimensions for each package/box:
1. calculate the "true" volume of all products in the package
2. calculate the "max"  volume, which is defined as the product of each of the max of the dimensions of all the products
3. use the max dimensions IFF the true volume <= the max volume
4. if true volume is > max volume, then scale up the max volume with a dimensional multiplier, which is calculated as the ratio of the true volume to the max volume (always > 1)
5. add in a bit of padding to the mix for packaging materials/bulk (configured as an admin config setting of the module), and to make fine-tuned adjustments to the calc

This works fine on my site so far. Here are some code snippets:

## Added new method "getPackages" to system/library/cart.php:

```php
public function getPackages() {
	$packages = array();

	foreach ($this->getProducts() as $product) {
		if ($product['shipping']) {
			// 'cpm_customer_id' is the unique id associated with each member account and is how products are grouped into packages (each product is associated with a member id, otherwise zero)
			if (isset($packages[$product['cpm_customer_id']]['weight'])) {
				$packages[$product['cpm_customer_id']]['weight'] += $this->weight->convert($product['weight'], $product['weight_class_id'], $this->config->get('config_weight_class_id'));
			} else {
				$packages[$product['cpm_customer_id']]['weight'] = $this->weight->convert($product['weight'], $product['weight_class_id'], $this->config->get('config_weight_class_id'));
			}
			
			if (isset($packages[$product['cpm_customer_id']]['dimensions'])) {
				$packages[$product['cpm_customer_id']]['dimensions']['max_width'] = max($product['width'], $packages[$product['cpm_customer_id']]['dimensions']['max_width']);
				$packages[$product['cpm_customer_id']]['dimensions']['max_length'] = max($product['length'], $packages[$product['cpm_customer_id']]['dimensions']['max_length']);
				$packages[$product['cpm_customer_id']]['dimensions']['max_height'] = max($product['height'], $packages[$product['cpm_customer_id']]['dimensions']['max_height']);
				$packages[$product['cpm_customer_id']]['dimensions']['volume'] += ($product['length'] * $product['width'] * $product['height']) * $product['quantity'];  // use round float
			} else {
				$packages[$product['cpm_customer_id']]['dimensions']['max_width'] = $product['width'];
				$packages[$product['cpm_customer_id']]['dimensions']['max_length'] = $product['length'];
				$packages[$product['cpm_customer_id']]['dimensions']['max_height'] = $product['height'];
				$packages[$product['cpm_customer_id']]['dimensions']['volume'] = ($product['length'] * $product['width'] * $product['height']) * $product['quantity'];
			}
		}
	}

	return $packages;
}
```

As you can see, the above returns an array of packages that are indexed by the member. Of course, this could be modified for other uses.

## Modified USPS Shipping extension

```php
$quote_data = array();
$packages = array();
$dimensional_padding = $this->config->get('cpm_shipping_padding') * 2; // extra inches to add for padding and packaging all around a package; doubled for each dimension

// check if membership module is enabled
if ($this->config->get('cpm_status')) {
	foreach ($this->cart->getPackages() as $cpm_customer_id => $package) {
		// get package weight in pounds and ounces
		$packages[$cpm_customer_id]['weight'] = $this->weight->convert($package['weight'], $this->config->get('config_weight_class_id'), $this->config->get('usps_weight_class_id'));
		$packages[$cpm_customer_id]['weight'] =  ($packages[$cpm_customer_id]['weight'] < 0.1 ? 0.1 : $packages[$cpm_customer_id]['weight']);
		$packages[$cpm_customer_id]['pounds'] = floor($packages[$cpm_customer_id]['weight']);
		$packages[$cpm_customer_id]['ounces'] = $ounces = round(16 * ($packages[$cpm_customer_id]['weight'] - $packages[$cpm_customer_id]['pounds']), 2); // max 5 digits
		
		$volume_max = $package['dimensions']['max_width'] * $package['dimensions']['max_length'] * $package['dimensions']['max_height'];
		
		// set package sizes
		if ($package['dimensions']['volume'] > $volume_max) {
			$dimension_multiplier = round(((float)$package['dimensions']['volume'] / (float)$volume_max), 2);
			$packages[$cpm_customer_id]['width'] = $package['dimensions']['max_width'] * $dimension_multiplier + $dimensional_padding;
			$packages[$cpm_customer_id]['length'] = $package['dimensions']['max_length'] * $dimension_multiplier + $dimensional_padding;
			$packages[$cpm_customer_id]['height'] = $package['dimensions']['max_height'] * $dimension_multiplier + $dimensional_padding;
		} else {
			$packages[$cpm_customer_id]['width'] = $package['dimensions']['max_width'] + $dimensional_padding;
			$packages[$cpm_customer_id]['length'] = $package['dimensions']['max_length'] + $dimensional_padding;
			$packages[$cpm_customer_id]['height'] = $package['dimensions']['max_height'] + $dimensional_padding;
		}
		
		// USPS-specific requirements (must be in INCHES)
		$packages[$cpm_customer_id]['girth'] = round(((float)$packages[$cpm_customer_id]['width'] * 2 + (float)$packages[$cpm_customer_id]['height'] * 2), 1);
		
		if (($packages[$cpm_customer_id]['width'] > 12) || ($packages[$cpm_customer_id]['length'] > 12) || ($packages[$cpm_customer_id]['height'] > 12)) {
			$packages[$cpm_customer_id]['size'] = 'LARGE';
			$packages[$cpm_customer_id]['container'] = 'RECTANGULAR';
		} else {
			$packages[$cpm_customer_id]['size'] = 'REGULAR';
			$packages[$cpm_customer_id]['container'] = 'VARIABLE';
		}
	}
} else {
// if membership module is not enabled, then calc only 1 package
	$packages[1]['weight'] = $this->weight->convert($this->cart->getWeight(), $this->config->get('config_weight_class_id'), $this->config->get('usps_weight_class_id'));
	$packages[1]['weight'] = ($packages[1]['weight'] < 0.1 ? 0.1 : $packages[01]['weight']);
	$packages[1]['pounds'] = floor($packages[1]['weight']);
	$packages[1]['ounces'] = round(16 * ($packages[1]['weight'] - $packages[1]['pounds']), 2); // max 5 digits
	$packages[1]['width'] = $this->config->get('usps_width');
	$packages[1]['length'] = $this->config->get('usps_length');
	$packages[1]['height'] = $this->config->get('usps_height');
	$packages[1]['container'] = $this->config->get('usps_container');
	$packages[1]['size'] = $this->config->get('usps_size');
	$packages[1]['girth'] = round(((float)$packages[1]['width'] * 2 + (float)$packages[1]['height'] * 2), 1);
}
```

Shameless plug: the membership module extension may be found in the OpenCart extension store at http://www.opencart.com/index.php?route=extension/extension/info&extension_id=10860.
