### ISSUE TITLE
SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by Saikat29** [opencart/opencart#2361]
While trying to update order history and change the status of the a new order then getting this error. I have created a new API user and assign it to the store but no help.

**Comment by Saikat29** [comment]
I have tried all possible option that is available in the internet for this issue. So my question is it a problem with Open Cart or it is a problem with configuration?

**Comment by moyaxatka** [comment]
hello, so you find  answer ? what  is that problem?

**Comment by imdevlper18** [comment]
Daniel is correct. I had my store on maintenance mode. So order details were failing.
Removing from maintenance mode fixed the issue and i was able to edit the orders.

**Comment by diegolupi** [comment]
Dear,

in my case the problem was in the language files.

I have Opencart in Spanish, and some characters gave error.

I hope this helps someone else to solve the problem.

Cheers!!!

Estimados,

en mi caso el problema estaba en los archivos de idioma.

Yo tengo Opencart en español, y algunos caracteres daban error.

Espero que con esta ayuda alguien mas pueda solucionar el problema.

Saludos!!!
