### ISSUE TITLE
Discounts don't work, when Special is active

### ISSUE THREAD

**Issue by thekrotek** [opencart/opencart#237]
Discount feature does NOT work, when you have a special active. For example, I have a permanent discount (Special tab) plus a discount for certain quantity of the same item (Discount tab). When special is active, discount don't count. If I remove special, discount will work.

Special price and quantity discount must NOT cross. At least, when quantity in discount is higher than 1. I want to stimulate customers to buy more and it's OK to give them even bigger discount, when they do so.

This is definitely IS a bug or underestimated feature.

**Comment by JoeriVervoort** [comment]
I'm also looking all over the internet to find a solution for this. I see many people with the same problem.
For reference: we have a B2B shop and use different prices for installers, dealers and wholesalers. They all get an extra discount when they purchase by certain amounts.
So I too have to combine both functionalities.
If it is indeed blocked on purpose, I would like to know how to enable the combination of both, since it is an essential part of our price structure.
Thanks
