### ISSUE TITLE
API Issue when trying to read cookies

### ISSUE THREAD

**Issue by raicabogdan** [opencart/opencart#2476]
Hello,

I have a client with an issue using OpenCart 2.0.1.1, trying to edit an order from admin and right when you press the 'Continue' button, you get a javascript error, NULL.

API settings look alright, the store is active / not in maintenance.

From my little debugging on this, I got around that the issue is due to not being able to read the cookies.

Not an expert with opencart and so it will take me time to get used to the code and and debug it properly.

But some things that I noticed are in file
`/admin/controller/sale/order.php`

The issue appears to be in section

```
if (isset($this->session->data['cookie']) && isset($this->request->get['api'])) {
[....]
}
```

I used the following to print the information:

```
var_dump($_SESSION); 
var_dump($_COOKIE); 
var_dump($this->session);
```

and got the output:

```
----------------------------------------------------- 
array(3) { 
["currency"]=> 
string(3) "USD" 
["user_id"]=> 
string(1) "1" 
["token"]=> 
string(32) "3b654c47d43f885ad7bb79bad018689b" 
} 
------------------------------------------------------------------ 
array(7) { 
["__cfduid"]=> 
string(43) "d858fd68748b5d39d44e098423ad0c6511416087543" 
["__zlcprivacy"]=> 
string(1) "1" 
["language"]=> 
string(2) "ro" 
["_ga"]=> 
string(26) "GA1.2.159252420.1416144240" 
["__zlcmid"]=> 
string(14) "Qte4DqDOGTxVdC" 
["PHPSESSID"]=> 
string(32) "28b34d2ea0591010207230812525851e" 
["currency"]=> 
string(3) "USD" 
} 
------------------------------------------------------------------ 
object(Session)#14 (1) { 
["data"]=> 
&array(3) { 
["currency"]=> 
string(3) "USD" 
["user_id"]=> 
string(1) "1" 
["token"]=> 
string(32) "3b654c47d43f885ad7bb79bad018689b" 
} 
} 
------------------------------------------------------------------
```

As you can see, there's no array `cookie` in the object `$this->session`

Hope this helps to debug this further. If there's any server related cause for this, I would like to hear it so that I can check further.

Kind regards

**Comment by richard-kong** [comment]
I have had the same problem and it is because the curl request is blocked that is causing this problem. If you look at other parts of the same table `$this->session->data['cookie']` is actually set by a response from another curl request.

In my case, on my development machine i was running opencart ssl on port 888 but the curl requests go to 443 so the cookie was never being set.

**Comment by diegolupi** [comment]
Dear,

in my case the problem was in the language files.

I have Opencart in Spanish, and some characters gave error.

I hope this helps someone else to solve the problem.

Cheers!!!

Estimados,

en mi caso el problema estaba en los archivos de idioma.

Yo tengo Opencart en español, y algunos caracteres daban error.

Espero que con esta ayuda alguien mas pueda solucionar el problema.

Saludos!!!

**Comment by eugen-pasca** [comment]
hello, 
i'm writing there because i had the same problem and after a few github posts with the same solutions that did not help me, i found out that in my case the problem was that my staging server was password protected ( apache httpaswd ) and that curl could not get the cookie. Hope it will help someone else.
