### ISSUE TITLE
SyntaxError on adding order history/click Continue in the order

### ISSUE THREAD

**Issue by terales** [opencart/opencart#2529]
I can't add history or edit order from administration panel, please see small video below.

Error on adding history:
https://cloud.githubusercontent.com/assets/1920639/5584761/48aa8bb0-90a0-11e4-8b6d-3dd9e95b01d7.gif

Error on editing order:
https://cloud.githubusercontent.com/assets/1920639/5584762/4ad2a9ae-90a0-11e4-83e7-bc4a8b0bfb39.gif

Also I found fresh reports about this issue in the another tracker: https://opencart.atlassian.net/browse/OC-1804.

I've ended my debugging with 2444 row in the `admin/controller/sale/order.php`:

<pre>if (isset($this->session->data['cookie']) && isset($this->request->get['api'])) {</pre>

`$this->session->data['cookie']` is not set, so this check won't pass. How can I fix this?

**Comment by pad1a** [comment]
How can I fix this?

**Comment by terales** [comment]
You should manually add API user (Options tab in the store settings)

**Comment by pad1a** [comment]
I added API user

**Comment by dazzyweb** [comment]
Adding the API didn't work for me and doesn't work for many others

I did manage to fix the issue in the end though I don't fully understand how this sorted it out and I am not using ssl.

I Opened config.php in the admin folder and found the following lines

define('HTTPS_SERVER', 'http://www.topmeals.uk/opencart2/admin/');
define('HTTPS_CATALOG', 'http://www.topmeals.uk/opencart2/');

Then changed the http to https as below:

define('HTTPS_SERVER', 'https://www.topmeals.uk/opencart2/admin/');
define('HTTPS_CATALOG', 'https://www.topmeals.uk/opencart2/');

This sorted it out for me.

**Comment by pad1a** [comment]
Thank you, it did not help.

**Comment by pad1a** [comment]
The website address where the error - mystore.com
I installed a clean system in mystore.com/clean
Take a database of mystore.com and put on mystore.com/clean - everything works!
Put the database from mystore.com/clean to mystore.com - the error persists!
I understand that it is not in the server settings or store settings. 
The error in the code Opencart.
What files do I need to replace? How can I fix the error?

**Comment by nhucbcb** [comment]
Hi,

You did try change the file admin.config.php ?
find code:
define('HTTPS_CATALOG', 'https://www.yoursite.com/');
chang to:
define('HTTPS_CATALOG', 'http://www.yoursite.com/');
=> change to "https" to "http"
=> Because the Opencart did use the 443 port for Curl function and your Hosting(domain) did disable the 443 port. If you change to "https" to "http" so the Opencart will use the 80 port or you can try enable the 443 port for your domain.

**Comment by pad1a** [comment]
Hello,
I tried it.
It did not solve the problem.

**Comment by milimar** [comment]
I just tried to edit order on my test store, and I did it with no problems. I used OC 2.0.1.2rc.

**Comment by richard-kong** [comment]
@pad1a I had the same problem. Check that the API user is setup correctly

```sql
select * from setting where `key` = 'config_api_id';
select * from api;
```
If it all looks good, its mostly likely the curl requests are getting blocked. You will have to step through the code and add some logging to make sure. I found that the curl requests are hardcoded to go to port 443, if you are running on a different port these requests won't be getting to the api.

If you are finding that the same line as the original post is not passing 
```php
if (isset($this->session->data['cookie']) && isset($this->request->get['api'])) {
```
Then it is a curl problem. There is a curl request earlier in the order controller that sets `$this->session->data['cookie']`. The problem is likely to be your environment where curl loopback does not work, or you are running on a non-default ssl port.

**Comment by bibil1986imns** [comment]
@nhucbcb

Thanks your code really works.

**Comment by diegolupi** [comment]
Dear,

in my case the problem was in the language files.

I have Opencart in Spanish, and some characters gave error.

I hope this helps someone else to solve the problem.

Cheers!!!


Estimados, 

en mi caso el problema estaba en los archivos de idioma.

Yo tengo Opencart en español, y algunos caracteres daban error.

Espero que con esta ayuda alguien mas pueda solucionar el problema.

Saludos!!!

**Comment by zharding** [comment]
This seems pretty crazy. 

I have a similar if not identical issue and it is all revolving around this SSL and cURL and this loopback environmental issue. Who develops an application that does an external loop on its self anyway? On top of which, preventing the admin from setting a separate url for API calls for security and to ensure there isn't loopback issues from a secondary no firewalled, cdn'd, or other security method is crazy. 

By having this insane issue, you are forcing admins to setup up a VERY INSECURE system. 

Solution: If the server does not have configured an "API" URL then USE LOCALHOST!!!!!! cURL can run localhost requests SECURELY! Use the site external address of course for the AJAX requests and then any potential loopback requests should be handled internally. 

Anyway, I have not found a solution for my issue yet and because everyone keeps posting the same response and it is clearly not working for everyone. 

An additional issue, upgrading for most is not possible as the new version destroys the whole site when you upgrade. This is slowly turning into a very poor project. I have promoted OpenCart to many of my clients and I now feel like an idiot for doing so.

**Comment by savjignesh** [comment]
+1 anyone can help?

**Comment by zharding** [comment]
Hey, 

Maintenance mode is the most common issue it seems. It is still ridiculous that this mode would interfere with anything in the admin but it does. I essentially gave up and started redeveloping this pile of "awesomeness". 

Maintenance mode should never be an issue for admins as they are making changes or adding extensions, products etc to test. Cant test however because of maintenance mode. 

Please post some details savjignesh on your exact issue and ill see if I can lend a hand.

**Comment by danielkerr** [comment]
@zharding 

Who develops an application that does an external loop on its self anyway?

diffent scripts on the same server. akslo the admin could be on another server. you never know. also this was removed for over a year,.

**Comment by danielkerr** [comment]
also will be back fixing issues soon. just finishing off the new site rebuild.

**Comment by eugen-pasca** [comment]
hello, 
i'm writing there because i had the same problem and after a few github posts with the same solutions that did not help me, i found out that in my case the problem was that my staging server was password protected ( apache httpaswd ) and that curl could not get the cookie. Hope it will help someone else.

**Comment by nilufary** [comment]
Hi all, 
Please visit the link below to get the SyntaxError issue fixed. Though it is a paid extension but only real solution there. I have tried many solution but this one was the exact one.
**https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=24725**
