### ISSUE TITLE
no review sent confirmation message

### ISSUE THREAD

**Issue by pinkslink** [opencart/opencart#2536]
can send a review no problem
and also get warning messages fine

but when sending a review there is no review sent confirmation message
and text area is not cleared

if there is already a warning message displayed, that simply remains, even though review was sent

using 2.0.1.1

**Comment by mario-inventum** [comment]
There is a bug in OC v.2.0.1.1 in file /catalog/model/catalog/review.php on line 25:
```php
$mail->setTo(array($this->config->get('config_email')));
```
Method Mail::setTo() expected string, not an array. 
But error or warning messages is not displayed because in ayax call in file /catalog/view/theme/default/template/product/product.tpl after line 606 missing error-handling code (something like this):
```javascript
error: function(xhr, ajaxOptions, thrownError) {
			alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
		}
```
Set this error-handling code and you will see error warning.

Then modify line 25 in /catalog/model/catalog/review.php to:
```php
$mail->setTo($this->config->get('config_email'));
```
and bug will desappear :-)

**Comment by CoverUp** [comment]
most of the ajax calls haven't an error handling, so catch errors is more difficult. well done mario

**Comment by danielkerr** [comment]
not sure why array was there

**Comment by demiralidemirali** [comment]
Hi,
I have applied the solution (code at 25th line)
still have the problem (captcha error)
any developments?

**Comment by axiscars** [comment]
This worked a treat for me, turned out they were being submitted, just didn't look like it but now all works perfectly..
Thanks so much
