### ISSUE TITLE
Tool bar Icons & Buttons are Not Lording perfectly most of the time.

### ISSUE THREAD

**Issue by pushpikasj** [opencart/opencart#2739]
Tool bar Icons & Buttons are Not Lording perfectly most of the time.

![icons](https://cloud.githubusercontent.com/assets/9498899/6509789/b06974c2-c387-11e4-9e4c-12ffe15c8fe7.png)

**Comment by mathsolutions** [comment]
I've encountered the same problem, but noticed that the difference is if I write the url of the site with or without www. I explain better, if in config, I've put www.mysite.com and connect to mysite.com, icons doesn't load properly and viceversa. A permanent redirect to the right url solves the problem for me.

**Comment by pushpikasj** [comment]
Thank you very much @mathsolutions 
can you please tell me which one is better "www" vs "non www" for opencart

**Comment by munirasim** [comment]
@pushpikasj 
Use "mysite.com" without "www"
"www.mysite.com" is sub-domain of "mysite.com"
To improve your SEO, redirect "www.mysite.com" permanently to "mysite.com"
Keep in mind, People love to type short. 
Further read: https://www.mattcutts.com/blog/seo-advice-url-canonicalization/

**Comment by pushpikasj** [comment]
Thank you very much @munirasim

**Comment by pushpikasj** [comment]
@mathsolutions and @munirasim 
redirect "www.mysite.com" permanently to "mysite.com" solves the problem. But please check on Google Translate. https://translate.google.com
again same problem. 

![error](https://cloud.githubusercontent.com/assets/9498899/6621370/3b71ce74-c8fc-11e4-991c-b4850856b3b4.png)

**Comment by munirasim** [comment]
It is due to AJAX which is JavaScript that does not allow loading resources from cross domains. 

Let me simplify it for you. When you access your website example.com through https://translate.google.com, your domain example.com becomes the other domain and the javascript called Ajax (used in Opencart) won't allow you to load certain files from example.com and your site crashes.

The question is why you or your site visitors will use Google translator?

The right solution is to add "English" or any other desired language to Opencart and fill contents for it so that a user can select the right language from there.

**Comment by pushpikasj** [comment]
bcz there is no our language pack.

**Comment by munirasim** [comment]
You can build language pack yourself with a little effort. Just follow these steps:

1) Go to 'catalog->language->english' folder. 
2) Copy 'english' folder and rename it to your language name e.g. 'finnish' or 'swedish'
3.) Now in 'finnish' or 'swedish' folder and subfolders translate and edit value of each variable to the corresponding text in Finnish or Swedish
4) Do the same process to the 'admin->language->english' folder in admin folder
5) Enable the langauge in Opencart and you're done

Note: Be careful not to put illegal values for date, time variables etc.
Give it a try and you will start gripping it. 
Best of luck!
