### ISSUE TITLE
New vqmod/ocmod system

### ISSUE THREAD

**Issue by thekrotek** [opencart/opencart#2877]
Are there any plans to replace absolutely awful new vqmod/ocmod system with something better? I can't even express how bad and faulty it is. Would love to have something similar to previous OC version. Right now it takes like 10 times more time to create modification for OC 2.0, than for OC 1.0.

Just FYI, most developers hate it.

**Comment by beifloyd** [comment]
Please note the best place for this is the http://forum.opencart.com/
also note VQmod hasn't changed works the same wya as in OC 1.0
OCmod is the new addition.  I understand ocmod works similar to vqmod however it is deliberately less complex and with less features of VQMod.
that said, you have to pick one only. There is no need to use both at the same.

> Just FYI, most developers hate it.
> - thekrotek
This is a exaggeration ..... who/where?

**Comment by aamnah** [comment]
I like OCMOD! It's easier for clients and non-developers to use Extension Installer as compared to having to install vQmod. Also, the changes between the two ('path' instead of 'name', add position instead of search) do actually make more sense. And it does not take more time to create mods for this version than it did to create mods for 1.5.x.

The OP accomplished nothing but being hateful with his comment. Either explain why and what is awful so we can understand the frustration, or make something better, if you can.

**Comment by thekrotek** [comment]
Yes, it's easier for customers, but for developers it's a nightmare. I am a developer and I accomplished much more, than you can even imagine.

**Comment by aamnah** [comment]
Still don't get your frustration.. You created an issue but only gave an opinion, i.e. you hate ocmod.

**Comment by thekrotek** [comment]
@aamnah, Maybe because you're not a developer or don't have enough experience yet?

Also there were so much said about how much new vqmod/ocmod system sucks, that I don't want to repeat the same. I only wanted to know, are they planning to make it easier for developers, because right now it updating extension to OC 2.0 is A PAIN.
