### ISSUE TITLE
SEO not working in IE, firefox or chrome

### ISSUE THREAD

**Issue by gsc1ugs** [opencart/opencart#2885]
When enabled in admin/settings/server/
get error, it this example seo word is "MAXI-and-1453-Clearomizer-Replacement-Coil-Heads"

Not Found

The requested URL /MAXI-and-1453-Clearomizer-Replacement-Coil-Heads was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by gsc1ugs** [comment]
Why close this one?

**Comment by gsc1ugs** [comment]
Why close this? it says on opencart, any bugs place here, where?

**Comment by aamnah** [comment]
Probably because this is not a bug.. **GOOGLE** before you create an issue. Also, please use the forum http://forum.opencart.com/ 

If your SEO URLs are not working,
1- check if .htaccess.txt has been renamed to **.htaccess**

2- check if mod_rewrite is enabled: `sudo a2enmod rewrite`

3- check if overrides are allowed ([link](http://stackoverflow.com/questions/16462642/opencart-enabling-seo-url-leads-to-404-error)) in virtual host file. make sure your virtual host file contains `AllowOverride All` ([link](http://hasin.me/2008/05/29/setting-up-virtual-host-with-mod-rewrite-in-ubuntu-hardy-heron/)):

```
DocumentRoot /home/<user>/www/site/path       
<Directory /home/<user>/www/site/path>               
  Options FollowSymLinks               
  AllowOverride All  
</Directory>
```
and then reload Apache2 `sudo service apache2 reload`

If you have no idea what step 2 and 3 are, contact your web host. 

By now your SEO Urls should have started working. If not, try the following ([link](http://varabrahmacodes.blogspot.in/2013/04/how-to-solve-404-page-not-found.html)):

4- Open the .htaccess file. Search for
     `‘RewriteBase /‘`
and change it to
     `‘RewriteBase /yourstorename/`

**Comment by gsc1ugs** [comment]
I don’t have control over the server
