### ISSUE TITLE
Category Product Count Not working

### ISSUE THREAD

**Issue by gsc1ugs** [opencart/opencart#2893]
Click the Category Product Count option and it just shows zero for all subcats - OC 2.0.2.0

**Comment by stockmaster** [comment]
has a small feeling you gonna feel the wrath of Daniel the Great!

**Comment by gsc1ugs** [comment]
Pray tell why?

**Comment by gsc1ugs** [comment]
Ok, lets sort this now!! where do bugs go opencart? or here? whats this for and why on opencart do they point me to github for bugs

**Comment by stockmaster** [comment]
On the front page of Github, worth reading - https://github.com/opencart

"Reporting a bug

Read the instructions below before you create a bug report.

Search the OpenCart forum, ask the community if they have seen the bug or know how to fix it.
Check all open and closed issues on the GitHub bug tracker.
If your bug is related to the OpenCart core code then please create a bug report on GitHub.
READ the changelog for the master branch
Use Google to search for your issue.
Make sure that your bug/issue is not related to your hosting environment.
If you are not sure about your issue, it is always best to ask the community on our bug forum thread

Important!

If your bug report is not related to the core code (such as a 3rd party module or your server configuration) then the issue will be closed without a reason. You must contact the extension developer, use the forum or find a commercial partner to resolve a 3rd party code issue.
If you would like to report a serious security bug please PM an OpenCart moderator/administrator on the forum. Please do not report concept/ideas/unproven security flaws - all security reports are taken seriously but you must include the EXACT details steps to reproduce it. Please DO NOT post security flaws in a public location."
-------------------

The words "SURE" apear at least 4 times there. 
Please be SURE before reporting.
Do your own tests, and give as much info as possible, you are doing 1 line reports that contain nothing. is like guessing game.

**Comment by gsc1ugs** [comment]
Ok so the way your talking this is not a bug? Ive searched here and opencart found nothing, 0 is product count in all categories, id say a typo or bug

**Comment by stockmaster** [comment]
First of all: 
System -> Settings -> [edit] -> Option -> Category Product Count -> ?!
Is that set to Yes or No?

**Comment by osworx** [comment]
@gsc1ugs: no more nerving messages in the forum?
As said this afternoon: until now, all problems are based on you or on your settings.
Guess same here.

It does not mean because you have found nothing, that it could be not a bug, etc.
But I would rather say, that no one except you has this trouble(s).
Conclusion: not the software is the 'evil' ...

**Comment by gsc1ugs** [comment]
Set count to yes, get zeros, set to no it doesn't count so its half right

**Comment by osworx** [comment]
If 0 (zero) => no products, otherwise amount of products is displayed.
![kategorie_zaehler](https://cloud.githubusercontent.com/assets/1905204/7076823/6a14dfe8-df0c-11e4-962d-87ea760930e0.png)

**Comment by gsc1ugs** [comment]
Thats what should happen yes, category has products but says zero

**Comment by stockmaster** [comment]
Cant reproduce, all looks fine my side.
You might want to let someone - with skills (not me) to have a look at your backend. 
But this is clearly forum realm not here.

**Comment by gsc1ugs** [comment]
Which file does the count?

**Comment by beifloyd** [comment]
Not a bug. All works as expected. 
getTotalProducts() public function in catalog/model/catalog/product.php
$sql = "SELECT COUNT(DISTINCT p.product_id) AS total";

**Comment by osworx** [comment]
@gsc1ugs you are wasting everybodies time.
Either provide an URL to that shop and let some dev look over that, or stop such messages.

**Comment by gsc1ugs** [comment]
Shows zero in both these categories, one has 13 and the other has 6 ... and if reporting bugs is a waste of time i will cease using github
![github](https://cloud.githubusercontent.com/assets/11752019/7084581/ae548186-df66-11e4-9345-665474e7d136.jpg)

**Comment by osworx** [comment]
As said: no on else has this troubles.
Give a dev access to your shop and we can check if this is a bug, while I do not expect to find one.

**Comment by GomDani** [comment]
What displaying pagination results on the category page? It is the right amount of items.

**Comment by gsc1ugs** [comment]
Ok, I found the problem, there is a new table used in new version but I managed to import all data with a few changes to import queries BUT... BUT... ARGH!!! new table screwing it all up . oc_category_path not in the old version, if someone can tell me what PATH_ID is leading to it will help sort out the id's and I believe level refers to where it sits on the page?. Thxs in advance

**Comment by stockmaster** [comment]
Heres your problem. You been tinckering so much with things now you dont know what is what.
But it shows if YOU dig down enough you can find things, so why jump the gun do 1 line reports?
as for example, Whats Old version? whats NEW version? 1.5 - 2.0?
2.0.1 - 2.0.2?

**Comment by gsc1ugs** [comment]
1.5.6 to 2.0.2.0 obv, that table was not touched, i just need know what path.id points to

**Comment by stockmaster** [comment]
ah well, obviously you know what you doing

**Comment by osworx** [comment]
Before Daniel is closing this thread - and he is right with that - move that discussion to the forum where it belongs!

**Comment by stockmaster** [comment]
@osworx daniel already did :D
