### ISSUE TITLE
Bug in admin/controller/module/bestseller.php

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#2936]
For OpenCart 2.0.2.0:

Line 80 in admin/controller/module/bestseller.php should be like this:

````
				'href' => $this->url->link('module/bestseller', 'token=' . $this->session->data['token'], 'SSL')
````

instead of

````
				'href' => $this->url->link('module/banner', 'token=' . $this->session->data['token'], 'SSL')
````

**Comment by stockmaster** [comment]
Pull request please? ;) seems like a copypaste typoish!

**Comment by mhcwebdesign** [comment]
If I were to create a fork for the sake of submitting a pull request each time I report a simple bug, believe me I'd end up with so many github accounts it's not funny any more!

Github is a very user-unfriendly system, simple  things like synchronizing a fork with the latest changes from the master branch, including comments, is just a nightmare. Github tends to prevent one from being productive.

**Comment by stockmaster** [comment]
@mhcwebdesign 
a) you can create forks, and forks of your fork (as well as delete them) under ONE account only
b) dont bother, i will do it
c) Thank you

**Comment by mhcwebdesign** [comment]
Hmm, multiple forks under one free github account? Last time I tried it wouldn't allow me to do so, I'll have to try it again.

**Comment by stockmaster** [comment]
you would be surprised :D

**Comment by mhcwebdesign** [comment]
This still leaves me with the problem of finding a more user-friendly way of merging changes from an upstream repository with a fork, github suggests this cumbersome procedure: 

https://help.github.com/articles/syncing-a-fork/

**Comment by stockmaster** [comment]
no noooo!
i will explain in a moment let me get my coffe! lol (but all is website based, here)

**Comment by stockmaster** [comment]
So 1st Part, to submit a patch:
Lets assume you have your own fork already. (will do the examples exactly for this bug here)

Go to https://github.com/opencart/opencart/blob/master/upload/admin/controller/module/bestseller.php
Click on the Cryon icon -> top right corner

notice the message:
You're editing a file in a project you don't have write access to. Submitting a change to this file will write it to a new branch in your fork stockmaster/opencart, so you can send a pull request. (so this will make like a patch-xx as a sub fork of yoru fork)

Go to line 80, change module/banner to module/bestseller

Look under the code box.
Add, a description and title -> Propose file Change
THis will on it own crate a pull request for THAT change along

Note: If you change your master in your branch, is harder to isolate small changes like this from all other commits you made over time when doing a pull request. therefore this patch-x is a best option.

P.S. i am not good at github, all this is trial and error
p.s.2 lol, i will post the how to synch your branch from master/other branches in a moment

**Comment by stockmaster** [comment]
Part 2: How to synch your branch from Master repository or, other branches:

I assume, you should have already a fork (MyFork) of the common repo (BaseRepo) which has the pending pull request from a fork (OtherFork) you are interested in.

Navigate to the fork (OtherFork) which has initiated the pull request which you like to get into your fork (MyFork)
Go to the pull requests page of OtherFork
Click new pull request
The pending pull request(s) should be offered. Select on the left side as the base fork your fork (MyFork) (IMPORTANT)
Now the option of View pull request should change to Create pull request. Click this.
Now you should have a pending pull request in your fork (MyFork), which you can simply accept.

**Comment by danielkerr** [comment]
fixed
