### ISSUE TITLE
Admin order edit attempting to query products instead of order products

### ISSUE THREAD

**Issue by veksen** [opencart/opencart#2997]
In sale/order/edit, on page load, the products are correctly loaded (`$products = $this->model_sale_order->getOrderProducts($this->request->get['order_id']);`) in [admin/controller/sale/order.php:751](https://github.com/opencart/opencart/blob/master/upload/admin/controller/sale/order.php#L751).

However, when going to the products tab, products are called through the API (`api/cart/products`) [admin/view/template/sale/order_form.tpl:963](https://github.com/opencart/opencart/blob/master/upload/admin/view/template/sale/order_form.tpl#L963) though an AJAX call, sending us to [catalog/controller/api/cart.php:138](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/cart.php#L138), which is itself sending us to this [query](https://github.com/opencart/opencart/blob/master/upload/system/library/cart.php#L43):

`$product_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "product p LEFT JOIN " . DB_PREFIX . "product_description pd ON (p.product_id = pd.product_id) WHERE p.product_id = '" . (int)$product_id . "' AND pd.language_id = '" . (int)$this->config->get('config_language_id') . "' AND p.date_available <= NOW() AND p.status = '1'");`

Of course, only getting us available products. So it's impossible to edit an order where a product is not available (anymore).

**Comment by danielkerr** [comment]
so make it available or void the order.

i keep telling people this. 

you should not edit orders set it as void and create a new one.

**Comment by danielkerr** [comment]
actually it might be better to have a warning message at the top of the order edit page to say it contains products unavailable.

**Comment by veksen** [comment]
still an error in the code, not a user issue. users are allowed to edit orders, and they will do it.

**Comment by veksen** [comment]
Plus, it's a perfectly valid use case to edit the status of an order (make it shipped). It's possible to ship an order where products are not available anymore, but were available in the order. Are you with me on this one? I don't really know why the AJAX call is made in the first place.

**Comment by danielkerr** [comment]
@veksen

"still an error in the code, not a user issue. users are allowed to edit orders, and they will do it."

wrong!

users can do a lot of things that are wrong. its down to the the internal company policy to make sure staff are not editing orders. otherwise their taxes will not add up at the end of the year!

"Plus, it's a perfectly valid use case to edit the status of an order (make it shipped). "

you don't change the order status via the order editor! you do it via the info page. you need to learn how to use software properly.

"t's possible to ship an order where products are not available anymore, but were available in the order."

im not arguing with you. I have more experience at running online shops than you do and also know the law for creating invoices.

again I will explain to you! you void the order because that order is no longer valid and create a new order for the customer.

"I don't really know why the AJAX call is made in the first place."

Unless you want to double the amount of code for the order totals, payment methods, shipping methods and about a million other things it should all be done from the front end. most carts require api access so they can import orders into different systems. so its killing 2 birds with one stone.

don't post a bug report here again. you are only reporting how you think something should work.
