### ISSUE TITLE
File Upload doesn't work for PDF files (Incorrect file type)

### ISSUE THREAD

**Issue by Frank1279** [opencart/opencart#3043]
PDF files seem to have a wrong MIME file type, sometimes it's set to "application/download" instead of "application/pdf". I have created three pdf files with three different softwares, and after uploading them, the server returned the error "Incorrect file type".

How to reproduce the issue (Tested on Opencart 2.0.2.0 only): 
- Go to Catalog -> Download
- Upload a PDF file;
The server returns the error "Incorrect file type"

Fix:
In the Store Settings, Tab "Server", add the following MIME file type:

application/download
"application/download"

**Comment by danielkerr** [comment]
adding application/download will probably allow anything to be upoloaded.

**Comment by adrianrosian** [comment]
This is due to a bug in Firefox, https://bugzilla.mozilla.org/show_bug.cgi?id=373621

Firefox incorrectly sets the uploaded file mime type to "application/download", even for pdf files that were not downloaded. This in turn makes the file manager deny uploading, even with extensions such as "Upload manager". The fix is to delete the file 'mimeTypes.rdf' from the firefox profile

@danielkerr you might not want to close this sort of issues before investigating, they might reveal deeper problems. This is not a OC bug, but it is good to be aware of
