### ISSUE TITLE
Installer check for Curl HTTP Loopback support

### ISSUE THREAD

**Issue by qphoria** [opencart/opencart#3062]
I do a lot of upgrades to 2.x and I think about 35% of people's servers DO NOT support curl http loopback which means the API calls throw an ajax error and people cannot do any of the API calls like edit orders or update order history. This is a pretty major showstopper and I think a check should be done during install to see that curl loopback is enabled.

The easiest way would be to simply attempt a curl call to the main install index and either check the response isn't empty, or use curl_getinfo() to check the http_code. This returns "0" on sites that do not have loopback enabled.

It should also be documented somewhere explaining the issue. Backupbuddy for Wordpress has some info for their own system here: http://ithemes.com/codex/page/BackupBuddy:_Frequent_Support_Issues#HTTP_Loopback_Connections_Disabled

**Comment by sculptex** [comment]
I second that. My hosting did not really understand the issue when I tried to explain and wanted to start poking around in the software. So there definitely needs to be an official page to explain the issue that people can direct their hosting to.
That said, considering over 1/3rd have this problem, isn't it a bit unrealistic to expect so many to get their hosting to change to accommodate this? If less than 5% maybe but 35%? So perhaps there should be a workaround which would only be enabled if the issue was identified on install.

**Comment by exit15** [comment]
I posted a comment at https://github.com/opencart/opencart/issues/3062. Don't know if this makes sense, but would it not be better if supporting curl http loopback was not a "requirement"? My server supports loopback, but when trying to use CDN service like Cloud Flare I got the same error because of the way they handle DNS routing.

**Comment by qphoria** [comment]
The design really isn't bad, it's just unfortunate that servers are not willing to enable it.
The only workaround I have would be to create a subdomain and have a redirect script on that subdomain to bounce around the servers, thus bypassing loopback. I am making a script for that for a client of mine. We shall see if it works

**Comment by danielkerr** [comment]
can changing the url to local host or 127.0.0.1?

**Comment by danielkerr** [comment]
Ok i have a solution. Need to set a config value so a sub domain can be used. Maybe api.yourstore.com

**Comment by danielkerr** [comment]
that did not work either. looks like i'm rewriting the order editor system

**Comment by juankadiaz** [comment]
Hi! I have the same bug!! any news on this?

Thank you very much for contributions.

**Comment by sculptex** [comment]
How is this closed? Daniel have you approved this? So many changes here, far more than just curl issue fix.
Addition of define.php, admin/define.php, system/library/client.php, system/library/modification.php, system/library/trigger.php, system/library/utility.php,
Is this where opencart is going otherwise this will surely break with next release?

**Comment by qphoria** [comment]
Daniel has rewritten it to use another method in the next version. Meanwhile I have a work around here: http://forum.opencart.com/viewtopic.php?f=34&t=146714#p567180

**Comment by danielkerr** [comment]
i closed the issue because some d*** head is trying to market their project via github.
