### ISSUE TITLE
Properly handle errors on sites with curl http loopback disabled

### ISSUE THREAD

**Issue by qphoria** [opencart/opencart#3063]
See this issue first to understand the problem: https://github.com/opencart/opencart/issues/3062

On sites that have this loopback disabled, the ajax callback error isn't handled and it throws an ugly "Syntax Error: Unexpected end of message" or "Unknown index: json" or something to that point. You can see it easily when trying to add order history or edit an order in the admin.

**Comment by exit15** [comment]
I have struggled with this error, but it was not inherent to my server. I have tried to use Could Flare and it seems that this error (cannot update order history) has to do with they way they rout DNS. As soon I disabled DNS rerouting on CF the problem went away. So while I'm not savvy enough to identify the underlying problem as "curl http loopback" I think it goes beyond ones server and a solution must be found so that OpenCart will function properly regardless of the server blocking loopback or a third party service like CF creating the same effect as blocking loopback.

**Comment by danielkerr** [comment]
Could Flare you need to make sure the ip of the server can get through.

**Comment by qphoria** [comment]
This is not a cloud flare issue. That's just another variable in the mix.
This happens on any server without curl loopback support and the errors
simply need to be handled in the code

**Comment by exit15** [comment]
Thanks D.  FYI - using the default settings of CF and after review I see that the server's IP is whitelisted under the firewall tab.

**Comment by exit15** [comment]
Hi... i opened a case with CF. They are asking for an example of the cURL requests that OpenCart is sending? any idea what I should give them?

**Comment by qphoria** [comment]
http://yoursite.com/index.php?route=api/login

**Comment by exit15** [comment]
Hi Q! this is what I got from the CF folks. They tried to activate and deactivate the service.

Can you provide the full request to that URL? Is there data that needs to be sent along with it? I'm just getting:
{
error: "Warning: No match for Username and/or Password."
}
 Eric
 CloudFlare | Support Engineer

**Comment by qphoria** [comment]
That is all you need. If you get the error, then loop back works. If you
get no message and http code 0 that means it didn't work
