### ISSUE TITLE
Undefined variable: entry_captcha in

### ISSUE THREAD

**Issue by bajpangosh** [opencart/opencart#3068]
this Version 2.0.3.1 shows errors in theme 
Undefined variable: entry_captcha in

product_detail_hitech.tpl

and contact us page how do i fix this issue

**Comment by haxcop** [comment]
Hi, i recently have this error and it was because i have a custom theme that do not support the integration with re-captcha and it has the old captcha, so i disable the google re-captcha and works with the old one. try it in this way and let me know if it works for you. other solution i don't know and i will be all ears to anyone here. Thanks!

**Comment by bajpangosh** [comment]
am Google reCAPTCHA still got this error

**Comment by haxcop** [comment]
be sure you refresh your modifications, cache & cookies  after the following steps and try again, 
disable google re-captcha
Allow Reviews Yes 
Allow Guest Reviews  No
New Review Alert Mail Yes
This works for me.
if still not working it may be a theme error. and must consult with your theme dev's

**Comment by bajpangosh** [comment]
Thank you :)

**Comment by haxcop** [comment]
Glad to help,
You welcome.
