### ISSUE TITLE
i got this issue when i try to change status order #3072

### ISSUE THREAD

**Issue by gilas1959** [opencart/opencart#3087]
I hope you can answer to the previous issue and clarify.
You closed the issue without give any answer.
thank you

**Comment by milimar** [comment]
I will try to save you from the rage of Daniel. He has closed your previous issue because he considers it is not a bug related to the core of Opencart, and he usually closes a lot of issues without an explanation, because he claims he doesn't have time to answer all that issues that are personal problems and not bugs in opencart. So, better try to obtain an answer at the forum http://forum.opencart.com .

Greetings.

**Comment by gilas1959** [comment]
Thank you very much, this is an *answer* but keep note that I tried *all* suggestion found in the forum.
Moreover, you say that your developer expressed 'rage'. 
My ask was very simple: "there is a problem with DNS? If yes, I waited and expleced for an answer in this sense."
As currently I'm using some other CMS and carts, frequently I install some software on my PC and network without a DNS, and found always help from developers.
The previous O.C. seems to work correctly in this way. I suppose that If something goes wrong due to DNS miscofigured, this should be documented to avoid that new people fall with this error.
thank you

**Comment by gilas1959** [comment]
Hi staff and thank you very much for your patience and precious work.
I solved myself, adding the constant

HTTPS_CATALOG

in config.php

This should be (I suppose) a new constant used since 2.0; the config.php used came from previous 1.5.4.x

**Comment by danielkerr** [comment]
@milimar do you want to be banned?

I close a issue down without replying means its a waste of time!

**Comment by milimar** [comment]
@danielkerr , you are right, I should not have made that comment, sorry. I do not apologize because I am afraid of banning, I apologize because you are right.
