### ISSUE TITLE
Fatal error: Call to undefined method ModelAffiliateAffiliate::deleteLoginAttempts()

### ISSUE THREAD

**Issue by Uniarts** [opencart/opencart#3116]
When a customer wants to register to affiliate program there is:
Fatal error: Call to undefined method ModelAffiliateAffiliate::deleteLoginAttempts() in /home/.../public_html/vqmod/vqcache/vq2-catalog_controller_affiliate_register.php on line 21

and after when someone affiliate login: 
Fatal error: Call to undefined method ModelAffiliateAffiliate::getLoginAttempts() in /home/.../public_html/vqmod/vqcache/vq2-catalog_controller_affiliate_login.php on line 124

and there is no possibility to login

-------------------EDIT ------------------------------------
opencart ~~2.0.3.1~~  not affected with this bug
**Latest OpenCart 2.0.3.2_rc** until commit 4,474 https://github.com/opencart/opencart/commit/feffa3a2d82e6176b554e3717df8917a1aa30dae  has this error >>> but **@mrnfrancesco** applied this fix https://github.com/opencart/opencart/pull/3117 [Fixed call to undefined methods and calling method on null object] (https://github.com/mrnfrancesco/opencart/commit/f9105bf21b9b3d77cfde69578a46f0e39e6bfdfc). I tested on a live site and the fix worked.

**Comment by kanenas** [comment]
@Uniarts this is a bug tracker. Please ask for help here http://forum.opencart.com/ or you could just delete the **vQmod** that generates the fatal error.

**Comment by mrnfrancesco** [comment]
@Uniarts is right. I do not have vQmod installed and can reproduce the error.

**Comment by Uniarts** [comment]
@kanenas Sorry for my ignorance but are you sure that this is not a bug?

**Comment by mrnfrancesco** [comment]
@Uniarts yep, it is a bug. It depends on these lines (as you suggested):

catalog/controller/affiliate/register.php
```
// Clear any previous login attempts in not registered.
$this->model_affiliate_affiliate->deleteLoginAttempts($this->request->post['email']);
```
and
catalog/controller/affiliate/login.php
```
// Check how many login attempts have been made.
$login_info = $this->model_affiliate_affiliate->getLoginAttempts($this->request->post['email']);
```

The problem is that in affiliate model (catalog/model/affiliate/affiliate.php) there are no methods like `deleteLoginAttempts` and `getLoginAttempts`.

**Comment by milimar** [comment]
I tested this on my oc 2.0.3.1 and here are the results...no errors, please someone else check this too.

![affiliate](https://cloud.githubusercontent.com/assets/9386798/8264207/9e0bf656-16e3-11e5-8302-64f089edbfd5.jpg)

![affiliate-login](https://cloud.githubusercontent.com/assets/9386798/8264208/a2d2c8a4-16e3-11e5-9994-21b13de452ba.jpg)

**Comment by mrnfrancesco** [comment]
This bug was introduced with a recent commit (a few days ago). OC 2.0.3.1 is not affected.
I'm fixing it!

**Comment by milimar** [comment]
@Uniarts said that he used OC 2.0.3.1.

**Comment by Uniarts** [comment]
@mrnfrancesco and @milimar thanks both of you. I am sorry again. I have last opencart until commit 4442 https://github.com/opencart/opencart/commit/6bdc37dd654f109a239b6744a0012f371b2fd590

**Comment by mrnfrancesco** [comment]
@milimar you are right. This bug was introduced with commit 32cb600a2621c00a300bbac1cf17721d9a5cda59 which is still OC 2.0.3.1
Probably you have the same version, but some commit behind.

**Comment by Uniarts** [comment]
@mrnfrancesco Very nice.

**Comment by mhcwebdesign** [comment]
Opencart 2.0.3.1 has this in catalog/model/affiliate/affiliate.php:

```
	public function getLoginAttempts($email) {
		$query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "affiliate_login` WHERE email = '" . $this->db->escape(utf8_strtolower($email)) . "'");

		return $query->row;
	}

	public function deleteLoginAttempts($email) {
		$this->db->query("DELETE FROM `" . DB_PREFIX . "affiliate_login` WHERE email = '" . $this->db->escape(utf8_strtolower($email)) . "'");
	}
```
I am unable to reproduce above mentioned error. Not a bug!

**Comment by mrnfrancesco** [comment]
Just look at last affiliate model commit at https://github.com/opencart/opencart/blob/master/upload/catalog/model/affiliate/affiliate.php : it has not those methods.
Probably you have not the last version.

**Comment by mhcwebdesign** [comment]
The original poster claimed to use to OpenCart 2.0.3.1 where this issue doesn't exist. You are talking about OpenCart 2.0.3.2_rc' where these methods were indeed removed. 2.0.3.2_rc' is not recommended to be used in live stores, it is work in progress.

**Comment by mrnfrancesco** [comment]
even if this issue is intended to be for version 2.0.3.1, it highlighted an issue in the latest version. 
The goal of my related pull request is to fix the bug. If previous version has not this bug I'm happy for you, but I really don't care because 2.0.3.2 is a release candidate, so it is intended to be released soon or later.

The right solution is to modify the issue description, not to say that the bug doesn't exists.

**Comment by milimar** [comment]
Somehow you are all right. Today I tested for the affiliate problem and discovered that it doesn't work properly. The test is performed on a clean installation of OC 2.0.3.2_rc from today.

1. When I try to register as an affiliate, I obtain this error: 

Fatal error: Call to undefined method ModelAffiliateAffiliate::deleteLoginAttempts() in /home/milimari/public_html/oc32rc/catalog/controller/affiliate/register.php on line 20

Please note that however, the affiliate will appear in admin panel, but if you try to edit it, then you have a huge number of errors.

2. I tried the fix of @mrnfrancesco , but unfortunately it doesn't work neither, because after applying the fix and trying to register as an affiliate, I obtain this error:

Fatal error: Call to a member function deleteLoginAttempts() on a non-object in /home/milimari/public_html/oc32rc/catalog/controller/affiliate/register.php on line 21

The affiliate will appear as registered in admin panel, but yet,  if you try to edit it, then you have a huge number of errors.

To avoid the confusion, after applying the fix of @mrnfrancesco , the error is located on line 21 because I commented the line 20 and inserted the fix on line 21.

**Comment by milimar** [comment]
I have to mention that  the official release of OC 2.0.3.1 is not affected with this bug.

**Comment by mrnfrancesco** [comment]
@milimar my fault, I forgot to commit the whole fix.
Just try with the latest one in pull request #3117 and let me know.

**Comment by milimar** [comment]
@mrnfrancesco , your fix works when is about registering as an affiliate, but there is still a problem when  editing the affiliates in the admin. Try to edit an affiliate an you will see a pop up box with errors.

**Comment by mrnfrancesco** [comment]
The pull request rules say that each request has to be related to just one issue, so I cannot fix the admin affiliate issue too.

I suggest you to open a new issue, because it is a different bug related to an ajax call to the inexistent method `country` in `admin/controller/marketing/affiliate`.

Meanwhile, I'm working on it! I'll make a new pull request as soon as possible to fix it.

**Comment by mrnfrancesco** [comment]
@milimar take a look at pull request #3122 (related to issue #3121) to fix your problem in admin panel.

**Comment by milimar** [comment]
@mrnfrancesco you are great! You have fixed the issue, it works perfectly!
