### ISSUE TITLE
Option value list layout issue

### ISSUE THREAD

**Issue by tvanbeek** [opencart/opencart#3201]
In Admin, Catalog->Options Edit or Add. The table with the list of option values has a layout issue, see screenshot. This is also the case in OC2.0.3.1. I dont see the problem in Safari but it does show on OSX Chrome Version 44.0.2403.89 (64-bit).

![image](https://cloud.githubusercontent.com/assets/3518980/8889616/e5964d5e-32e1-11e5-8dd7-384336622148.png)

**Comment by milimar** [comment]
Yes, I just recreated this error on Chrome browser, and can confirm that Mozilla Firefox is note affected.

**Comment by danielkerr** [comment]
the demo site is the first version of 2.0

not sure which version you are using but i can not replicate this.

**Comment by milimar** [comment]
I recreated this error using OC 2.0.3.1, but this days I had to reinstall my PC, and today checked again for this error, but it doesn't exist. Recently I started using Mozilla Firefox, because Chrome was causing me several problems that Mozilla didn't. So, conclusion, it is not an OC bug, but Chrome error. 

@tvanbeek , try to reinstall your Chrome, it is pretty sure that you won't face this error again.
