### ISSUE TITLE
Annoying sample data

### ISSUE THREAD

**Issue by costa974** [opencart/opencart#3210]
It's incredibile that there's no option to delete or not to install the sample data!

**Comment by costa974** [comment]
Ho can I delete sample data?

**Comment by milimar** [comment]
@costa974 , you cannot ask question here about OC, because this is a place for bug reporting. 
If you find any bug in OC, you should report it here, but if you have any questions related to OC, then please use the official forum of OC http://forum.opencart.com . 
I hope this explanation was helpful...
