### ISSUE TITLE
Please add textarea for Google Tag Manager (OpenCart 2.0.3.1)

### ISSUE THREAD

**Issue by VadymVolos** [opencart/opencart#3238]
Please add textarea for Google Tag Manager (OpenCart 2.0.3.1)
Code need after teg < body>

Code of course you can add manually.
(catalog/view/theme/YOURTHEME/template/common/header.tpl)
But after updating thames, or update engine, code is erased.

**Comment by danielkerr** [comment]
no idea what you are talking about

**Comment by VadymVolos** [comment]
In the admin panel OpenCart need the ability to embed code from Google Tag Manager.

**Comment by danielkerr** [comment]
you mean you want your site to do this! i dont work for you. pay a developer or look or an extension.

**Comment by VadymVolos** [comment]
I thought OpenCart is a joint project?
And we all do it together.

From what you say, this is your personal project?

**Comment by haxcop** [comment]
Guys this is a simple mistake and there's no point to discuss for this... 
@vadymvolos you can add the google tag manager snippet instead the google analytics ;_) 

Remember that google tag manager you can add all the G's association like analytics, adwords and etc... 

It works really well and as it should be , because the principe to add any of those tracking service are the same. 
You can do more research,  studies or hire a developer to do it for you. As Daniel said...




Yours faithfully 
Carlos Lozada
