### ISSUE TITLE
Wrong redirect

### ISSUE THREAD

**Issue by GomDani** [opencart/opencart#3276]
On shipping estimate and review form, when press enter and input field is focused redirected on home page. Maybe also on some other forms . I didn't checked.

**Comment by danielkerr** [comment]
there is no redirect on the review form.

**Comment by GomDani** [comment]
On Firefox and Chrome I try and when click on name field and press enter redirect me on home with form values in url.

**Comment by hotwer** [comment]
Yes, there is a bug on `checkout/cart` route.
The `$shipping` variable is populated with the index of `total/shipping` controller.
Since the shipping is a formulary...

```php
<form class="form-horizontal">
    // zone code...
    <div class="form-group required">
      <label class="col-sm-2 control-label" for="input-postcode"><?php echo $entry_postcode; ?></label>
      <div class="col-sm-10">
        <input type="text" name="postcode" value="<?php echo $postcode; ?>" placeholder="<?php echo $entry_postcode; ?>" id="input-postcode" class="form-control" />
      </div>
    </div>
    <input type="button" value="<?php echo $button_quote; ?>" id="button-quote" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-primary" />
</form>
```

Since there's a formulary, the default way the browser handles the enter (since there's button in the formulary) it's to send with default settings (it performs a get with and empty action). 

The problem is, the button is supposed to be performing an ajax call.
Either the way is to handle the enter press on any fields, to perform the button click, os just prevent the default submit action.

To be honest, I think it's better to turn the enter action to behave as clicking the button, but's that's just my opinion.

**Comment by danielkerr** [comment]
it wont submit the form if the button is set to type button.

**Comment by danielkerr** [comment]
it does it on shipping

**Comment by GomDani** [comment]
This is url after click on name field and press enter in review form:

http://localhost/gombac_2/index.php?name=&text=
