### ISSUE TITLE
Typo and Suggestion on OC 2.1.0.1

### ISSUE THREAD

**Issue by hendrachristian** [opencart/opencart#3494]
Just reporting some typo and giving suggestion. I'll add as I see them.

**Typo:**
admin/language/english/sale/order.php
Line 25:
$_['text_shipping_address']      = 'Shipping Adress';
*should be*
$_['text_shipping_address']      = 'Shipping Address';

Line 31:
$_['text_shipping_custom_field'] = 'Shipping Adress Custom Fields';
*should be*
$_['text_shipping_custom_field'] = 'Shipping Address Custom Fields';

Line 78: (inconsistent with others)
$_['column_weight']              = 'Product weight';
*should be*
$_['column_weight']              = 'Product Weight';

**Suggestion:**
1. Change the date_added from "12/10/2015" to "12 Oct 2015 08:33AM" for better legibility on invoice and shipping notes
admin/language/english/english.php
Line 6: after line add
$_['date_format_datetime']             = 'd M Y H:iA';

admin/controller/sale/order.php
Line 1733, 1943:
'date_added'       => date($this->language->get('date_format_short'), strtotime($order_info['date_added'])),
*changed to*
'date_added' => date($this->language->get('date_format_datetime'), strtotime($order_info['date_added'])),

**Comment by Tangol** [comment]
:+1:

**Comment by OpenCartAddons** [comment]
Submitted a PR for the typos you mentioned.

I didn't include the changes to the date format as this should be a separate PR.  I do agree with making it more legible.  

Perhaps instead of using a language variable for the datetime format it should be a config field in the settings?  This way it's easy for any site admin to customize it to their liking without having to modify the core language files.


Cheers,
Joel.

**Comment by hendrachristian** [comment]
I seconded the datetime format settings on admin. It would be much easier to change than in core language files.

As of now, people with different region (diff date format) can misunderstood the information if it's just 8/10/2015 (ie. d/M/Y and M/d/Y).

**Comment by danielkerr** [comment]
ok add a suggest for the date time. im closing this as the requested typos changes have been fixed

**Comment by BinotaLiu** [comment]
OpenCart use a language key "date_format_long" for display a detailed format of date time.
In other language, we may need to use a custom string for displaying the day of the week,
for example, in English, we use Sunday to Saturday for a week,
日曜日 to 土曜日 in Japanese, and 星期一 to 星期日 in Chinese.

Since OpenCart using php's build-in function "date" to displaying a formatted date time,
we have been limited to show the day of the week in English.

Maybe we need to write a date time helper to format the date time in other language?
