### ISSUE TITLE
Search Engine Friendly Urls not used everywhere

### ISSUE THREAD

**Issue by ChangePlaces** [opencart/opencart#3673]
For the categories and products, there are links to the SE friendly urls, but the logo, and the whole checkout process uses non-friendly urls. 2.1.0.1

**Comment by drkskwlkr** [comment]
@ChangePlaces : I wonder why you considered this a bug? This is the way OC is designed to work, and even if it worked otherwise, 'URL friendly' checkout pages have zero SEO value.

If you want to make these easier on the eyes, you could do a simple rewrite via the .htaccess in your root directory. Here is what I have in mine:
```
RewriteRule  ^home/$  index.php?route=common/home [L] #Home Page
RewriteRule  ^contact/?$  index.php?route=information/contact  [L] #Contact Page
RewriteRule  ^account/?$  index.php?route=account/account  [L]  #Account Page
RewriteRule  ^login/?$  index.php?route=account/login  [L]  #Login Page
RewriteRule  ^logout/?$  index.php?route=account/logout  [L]  #Logout Link
RewriteRule  ^cart/$  index.php?route=checkout/cart  [L] #Cart Page
RewriteRule  ^checkout/$  index.php?route=checkout/checkout  [L] #Checkout Page
```

You can extend this to other resources, but it is pointless to have a 'friendly logo URL'. The logo *could* benefit from being tagged on the homepage as an OpenGraph element via og:img, or as a TwitterCard via twitter:picture (but Twitter will dig OG markup too).

**Comment by ChangePlaces** [comment]
It isn't so much for the search engines, but the user. a url like `/checkout/cart` is much nicer to see than `index.php?route=checkout/cart`

**Comment by danielkerr** [comment]
stop wasting my time!

**Comment by ChangePlaces** [comment]
Reporting bugs is wasting your time? I'm sorry to have to report on how terrible your software is.

You've wasted mine (and everyone elses) time having to evaluate your appalling software and decide it's more holier than the bible...or something and keep away from it. Whilst you're turning a blind eye to things that need doing, opencart will be driven into the ground.

Godspeed.

**Comment by jamesallsup** [comment]
And that kind of comment is exactly why you will be shortly banned from this project.

Your report was not a bug, you can't be bothered to read the readme and you vent your unwanted opinion to those who can be bothered to reply and follow the rules. So yes, your wasting valuable time to people who work on actual bugs. @drkskwlkr gave you a perfectly reasonable bit of advice and you should have closed your own issue first before one of the admins had to look into it.

https://github.com/opencart/opencart
