### ISSUE TITLE
Bug in catalog/controller/feed/google_base.php

### ISSUE THREAD

**Issue by volodyahome** [opencart/opencart#3682]
Hello!
Array $product_data in line  31 all empty and check does not work because the array is not filled!
Merchants google show errors in products.
Paste please between lines 31 and 32 $product_data[] = $product['product_id'];

**Comment by volodyahome** [comment]
Why my issue has been closed?

**Comment by mneilly** [comment]
I see the same issue and am getting duplicate entries in the feed xml as a result. As volodyahome indicated, _$product_data_ is created as an array and it is checked by _in_array_ but nothing is put into it so duplicate products are not avoided.

This means that the feed is broken for any item that has more than a single category because a duplicate entry is generated and Google's feed processing flags it as a "Duplicate item" error.

OpenCart clearly allows more than one so using the first one seems reasonable but duplicates break the feed which is obviously a problem.

```
$product_data = array();
...
	$products = $this->model_catalog_product->getProducts($filter_data);
	foreach ($products as $product) {
		if (!in_array($product['product_id'], $product_data) && $product['description']) {
```
