### ISSUE TITLE
OcMod loads Admin modifications in Frontend

### ISSUE THREAD

**Issue by basvandenberg77** [opencart/opencart#3684]
Problem: OcMod loads Admin modifications in Frontend because (I think) Installatron defined DIR_CATALOG in config.php.

More: 
https://forum.opencart.com/viewtopic.php?f=183&t=154953&p=592503#p592503

**Comment by bzark** [comment]
I ran into this issue as well, not an OpenCart issue, it is an Installatron issue.  I made Installatron aware of this as well.

https://forum.opencart.com/viewtopic.php?f=191&t=154782#p592030

**Comment by basvandenberg77** [comment]
Nice work. I reported it in the issue tracker on github but its indeed not an opencart issue. However it would be better to use a variable is_frontend in the config instead.
Bas

Verstuurd vanaf Bas iPhone

**Comment by kalpeshdesai20** [comment]
I am having same issue of path in ftp module because of Installatron of GoDaddy as they have not still changed their code. please inform godaddy again because I have wasted so many days to solve this error because I don't have knowledge of codding. I could have been left opencart but in last fortunately I came to know this issue and I fixed it.

**Comment by bzark** [comment]
@kalpeshdesai20 I already informed GoDaddy, they informed Installatron and I also informed Installatron.  That is the best you can do.  Call GoDaddy yourself, I was on the phone 45 minutes because they had to do a code review before they could submit the bug to Installatron.

**Comment by kalpeshdesai20** [comment]
Ok not an issue. thankx for buddy for quick reply.
apart from this I want to ask, as per your accordance, which is the best to install opencart. either installing opencart using Instalatron or manually ?

**Comment by bzark** [comment]
I would think Installatron being they applied a patch to fix some bugs but it is hard to say because they didn't reference any OpenCart forum patch in the description.  All they wrote was what is below and that is pretty vague.

This version was originally withheld due to issues discovered during our QA process. These concerns have been remedied through a patch available on the OpenCart forums.

**Comment by kalpeshdesai20** [comment]
means installation manually is good way.

**Comment by GomDani** [comment]
O
2. dec. 2015 18.16 je oseba "Kalpesh" <notifications@github.com> napisala:
>
> Ok not an issue. thankx for buddy for quick reply.
> apart from this I want to ask, as per your accordance, which is the best
to install opencart. either installing opencart using Instalatron or
manually ?

**Comment by basvandenberg77** [comment]
I would prefer installatron, just because upgrading can also be done with installatron. Really easy. Just check for this bug in config.php

**Comment by kalpeshdesai20** [comment]
thank you for your suggestion and for your valuable time.

Kalpesh Desai
+918286818182

**Comment by danielkerr** [comment]
i think this issue is caused by your self.
