### ISSUE TITLE
XSS Vulnerability in OpenCart 2.1.0.1

### ISSUE THREAD

**Issue by robert81** [opencart/opencart#3721]
Hello,

We identified a XSS vulnerability in OpenCart 2.1.0.1. Can you please advise whom we shall contact to disclose the technical details of the vulnerability?

Looking forward to hearing from you.

**Comment by danielkerr** [comment]
use the forum to pm me.

**Comment by danielkerr** [comment]
also its not an XSS Vulnerability until i confirm it is!

had to many people wasting my time make believe vulnerabilities.

**Comment by robert81** [comment]
@danielkerr I cannot subscribe to the forum for PMs etc. If I had to do so for every vulnerability we discover I'll just spend the majority of my time registering to bug tracking and forum systems.

Also, considering our track record I do not think we have a make believe vulnerability: https://www.netsparker.com/netsparker-advisories/

**Comment by jamesallsup** [comment]
Use the contact form on OpenCart: http://www.opencart.com/index.php?route=support/contact

This will be escalated over to myself or Daniel by the support team.

**Comment by robert81** [comment]
@jamesallsup I did that already and they asked me to use Github or the forum. Please advise.

**Comment by jamesallsup** [comment]
Huh, sorry for that - Ill mention this to them as it should be escalated.

Can you submit a ticket here (easier than forum)

http://support.opencart.com/home

Put for the Attention of JAMES and it should be sent over to me. I will pm the support too and ensure it is.

Thanks.

**Comment by danielkerr** [comment]
Still no ticket opened after 3 days.

**Comment by danielkerr** [comment]
Also no support tickets from u with my staff telling u to use github

**Comment by danielkerr** [comment]
Not one email from robert@wpwhitesecurity.com

**Comment by danielkerr** [comment]
Im calling bullshit

**Comment by danielkerr** [comment]
Your track record. looks pretty crappy.

**Comment by danielkerr** [comment]
Let me guess your trying to promte your services?

Its taken over 5 days and still have not had any contact from you, as well as no messages that you say you sent on the support tocket system.

**Comment by robert81** [comment]
Hello @danielkerr 

I am in touch with James directly via another email of mine; robert@netsparker.com. Would really appreciate if you would tone down your arrogant approach and act a bit more professional. 

Thank you and have a good weekend.

**Comment by davidbfranks** [comment]
lol @robert81 post the exploit if he doesn't believe you....

**Comment by jamesallsup** [comment]
I'll explain this clearly so anyone watching this thread understands.

1. We have had people reporting "security issues" countless times and are almost always false. This takes up significant time which could be spent on more productive work but since security takes priority we investigate all reports regardless. This gets irritating and distracting.

2. We have a clear policy on how to report security potential threats in the readme.

3. Security issues affect merchants, not us. So trying to be clever and encouraging people to post any kind of threat publically before we can investigate and help resolve is unfair to merchants. Quite honestly I'll just ban you from the project and report people to github if any more comments like that are made. If ANY of our merchants are affected by a threat that is made public the person releasing the information will be reported to the police.

4. Until we get the information, there is no threat. Until we confirm any information there is no threat. Saying there is a threat when we have no proof is effectively an attempt to damage the project reputation and again will be reported to github & police.

5. We will not pay ransoms, we won't pay for services and we certainly will not tolerate people trying to damage reputation.

The person who reported the potential issue has my information. When I get any info it will be looked into and if any action needs to be taken it will be. I appreciate that @robert81 has reached out and I am waiting for the information. Until that time this thread is locked.

**Comment by danielkerr** [comment]
yeah there is something but nothing that would affect store owners. nothing that would compromise anything to be honest. its is worth pointing out but again a useless bit of hackery.
