### ISSUE TITLE
Force update price when admin edits order

### ISSUE THREAD

**Issue by guiltar** [opencart/opencart#3797]
Since last report was understood wrongly, I eplain one more time!

When admin edits some order with outdated prices, they make auto-updated.
For example, you cannot change ONLY Last Name of order with outdated price.
You FORCED to updated a price from OUTDATED to CURRENT.

This is bug!

**Comment by danielkerr** [comment]
no its not!

you should not legally be able to change an invoice! only void it and create a new one. I only added the order editor because its something people want.

now as for the old price and current price.

what do you expect!

its not just product prices! its also shipping methods, payment methods, shipping price, coupons (maybe a coupon has expired) Product available dates, product status, stock, discontinued products, etc..

I suggest you have a policy in the company of not editing orders after a certain date range intead of wanting me to add a feature that you want!

**Comment by guiltar** [comment]
You cannot change status without changing price! This is bug!

Price gets updated automatically

**Comment by danielkerr** [comment]
you shouldn't be editing an order if you only want to change the order status! thats what the order info page and order history is for!

**Comment by guiltar** [comment]
Ok for order status is true. 
You cannot change a single letter in Last Name without changing price!

**Comment by kotysoft** [comment]
Hi. 
We're really pleased about Opencart. Basically this is an awesome, modular and great engine with outstanding possibilities.

Unfortunately I have to agree with this issue. This is really strange to completely update the order (especially prices) when someone just want to edit name, address, or maybe add or remove a product. Everyone using specials, and everyday get and order change (or correction) request by customer. And yes, unfortunately deleting and making a new order is not a solution, since the price will be the new price.

Also not a solution to temporarily changing back the product price, because for that time the price (and product) will be publicated and available to all customers, even when it's not available anymore (since you have to reactivate if you want to add to order).

**We don't ask you to rewrite the whole opencart. We just need a HELP** how can we make it, how can we customize it for our needs. A paid or free OCMOD or VQMOD would be awesome.

We would like to keep the original products and prices (as in original order) as long as originally ordered products are untouched.

Please help us where can we start or who can help us to make it!?

Thanks in advance

#1373 #3298
