### ISSUE TITLE
NS-15-023

### ISSUE THREAD

**Issue by fgeek** [opencart/opencart#3972]
When do you plan to release 2.2.0.0, which (if I am correct) is going to contain a fix (https://github.com/opencart/opencart/commit/303fa88fe664ded4bf8753b997abd916f0a3c03f) for cross-site security vulnerability? I would like to notify users of OpenCart to upgrade their installations (with https://github.com/fgeek/pyfiscan).

Advisory here: https://www.netsparker.com/web-applications-advisories/cve-2015-4671-xss-vulnerability-identified-in-opencart/

**Comment by jamesallsup** [comment]
There is already a release to cover this fix.

**Comment by danielkerr** [comment]
Im blocking u later as it seems ur advertise ur own product.

**Comment by fgeek** [comment]
It was not meant as advertisement and mentioning it in similar situation hasn't been a problem before. Sorry if you felt that way and I won't mention the software name again here. I wouldn't even call it a product. It is just a free tool to make system administrators life easier and help them notify users of software to keep them updated and secure. There is no money involved in development (no ads, no homepage). I just wanted to tell you the scenario where I need to version information I was politely asking.

@jamesallsup What release contains this patch? Is there some release, which is not beta-version? Is OpenCart beta-versions considered usable in the production? At least this page http://www.opencart.com/index.php?route=feature/blog/info&blog_id=74 says
```
we would strongly advise against installing the Beta version on a live store
```
so I am trying to avoid the situation where I request users to upgrade to such version even it fixes a security issue. If I understood correctly 2.2.0.0_a1 means beta/alpha or similar release or have I misunderstood?
```
git tag --contains 303fa88fe664ded4bf8753b997abd916f0a3c03f
2.2.0.0_a1
2.2.0.0_b1
```

**Comment by danielkerr** [comment]
the fix was already added to the official release before the issue was made public. 

the vulnerability is very low!

to pull the the vulnerability off you would require a customer to be logged into the account on a store.

1. How to identify a customer of a store when no emails or identifying information about customers is given out via the store front.

2. to actually know when a customer is logged into a store at the same time trick the customer to go to a page with the hacking code in.

also why would do you need to notify my users of this fix? or even recommend them to upgrade? 

I wouldn't recommend some one to upgrade a store and possibly lose some ones business if the upgrade goes wrong when all they need to do was add 3 characters of code. 

to me it sounds like your trolling  through CVE's then visiting open source projects github issue tracking and posting unwanted issues.

**Comment by jamesallsup** [comment]
Maybe look at the [releases page](https://github.com/opencart/opencart/releases)? 

Or the [download page](http://www.opencart.com/index.php?route=download/download) under changlog

We already use Netsparker along with other tools to test builds.
