### ISSUE TITLE
Pagination library is broken in OpenCart 2.2.0.0

### ISSUE THREAD

**Issue by bull5-i** [opencart/opencart#4054]
Links back to first page are broken, they show as `...&page=`
Furthermore, support for custom `page` variable is broken due to hardcoded replaces such as `&amp;page={page}`

**Comment by danielkerr** [comment]
can not replicate and also the pagination has not been changed since oct 2015

https://github.com/opencart/opencart/commits/master/upload/system/library/pagination.php

**Comment by bull5-i** [comment]
It has been changed since 2.1.0.2 release. Everything is working with the 2.1.0.2 version of the library.
By hard coding the the replace variables `&amp;page={page}` you break compatibility with custom page variables (eg `article_page={page}`) that custom modules may be using. When a custom module uses pagination on an OpenCart page that also uses pagination then using the same variable name causes navigation issues.
If you want to include the variable in the replace, better use a regular expression replace so arbitrary variable name could be used.

**Comment by gob33** [comment]
I agree totally. It is broken on first page.
Seems that current code in 2.2.0.0 doesnt ressemble to the fix #3617 (10 nov 2015)

Also as bull5-i says,  you cant use str_replace() with 'page=' because some extensions have more than one pagination box (ex: one on each tab).

**Comment by Steinweber** [comment]
I got the problem after set to seo-url. The pagination is check only on "&page=". But not on "?page =".

```xml
<file path="system/library/pagination.php">
        <operation>
            <search>
                <![CDATA[$this->url = str_replace('%7Bpage%7D', '{page}', $this->url);]]>
            </search>
            <add position="after">
                <![CDATA[if(strpos('&amp;page={page}',$this->url) !== false){
			$con = '&amp;';
		}else{
			$con = '?';
		}]]>
            </add>
        </operation>
        <operation>
            <search>
                <![CDATA[str_replace('&amp;]]>
            </search>
            <add position="replace">
                <![CDATA[str_replace($con.']]>
            </add>
        </operation>
    </file>
```
thats my fix

**Comment by 2valenki** [comment]
The fix by **skyosev** is of a great value, it has resolved the issue with visible and broken hrefs to the first page in a pagination ruler.

https://github.com/ThemeBurn/OpenCart-Enhanced-Edition/blob/e79256141c228841a87a0d5b94b182dfd131def0/upload/system/library/pagination.php

**Comment by wj81** [comment]
I'm using opencart 2.3.0.2 and run into this problem after starting to use SEO urls for categories. I'm using SEO Pack PRO.

I used the fix by skyosev but it only solved the matter after I added '{page}' to the str_replace array. Next I found out that the first page link still didn't work because it referred to '/ ' and not the page no. I added $page / $page to the str_replace array to get it to refer to the first page. Now it works but it broke the first page when not using a SEO url for a category. I resolved this by taking out the other str_replace array values: '&amp;page={page}', '?page={page}', 'page={page}'.

I don't know why this problem occured I have many extensions but not any that alter the pagination that I'm aware off. And I'm not sure if this method is good programming since it's not my profession but I added it anyway maybe it can help others with this problem.

`		$first_page_href = str_replace(array('{page}'), $page / $page, $this->url);`

**Comment by Y-Kilic** [comment]
> I'm using opencart 2.3.0.2 and run into this problem after starting to use SEO urls for categories. I'm using SEO Pack PRO.
> 
> I used the fix by skyosev but it only solved the matter after I added '{page}' to the str_replace array. Next I found out that the first page link still didn't work because it referred to '/ ' and not the page no. I added $page / $page to the str_replace array to get it to refer to the first page. Now it works but it broke the first page when not using a SEO url for a category. I resolved this by taking out the other str_replace array values: '&page={page}', '?page={page}', 'page={page}'.
> 
> I don't know why this problem occured I have many extensions but not any that alter the pagination that I'm aware off. And I'm not sure if this method is good programming since it's not my profession but I added it anyway maybe it can help others with this problem.
> 
> ` $first_page_href = str_replace(array('{page}'), $page / $page, $this->url);`

Thank you. This solved problem caused by SEO Pack Pro
