### ISSUE TITLE
Opencart 2.1.0.2 Not Sending Out Confirmation E-Mails

### ISSUE THREAD

**Issue by gbensonii** [opencart/opencart#4132]
I believe this is a bug.
**BACKGROUND ON ISSUE:**
I am using Opencart 2.1.0.2 being hosted on a Hostgator Reseller Account and have attached a screenshot of my mail settings below for reference.
![mailsettings](https://cloud.githubusercontent.com/assets/17861962/13795193/091a7a78-ead6-11e5-8c7d-77de42e7e813.png)

I have searched the forums and have not yet come up with any answer that works.

1. I have setup the mail settings as shown in the attached screenshot and with those settings I can use the Marketing>Mail function to send e-mails to my test customers.
2. I have also placed test orders and verified that the order is generated and an e-mail is sent to the store owner when the order is placed.
3. I have also tested to verify that a person using the Contact Us function from the front end of the website is able to send a message to the store owner.
4. I have also tested to verify that the store owner is notified when a person registers with the site.

**THE ISSUES I AM HAVING:**

1. I am under the impression that when a new customer registers with the site a confirmation e-mail should be sent to the person registering with the site? Is this correct?
2. I am under the impression that when a new order is placed that a customer should receive a confirmation e-mail about the order placed? Is this correct?

**Assuming that I am correct and the confirmation e-mails are supposed to be sent...then the issue I am having is that those confirmation e-mails are NOT being sent (Or if they are they are never received by the test customers).**

Is there a setting somewhere I am supposed to check? Is this a bug?

I have also verified that the System>Settings Page - under the Server Tab - Under the Error Handling section I have:
Display Errors=Yes, Log Errors=Yes, Error Log Filename=error.log

I have reviewed the error.log and it is empty.

Please help!

Thanks in Advance!

Sincerely,

- George Benson

PS. - I have posted this in the OpenCart Forum - http://forum.opencart.com/viewtopic.php?f=190&t=159552 but have not had any responses.

**Comment by ynagarjuna1995** [comment]
I am facing similar issue you can check the error in the image below How to fix this ?

Since I have enabled and need Email Verification.My Customers won't be able to move forward without verification

![image](https://cloud.githubusercontent.com/assets/5663901/14049821/bc8cd628-f2dd-11e5-84c2-08303f1c953a.png)

**Comment by scw1937** [comment]
I can confirm this bug. No error is logged. Email from contact page is sent correctly, while notification fails. The forums do not provide a proper solution yet.

Host: Antagonist, PHP 5.6
Version: Opencart 2.1.0.2
Mail protocol: Mail
Order mail alert: yes (other mail alerts: no)

**Comment by nik2020** [comment]
Your mail parameter is wrong I guess.... Go to cpanel of your website and go to mailing accounts. 
Click configure email and I shall see the parameter value and all others to be fixed !

**Comment by rockdroid** [comment]
I have the same exact problem, and i don't know what to do.

I've changed the SMTP configuration to the recommended by my server and the one recommended bye google, the both doesn't send the F*** mail notification, but i realize that if i register a user with a contact mail that is hosted in the same IP but different domain, it works... Because of this, i thought that my MX records in the DNS was bad, so i re-checked and they were fine. My final test was, send from my webmail a test-mail to another external domain (ex. google, hotmail, etc.), this test was successful, all the test-mails were received fine.

In conclussion i can say that the problem isn't the protocol, or the server, or the configuration. I think the problem is in OpenCart, but i cant figure out where. I really hope that my exp can help to others, and i really need a hand here, i need to fix it ASAP. thank you

**Comment by emersonian** [comment]
I believe 7d42e75d256bd8ee0f6ffa5ad794486b91b5b3b5

**Comment by rockdroid** [comment]
@emersonian 
it looks like this, and doesn't work
$mail->smtp_hostname = $this->config->get('config_mail_smtp_hostname');
$mail->smtp_username = $this->config->get('config_mail_smtp_username'); 
can you help me? thanks

**Comment by danielkerr** [comment]
@rockdroid you need to set 2fac auth on gmail and set a app passowrd and use the app password as your password. I know smtp works because i tested it not so long ago on gmail. i think godaddy maybe have a special configuration and maybe need to use some parameter setting.

**Comment by danielkerr** [comment]
@scw1937 your issue is not the same. hes using smtp your using the default mail fucntion built into php. if your site is not sending out emails you shoudl contact your host as the php mail function needs to be configured in PHP!

**Comment by danielkerr** [comment]
@gbensonii 

> PS. - I have posted this in the OpenCart Forum - http://forum.opencart.com/viewtopic.php?f=190&t=159552 but have not had any responses.

you posted on the 15th and got a response on the 15th!

**Comment by danielkerr** [comment]
send my staff a support request via the oc web site. i would also like to see whats causing the issue.

**Comment by scw1937** [comment]
@danielkerr It may be not the same method, but it can still address the same issue. As I mentioned the mail function is working with the contact form, but the notification mail fails to send. This does not indicate a host problem, right?

In the mean time, we decided to continue using other webshop software for the next months. Thank you for your answers and good luck with the project.

**Comment by danielkerr** [comment]
@scw1937  maybe you have explained this wrong!

> As I mentioned the mail function is working with the contact form, but still no notification mail is sent. T

so what your saying is you expect to receive a notification email as well as the buyers email when some one uses the contact us from?

notification emails only go out to store owners for receiving new orders.

**Comment by danielkerr** [comment]
i can send emails and nearly every one else can send emails then maybe you should contact your host to complain the hosting is not set up properly!!!!

theres a million reasons you can not send emails, maybe your using a free host, maybe you have to set a specific port for your hosting company. maybe your host is blocking html emails!

if it works for others it means your issue with the server!

**Comment by scw1937** [comment]
No need to be frustrated, sir. Maybe I did not explain it very well.

If a visitor uses the contact form, an email is sent to the shop owner. This works properly and it uses PHP Mail. However, when a visitor buys a product no notification (mail alert) is sent to the shop owner. This seems strange to me, because I did configure the settings to send a mail alert in that occasion. 

Remember I am talking about version 2.1.0.2, which is not the most recent version anymore. I agree that, if I would be the only one facing this issue, it is caused by the environment I use.

But, once again, for now we're good and I'll look into OpenCart again in the near future. Thank you.

**Comment by munirasim** [comment]
May be you're not paying attention to admin SETTINGS.

Go to SETTINGS and under OPTION tab and following to YES:

- New Order Alert Mail
- New Account Alert Mail

**Comment by scw1937** [comment]
Thank you, but I did. New Order Alert Mail is set to yes, and the other alert mail options are set to no.

**Comment by munirasim** [comment]
Could you please share error log, if generated?

**Comment by scw1937** [comment]
Please read my first post. There was no error logged.

I really appreciate your efforts in order to help me, but as I said we stopped developing a new webshop for now. As this seems a particularly case, there is no need for further investigation. I don't want to waste your time.

**Comment by jmasril** [comment]
I have the same problem, no email notification after new register or buying products is sent to the customer or to the admin. please help cause im using this solution.
Thank you

**Comment by jmasril** [comment]
i just has solve it. if you use gmail it dont send the emails, but, if you change to another mail, it works

**Comment by danielkerr** [comment]
you have to set the app password for gmail to work!

**Comment by jmasril** [comment]
set app password, where???

On Fri, Jul 8, 2016 at 2:00 PM Daniel Kerr <notifications@github.com> wrote:

> you have to set the app password for gmail to work!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/opencart/opencart/issues/4132#issuecomment-231444862>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATau3qstRyrUZ1r9WNO1qnDwPX90pbonks5qTp5IgaJpZM4Hxet7>
> .
>
-- 
JML

**Comment by danielkerr** [comment]
https://security.google.com/settings/security/apppasswords?utm_source=OGB&pli=1

**Comment by jmasril** [comment]
Thank you Daniel, but the link is not working for me[image: pasted1]


On Sat, Jul 9, 2016 at 12:17 AM Daniel Kerr <notifications@github.com>
wrote:

>
> https://security.google.com/settings/security/apppasswords?utm_source=OGB&pli=1
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/opencart/opencart/issues/4132#issuecomment-231516132>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATau3l7TEZUMz9OR9vXEJxfGweR6pu2Hks5qTy7agaJpZM4Hxet7>
> .
>
-- 
JML

**Comment by danielkerr** [comment]
google it!!!

**Comment by Imonda** [comment]
Hello,
I have similar problem with GMAIL. I setup gmail correctly as I can receive a order confirmation and my customers can get email confirmation also.

The problem is that CONTACT FORM doesn't work with this settings.
There is no error in the log file but:

I put this to index.php
error_reporting(E_ALL);
ini_set('display_errors', '1');
ini_set('log_errors', '1');         

and I could see the error.
So the error is:

Fatal error: Uncaught exception 'Exception' with message 'Error: Password not accepted from server!' in /var/www/vhosts/canineandco.co.uk/httpdocs/system/library/mail.php:281 Stack trace: #0 /var/www/vhosts/canineandco.co.uk/httpdocs/catalog/controller/information/contact.php(31): Mail->send() #1 [internal function]: ControllerInformationContact->index() #2 /var/www/vhosts/canineandco.co.uk/httpdocs/vqmod/vqcache/vq2-system_storage_modification_system_engine_action.php(44): call_user_func_array(Array, Array) #3 /var/www/vhosts/canineandco.co.uk/httpdocs/system/engine/front.php(34): Action->execute(Object(Registry)) #4 /var/www/vhosts/canineandco.co.uk/httpdocs/system/engine/front.php(29): Front->execute(Object(Action)) #5 /var/www/vhosts/canineandco.co.uk/httpdocs/system/framework.php(99): Front->dispatch(Object(Action), Object(Action)) #6 /var/www/vhosts/canineandco.co.uk/httpdocs/index.php(30): require_once('/var/www/vhosts...') #7 {main} thrown in /var/www/vhosts/canineandco.co.uk/httpdocs/system/library/mail.php on line 281

So this is a proof of contact form error when u want to use gmail account in opencart.

**Comment by acherondigital** [comment]
Might help someone - make sure in cpanel under MX Records email routing is set to "Remote Mail Exchanger" if using email at another provider rather than the server opencart is on.

**Comment by munirasim** [comment]
Good ... Your MX records must also point to external servers. For example, if you are using GMAIL as external server then MX records would be:

1	ASPMX.L.GOOGLE.COM.
5	ALT1.ASPMX.L.GOOGLE.COM.
5	ALT2.ASPMX.L.GOOGLE.COM.
10	ALT3.ASPMX.L.GOOGLE.COM.

Another issue is that most popular email servers such as gmail, yahoo and outlook etc. have implemented strict DMARC (https://dmarc.org/) policy so make sure you setup SPF and DKIM records properly so that your emails don't go to SPAM folder of your customers' inbox.

**Comment by victornewman** [comment]
I am using opencart 2.3.0.2 I am using my domain name and e-mail so there is no gmail account in my question. All settings done -finfo@xxxx.com, mail.xxx.com etc. It works because when I send mail under marketing menu to all customers they receive mails (in spam but they receive).
 
The problem is whenever I have nev registration or new order I do not receive confirmation e-mail. Yes under mail settings mail allerts chosen as register, order, rewievs.

I can say that problem is nor on e-mail settings with my limited programing but sharp logic;)

is there any idea except mail settings and gmail isue?
Thanks in advance

**Comment by okmela** [comment]
hi i got same mail problem please help me out ,  its not sending email to customer.

**Comment by okmela** [comment]
anyone there to help me about email on opencart?

**Comment by arnisjuraga** [comment]
Can you access webserver log files? 
`system/storage/logs/error.log` also?

**Comment by sfshameem5** [comment]
I'm also facing this problem. No confirmation emails being sent to the user or the customer. I'm using opencart version 2.1.0.1

**Comment by rayhan007** [comment]
using mail protocol I am not able to send mail through my windows server but able to send through linux cpanel server...can any one help me that how to do it by windows server....

**Comment by RaidoDev** [comment]
You need a mail protocol app for windows. Are you using IIS or Apache on Windows?

**Comment by rayhan007** [comment]
Hi @RaidoDev  I am using IIS for windows server 2008R2

**Comment by webcorvo** [comment]
hi @rayhan007 , for send email through opencart is simple:

For a **gmail** account:

Protocol: **SMTP**
SMTP Hostname: tls://smtp.gmail.com
SMTP Username : your gmail user name
SMTP Password : your gmail pwd

**Comment by rayhan007** [comment]
hi @webcorvo i am getting this error http://prntscr.com/fqz7yi using smtp

**Comment by webcorvo** [comment]
@rayhan007 if you upgrade for version **Version 2.3.0.2** work´s well ;o)

**Comment by rayhan007** [comment]
@webcorvo  I tried no results...can u give me a proof is it really works for opencart SMTP service?

**Comment by webcorvo** [comment]
yes, i use that one! 
install that version and i will show you :o)

**Comment by rayhan007** [comment]
http://www.delsyscanada.com/sites/oc2302/admin
user: admin
password: admin

**Comment by webcorvo** [comment]
the problem is in your server provider :o(

**Comment by rayhan007** [comment]
my server is ok....i tried more than 2 server....

**Comment by rayhan007** [comment]
@webcorvo  can u show me ur one from where it is working...it's hard to believe for me that it is working for u

**Comment by webcorvo** [comment]
send-me a private email: webcorvo@gmail.com

**Comment by rayhan007** [comment]
@webcorvo  sent to u

**Comment by RaidoDev** [comment]
Sometimes, the mail settings can help. In Store settings under "Mail" set:

"from" your store address:

Mail Parameters: `-fshop@example.com` 
or with a space:
Mail Parameters: `-f shop@example.com` (notice space after "-f" parameter).

**Comment by webcorvo** [comment]
Hi Rayhan,

I create a script to see the real erros:

Download: - https://we.tl/XCnjSQFC0X

Just unzip the mail.zip to your root shop.

Then run : http://www.delsyscanada.com/sites/oc2302/mail/gmail.php

When you run the page, will retrieve a lot of information:

If on the end of the file says Message sent! - you will receive one email 

else if it says Mailer Error: xxxxx

Tell me the errors

**Comment by kashifmoin** [comment]
I have the same issue bro.. my customers are not receiving any emails and neither me as a admin any email is coming if any order is there.. 
http://silkcouturedubai.com

can u brothers have a look to my site and help me in this to solve this problem

I have already configured MAIl.
and also sent new order and review order new accoutn to YES..
