### ISSUE TITLE
No rights to change order status

### ISSUE THREAD

**Issue by kevinmoons** [opencart/opencart#4160]
Installed V2.2.0.0

When editing an order trying to change the order history, "You do not have rights to change these settings!" is appearing. (Or something like that, I'm using NL.)
--> "U heeft geen rechten deze instellingen te wijzigen!"

Tried with and without API user, makes no difference.

**Comment by Digibitsnl** [comment]
I have exactly the same issue, also in Dutch. I have been trying to fix this for some weeks now! But al the found solutions fail. I am using opencart 2.031

**Comment by kevinmoons** [comment]
@Digibitsnl How did you find this thread? Searching for the Dutch error code? (To know if only Dutch installations have this problem, then it might be a problem with the Dutch language only, but looks unlikely to me..)
@danielkerr Why was this actually closed, I've been looking for a duplicated post or solution, but didn't found any. Thanks!

**Comment by Digibitsnl** [comment]
Hi there,


Thanks for your reply.
I am sorry I really don’t know in which language I found it, I am searching every day in different languages (dutch and english)
I also found one solution one day, it says when the user used default language English for Admin instead of dutch he/she didn’t have the problem.
In my case that didn’t work.




*************************
Met Vriendelijke Groeten,
Harold Osterloh-Digibits Webdesign


Monteverdistraat 28
1447 NA Purmerend.
http://www.digibits.nl
web@digibits.nl
*************************

**Comment by Digibitsnl** [comment]
This thread has been closed as I believe because it is been told that this issue has been discussed many many times on this forum. Unfortunately it hasn't solved my problem, I believe it is a bug in the software so upgrading would fix it. But upgrading wil most likely break some of my other installed extensions. It would be better for me to fix this error. Tried al the solutions but nothing worked for me. Already cope with this problem for weeks now! Any help would be very appreciated.

**Comment by kevinmoons** [comment]
@Digibitsnl you need to create an api user and use it. Then you can click to add ip address when you want to edit an order. It works fine in this way.

**Comment by Digibitsnl** [comment]
Thx but I have also seen your solution, my version is 2.0.3.1 in this version you cannot add IP address. I would like to fix this rather than upgrading to a higher version. If possible to change code only to add IP address it would be great!

**Comment by kevinmoons** [comment]
Ohh @Digibitsnl , then why not just disable the lines of code that check this rights? It shouldn't be more than a few lines. I think it will be much harder to add code to add IP address..

**Comment by Digibitsnl** [comment]
I would like to disable the lines, but also this solution has not been found by me yet.
It could be more than just a few lines.

**Comment by haxcop** [comment]
Hi There's an actual solution for this? still facing the errors I cannot edit any order for the api permission issue. with or without creating the api and adding as many possible ip's still not working at all. Any person here have found the solution?,

Thanks in advance.

**Comment by Digibitsnl** [comment]
I have not heard of any, I am also working on it for weeks (time after time) If someone find something please let us know. The solution of disable lines of code as Kevinmoons says in this thread seems a fine solution to me, but what lines? Who is helping us out?

**Comment by kevinmoons** [comment]
Best all, I've not looked into the code that is necessary to disable some lines because after making a default API user and using this in the store settings, it is possible to add IP addresses to it, and managing orders works like a charm.
If you want me to have a look into it, PM me.
Good luck!

**Comment by Digibitsnl** [comment]
@kevinmoons 

I believe github has removed private messaging.
I have updated my profile, with a personal email adres, if you use it, i will be able to contact you.
It would realy help me if you could help me out with this problem.
Best regards.

**Comment by Digibitsnl** [comment]
Unfortunately the problem still exist. We have not been able to find a solution yet.
From all the solutions nothing has worked. Anyone anything new??

**Comment by Extrapet** [comment]
Unbelievable:  this issue still remains in 2018 / Version 3.1.0.0_a1
Opencart = No solution, no support!
this was my final -blocking- issue to decide Opencart is not my tool. waist of time & effort.
