### ISSUE TITLE
Uploaded Images/Files are not recognised by opencart in admin Panel

### ISSUE THREAD

**Issue by ynagarjuna1995** [opencart/opencart#4161]
I have uploaded some images &  Payu Extension Module through FTP but when I try to access images as well as module I was unable to see them.

 But when I check manullay using FTP I was able to see the files as well as images.

I am using bitnami opencart 2.1.0.2 VM

What is the Issue ? I have checked modifying permissions but there is no use

**Comment by Rpent001** [comment]
@ynagarjuna1995 what folder did you upload the images to?  I know first hand that uploading images is doable because I had imported 15,000 products to a test install of OpenCart.

**Comment by Rpent001** [comment]
FYI, OpenCart DOES NOT do well with that many products.

**Comment by kanenas** [comment]
@Rpent001 Opencart **DOES** do well with that many products if you know what you are doing!

**Comment by ynagarjuna1995** [comment]
I have uploaded images in the root folder by creating a another directory..

I was not able to see those images in admin panel.

Afterwards,  today I have uploaded a extension of Pay U payment gateway
even that is not recognized by the opencart admin panel.

I have merged the Payu folders with existing folders there are no
overwrites just merging of folders.

Still I was not able to see them

I was using Bitnami's Linux VM for Opencart 2.1.0.2

Please respond ASAP this is very urgent

**Comment by Rpent001** [comment]
@kanenas of course it's because I don't know what I'm doing and not because OpenCart lacks some basic functionality.  

I've had four pull requests closed that were for simple, we'll call them enhancements instead of fixes, that I found quite useful when dealing with many products in a catalog.  You cannot even modify the price of an item during a manual order entry.  You also can't set a special price and a quantity discount on the same product if you want to.  It's all in my recent pull requests.  Shall I continue?

Unfortunately, the product has a bit of maturing to do before it's ready for main stream release.  At least the 2.0 versions anyway.

**Comment by Rpent001** [comment]
@ynagarjuna1995 you should upload your images to the /image/catalog folder.  You can even split them into sub-directories if you'd like.  Then, you need to link your products with the images and the system will create the appropriate sized images for each view when they are first called upon.  For additional images, you can import the filenames from a CSV file into the oc_product_image table.  Take a look at the table structure and format your spreadsheet accordingly.  I wrote a script that finds the additional images based upon the main file I imported into the image column of the oc_product table, but that probably won't work for you.

Note: I did all of my product entry when I was considering OpenCart via CSV files in Adminer because it was MUCH faster.  Do so at your own risk.

**Comment by danielkerr** [comment]
@Rpent001 

its down to me if i accept your requests or not. dont commit any if you start complaining about the ones i decline!

**Comment by Rpent001** [comment]
@danielkerr it would just be nice to know why a simple change that's common sense gets declined and one that was an actual bug in the system that I submitted an actual fix for was just shot down.
