### ISSUE TITLE
table cart engine change to file opencart.sql

### ISSUE THREAD

**Issue by pekka2** [opencart/opencart#4180]
This table `cart` sql:

 `ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;`

change to:

 `ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;`

**Comment by danielkerr** [comment]
why???

innodb is better for tables that are updated a lot.

dot make comments like this unless you know what you are doing!

**Comment by pekka2** [comment]
That sql code did one my client errors:

`2016-03-24 12:18:03 - PHP Notice:  Error: Unknown storage engine 'InnoDB'<br />Error No: 1286<br />SELECT * FROM oc_cart WHERE customer_id = '0' AND....`

**Comment by osworx** [comment]
@pekka2 Your 'Client' should select another developer/agency and general another provider who offer qualified services (where InnoDB is enabled).
Better than this stupid PR.

**Comment by Rpent001** [comment]
@pekka2 if your client has control of their own server they should enable the InnoDB storage engine in MySQL and also make sure that you set the innodb_file_per_table to 1.  Do some research on the MySQL website on the various innodb settings prior to setting up your database.  There are a couple other settings that go along with making innodb use separate files.

The MyISAM storage engine creates files for each table by default, while InnoDB creates a single ibdata1 file.  In most cases this is probably fine.  The problem is that the ibdata1 file just keeps growing and growing and GROWING...  If that file becomes corrupt, then your entire database (or databases) on that machine will go down.  I have a table with around 150,000,000 records in it.  My ibdata1 file was over 20GB in size before I built a new server and switched to innodb_file_per_table.  Now, each table has its own files and if one becomes corrupted you can at least restore that single table while the other tables and databases remain intact.

**Comment by Rpent001** [comment]
@danielkerr why not try being a little less arrogant.  If you don't have time to be bothered with pull requests and issues that come up from various people using your software why did you make it open source in the first place?  I don't know why you feel like you are the smartest person here and everyone else who can't get your system running is just plain stupid.  ALL software has bugs.  Not everyone's servers are configured the same way, as you can see in this case.  Kick your ego down a few notches and realize that these people are just trying to help out.

Oh and I think your comment can use a little revision as well.

"dot make" should be changed to "don't make" - Unrecognized method 'dot()'

**Comment by pekka2** [comment]
@Rpent001 
I am fixed this simply. I am changed my Remote Upgrade data to sql file. 
My clients are no longer stop to this issue.

**Comment by osworx** [comment]
@Rpent001 innodb_file_per_table is ON per default when the engine is 5.6.6 and higher
So as said before, if the provider know his job this should be also no issue.

**Comment by Rpent001** [comment]
@osworx True, but if they are hosting on a server that doesn't even have InnoDB enabled by default chances are it's a version lower than 5.6.6 (most likely 5.5.x) and if they have to turn it on they might as well also enable the file per table options while they are at it.

I'm glad it's enabled by default now though.  Those bloated ibdata files are a killer.  Both from a risk standpoint as well as a backup/restore standpoint.
