### ISSUE TITLE
[SECURITY] json_decode remote code execution

### ISSUE THREAD

**Issue by paragonie-scott** [opencart/opencart#4238]
Found on Bugtraq: http://seclists.org/bugtraq/2016/Apr/61

Note this only affects systems without the JSON extension.

From what I understand, **this *is* currently being exploited in the wild.**

**Comment by n4s3r** [comment]
@paragonie-scott apparently they don't care
https://github.com/opencart/opencart/issues/4220
https://github.com/opencart/opencart/pull/4228

**Comment by paragonie-scott** [comment]
I hadn't seen the prior notifications. Closing it, then.

**Comment by jamesallsup** [comment]
@n4s3r don't come onto this project and start with attitude like that, you are the one who couldn't be bothered to read the readme about how to report a security issue. I even thanked you on the previous thread and moved to internal tracker to review. Now instead you start to hijack another thread with comments like that. You have no prior history with the project, instead you find a flaw, post it publicly for everyone and now according to @paragonie-scott it is "being used in the wild". So I hope your proud that all those merchants who get affected by this will likely be screwed in some way - they all have you to thank for that, care to share your contact info so they can personally thank you? I doubt it.

FYI we do care, hence why it is being looked into for the best possible solution, but as I've put above because of your lazy attitude to reporting the issue it seems that you are indeed the one who doesn't care [about getting people screwed over].

@paragonie-scott thanks for reporting the link, we are aware of it and will have a solution announced for it asap.

**Comment by r3s34rch3r** [comment]
@jamesallsup  Thx for banning me.
I have fixed the issue for you https://github.com/opencart/opencart/pull/4228 you didn't merge it!!! and this bug is still not patched.

https://github.com/opencart/opencart/issues/4238#issuecomment-209544873 And this is another golden response to security researcher who tries to fix your broken project.

https://github.com/opencart/opencart/issues/1269
https://github.com/opencart/opencart/issues/1534
https://github.com/opencart/opencart/pull/578
https://github.com/opencart/opencart/issues/1279
https://github.com/opencart/opencart/issues/1594
https://github.com/opencart/opencart/issues/3721

good luck with your project.
