### ISSUE TITLE
Order view prolem "Block mixed content" after installing SSL

### ISSUE THREAD

**Issue by MuhamedAuda** [opencart/opencart#4306]
Opencart: Version 2.1.0.2
if you have orders in store then later installed SSL,
now when you try to view orders done before adding SSL you will block with "Block mixed content"

The site "store_url" filded in orders table store with  http make confiled with https recently installed .
so you have to fix code or chaage url in database to https for every product

**Comment by pine3ree** [comment]
@MuhamedAuda 
Hello, i just checked v 2.1 and 2.2 code and master. This issue seems to have been fixed in 2.2. The problem you report is due to ajax calls to with http scheme while being on an url with https schema.
kind regards, 
maks

**Comment by pine3ree** [comment]
basically  in `admin/controller/sale/order.php method info()`:
```php
$data['store_url'] = $order_info['store_url'];
```
was changed to
```php
$data['store_url'] = $this->request->server['HTTPS'] ? str_replace("http", "https", $order_info['store_url']) : $order_info['store_url'];
```

but in 2.2.0 there are more assignments in getList() and getForm() controller methods
```php
$data['store_url'] = $this->request->server['HTTPS'] ? HTTPS_CATALOG : HTTP_CATALOG;
```

**Comment by CoverUp** [comment]
I wonder why is necessary to store the store_url in first place

**Comment by pine3ree** [comment]
@CoverUp 
I am not sure because i use my own fork started from 1.5.1 long time ago, but i believe that could be related to the new admin/order now mapped to frontend api. Maybe the api needs to identify the store in which the order was made, so that's why it's been used in the ajax calls. If that's the case, perhaps a simple query parameter store_id would suffice to achieve the same results, but i am not sure i haven't checked the frontend api code. :-)
