### ISSUE TITLE
Show Subcategory Items in Category

### ISSUE THREAD

**Issue by bizzynate** [opencart/opencart#431]
There seems to be an issue with products placed in a subcategory not appearing in the parent category's view. Upon some investigation, I discovered an "extension" (which is actually a modification of a core file) that corrects this behavior:

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=8565

The suggestion made by the contributor indicates to me that this may be a bug in the /catalog/controller/product/category.php file. It recommends changing line 195-196 from:

```
 'filter_category_id' => $category_id,
 'filter_filter'      => $filter,
```

to:

```
 'filter_category_id' => $category_id,
 'filter_sub_category' => true,
 'filter_filter'      => $filter,
```

While this fixes the issue, it doesn't give a configurable option to the administrator, so perhaps instead of a hard-coded "true" value, this would become a variable linked to the category configuration from the administrator panel to allow a true/false selector.

 This proposed solution is based on the 1.5.5.1 release.

**Comment by forkineye** [comment]
What is the point of "Show All" if it doesn't show all??

**Comment by AdventureTK** [comment]
I don't see the point in it saying "Show all" when all it will show you is the same sub-category list that is already displayed in the very Category list they just clicked to "Show all" to view. In other words, someone would only click show all if they wanted to see all the products in a Category list and then use refine to cut it down to more specifics.  This "show all" button is definitely an issue and I consider it an error or fault and feel it should be corrected by OpenCart.  It is meant to SHOW ALL not show sub-category list, otherwise it should say: Show Sub-Category List. VERY DISAPPOINTING!!

**Comment by bitlineweb** [comment]
Is it possible to make it show products from all levels of subcategories? not only the the first level?
for example

category A > sub-category A1 > sub-category A2

when opening category A, all products from categories, A, A1 and A2 should be displayed

**Comment by agriboed** [comment]
> Is it possible to make it show products from all levels of subcategories? not only the the first level?
> for example
> 
> category A > sub-category A1 > sub-category A2
> 
> when opening category A, all products from categories, A, A1 and A2 should be displayed

https://github.com/agriboed/opencart_show_subcategory_products

**Comment by munirasim** [comment]
> **when opening category A, all products from categories, A, A1 and A2 should be displayed**
Opencart allows more than one categories against a single product. When you add a product to category A1 or A2 also assign it category A and you will get your desired results.

**Comment by agriboed** [comment]
> **when opening category A, all products from categories, A, A1 and A2 should be displayed**
> 
> Opencart allows more than one categories against a single product. When you add a product to category A1 or A2 also assign it category A and you will get your desired results.

Yes, you're right. But for my case, we're using import products with one single (let's say child) category.
So I've added to a controller:
$sub_cats = [...];

and to model:
p2c.category_id IN (...)

Because it's not possible to re-check add re-assign each product when you have them thousands imported automatically :)

**Comment by stalker780** [comment]
@agriboed
If you use custom import it should have ability to assign not only target category but also an option to fill parents.

**Comment by agriboed** [comment]
> @agriboed
> If you use custom import it should have ability to assign not only target category but also an option to fill parents.

It will take much more resources for import flow cause all our products are in another system where they have only one category, so I need to re-check categories tree on each product import, so for my case much simple to made changes above.

As for, I prefer to set only one category for a product. Maybe it will be helpful for someone like me.

**Comment by slva2000** [comment]
> > Is it possible to make it show products from all levels of subcategories? not only the the first level?
> > for example
> > category A > sub-category A1 > sub-category A2
> > when opening category A, all products from categories, A, A1 and A2 should be displayed
> 
> https://github.com/agriboed/opencart_show_subcategory_products

Not correct format href url for products...
