### ISSUE TITLE
FedEx Not Working Outside of Tax Class

### ISSUE THREAD

**Issue by moneycarlo** [opencart/opencart#4349]
I'm running OC 2.2 and FedEx module doesn't seem to like having an origin zip code that is NOT in the same region as my tax class.
I drop ship, so I collect taxes in MN and drop ship from TX.

I have a tax class set up for MN - USA
Tax rate set for the MN - USA tax class
2 geo zones, MN and all of USA

USPS works fine, but FedEx doesn't show any rates. 
Trying different combinations, it seems that it doesn't work when my origin zip is NOT in my tax class.

I know my FedEx credentials work, because if I change the origin zip code in the FedEx settings to a MN zip (where my tax class is) I get fedex rates. But a zip code outside MN will fail to get any fedex rates.

**Comment by danielkerr** [comment]
so setup another geo zone called shipping.

**Comment by danielkerr** [comment]
ok spotted the issue

**Comment by danielkerr** [comment]
its not about the tax class its about you setting your origin country and zone in the settings and adding zip code in the fedex shipping module that match.

**Comment by danielkerr** [comment]
the issue is even if i alter the fedex module so you can set a different shipping location that woudl only work for the items being dropped shipped. theres more people out there that are shipping directly from their own businesses. im not going to alter the code just to deal with your problem. this is not a bug. 

I suggest you try the extension store. 

http://www.opencart.com/index.php?route=extension/extension&filter_search=multiple%20store%20locations

**Comment by moneycarlo** [comment]
@danielkerr Can you tell me what changes I would need to make for it to work?
