### ISSUE TITLE
Filemanager search stop working

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#4387]
Because of this line search in filemanager stop workng:

`if (substr(str_replace('\\', '/', realpath($directory . '/' . $filter_name)), 0, strlen(DIR_IMAGE . 'catalog')) == DIR_IMAGE . 'catalog') {`

**Comment by tyler-x** [comment]
I still have this problem on 2.3.0.2, and the master code is the same. Bug fixed?

**Comment by elalemanyo** [comment]
I am also having the same issue. I have to say that the issue is just happening on my live server, when I run the code locally the issue is not there...

I also have another issue and I think is related to this one: https://forum.opencart.com/viewtopic.php?t=172773

did someone find a solution? For the moment I am using a vqmod xml patch and for file manager I edit just the core file directly. I hope there is a better solution for this.

Thanks!
