### ISSUE TITLE
Cannot create sub-categories with same SEO name

### ISSUE THREAD

**Issue by Khaleel** [opencart/opencart#4401]
Hi

I am trying to achieve this architecture:

/mens
/mens/footwear
/mens/clothing
/womens
/womens/footwear
/womens/clothing

However when I try creating the subcategory with the same SEO keyword "footwear" under the parent Womens for Womens Footwear it says "SEO keyword already in use!"

This should not be the case. This is COMMON practice in ecommerce platforms like Magento to support child categories to have their own SEO rules applied.

**Comment by opencarteli** [comment]
May i have to know which opencart version you are?

**Comment by munirasim** [comment]
SEO KEYWORDS are unique site wise i.e. you can not use one seo keyword for two or more pages. Therefore, It might be wise to define more explanatory SEO keywords for sub category e.g. footwear-men or footwear-leather etc.

**Comment by danielkerr** [comment]
HOW IS THIS A BUG!!!!!

 it says "SEO keyword already in use!"

its telling you the issue! same issue that wordpress and may others have

**Comment by Khaleel** [comment]
Your a cocky sport Dan as ever. This is cleaning URL architecture and cross compliant SEO with virtually all the major companies adopting this practice. I want to acheive the URL structure above with the shitty vQMod (oh yeah I forgot your OC platform has no marketplace tool)

**Comment by CPHgroup** [comment]
this doesnt have to be a problem there is no need for categories of different paths to not have unique keyword !!

**Comment by hayden-t** [comment]
this doesnt have to be a problem there is no need for categories of different paths to not have unique keyword !!

**Comment by hayden-t** [comment]
> Your a cocky sport Dan as ever. 
yes hes a total dickhead

**Comment by Khaleel** [comment]
Dan is the failure of OpenCart. So is vQMOD. OpenCart and the XML way of working is dead. There is useless API, no headless architecture, nothing for scale, CDN features out of box. 

I no longer use OpenCart and I used to develop and promote it.

**Comment by hayden-t** [comment]
oh here's this comment, sorry took so long to reply. to oc credit if you think its good or not oc4 actually doesnt rely on vqmod xml or ocmod, using an event system instead. Ive not tried it out and many/most mods i buy are still using xml vqmod system which works at least, and i use it extensively for my own changes to my system rather than edit the install files (except for twigs)

When I did look at the api excited , i was surprised how little functions there was actually in it, but i guess this will get better over time.
