### ISSUE TITLE
\0 and \9 in admin stylesheet.css

### ISSUE THREAD

**Issue by samchen945** [opencart/opencart#4414]
There are five /0 in the admin stylesheet.css file, and one /9 in there too.

http://demo.opencart.com/admin/view/stylesheet/stylesheet.css

**Comment by stamster** [comment]
\0 represents NULL byte. 
\9 represents TAB or HT.

I would guess this is due to a tool used to minify CSS which converted null terminators/characters and tabs into escape sequences.
In low-level languages like C, this is allowed, while on the other hand can break CSS parsing which is happening in browser.

**Comment by progcode** [comment]
This is custom IE css fix, not a bug

**Comment by stamster** [comment]
@progcode 
You basically state that IE would not read CSS compiled in one big line w/o those escape sequences? I really don't think so, even IE is not that bad/stupid.
