### ISSUE TITLE
installation doesn't work on https

### ISSUE THREAD

**Issue by rattkin** [opencart/opencart#4539]
install/index.php?route=install/step_1 does not work on https

**Comment by danielkerr** [comment]
more info required. 

is it shared ssl?

**Comment by rattkin** [comment]
no, there is just one vhost on the server.
if i turn off https, install works.

**Comment by mistabiggx** [comment]
so what do you mean by "doesn't work"? What behaviour are you getting?

**Comment by rattkin** [comment]
when i click on the "next step" button, nothing happens.
I was able to complete install without problems using the "http://"

**Comment by VistaXP** [comment]
If I'm not mistaken, your suppose to setup "https://" after you installed opencart and your SSL at the "http://" address. That's why "https://" isn't working during your installation. And if you want https:// to show on all your pages, you need to setup a redirect from your domain host or in cpanel.

Guide that may help:

http://www.inmotionhosting.com/support/edu/opencart/setting-up-payment-gateways/how-to-enable-ssl-connection-in-opencart

http://forum.opencart.com/viewtopic.php?f=138&t=64685

**Comment by danielkerr** [comment]
@VistaXP agreed!

I have just tested the install process with on my localhost with SSL and it works fine.

**Comment by danielkerr** [comment]
maybe the SSL is invalid i dont know.
