### ISSUE TITLE
undefined variable $user in catalog/controller/module/amazon_login.php

### ISSUE THREAD

**Issue by rmullaney77** [opencart/opencart#4596]
PHP undefined variable error displayed when a visitor clicks "Cancel" in the "Login with Amazon" popup. I fixed with an ocmod in my store by simply adding `$user = array();` above `if (isset($this->request->get['access_token'])) {`

**Comment by rmullaney77** [comment]
https://github.com/rmullaney77/opencart/commit/8e4c0cad607daa1aad144c843138a257943fdb85

Side-note/rant/whatever: Can we not just call this 3.0 already? You guys are moving so many files around in MINOR updates it's making modification maintenance a MAJOR pain in the ass. Seems like with each new version controllers are being moved around these days.

**Comment by pekka2** [comment]
@rmullaney77 
Hi, what file, what line do that error message?
https://github.com/opencart/opencart/blob/master/upload/admin/controller/extension/module/amazon_login.php

**Comment by pekka2** [comment]
Option:
```
		if (isset($this->request->get['access_token'])) {
			$this->session->data['access_token'] = $this->request->get['access_token'];
			$user = $this->model_extension_payment_amazon_login_pay->getUserInfo($this->request->get['access_token']);
		}
```
change to:
```
		if (isset($this->request->get['access_token'])) {
			$this->session->data['access_token'] = $this->request->get['access_token'];
			$user = $this->model_extension_payment_amazon_login_pay->getUserInfo($this->request->get['access_token']);
		} else {
                  $user = array();
            }
```

**Comment by danielkerr** [comment]
its not going to be 3.0 because if you notice in the code i hvae blocked out loads of features that will be in the next version. Im going to get another release done for the end of this month that will include the new stuff. 

at the moment this next release is a bug fix one. the only major change is the extension folders. i think its better to have extension folders in their own folder to keep things clean. I will expand on the number of folders and also setup a uninstall system in the next version.

**Comment by rmullaney77** [comment]
I already forked with a fix. No needs for an else. Just define it as an array before the if ;)

**Comment by pekka2** [comment]
@rmullaney77 
seconly else loop use is consistent with Opencart code structure:
https://github.com/opencart/opencart/blob/master/upload/admin/controller/setting/setting.php#L528
