### ISSUE TITLE
Different store URL and SSL URL

### ISSUE THREAD

**Issue by RichardThomas1** [opencart/opencart#4631]
Testing 2.3.0.0_b1. 

With an additional storefront, the links from the cart to the SSL URL are correct, however this redirects back to the cart (as if the cart is empty / sessions not shared).

Fresh install with domains never used for Opencart. I have tried enabling "shared sessions" but that didn't help.

Using CentOS Linux 7.2.1511 (Core) with PHP 7.0.8 as FPM application served by Apache and same result on all common browsers.

test site: www.appliedbags.co.uk - default install with one product linked to this store.

There is no security certificate so once you "accept the risk" it goes to the SSL URL and is then redirected back to the cart. Works fine if both domains are the same (so the problem is not due to the lack of security certificate).

**Comment by danielkerr** [comment]
maybe because you dont have an ssl certifcate on your site?

or your ssl is on a different domain name?

Your connection is not private

Attackers might be trying to steal your information from www.appliedbags.co.uk (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID
  Automatically report details of possible security incidents to Google. Privacy policy
Back to safetyHIDE ADVANCED
This server could not prove that it is www.appliedbags.co.uk; its security certificate is not trusted by your computer's operating system. This may be caused by a misconfiguration or an attacker intercepting your connection.

try this go to settings table in the db and look for a entry config_url and delete it. it was left in by mistake. if you change domain names after install this can cause an issue.

**Comment by RichardThomas1** [comment]
I had already trusted the security certificate in my browser (tested on multiple browsers) before adding items to the cart and tried with Cloudflare SSL (although as that added cookies and caching I thought it would confuse the situation by showing you this). There are no errors, it just redirects back to the cart because the cart is empty on the SSL URL.

There is now a valid security certificate and I have done a fair bit of testing with and without www. in the SSL URL domain (as I suspected this was behaving differently - but now uncertain). To demonstrate the problem I have left the installation with three domains that behave differently:

Store 1 - www.appliedbags.co.uk which has secure domain with https://www.secure... (not working).

Store 2 - www.appliedbags.com which has secure domain https://www.appliedbags.com/ (i.e. same domain without a security certificate and works fine).

Store 3 - www.baglines.co.uk with the SSL as https://secure..... (same SSL domain as Store 1 but withougt the www.) - this still doesn't work but causes more confusion as the checkout redirects back to Store 1 which has SSL configured as https://www.secure.... This however looks like a different issue.

Could you please check the SSL URL cookies are as you expect when checking out via www.appliedbags.co.uk. This is a default install / no mods or .htaccess files in the path to the installation and with a full SSL certificate and no errors.

The PHPSESSIDs are different on the SSL URL and there is no __atuvc or __atuvs.

I have never noticed the difference with the setting "Use SSL" - which is currently "off" but same when "on".

I only had one entry for confing_url (before adding the above stores), deleted this and re-entered the Store 1 URL in admin - no difference. If there is anything changed with URLs in the master since B1 release I can try a master or specific version install that should be stable?

All my testing relates to additional stores.

Happy to provide FTP and Admin access to change URLs.

**Comment by danielkerr** [comment]
search in the db settings table for config_url and delete it. see if that
fixes the issues.
