### ISSUE TITLE
Cannot insert images from Image Manager

### ISSUE THREAD

**Issue by tommellor** [opencart/opencart#4675]
When trying to insert an image using the Image Manager, if there is more than 1 page of images, and you navigate to any page, other than page 1, when you click on the image to insert it, it just opens in the web browser.

Even if you navigate to page 2, then back to page 1, this will break also.

**Comment by herod2k** [comment]
I have just tested it with the latest relase and the default images/database and I can select and insert an image on page 2.
Which version are you using? Which browser/os?

**Comment by tommellor** [comment]
I am using v2.2.0.0. It has not worked on all the browsers I have tested (IE 10, IE 11, Edge, Firefox, Chrome) and I am using Windows 10.

I have also tried on a standard install, just adding a few more images, and it still breaks.

But, I found a solution to the issue, which I have posted here: http://forum.opencart.com/viewtopic.php?f=190&t=165268&sid=a138c24432a5f79c901796b5054d7491&start=20#p629275.

**Comment by tommellor** [comment]
So is this going to be fixed in 2.3.0.0?

**Comment by danielkerr** [comment]
@tommellor works fine for me!

**Comment by tommellor** [comment]
Well, clearly it is not working properly because it is not only me that is having issues with this. I have also tried it on other sites, that are also having this problem. So please at least wait until someone else has tested this before closing the Bug report.

Actually, we are moving over to Shopify for these very reasons, OpenCart is just riddled with bugs and now I understand why. So keep this closed if you want.

**Comment by trueliarx** [comment]
I have the same problem on 2 websites with opencart 2.2. Other versions of OC are working fine.

When I select the image it's not used by opencart but it just opens in the browser (In the address bar I have the full url to the image).

It happens adding images in the "information" pages and the image is located in a subfolder of the main catalog folder.
In other cases it also happens when I move to the 2nd+ page (with a lot of images) of the images manager and I go back.

I'm using firefox and from the errors console  (webdeveloper toolbar) I get no errors.
Other users have the same problem with different browsers.

**Comment by trueliarx** [comment]
following the link from tommelor I figured several of the problems/fixes.
I downloaded the opencart 2.3beta version of admin/view/template/common/filemanager.tpl (also updated system/library/image.php), that already adds some fixes, and replaced
this -> $('.pagination a').on('click', function(e) {
with -> $('.pagination').on('click', 'a', function(e) {

Right now the pagination seems to work.

Sorry for the disturb!
