### ISSUE TITLE
Customer_group_id set to 0

### ISSUE THREAD

**Issue by marioberberyan** [opencart/opencart#4704]
I have an issue with some of the customers who register on the website.

I`m using OpenCart v2.1.0.1. For some reason some of the customers do not have a valid customer group set - it`s set to 0. I have defined only one customer group in the Admin panel and it takes this Customer Group by default when registering new users. 
But for some reason a couple of users do not have this set. I`ve tried to reproduce this issue myself with not luck. 

The outcome is that those users are not displayed in the Users list and I cannot add tax on the products they order. 

I`m also using OneAll extension for social login - is there any chance it affects the customer_group_id field in some way?

Thanks,
Mario

![opencart_customgroup](https://cloud.githubusercontent.com/assets/6978005/17176541/dd603810-5415-11e6-9dc5-9b34cdfd94de.png)

**Comment by Felix-Ho** [comment]
do you mean this extension?
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24825&filter_username=OneAll

if your customer using this extension to login+register, probably the issue come from the extension code that did not adding the customer to a customer group.
Trying email the developer to check it for you.

Also, if your question related to extension.
Please try send email to support@opencart.com since this platform is using for bug report on opencart system only.
