### ISSUE TITLE
Sub-Total and Total

### ISSUE THREAD

**Issue by businessera** [opencart/opencart#4742]
Extensions > disabled Sub-Total not work Total in cart

**Comment by andrei-bogdan** [comment]
Hi, 

This is not an issue, the Sub-Total should always be left Enabled, it has to be calculated in order to show the Total.
This has already been discussed, you can find more information about it on OpenCart forum:
http://forum.opencart.com/viewtopic.php?t=84695
http://forum.opencart.com/viewtopic.php?t=18065

**Comment by trueliarx** [comment]
You must not to disable it or the calculations will be broken.
If you want to HIDE the subtotal you can try our free extension
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=22654

**Comment by asmaDur-01** [comment]
> Extensions > disabled Sub-Total not work Total in cart

if you use opencart V3 
Go to model -> extension -> total ->sub_total.php
add comment from 14 to 19
like this 

/*
		$total['totals'][] = array(
			'code'       => 'sub_total',
			'title'      => $this->language->get('text_sub_total'),
			'value'      => $sub_total,
			'sort_order' => $this->config->get('sub_total_sort_order')
		);
*/

**Comment by eka7a** [comment]
https://github.com/opencart/opencart/commit/2cd9265dd9e90b88e866498400d177c48d7cf6b3
