### ISSUE TITLE
2.3.0.2 Checkout with no shipping Issue

### ISSUE THREAD

**Issue by mallone** [opencart/opencart#4753]
Wanted to give a heads up on a verified bug with 2.3.0.2.

If a product has shipping you can checkout with no issues. 

If a product doesn't have shipping you cannot checkout. When you reach payment you get the "Warning: No Payment options are available. Please contact us for assistance!" message.

**Comment by danielkerr** [comment]
Don't choose pay on arrival then

**Comment by bositman** [comment]
This IS an actual bug and no settings affect it. If a product is set as no shipping required, you cannot get past the payment method step, since there are none listed there.
This completely breaks the no shipping feature of OpenCart since you can't actually use it without breaking check out. @danielkerr's response didn't make any sense to me.

**Comment by OpenCartAddons** [comment]
@bositman It makes sense that "Cash On Delivery" would not be available during checkout if no shipping is required.  This is because the system checks to see if the cart has shipping, since the intention is to collect payment at the time of delivery.  

You can remove the shipping requirement check for Cash On Delivery by making the following modification:

In **catalog/model/extension/payment/cod.php**

Find & Remove:
`} elseif (!$this->cart->hasShipping()) {`
			`$status = false;`

Free Checkout will not appear at checkout for any cart that has a value greater than $0.00.  You can remove this requirement by making the following change:

In **catalog/model/extension/payment/free_checkout.php**

Replace:
`if ($total <= 0.00) {`
`			$status = true;`
`		} else {`
`			$status = false;`
`		}`

With:
`$status = true;`

Cheers,
Joel.

**Comment by abelncm** [comment]
@OpenCartAddons you sir are the savior of the homeland thank you very much
