### ISSUE TITLE
Upgrade Opencart 2.2 oc_paypal_order_transaction issue

### ISSUE THREAD

**Issue by garychong** [opencart/opencart#4774]
After upgrade from 2.1.1 to 2.2 when I view any order which paid by paypal show this error:
`Fatal error: Uncaught exception 'Exception' with message 'Error: Unknown column 'parent_id' in 'where clause'<br />Error No: 1054<br />SELECT SUM(`amount`) AS `amount` FROM `oc_paypal_order_transaction` WHERE `paypal_order_id` = '5' AND `payment_status` = 'Refunded' AND `parent_id` != ''' in /public_html/system/library/db/mysqli.php:40 Stack trace: #0 /public_html/system/storage/modification/system/library/db.php(49): DB\MySQLi->query('SELECT SUM(`amo...', Array) #1 /public_html/control/model/payment/pp_express.php(146): DB->query('SELECT SUM(`amo...') #2 [internal function]: ModelPaymentPPExpress->getRefundedTotal('5') #3 /public_html/system/vendor/multimerchlib/module/autogenerated/system/engine/oc_loader-2.2.php(150): call_user_func_array(Array, Array) #4 [internal function]: oc_loader->{closure}(Array) #5 /public_html/system/engine/proxy.php(13): call_user_func(Object(Closure), Array) #6 /public_html/control/controller/payment/pp in /public_html/system/library/db/mysqli.php on line 40`

Can anyone teach me how to fix this! thanks a lot !

**Comment by garychong** [comment]
SOLVE!
In opencart 2.2.0.0 table oc_paypal_order_transaction field name parent_transaction_id change to parent_id. working fine now!

**Comment by robinflyhigh** [comment]
In https://github.com/opencart/opencart/blob/master/upload/admin/controller/extension/payment/pp_express.php

Line number 703 should be 

'parent_id' => $this->request->post['transaction_id'],

instead of 

'parent_transaction_id' => $this->request->post['transaction_id'],

Error Message: Notice: Undefined index: parent_id in /home/smartfxu/public_html/smartfx_co_uk/admin/model/payment/pp_express.php on line 64
