### ISSUE TITLE
model/extension/modification.php

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#4784]
If using ocmod make changes to the model/extension/modification.php, an error occurs after the refresh

Fatal error: Cannot redeclare class ModelExtensionModification in /home/****/public_html/****/admin/model/extension/modification.php on line 76

**Comment by florinsith** [comment]
That doesnt happen by default. Check that file, it should have only 76 lines.

**Comment by chulcha** [comment]
copy
admin/model/extension/modification.php
to
system/storage/modification/admin/model/extension/modification.php

Refresh!!!

**Comment by ksjones** [comment]
I'm getting the same thing happen, but I think that this is due to a modification being applied to the file you are calling.

In my case the refresh url is extension/modification/refresh so its calling the public function refresh in the controller/extension/modification.php file... while the system is removing the copy and rewriting a new one!

Check your modifications for any that apply to this file and I'm sure that you will be getting the same.

If it annoys you you could copy the original modification.php file and call it something different, then hack the core files to call extension/modification-copy/refresh from the refresh button instead - if it bothers you that much that you just need to refresh the refresh page when the error shows.

**Comment by AvanOsch** [comment]
Why is this issue closed?!?

OCModding extension/modification.php wasn't a problem before (at least up to v2.0.3.1), but now it's causing errors every time modifications are refreshed.
This makes modifying the modifications page next to impossible...

**Comment by danielkerr** [comment]
but I think that this is due to a modification being applied to the file you are calling.

**Comment by AvanOsch** [comment]
Definitely. I'm trying to modify the modification page, and indeed calling AND modifying extension/modification/refresh...
But like I said, this wasn't a problem before;
I'm updating an OCMod extension from version 2.1.0.1 to 2.3.0.x
There are hardly any changes to be made in the extension itself (only some changes in the <search> fields), but I keep running in to this error.

Is there a workaround I can use to get my extension up and running again (without hacking core files)?

**Comment by danielkerr** [comment]
This issue simple the mid needs updating. Should not be creating 2 function
of the same name. Should replace

**Comment by AvanOsch** [comment]
I'm not creating any functions.
Any change to /admin/model/extension/modification.php will cause the error...
Attached an example that only adds a comment to that file.
[test.ocmod.txt](https://github.com/opencart/opencart/files/833644/test.ocmod.txt)
rename to .xml, install, go to Modifications page, and click refresh (maybe a couple of times).

**Comment by AvanOsch** [comment]
I believe when there's a model/extension/modification.php in OCMod cache and refresh is called, somehow the original and the one in OCMod cache are loaded...

After some checking & debugging I found that the OCMod cached version gets loaded _first_, after which the original version is called.
So it has nothing to do with the file being saved or otherwise not being available.
