### ISSUE TITLE
Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model total!'

### ISSUE THREAD

**Issue by usefulz** [opencart/opencart#4789]
Fatal error: Uncaught exception 'Exception' with message 'Error: Could not load model total!' in /home/user/domain.com/system/engine/loader.php:169

Stack trace: #0 [internal function]: Loader->{closure}(Array, Array) #1 /home/user/domain.com/system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array)
#2 /home/user/domain.com/catalog/controller/common/cart.php(37): Proxy->__call('getTotal', Array)
#3 /home/user/domain.com/catalog/controller/common/cart.php(37): Proxy->getTotal(Array)
#4 [internal function]: ControllerCommonCart->index(Array)
#5 /home/user/domain.com/system/engine/action.php(51): call_user_func_array(Array, Array)
#6 /home/user/domain.com/system/engine/loader.php(24): Action->execute(Object(Registry), Array)
#7 /home/user/domain.com/catalog/controller/common/header.php(129): Loader->controller('common/cart')
#8 [internal function]: ControllerCommonHeader->index(Array)
#9 /home/user/domain.com in /home/user/domain.com/system/engine/loader.php on line 169

Version 2.3.0.2
PHP 5.4.45 (cli) (built: Sep  5 2015 09:31:58) 
Server version: Apache/2.2.31 (Unix)

2022579    4 -rw-r--r--   1 user user      355 Jul 30 16:34 catalog/model/total/total.php

**Comment by ratkobucic** [comment]
Hm, got same error with 2.0.3 -> 2.3.0.2 upgrade... shared hosting. And just figured out that catalog/model/total doesn;t not exist in default install archive?
And this issue is closed without any solution?

**Comment by losttheplot** [comment]
I'm getting exactly the same error after a 2.0.3.1 -> 2.3.0.2 upgrade ... dedicated server.
-rw-r-----.  1 webdev apache  355 Aug 18  2015 catalog/model/total/total.php

Any ideas anyone?

**Comment by losttheplot** [comment]
The problem is that there are lots of redundant directories and files left over from previous versions of opencart, that - I assume - the autoloader is trying to load. For example, the system is looking for /html/catalog/model/total.php (not /html/catalog/model/total/total.php) but total.php seems to have been moved to /html/catalog/model/extension/total/total.php. I'm not sure where the redundancies have come about from, 2.0.3.1 or earlier, but it would have been helpful if notices of these changes had been made in upgrade notes so that I could have deleted directories as necessary. Apologies if this has been done, but I could not find anything of help. 

I too would like to know the logic behind closing this issue!

Anyway, I started to compare and delete directories that appeared to be redundant, and came to the conclusion that far too much has changed over recent updates to leave me confident about the system being stable enough for a busy online shop. So I am now carrying out a completely fresh OC install and will then try and reinstall all the client's extensions and product images, and point the new file-tree at the old database, and re-theme everything, and maybe if I am successful I will take a well-earned holiday.

For all of OpenCart's strengths, the biggest criticism I have is that updates are such a royal PITA. If I ever get this site working properly again, I think I will leave it alone until it dies of old age!

**Comment by milezzz** [comment]
I get the same error after doing a 1.5.4.1 to 2.3.0.2 upgrade. 

@losttheplot:  Can you explain where to look for the routes, like you mentioned 'I started to compare and delete directories that appeared to be redundant'. Hoping someone can offer some assistance!

**Comment by losttheplot** [comment]
@milezzz: I compared each directory in my updated instance of opencart with each directory in the 2.3.0.2 download. I noticed that many files and directories had changed location (e.g. /html/system/modification/ is now /html/system/storage/modification/), and because the now-redundant files were still in place, I assume there were some redundant classes being auto-loaded, which was causing the original error as reported in detail above.

Anyway, I decided to effectively start from scratch again, and have managed to get the site working in its basic form using a fresh install of the 2.3.0.2 codebase. Except for another issue which I have raised here > #4903 which definitely seems to be a bug, and which I am hoping that someone who knows opencart better than me will be able to solve before I'm ready to go live with the updated site.

**Comment by losttheplot** [comment]
I'd still like to know why this issue was closed.

**Comment by milezzz** [comment]
Thanks for your comments @losttheplot.  I am hoping you could detail a little bit how you managed to get all your old data working with a fresh install of OC as I assume that is what i will have to do next.  *shudder*

I actually tried to export the data from my 1.5.4.1 OC and import via the OC tool but that failed miserably.

**Comment by losttheplot** [comment]
Because I was this time updating 2.0.3.1 -> 2.3.0.2, as opposed to 1.5.6.4 -> 2.0.3.1, and because the problems I was experiencing were being caused by the codebase files, and because I had already run the 2.3.0.2 database schema update, it was relatively easy to install a fresh copy of the codebase, then copy across the image directory and the two config files. This means that the fresh 2.3.0.2 instal is now pointing at the updated 2.0.3.1 database, and with the exception of the bug I mentioned above, it seems to be functioning as expected.

However, this does not allow for any of the many extensions/mods we have been running for the client, nor for the theme, which I had been growing increasingly unhappy with each time the theme was updated. The theme has lots of snazzy 'bells and whistles' features, but the more I had reason to study the files, the more I realised that they had not been coded particularly well or efficiently, and the more I understood why the site was so damn slow!

So I decided that with the introduction of a clean 2.3.0.2 codebase, and one with an HTML and Bootstrap layout structure that is considerably better than what opencart was a few years ago, that now was the time to design my own theme, working predominantly with CSS, so that I only need to update the header and footer file when updating opencart in future. Why the header and footer? ...because I also recognise one of the reasons opencart is so slow (regardless of the theme): because so many separate CSS and JavaScript files are loaded from the document head.

So this time round I have set up a sass/gulp workflow inside the custom theme directory, so that I can tweak all the bootstrap variables prior to loading bootstrap (saving the need for overrides), then load the opencart and extension CSS files, then my theme tweaks, then concatenate and compress (and a few more tricks besides) everything into one minimised and optimised CSS file. I've done the same thing with the JavaScript files and call them from the footer, and the site's speed increase is noticeable (as expected). This is all exactly what I do for normal websites and apps, but it's a bit more involved with opencart due to the wide distribution of CSS and JavaScript files throughout the codebase.

The only downside to moving the JavaScript down the page is that any JavaScript written by a module or extension 'in the page' has to be wrapped with a DOMContentLoaded event listener. But this is a small price to pay (and to have to repeat during updates) for the faster load times. As you say, upgrades are a pain, so I'm now doing my best to keep the codebase as clean as possible, and in the case of the javascript wrappers, I would rather manually update the core 'default' view files (God forbid ... "burn him!"), than have to run override theme files that might go out-of-date without me noticing.

So this is what I am in the middle of right now, as well as having to clean up the database of now-redundant theme and extension tables, and write or find new extensions and mods to restore functionality that our client cannot do without. If the client wasn't also a very good friend, I'm not sure I would spend this amount of time treating the project to such an in-depth upgrade, but I also see it as a challenge to try and get the best out of opencart despite its many problems, most of which stem from the collaborative nature of its life, and the endless pace of technological innovation and advancement in recent years.

As for the update of all the product data from 1.5.6.4 -> 2.0.3.1, well that was an experience I went through a year ago, and one that I would not want to repeat. Any automated update tools available at the time failed miserably, so I studied the 1.5.6.4 database schema in depth, then did the same for the 2.0.3.1 schema, then manually converted each and every product-related table across from v1 to v2 format/schema/structure. All turned out well but I would not recommend it unless you are already confident that you know what you are doing.

I would also suggest that if you don't have hundreds or thousands of products in your database as we do, there might be a case for simply starting all over again with a completely clean instal, and manually entering your product data from scratch. It depends how many products you have, of course, but don't underestimate the time involved in all the things I've described above. Good luck, whichever way you go.

**Comment by danielkerr** [comment]
its closed because its not an issue with the default OC!

I sugget using the forums!

there is no model total!

its model/extension/total/total

**Comment by milezzz** [comment]
Yeeesh. Well I've had too much scotch to go through that wall of text but I managed to convert a vintage OC 1.5.4.1 to 2.3.0.2 today. This was a large install with around 300 products, 5000 sales, 10000 customers and over $220k in revenue.  Worked ok!

I used this tool: http://www.opencart.com/index.php?route=extension/extension/info&extension_id=24347

I solved the problem mentioned earlier in the thread and discussed with the guy who **lostheplot** by:

- deleting my `admin, catalog` dirs and reupload them.  Also reapplied proper perms.
- delete `vqmod` and reinstall new version.
- More than a little bit of data massaging. 
- So much whiskey and greens.

**Comment by milezzz** [comment]
So yeah it was orphaned controllers and possibly other things left over from the prior OC install.  What shenanigans!  Is the OC upgrade path always going to this painful going forward? I need an anemia.

**Comment by losttheplot** [comment]
Sorry about the wall of text - I was trying to be helpful. Glad you got things sorted @milezzz .

WRT being a valid issue or not, if an app can't be updated easily then I call that an issue. If the upgrade instructions do not cater for dealing with orphaned controllers, then again I call that an issue.

**Comment by alex-ghub** [comment]
This site has the resolution:
https://forum.opencart.com/viewtopic.php?f=191&t=166012
