### ISSUE TITLE
Cannot create account with specific password

### ISSUE THREAD

**Issue by naramski** [opencart/opencart#4836]
It's seems it's impossible to create an account with password "test0test" (including double quote) but the password "test0test (no double quote at the end) succeeded. 

The validation of the form remind that the password must be length between 4 and 20 in the first case. Accounts creation succeeded in the second case.

**Comment by naramski** [comment]
If the password is "testtest" it succeeded also.

**Comment by andrei-bogdan** [comment]
Hi,

It seems that the double quotes characters from your password might get converted to `& #39;`
as explained here: http://stackoverflow.com/questions/19024821/php-strlen-returning-incorrect-string-length-caused-by-quote therefore giving incorrect length result. 
This seems to have already been fixed in the latest `catalog/controller/account/register.php` file version from GitHub. You need to open the mentioned file and replace this:
`if ((utf8_strlen($this->request->post['password']) < 4) || (utf8_strlen($this->request->post['password']) > 20)) {`
with this:
`if ((utf8_strlen(html_entity_decode($this->request->post['password'], ENT_QUOTES, "UTF-8")) < 4) || (utf8_strlen(html_entity_decode($this->request->post['password'], ENT_QUOTES, "UTF-8")) > 20)) {`
