### ISSUE TITLE
Sort Status Orders At Admin Gives Fatal Error OC 2.2

### ISSUE THREAD

**Issue by iplocker** [opencart/opencart#4886]
**Hello.**
It seems the sort order status gives a fatal error as there is no status column in the order status table. 
More here: 
http://forum.opencart.com/viewtopic.php?f=191&t=167770&p=638296 
**Thanks
Theo**

**Comment by andrei-bogdan** [comment]
Hi, indeed, there seems to be an error in OpenCart 2.2, but it has been fixed in the latest OpenCart versions.
If you don't want to update your OpenCart version, you should open file:
`admin/model/sale/order.php`
and replace this:
`'status',`
with this:
`'order_status',`
You can close this issue, since it has already been fixed in the new versions.

**Comment by iplocker** [comment]
OK if you said so :) 
Thanks
