### ISSUE TITLE
Opnecart 2.3.0.2 email not sending new order alert or from contact form.

### ISSUE THREAD

**Issue by gunaa08** [opencart/opencart#4946]
Hello, I'm having issue with opencart 2.3.0.2 mail problems.
1.Not getting any mail from contact form.
2.Not getting email alert for new orders.
Please help.
Thanks.

**Comment by munirasim** [comment]
Most of the time, it is email settings issue.

Many mail servers around the world have now implemented SPF, DKIM and DMARC hence you need to add SPF record of your web host's mail server to your primary mail server (where your email address is created) ... in case of Google, Yahoo and other mail services like that you have no way to add SPF record hence you can't use these email addresses with Opencart or any other CMS like Wordpress.

Therefore, do following steps:

1. Create email address on your domain where Opencart is installed

2. Make sure that email address works by sending and receiving email to and from that address (In one case I found that email box was full and user was complaining about Opencart not sending emails)

3. Under mail tab use MAIL protocol which only requires 2 fields:

a) Mail Potocol: MAIL
b) Mail Parameters: -f and then your email address so that they look like as in bold below
**-fyouremailaddress@example.com**

You may leave other fields blank and same email address should be under STORE tab but without **-f** parameter

I hope it helps.

**Comment by faca5** [comment]
https://www.opencart.com/index.php?route=marketplace/extension/info&member_token=EohEEKo1l4dA4UJ0259SSxlB1yX5k3Sj&extension_id=32538
