### ISSUE TITLE
Malicious files detected for example.com

### ISSUE THREAD

**Issue by nadygold** [opencart/opencart#4959]
Hi 
I am new in opencart but unfortunately when I upload my project online then my hosting provider(hostgator.in) said following file is infected Malicious. thatswhy they block outbound port 80, 443, 587 and 465 onward i couldn't enter in my admin panel.
infected file name is following.
www.example.com/catalog/controller/extension/payment/pilibaba.php
kidnly solve my problem
Thanks

**Comment by villagedefrance** [comment]
I can't see anything malicious in that file ...
Most payment files need to connect to an external payment gateway using callbacks, so there are external http links in the file, which is normal, but nothing suspicious.
If anything, I can't fix it anyway, as I can only comment here.

**Comment by priyorockz** [comment]
@nadygold I too faced the similar issue. To fix this, I removed catalog/controller/extension/payment/pilibaba.php (I don't need this payment gateway as well). Then I whitelisted the ports in the cpanel.

**Comment by jamesallsup** [comment]
There is nothing wrong with the file - if it was loading/including external JS files or something then that could be a cause but its not. The hosting provider is flagging a false positive but is still concerning that they are since it must be matching some kind of known signature for an exploit.

Have they provided any more information on why? Can you try and get more info from the host? Usually they will have a log entry from CXS scanner or maybe modsecurity (or something similar) as to exactly what line or bit of code matched the trigger. If you can get that I can look into it further.

Thanks.
