### ISSUE TITLE
DB password is visible when MySql server is offline

### ISSUE THREAD

**Issue by norbert-sz** [opencart/opencart#5027]
With mysqli driver, when MySql server is offline, we see raw PHP error that includes password, db name etc.

> Error No: ' in /home/user/domain/system/library/db/mysqli.php:10 Stack trace: #0 /home/user/domain/system/library/db.php(9): DB\MySQLi->__construct('localhost', 'opencart', 'pass123', 'opencart', '3306') 

I think that kind of errors should be hidden by default.

**Comment by danielkerr** [comment]
set error logging to off

**Comment by norbert-sz** [comment]
Setting display error to off in admin panel, does not have any affect in this case, because that variable is stored in DB which is offline. I know the solution is setting `error_reporting(0);` in system/sturtup.php, but who does that? I think this is serious problem, that affects almost all OpenCart installations and it should be fixed by setting error_reporting to 0 by default or by special exception for that class of errors.

**Comment by ThisIsADogHello** [comment]
Shouldn't e-commerce software probably take issues like this a bit more seriously?  This is a dangerously reckless attitude to have in general for software development, much less for something that handles real money.

**Comment by jamesallsup** [comment]
Servers should NEVER have display errors set to true to start with, but most people ignore it and do anyway (or leave it enabled in WHM settings for example). error_reporting(0); should not be needed on a production environment, 

That's not to say this is a server problem, because it certainly isn't.

This was already resolved a while back (Looked at v2.1.0.2) so I think it has been re-introduced by adding the throw exception when there is no default exception handler to catch it. That's why it will be ignoring the OpenCart settings for error handling; i.e. display or log errors

I'll patch this on the master but it is an easy fix for existing sites:

system/library/db/mysqli.php Replace lines 9 to 12 with one of the options here:
[https://gist.github.com/jamesallsup/5672a42b71fde477f971ed06651d307a](url)

The commit that broke it applied the same logic to the other database classes too, so may not be isolated to mysqli.

@norbert-sz I really hope they are not your username and passwords that you use! If it is I beg you to use something MUCH longer AND stronger

J.

**Comment by appeltaert** [comment]
huehue

**Comment by pgl** [comment]
@danielkerr Even if `display_errors` is `off`, you don't want passwords in your error logs either.

**Comment by kamranahmedse** [comment]
@danielkerr 

![](https://i.imgflip.com/17d4sc.jpg)
