### ISSUE TITLE
How to create Events for the Opencart 2.3

### ISSUE THREAD

**Issue by sippaprut** [opencart/opencart#5052]
Hello,

I would like to make hook after add product.
How to create Events for the Opencart 2.3?

I did see this document https://github.com/opencart/opencart/wiki/Events-(script-notifications)-2.2.x.x 
but it's old version.

Thank you

**Comment by johnwongoc** [comment]
Actually, it is not much different from 2.2. In order to create Events for OC, you need to add 

$this->load->model('extension/event');
$this->model_extension_event->addEvent(code, trigger, action); 

on the install function. Then, it will store the info on the database.  Once you load certain model or controller, events will be triggered.
