### ISSUE TITLE
Upload Custom sitemap.xml for each store

### ISSUE THREAD

**Issue by jimmypinto** [opencart/opencart#5065]
I'm using Opencart 2.0.2.0 and it is a multi store. I want to set custom sitemap.xml for each store. How can I achieve this?

**Comment by arnisjuraga** [comment]
What do you mean by "upload custom sitemap"?
Original extension google_sitemap - works for multistore.

In Admin It just does not display correct link for every store - but if you change the store address manually for the link - it works.

E.g.:

~~~
http://domain1.mystore.com/index.php?route=feed/google_sitemap
http://domain2.mystore.com/index.php?route=feed/google_sitemap
~~~

will generate correct sitemaps.

**Comment by jimmypinto** [comment]
Does Opencart create sitemap automatically for every store?If I prepare sitemap.xml file excluding some links, where should I upload it to?

**Comment by arnisjuraga** [comment]
Opencart Generates `sitemap.xml` for every request. This is made automatically. You just need to enable Extension under "Extensions > Feeds". Install AND enable "Google Sitemap" extension.

You also will see correct "path" for sitemap in Extension settings.

Sitemap will be generated automatically - just replace the domain name with your every store.

**Comment by jimmypinto** [comment]
Hi Arnisjuraga, thanks for explaining about the extension. Is there any possibility to upload my sitemap.xml which doesn't include all the links ?

**Comment by arnisjuraga** [comment]
You can, of course - then just upload it with different file names:
~~~
http://domain1.mystore.com/sitemap_firstStore.xml
http://domain2.mystore.com/sitemap_anotherStore.xml
~~~

And submit to Google with those links. It's "OK", if sitemaps has different file names, just be sure to submit them to Google.
Otherwise Google will now know correct file name to look up.

**Comment by jimmypinto** [comment]
My domains are like 
`http://abc.com
http://xyz.com`
Uploading them to the store folder means, the store's theme folder. Am I right?

**Comment by arnisjuraga** [comment]
If you create different sitemaps manually, then copy 2 different files with different filenames to `root`  folder of the store, 
if your root is `public_html` for example, put it there.

DO NOT use "sitemap.xml", because in .htaccess it's forwarded to OC feed controller.
Use, e.g.: 
create 2 files: 
`sitemap_store1.xml` and `sitemap_store2.xml`
and put them in root folder. 

Links will be accordingly:

~~~
http://abc.com/sitemap_store1.xml
http://xyz.com/sitemap_store2.xml
~~~
