### ISSUE TITLE
Header Search is not working on mouse click

### ISSUE THREAD

**Issue by jimmypinto** [opencart/opencart#5068]
I am using OC-2.0.2.0 Version. Header search auto complete select box is working by keyboard arrow selection but not on mouse click. Any help would be appreciated.

**Comment by arnisjuraga** [comment]
What do you mean, by "header search auto complete"? In Frontend?
I think Opencart does not have such feature at all for Frontend search:

![image](https://cloud.githubusercontent.com/assets/2185289/20978405/7610c576-bcb1-11e6-8eee-8a8bf14f719f.png)

**Comment by arnisjuraga** [comment]
http://demo.opencart.com

**Comment by jimmypinto** [comment]
You can check that here.
[](http://www.augasonfarms.com/)

**Comment by arnisjuraga** [comment]
This is nothing to do with Opencart itself. :(
This is a function you have in Theme template: 

You must contact a developer of theme Cosyone, or just develop it. But it can be more then just "search on click", because module must search also for empty strings (while you click in input field - there is no characters at the beginning).

Anyway - it's  not in a scope of Opencart Github.

Of course, you can try to ask in https://forums.opencart.com

**Comment by jimmypinto** [comment]
Hi Arnisjuraga, thanks again for giving an exposure on the issue. I'm unable to logon to opencart forums. I'll try to fix it myself :)
