### ISSUE TITLE
File Manager : Directory Does not exist

### ISSUE THREAD

**Issue by othreecodes** [opencart/opencart#5078]
I uploaded my opencart site to my host and now the File manager won't upload files. It keeps saying Directory does not exist. Also, The Product Images do not show for the already existing products. Ive checked all file permissions and everything checks alright.

**Comment by danielkerr** [comment]
reupload, reinstall.

**Comment by othreecodes** [comment]
@danielkerr I have done That already ... i even did a fresh install it still doesnt work

**Comment by danielkerr** [comment]
no one else is having this issue. also the this is a issue tracker for developers not your personal suppor ticket system. I think the issue will be with your hosting maaybe securtiy blocking urls with the word file manager.

**Comment by othreecodes** [comment]
@danielkerr Actually alot of other people have this issue... From the forums i found this 
https://forum.opencart.com/viewtopic.php?t=167778
and this 
https://forum.opencart.com/viewtopic.php?t=153707#p639722 .
It doesnt seem to have been solved yet.

**Comment by arnisjuraga** [comment]
Hi @othreecodes !
Check the email, may be we can find the problem and then post more info

**Comment by othreecodes** [comment]
I finally fixed the issue...guess the problem was from the config.php

**Comment by shubhamt619** [comment]
How did u fix it ? ? please share

**Comment by othreecodes** [comment]
First confirm the contents of your config.php is correct

**Comment by shubhamt619** [comment]
Done Bro. . . Thanks a lot

**Comment by arnisjuraga** [comment]
Could You share at least, what did you do wrong, so next time everyone can find the problem faster?

**Comment by sheldmandu** [comment]
@danielkerr the problem is actually in OpenCart code and is caused by the checks throughout the code which use realpath.  Many control panels as well as devops tools such as capistrano, ansistrano, AWS Code Deploy, etc use symlinks so that you have current -> release/20YYMMDDMM... In this case realpath will resolve to the actual real path rather than the symlink path and the check will fail.  This is the same problem if you use something like capistrano / ansistrano and use the concept of shared directories to store assets that should not change when you upload new code (e.g. catalog images).  I've run into this exact problem and only found the problem after digging into the OpenCart code.  It should be noted that this IS NOT a hosting provider problem, it's a problem with the way OpenCart has been written.

**Comment by brijeshtechximum** [comment]
i have tried everything but still now working .... need some help.

**Comment by danielkerr** [comment]
if ur using the master i altered something.

**Comment by danielkerr** [comment]
also i have no idea why you posted on a closed case and i have no idea what issue you are talking about as it works for every one else. i also use codebase and deploy and have no issues

**Comment by uviigideon** [comment]
I meet the problem today, and found might be this line on storage/modification/admin/controller/common/filemanager.php [line 240]
`
if (!is_dir($directory) || substr(str_replace('\\', '/', realpath($directory)), 0, strlen(DIR_IMAGE . '')) != str_replace('\\', '/', DIR_IMAGE . ''))
`
because realpath did not contain "/" on the end, so if DIR_IMAGE contains "/" on the end of dirname,
and User want to upload file on the image root. The test will be always fail.
I fixed this by replace line as follows solved my problem.
`
if (!is_dir($directory) || substr(str_replace('\\', '/', realpath($directory)).'/', 0, strlen(DIR_IMAGE . '')) != str_replace('\\', '/', DIR_IMAGE . ''))
`

**Comment by cascabels** [comment]
I am also met with the same problem...
What i did first,
in admin/controller/common/filemanager.php 
Change $json['error'] = $this->language->get('error_directory'); 
this to 
$json['error'] = $directory;

As a error it will show folder path and check the path if it all path is not excites create folder...  problem is fixed.. and revert the error msg code

**Comment by shashidhark** [comment]
Just create catalog folder in image folder.

**Comment by Lysak** [comment]
Need to check config.php, DIR_IMAGE shouldn't contain an additional slash (/) at begin of the path

```
$domainName = 'example.com';
$rootPath = "/home/www/domains/$domainName";
$path = "$rootPath/public_html";

// ...

define('DIR_IMAGE', "$path/image/");
```

**Comment by danielkerr** [comment]
this is an old post. and root path does not int he master branch.
