### ISSUE TITLE
vqmod DOMDocument missing in php5.6 issue

### ISSUE THREAD

**Issue by Olamyy** [opencart/opencart#5112]
I'm attempting to set up a store using opencart which i am honestly very new to. I bought a theme and for some reason the team uses vqmod. I was able to install the vqmod using:

> localhost/mystore/vqmod/install

and i get this response.

> VQMOD ALREADY INSTALLED!

Now, when i navigate to

> localhost/mystore

An error pops up saying

> DomDocument

The full error message is missing

> VQMod::bootup - ERROR - YOU NEED THE PHP "DOMDocument" EXTENSION INSTALLED TO USE VQMod

After a little research, i figured i had to install the php5.6-xml and php7.0-xml which i have.

However the error is still showing.

I went into the vqmod code and noticed the section raising the error is this.

```
if(!class_exists('DOMDocument')) {
        die('VQMod::bootup - ERROR - YOU NEED THE PHP "DOMDocument" EXTENSION INSTALLED TO USE VQMod');
    }
```
which means there's a DOMDocument class i'm missing.

However, i have tried everything i've seen online. From installing php-xml, purging php, installing php-dom,restarting apache2, checking phpinfo.

None of these seem to solve the issue.

How do i get the DOMDocument class?

**Comment by Icebox-Studio** [comment]
First off, this is not really an opencart coding issue which is what this posting forum is strictly here for. Your theme was created by a third party that you bought it from and VQmod is additionally an independent extension handler also created by a third party. When you go and buy OC themes, they are basically modified versions of opencart files, and furthermore, they can come bundled with other third party extensions. The only suggestion I can offer you is to either contact the theme developer in hopes of maybe seeking advice from them (most theme developers should offer some sort of a limited-time support for a paid theme right after it's bought - right?), or contact your hosting provider rather than further dabbling with php settings that may damage the functionality of your website. Again, this has nothing to do with the original opencart coding itself, since opencart didn't create your theme nor your extensions. Thus, it can't be deemed a coding issue. I hope my explanation makes sense to you, and I hope you seek out the appropriate forums/channels to get the support you are seeking.

**Comment by arnisjuraga** [comment]
@Olamyy if you install fresh Opencart, without theme - and add/install vqmod, does the original opencart with default theme works?
You must have libxml installed, to use VQmod, check this one: http://stackoverflow.com/questions/3403407/enabling-domxml-in-php
