### ISSUE TITLE
File manager/Image manager will not open

### ISSUE THREAD

**Issue by Olavnor** [opencart/opencart#5121]
Suddenly, when I try to add an image to a product (by clicking pencil pop-up) under product/image, it will not do anything. I just get a little "forbidden-icon".

**Comment by arnisjuraga** [comment]
Check browser console log. Any javascdipt errors? Custom theme?

**Comment by Olavnor** [comment]
I deleted some of the images via FTP and that seems to have solved the problem.

**Comment by Olavnor** [comment]
When I move some images into folders (all images were in root folder) it works again. I guess that means there's a limit for number of files in the root folder.

**Comment by osworx** [comment]
While you have closed this issue, maybe other will have this problem also.
You got an error 500.
Means simply, your server was gone - because of the massive amount of data (images).

**Comment by arnisjuraga** [comment]
Yes, you are tight now. Error appears because of "image resize".
When you open image browser, it requests image list and resizes Thumbnails.
- if you have a lot of images, then every time you open, it will generate thumbnails and can easily get "timeout" on server side (e.g. 30seconds). But, every next time you open it - it will generate thumbnails only for those images, which are not yet generated. So, eventually, afer X time, you should be able to open browser.

- but another problem is - if you have ANY huge image (>5MB and larger), then image resize can request a lot of server RAM, and you depend on PHP RAM limit. If you can, try to increase it to 256MB or 512MB. If not - then just search for largest images and resize them locally, then upload.

Give us a message, if you find which problem exactly this was.
