### ISSUE TITLE
Install via CLI usage: Must add slash at the end of http_server argument

### ISSUE THREAD

**Issue by sofyansitorus** [opencart/opencart#5130]
If we did not put a slash at the end of the http_server argument, the admin confirg for constant HTTP_SERVER and catalog config for constant HTTP_ADMIN will become:

define('HTTP_SERVER', 'http://domain.extadmin/');

**Comment by arnisjuraga** [comment]
`cli_install.php` is already trying to _validate_ slash at the end of `http_host` variable.

Unfortunately - it has no effect, because it's nor saving/changing it, nor returning any error anyway. Look here: https://github.com/opencart/opencart/blob/master/upload/install/cli_install.php#L122 

So, IMHO, better fix is just changing `valid()`  function definition to 

~~~php
function valid(&$options) { 
...
}
~~~

Then, it will work both and correctly add `/` if missing.

**Comment by sofyansitorus** [comment]
I don't thin return by reference is a good way. So I think it is better to format the options inside the get_options function, this way will make any options populated through this function will get correct format for the options.

**Comment by arnisjuraga** [comment]
It's not returning by reference. It's passing `$options` array as reference, so changes made inside function will appear in `$options` array after validation ends. But, of course, can be rewritten without reference, it's then just much more code.
