### ISSUE TITLE
Perhaps small bug in banner_form.tpl

### ISSUE THREAD

**Issue by thesamarkand** [opencart/opencart#5131]
File: banner_form.tpl

Line: 80
`<td class="text-center"><a href="" id="thumb-image-<?php echo $image_row; ?>" data-toggle="image" class="img-thumbnail"><img src="<?php echo $banner_image['thumb']; ?>" alt="" title="" data-placeholder="<?php echo $placeholder; ?>" /></a>`

Line: 110
`html += '  <td class="text-center"><a href="" id="thumb-image' + image_row + '" data-toggle="image" class="img-thumbnail"><img src="<?php echo $placeholder; ?>" alt="" title="" data-placeholder="<?php echo $placeholder; ?>" /></a><input type="hidden" name="banner_image[' + language_id + '][' + image_row + '][image]" value="" id="input-image' + image_row + '" /></td>';`

Change id="thumb-image' to id="thumb-image-' in line 110.

**Comment by thesamarkand** [comment]
Opencart version 2.3

**Comment by arnisjuraga** [comment]
I would say, that bug "is" on `Line: 80` - because:

pattern for HTML output `thumb-image<?php ...` is in files:

![image](https://cloud.githubusercontent.com/assets/2185289/21750498/c544bb42-d5bc-11e6-8b9d-7f8b36cacfdc.png)

but patter `thumb-image-<?php ...` is only in `banner_form.tpl` 

so because of majority, HTML output should be changed in `banner.tpl` not Javascript,
what do others think?

**Comment by danielkerr** [comment]
this has been fixed on the dev branch
