### ISSUE TITLE
Why Admin Can Change Password of customer in OpenCart

### ISSUE THREAD

**Issue by AkshayKungiri** [opencart/opencart#5143]
I view Open Cart. I also view deshboard of admin in opencart but i can't understand that admin can also change customer detail as well as username and password in opencart.
I don't know whether this is issue or feature?
If any one know about it then reply me

**Comment by arnisjuraga** [comment]
It's a standard security workflow. Administrators anyway will have access to site/admin/hosting/files/database etc. So, if you disable access to admin interface for changing passwords, it "does not matter", because admins will have other ways, how to alter users data.

E.g. - if admin can change customer e-mail, then
- he can set his own email as user email
- trigger "forgot password" and so on. 

:)

Quick search: http://security.stackexchange.com/questions/12339/should-an-admin-user-be-able-to-edit-passwords.
