### ISSUE TITLE
OpenCart 2.3.0.2 CSRF vulnerability - User account takeover

### ISSUE THREAD

**Issue by open-security** [opencart/opencart#5151]
Hello,
There is a security vulnerability in OpenCart 2.3.0.2 which allows a
hacker to break into a customer account.
The bug exists in "My Account Information" page. The form is not protected
with a token id, so a hacker can change user's information silently.
Here is a demonstrative video to explain this security vulnerability:
http://opensecurity.ca/media/opencart-csrf.mp4

With regards,
Open Security

**Comment by uksitebuilder** [comment]
How ridicuous - the hacker would need to be on the same machine and the user being hacked would need to have left browser window open and not have logged out of OpenCart

Much simpler for the hacker to use the browser history to go back to the PpenCart My Account page - Or press CMD / (Ctrl) + T until the tab re-opens

**Comment by arnisjuraga** [comment]
From the video, the hacker `doesn't need to be` on the same machine!

**This is VERY CRITICAL security issue, correct me if I'm wrong:**

1) User have to be logged into Opencart
2) If user now opens hacker link (sent in email, hidden in any web page) from the same browser in ANY tab, then hacker silently changes the user settings for the user.

**Comment by open-security** [comment]
Yes, the hacker doesn't need to be on the same machine.
CSRF is a dangerous security vulnerability and is one of OWASP's top 10 attacks:
https://www.owasp.org/index.php/Top10
https://www.owasp.org/index.php/CSRF

**Comment by arnisjuraga** [comment]
This has been discovered already 2 years ago. 
So, @danielkerr - this IS an issue:

https://www.curesec.com/blog/article/blog/OpenCart-2031-CSRF-66.html
http://seclists.org/fulldisclosure/2015/Nov/21

**Comment by danielkerr** [comment]
forget it! this guy has only registered an account to promote his own crappy services! 

Ive know about this for years but its always been at the bottom my priority list as its not worth fixing. I have explained this many times! 

but any reason i give this guy will argue with me rather than holding his hand up and admitting it, its always the "what if scenario!".

so lets do the maths

317,000 live web  sites using opencart.

1st how are you going to find which users are members of which store since no personal information about its users are listed on any opencart site!!! 

2nd even if you found a user the user would have to be logged into a specific store you are targeting while visiting a compromised page on another site. I dont know about you but i must spend a few minutes a year logged into sites i buy off. Im not logged in 24 hours a day while im, reading emails! 

so does this mean you need to randomly send out emails hoping that some one will click the link and be logged into an opencart store at the same time!

@open-security you are a scummy piece of s***!!

people are actually working and trying to help others so they can make money and get on with their lives! I dont need to spam posting on my issue tracker so you can lie to people to sell your services!

**Comment by attritionorg** [comment]
Generally, any targeted phishing attempt can be easily leveraged in cases like this by sending it to admin@ or support@ style email addresses for a site/company running a CMS or Shopping Cart. It doesn't necessarily require knowing exactly who has access, just relying on them being authenticated which they often are out of convenience and clicking a link (e.g. in email). So the bar for entry for this type of attack is not as high as you suggest.

Unrelated, I am curious about your comments about @open-security. The original bug report that included a link, did it go to a specific security company or Youtube?

**Comment by danielkerr** [comment]
"Generally, any targeted phishing attempt can be easily leveraged in cases like this by sending it to admin@ or support@ style email addresses for a site/company running a CMS or Shopping Cart"

and that is why there is a token based system protecting the admin from these attacks. but you have done nothing to check this. nor would ther

it went to a very badly designed web site about security with a video in the middle.

**Comment by attritionorg** [comment]
That makes sense why you redacted it, thank you for clarifying.

**Comment by iplocker** [comment]
**Hello.**
I dont know if this is relative but some times when I m going to login to the store front I see others customers details .
More in the ticket: https://forum.opencart.com/viewtopic.php?f=190&t=186673 
Thanks

**Comment by Shifterovich** [comment]
**Requiring current password to change password** (unless the forgotten password feature is used -- it's verified by email) is quick fix that should fix this.
