### ISSUE TITLE
Admin Change Password Without User Access

### ISSUE THREAD

**Issue by CCOC-Rick** [opencart/opencart#5177]
I have a user who wants to change their password once in a while, but they don't have access to the User settings section because I do not want them changing anything else.  Is there a way for them to just change their password via a screen where all it does is ask for the new password?

**Comment by danielkerr** [comment]
no. its something im planning but not on top of priorities.

**Comment by ChrisLancs** [comment]
Not sure how you organise your priorities but I would consider this to be a security matter.

The reason that I say this is because changing passwords (once authenticated) actually helps to keep an account more secure than a long standing password that give an errant user all the time they could ever need to A: circumvent any login failure limits and B: Attack an account by repeated attempts.

Of course I would not consider this to be a critical issue but certainly would consider it to be a priority issue.

One way: Password change form just needs to be available once logged in with three inputs in the form. Old password, new password and repeat new password.

Another way: a button to send a new password, old password needing entered to validate.

A different but more in depth way: granular settings that allow the site owner to fine tune what can and cannot be changed on the user pages. Ive seen this done web based billing software before and its a great tool.

The only caveat to locking it down for me is that it does put more strain onto support but as the owner I would have my own justifications.

**Comment by danielkerr** [comment]
@ChrisLancs you didn't read properly what hes talking about!

as usual some dick wannabe pretend security consultant has to make a uneducated reply without even reading what was said properly.

the current system is fine and secure!!! 

what @CCOC-Rick is talking about is having a separate page for users to update there details instead of having the sites top administrator handle it.

**Comment by ChrisLancs** [comment]
Thats the second time you have attacked me daniel, i dont know what the fuck your problem is but attacking the people that are using your software is not the way to go. Now i see why people think you are a prick. Its clearly because you really are.

**Comment by prhost** [comment]
@ChrisLancs you has email?

**Comment by webcorvo** [comment]
hi @prhost i think that you have one group editor.
The only way is you grant privilegies to user/user.
But there is a problem, that client access to all users and can unintentionally change your admin password :(

**Comment by prhost** [comment]
@ChrisLancs Sorry, you have email? Is that I have an extension that does this, I can pass if you prefer.

**Comment by webcorvo** [comment]
@ChrisLancs if you don´t mind i have the same problem ... webcorvo@gmail.com
Tks for your collaboration!

**Comment by CCOC-Rick** [comment]
Please send it to me as well if you could.  Rick@ccoc.email

**Comment by danielkerr** [comment]
@ChrisLancs maybe you should not post on the opencart github issue tracker 1 month later after i had already tagged it as planned. then you start some with some nonsense about security because you didnt read the issue.

**Comment by gujiman** [comment]
@prhost Please can you send it to me: gujiman@hotmail.com
