### ISSUE TITLE
Mail Error

### ISSUE THREAD

**Issue by mrrohanverma** [opencart/opencart#5179]
sir i am using oc 2.2x when i send mail from marketing>>mail to my
customers it show alert that  Your message has been successfully sent!
 but my customers can not receiving this mail please help me to solve
this problem

**Comment by arnisjuraga** [comment]
Watch and monitor for mail.log un hosting server, also `system/storage/logs/error.log` file endings.

1. customers could receive this mail in SPAM, it depends from hosting company.
2. you must create SPF record also Reverse IP DNS record for your hosting and so on.

If you CAN receive any email (password request, user registration, new orders), then, most probably, everything is ok with mail system.

Otherwise - check for error logs and give some debug info.

**Comment by mrrohanverma** [comment]
there is no error  it is sending mail to newsletter subscribers but not to customers and affiliates.

**Comment by dtlgc** [comment]
The sku’s I am looking for are

35350-2PK
35350-3PK

We have stock listed on amazon...
See attached images...

-Steve

**Comment by arnisjuraga** [comment]
@dtlgc ? :)

**Comment by mrrohanverma** [comment]
mr arnisjuraga you have uploaded open cart files can these are free from all errors and what is its version
