### ISSUE TITLE
OpenCart Vulnerability

### ISSUE THREAD

**Issue by robinflyhigh** [opencart/opencart#5285]
See this 5 min video @ https://vid.me/HH8k

Sorry to post as an issue but wanted immediate attention of @danielkerr

I know the attacker needs admin access to the site.

Attack SQL Query @ https://gist.github.com/robinflyhigh/4e13f7c444a3664441c150d125a18abe

**Comment by danielkerr** [comment]
if u have admin access u can do a lot more damage than what this video is
showing.

i dont know why people make stupid videos like this.  and then theres
people like you who post it but can clear see you need admin access!!!@!@

it like claiming ATM s have a visibility if the because the attacker
already knows your pin.

really what is the point of posting this crap!!!! try to get money from
advertising? try to make a name for them selves. they are morons.

**Comment by robinflyhigh** [comment]
Reason for logging it as an issue is these type of SQL script should not be executed https://gist.github.com/robinflyhigh/4e13f7c444a3664441c150d125a18abe

**Comment by robinflyhigh** [comment]
And if you have admin access you cannot view server files but then these type of attack happens they can have access to site files as well.

Sorry once again for posting and wasting your precious time.

**Comment by danielkerr** [comment]
@robinflyhigh are u stupid!

if u have access to the admin you can download a backup of the whole db decode the all the password hases or upload a hacking mod script to the extension installer! etc..!

but no not this clown!

so this clown not only logs into his own store using the username / password admin / admin but comes up with a bullshit hack of the error log rather than uploading a extension mod which one give him full access to the files.

this guy is an idiot! hes not a a hacker!

**Comment by samchen945** [comment]
We have several clients site got hacked by this simple attack. The key is that they have simple admin name and password like "123456 and "admin". Once hacker gets in, he will change the error.log -> error.php, and then...

We just mod the code from changing error.log extension  to *.php. Many new sites get hacked by this trick, guess they should be warne.

**Comment by danielkerr** [comment]
i really hope that was not your video you uploaded!

**Comment by robinflyhigh** [comment]
Nope, that's not my video @danielkerr

**Comment by danielkerr** [comment]
@samchen945

the user is the vulnerability if thewy use admin as their default login and poassword 1234.

its just the same as using a 5 character password for your web hosting! you will be hacked! very easy to get the login name from errors.

**Comment by danielkerr** [comment]
there person who posted this video would not know php properly., hes guessing what hes doing. it will be some guy poorly educated from some 3rd world country. vietnam, india, pakistain. etc..

use some common sense these guys cant code for shit.

**Comment by danielkerr** [comment]
also after the release of the cloud i plan to add 2 factor authentication to the admins.
