### ISSUE TITLE
Category Url Bug

### ISSUE THREAD

**Issue by offloo** [opencart/opencart#5302]
Hi Team
I Have Got Seo Url Error In All Sites 
Like I Have Two Category In My Site and site url is hello.com
1. abc
2.def 
if i opened
 hello.com/abc working fine
 hello.com/def working fine
Now if i Opened
Hello.com/abc/def
hello.com/def/abc
thats also working 
https://styloshopping.com/salwar-kameez/printed-saree
https://styloshopping.com/printed-saree/salwar-kameez

and i dont give any parent id to any category but working like that 
slove that bug

**Comment by cartbinder** [comment]
This links you are adding yourself.. In reality this links don't exist.
Links which exists on store or added in sitemap are only indexed.

Search engines don't have so much time to try such combination.
They shall index what links you have on store.

Also if your last seo keyword is correct it shall return the page since opencart checks the last seo keyword.

This is not a bug because Opencart is not generating this link its manually generated.

**Comment by arnisjuraga** [comment]
This is just how OC urls works.

e.g., these will work both. Even though, they are not "real".
The only thing, which uses the "path" from the url, is Breadcrumbs. It's not good, but that's how it works:

https://demo.opencart.com/index.php?route=product/category&path=28_25_28
https://demo.opencart.com/index.php?route=product/category&path=28

**Comment by danielkerr** [comment]
" It's not good, but that's how it works"

its not important!
