### ISSUE TITLE
OC 3.0.0.0-alpha: Additional email order alerts bug

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#5328]
In file **catalog/controller/mail/order.php**, in method **alert**, it doesn't send the additional alert emails because of a bug in file **admin/view/template/setting/setting.twig**:

To fix this bug please replace the line
```
                    <textarea name="config_mail_alert_email" rows="5" placeholder="{{ entry_mail_alert_email }}" id="input-alert-email" class="form-control">{{ config_alert_email }}</textarea>
```

with this one:

```
                    <textarea name="config_alert_email" rows="5" placeholder="{{ entry_mail_alert_email }}" id="input-alert-email" class="form-control">{{ config_alert_email }}</textarea>
```

**Comment by inktoner** [comment]
Notice: Error: EHLO not accepted from server! in /home/inktoner/public_html/system/library/mail.php on line 198
Alguem pode me dizer como corrigir esse problema??

**Comment by mhcwebdesign** [comment]
@inktoner: Your issue has nothing to do with this bug report. It is a separate support issue, please post on the OpenCart forum.

**Comment by mhcwebdesign** [comment]
Daniel, I just downloaded your latest code, and this bug is still there! In the twig template, the textarea field name is 'config_mail_alert_email', yet in the corresponding controller it uses '$this->request->post['config_alert_email']' for this posted variable!

**Comment by danielkerr** [comment]
ahh

**Comment by danielkerr** [comment]
ok should be fixed with my next commit

**Comment by mhcwebdesign** [comment]
Daniel, if you do it like this, you should also make sure that all occurrences of 'config_alert_email' are to be changed to 'config_mail_alert_email' in the files 

'system/library/openbay.php', 
'catalog/controller/mail/affiliate.php', 
'catalog/controller/mail/order.php', 
'catalog/controller/mail/register.php', 
'catalog/model/review.php',  and
'catalog/model/extension/payment/amazon_login_pay.php'.

**Comment by danielkerr** [comment]
I did . I maybe change the var name once more

On 10 Apr. 2017 3:23 am, "mhcwebdesign" <notifications@github.com> wrote:

Daniel, if you do it like this, you should also make sure that all
occurrences of 'config_alert_email' are to be changed to
'config_mail_alert_email' in the files

'system/library/openbay.php',
'catalog/controller/mail/affiliate.php',
'catalog/controller/mail/order.php',
'catalog/controller/mail/register.php',
'catalog/model/review.php', and
'catalog/model/extension/payment/amazon_login_pay.php'.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/opencart/opencart/issues/5328#issuecomment-292799396>,
or mute the thread
