### ISSUE TITLE
admin top right alert link are not working

### ISSUE THREAD

**Issue by scf8127** [opencart/opencart#5361]
HI

Admin top right alert link are not working

http://prntscr.com/evht30

**Comment by OpenCartAddons** [comment]
Current code is commented out because it needs to be patched.

admin/catalog/controller/common/dashboard.php
Line 75:  `$this->load->model('extension/report/customer');`
Line 77:  `$data['online_total'] = $this->model_extension_report_customer->getTotalCustomersOnline();`
Line 79:  `$data['online'] = $this->url->link('report/report', 'user_token=' . $this->session->data['user_token'] . '&code=customer_online', true);`

There should also be a check in place to ensure that `config_customer_online` is true and that the customer online report is installed and enabled.

The affiliate section including controller and model files appear to be missing from admin.

**Comment by danielkerr** [comment]
im reworking there stats as the current code is not good for large databases

**Comment by xdjxdaveyx** [comment]
If I may comment as you are re-coding this, it would be nice to see customisable stats to show stats for shipped, refunded, etc as an optional stat maybe? I don't know how you might go about coding this, but it could possibly be useful for monitoring totals? More of a suggestion for the future maybe?

**Comment by danielkerr** [comment]
Yes this could be done via extensions quite easily once I'm finished.

**Comment by xdjxdaveyx** [comment]
Thanks Dan. It was just an idea for a future release but I have no great need for it at present. One thing I would like to see is a feature to calculate the value for inventory (useful for tax purposes at the end of the year). This might be better as an extension which I had thought about doing myself as I have some programming experience but I don't really have much of a clue about the open cart module structure. I guess the program itself would mainly work on the database which can be done with php but I am unsure about integrating a UI with opencart. Are there any guides to programming modules for opencart available at all?
Kind regards,
Dave.

On 20 Apr 2017, at 15:55, Daniel Kerr <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes this could be done via extensions quite easily once I'm finished.

**Comment by danielkerr** [comment]
yes i senselabs has a good one for events.

im going to write one as soon as 3.0 is finished.

**Comment by xdjxdaveyx** [comment]
Okay cool thanks Dan ;)

On 22 Apr 2017, at 18:55, Daniel Kerr <notifications@github.com<mailto:notifications@github.com>> wrote:

yes i senselabs has a good one for events.

im going to write one as soon as 3.0 is finished.
