### ISSUE TITLE
Maintenance mode issue

### ISSUE THREAD

**Issue by barkeyo** [opencart/opencart#5394]
This is a re-open of issue #5334 and regarding OC forum thread -

[Maintenance Mode Issue](http://forum.opencart.com/viewtopic.php?f=181&t=173152)

Appreciate the recommendation not to use subfolders, and although I initially did, my OC 2.3.0.2 site was transferred to the public_html root to complete the upgrade process (from 1.5.6.4). Both of the config.php files (root and admin) and the .htaccess file were edited to ensure the correct paths were present. The /test subfolder was then deleted in its entirety. I now have just the main site resident in the root, and I still cannot view the site normally when logged in as admin with maintenance mode on. Everything else works just fine.

The issue still persists even after performing a completely fresh install of OC directly into the web root, as I originally indicated in the forum post that the OP on #5334 (akzogibbs) links to above.

Any ideas why?

**Comment by akzogibbs** [comment]
Hi Barkeyo, My hosting company has now resolved the issue for me. The issue was with the sessions not being saved. They changed the session save path and handler and the issue was resolved. I've asked them for details outlining how this was done as i'm unfamiliar with it. 

But what i don't know is why the path was wrong? My guess this that this isn't a Opencart issue but more of an issue with the server? But i'm not sure? Maybe Daniel can clarify?

**Comment by danielkerr** [comment]
delete the php.ini from all sub folders.
