### ISSUE TITLE
[PAYPAL EXPRESS] bug + fix

### ISSUE THREAD

**Issue by blakelongley** [opencart/opencart#5507]
Issue
OC Guest checkout > paypal saves products/shopping cart into a "MEMO" field however no checks for invaild characters. If invalid characters present, paypal payment reports error, flow ends but order complete. Invaild characters can be added from Product Options free text or File upload

Fix 
catalog > controller > payment > pp_express.php line: 462 run invalid character check or insert a generic place holder value ("Text input","Uploaded file" etc.)
Have had this issue on File uploads with image names

**Comment by blakelongley** [comment]
![screen shot 2017-06-12 at 12 36 02 12 jun 2017](https://user-images.githubusercontent.com/1914823/27033467-54f45d46-4f71-11e7-9c00-4dff72bfa97c.png)

**Comment by jamesallsup** [comment]
Thanks @blakelongley - I will take a look into this tomorrow

**Comment by jamesallsup** [comment]
Not sure why but commit notes dont show up!, Any this is now resolved.

SHA-1: 973b290e65f691734f80ce7ca519959e18d213af
* Admin side issues with PPEC recurring payments
* Notes:
Removed options from the description area when being passed to PPEC as there is too many minor issues that would render the data illegible. 1. PayPal has changed the design so the product info is actually hidden and you need to click to see it - it is also small so having large descriptions does not work well.

The issue also sparked a separate one with the actual name of products coming from OpenCart - PPEC expects 127 single byte strings but it is possible to pass a much large product name (tested - failed API request). Added max length check to all known fields I can find that would be required and now passes.

Issue #5507 is mitigated due to it no longer being part of the data being passed.

Close #5507
