### ISSUE TITLE
opencart 3 is very slow

### ISSUE THREAD

**Issue by nikto1** [opencart/opencart#5559]
This is the timeline of opencart 3:
![screen](https://user-images.githubusercontent.com/9814101/27333898-c1a12dd2-55c7-11e7-8b74-f0358a7eaedc.jpg)

Same page loaded of opencart 2.3:

![screen2](https://user-images.githubusercontent.com/9814101/27333942-ec21eb0a-55c7-11e7-8f9a-3adb253b078e.jpg)

The differenct between the 2 versions is about 9 seconds on the same server.
Thanks for looking into this

**Comment by xtensions** [comment]
If you are using localhost and especially admin panel then speed issue is due to system/config/admin.php

In action pre action of config it is compling sass to css on each call and it is taking too much time on localhost. I just commented the line 'startup/sass', and its working a lot faster and better now.

`'startup/sass'`
to
`//'startup/sass',`

Maybe this will help. Not sure why this being compiled on all url requests, should have been a flag system to refresh.

**Comment by danijelGombac** [comment]
This should be moved to events, where can be easy enabled or disabled.

**Comment by danielkerr** [comment]
u are also complaining about admin marketplace that uses curl. of course it will be slow when on localhost!

**Comment by danielkerr** [comment]
maybe setup a development mode as tempates are going to be cached

**Comment by danielkerr** [comment]
can some one do submit another issue for the sass.

**Comment by nikto1** [comment]
The test was made on the extensions-> extensions page, not in the marketplace page. Take a look on your own url's you write.

**Comment by danielkerr** [comment]
First url is the marketplace
