### ISSUE TITLE
Opencart image/file manager suddenly stopped displaying correctly

### ISSUE THREAD

**Issue by calexil** [opencart/opencart#5644]
very strange issue here, the image.file manager seems to have broken for some reason

I can fire it up in data tab>click image>edit just fine, but clicking any folder/button takes you to an unstyled page that does not function.

I checked permissions and everything seems right, DOM inspector shows no errors

![untitled](https://user-images.githubusercontent.com/3487071/27756296-5739d4b2-5dc4-11e7-84c4-62e94327aacd.png)

**Comment by webcorvo** [comment]
try to delete the system cache

**Comment by calexil** [comment]
how do I do that?

**Comment by calexil** [comment]
@danielkerr  that did not work

**Comment by calexil** [comment]
This was resolved by disabling Cloudflare rocket loader

Rocket Loader

**Comment by danielkerr** [comment]
self caused issue then

**Comment by calexil** [comment]
that's pretty dismissive @danielkerr  I didn't write the cloudflare api

:/

**Comment by danielkerr** [comment]
u maybe need to add some rules to cloud flare to allow the style sheet though

**Comment by calexil** [comment]
I just disabled rocket loader, it wasn't really doing anything

**Comment by kadlevent** [comment]
I'm having this exact same issue using version 2.3.0.2. I do not have cloudfare enabled! Can anybody help with this? I have cleared the system cache...

**Comment by danielkerr** [comment]
Clear Ur browser cache

**Comment by kadlevent** [comment]
I have cleared OC system cache and have also cleared my local browser caches. Still have the same issue. :-/

**Comment by danielkerr** [comment]
this must have been fixed. it runs fine in the oc demo and we are behind cloudflare. 

i recommend checking if this has been fixed in the latest version. 

if not then please post here. otherwise use the forums. or maybe use the contct us form ask for felix and provide ur login info so we can test ur store. also maybe ftp access.

**Comment by SlavaSt295** [comment]
sorry for my english. (google translate XD )

The reason is very stupid. I changed the pagination class in /system/library/pagination.php
Compare your file with the original one.

And yet, while looking for what might be the problem stumbled upon fix. I did not use it, it will suddenly help you. Change rows 33, 34 for this
`$this->request->get['directory'] = isset($this->request->cookie['file_manager']['directory']) ? $this->request->cookie['file_manager']['directory'] : '';
$this->request->get['page'] = isset($this->request->cookie['file_manager']['page']) ? $this->request->cookie['file_manager']['page'] : '';`
