### ISSUE TITLE
Opencart 3.0.2.0 Beta

### ISSUE THREAD

**Issue by tan2os** [opencart/opencart#5672]
1.You can`t see the page if you press, Desktops... show all desktops, you see just the  home page
   
2. After you change pictures of the banners slide show you see the initial one, i go back in the admin panel and i see no changes...it`s like begining.

**Comment by danielkerr** [comment]
1.You can`t see the page if you press, Desktops... show all desktops, you see just the home page

so i should guess your trying out SEO URL's? 

is this fresh install upgrade etc.. because it works for me!

try changing the basename on htacess


2. After you change pictures of the banners slide show you see the initial one, i go back in the admin panel and i see no changes...it`s like begining.

can not replicate.

wasting my time
