### ISSUE TITLE
Attempt to upgrade from OC 3.0.0.0 to OC 3.0.1.1 yielded error message!

### ISSUE THREAD

**Issue by naturecr** [opencart/opencart#5686]
Zip file for OC 3.0.1.1 was downloaded. All admin date backed up. Old config.php and admin/config.php was saved. Following upgrade instructions, all folders and files from OC 3.0.1.1 were uploaded to website, and allowed to over wright old files. Old config.php and admin/config.php were then uploaded. Browser set to http://<mystore.com>/openrart33test/upgrade/ and produced an upgrade page with continue button. When continue was clicked, the error shown below appeared.Per your instructions, I am turning in my results.

Error Code(0): Error: Table 'naturecr_opencart33test.oc_url_alias' doesn't exist
Error No: 1146
SHOW INDEX FROM `oc_url_alias` WHERE Key_name != 'PRIMARY' in /home/naturecr/public_html/opencart33test/system/library/db/mysqli.php on line 40

**Comment by naturecr** [comment]
Could this have anything to do with the Vendor folder placement? This folder was a part of the download, but no instructions given as to its placement. in the install notes, some mention was made to place the Vendor folder one level above the html_public, so I put it there. Not sure if the system knows whererit is. Also don't understand the Test folder placement.

**Comment by danielkerr** [comment]
download the master branch its fixed there.

**Comment by naturecr** [comment]
I have to ask you, where is the master branch, last time you told me to download oc3.0.1.1 and I did?

**Comment by naturecr** [comment]
you gave me this URL
https://www.opencart.com/index.php?route=cms/download

**Comment by danielkerr** [comment]
sorry this was an old table that is not used any more but was left in the upgrade script
u can delete this line of code if u know how.

https://github.com/opencart/opencart

the big grren button the right that says download. 

https://github.com/opencart/opencart/archive/master.zip

**Comment by danielkerr** [comment]
yes, and it was there when i told. it was called 3.0.1.1 (beta) i have not added a 3.0.1.2 (beta) yet,.

did u not look on the page?

Check out the previous releases

https://www.opencart.com/index.php?route=cms/download/history

**Comment by danielkerr** [comment]
im not wasting my time explaining this stuff.

**Comment by CoverUp** [comment]
Regarding this, I was testing the upgrade script.
3.0.0.0 -> 3.0.1.1 (compiled) Yields to oc_url_alias error, fixed in master
But i have tried
3.0.0.0 > 3.0.1.1 (master 06-07-2017) And i found a new error in the last step

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data OK Warning: file() expects parameter 1 to be a valid path, resource given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 161Warning: Invalid argument supplied for foreach() in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 163Warning: Invalid argument supplied for foreach() in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 174Warning: fopen() expects parameter 1 to be a valid path, resource given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 183Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 185Warning: fclose() expects parameter 1 to be resource, boolean given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 187Warning: file() expects parameter 1 to be a valid path, resource given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 199Warning: Invalid argument supplied for foreach() in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 203Warning: fopen() expects parameter 1 to be a valid path, resource given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 219Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 221Warning: fclose() expects parameter 1 to be resource, boolean given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 223Warning: file() expects parameter 1 to be a valid path, resource given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 161Warning: Invalid argument supplied for foreach() in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 163Warning: Invalid argument supplied for foreach() in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 174Warning: fopen() expects parameter 1 to be a valid path, resource given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 183Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 185Warning: fclose() expects parameter 1 to be resource, boolean given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 187Warning: file() expects parameter 1 to be a valid path, resource given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 199Warning: Invalid argument supplied for foreach() in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 203Warning: fopen() expects parameter 1 to be a valid path, resource given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 219Warning: fwrite() expects parameter 1 to be resource, boolean given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 221Warning: fclose() expects parameter 1 to be resource, boolean given in /home/opencart/public_html/demos/oc3/install/model/upgrade/1009.php on line 223{"success":"Patch 1009 has been applied (10 of 10)","next":"index.php?route=upgrade\/upgrade\/next&step=11"}

If you follow to 
http://yoursite_url/install/index.php?route=upgrade/upgrade/next&step=11

You get the correct answer
success | "Congratulations! You have successfuly upgraded your OpenCart installation!"

So the error is caused by the warning corrupting the json.

If you got warning muted you dont get any troubles of course.

It should be good to try-catch the warning on /install/model/upgrade/1009.php

**Comment by naturecr** [comment]
TECHDEV,
I found the same error--sort of long no?
