### ISSUE TITLE
Opencart 3.0.0.0 - Your shopping cart is empty ! missing message.

### ISSUE THREAD

**Issue by bond1126** [opencart/opencart#5699]
I found an error in catalog/view/theme/default/template/error/not_found.twig

`<h1>{{ heading_title }}</h1>
      <p>{{ text_error }}</p> // this will not display when item removed from cart`

Should be changed to:

      `<p>{{ text_empty }}</p>`

**Comment by danielkerr** [comment]
Stop wasting my time!

**Comment by bond1126** [comment]
It's a quite nice feedback. Will not report anything in a future.

**Comment by anerivala** [comment]
Thanks, it's working. But there are too many problems because of caching.

Whenever i changing the default theme folder then its show only disabled by default. Also not change the status of theme folder.

Need to more improvement...

Thanks
Tansukh Rathod

**Comment by rmullaney77** [comment]
Thinking this was another valid issue we found in OC3.0.2.0, seems fitting to report it here...

The text "Your shopping cart is empty!" is used in many places where it should not be. Seems "text_empty" is being used instead of "text_no_results".

Looks like every empty table/list in the "Account" area is affected at first glance of a clean OC 3.0.2.0 install. Figured it is worth mentioning so it doesn't get carried over to the next release.

Related: Many account pages are not getting the correct heading. One example is 'account/wishlist'. The 'wishlist.php' language files defines 'heading_title' as 'My Wish List' but 'Account' is shown. Have not dug very far into this one since we are treating 3.0.2.0 as not production ready at this point.

**Comment by rmullaney77** [comment]
See issue: https://github.com/opencart/opencart/issues/6070

**Comment by danielkerr** [comment]
i have just tested a category with no products in and guess what message i get using the master

**Comment by danielkerr** [comment]
if there is an issue its been fixed in the master branch

**Comment by bond1126** [comment]
I've fixed the issue by creating the new cart_empty.twig in the error folder.
