### ISSUE TITLE
permission denied to edit in Design > Layouts

### ISSUE THREAD

**Issue by leandroruel** [opencart/opencart#5767]
when i try edit one page layout i get the error: Permission denied! but i'm the admin, tried create another account with permission and get the same error!

**Comment by danielkerr** [comment]
i dont think opencarts ever had this issue. i can not replicate. which version are u using?

**Comment by leandroruel** [comment]
i'm using 3.0.1.1, wait... you think im lying?

![opencart](https://user-images.githubusercontent.com/2836002/28368971-837f42c6-6c6c-11e7-9e0b-07b60255bd47.png)
this is my admin panel and the message (in portuguese brazil)

**Comment by Opodeldoc** [comment]
Hit the same thing and came here googling for similar issues. I can't add any modules to any layouts, although I could remove one. The (only) user has all permissions. All I've done otherwise in the last week or so is add products and approve a review so I've no idea if it may have been triggered by a change otherwise.

![ocbug](https://user-images.githubusercontent.com/16832038/28590732-dabe111c-7148-11e7-89b9-85338204585c.png)

**Comment by Opodeldoc** [comment]
Looks like it's just a UX issue, at least for me. Hitting the edit icon without a module already selected in the dropdown. Not sure why this results in being sent to a permission denied page when it seems to have nothing to do with permissions, but there ya go. Hope it helps leandroruel.
