### ISSUE TITLE
OCMOD Modifications Not Working

### ISSUE THREAD

**Issue by gammo** [opencart/opencart#5852]
I have version 3.0.2.0 and have created an OCMOD that would normally work in previous versions of Opencart. It uploads and installs okay, at least I get a successful installation message. However, when I go to the Modifications page, I do not see it even after clicking the Refresh button. In addition, when I refresh my site, the modification is not seen. I know that I am coding the mod correctly, even ensuring that the .twig extension is appended to the template name in the file path. Is there a new step that I am missing to get the mod to work?

**Comment by Manitoou** [comment]
It's not a bug just make sure, if you doesn't run on the main web folder, to use for example : <file path="catalog/......> instead of  <file path="blablabla/catalog/......>.
If you have only a XML file w/o other files in upload, just rename your file to "install.xml" then zip it to "file_name.ocmod.zip" and install/refresh. That' it ;)

**Comment by gammo** [comment]
Thanks a lot, Manitoou, that worked! I was erroneously naming the OCMOD file with the full file_name.ocmod.xml . Thumbs up!

**Comment by amshehzad** [comment]
@Manitoou  i'm facing the same problem and carefully followed the steps mentioned above but still nothing is showing up in Modification list. Please help
