### ISSUE TITLE
[OpenCart 3.0.2.0] & in image name

### ISSUE THREAD

**Issue by shkabo** [opencart/opencart#5908]
How to reproduce:
Create new product, upload images that contain & character in their name. Result you won't have images displayed as you will have name&amp;name.extension stored in database, and that is not a valid url link for image.

**Comment by danielkerr** [comment]
Don't use the amp sign then

**Comment by zemguru** [comment]
May be this can help:
https://github.com/opencart/opencart/issues/616
https://github.com/opencart-ce/opencart-ce/commit/b1efd52de892d6aceea396278c7c5057f446d207
https://github.com/opencart-ce/opencart-ce/commit/43ec1e6ea0462641a934e90d407892320a3d0c38

**Comment by shkabo** [comment]
Why not to use it if its supported by the os and php?
I can upload image and when i browse it for the product image, I can see it in the selection modal, but if I use it e.g. rock&roll.png it will be stored in database as rock&amp;roll.png that will cause an error when loading in store.
There is no need for that "don't use it" attitude.

**Comment by danielkerr** [comment]
U should have a naming convention for all files.

**Comment by danielkerr** [comment]
It's going to get fixed because of another issue related to URL encoding.
But it's not a big issue. Files should always be a-z . - _ 1-9

On 29 Aug 2017 8:23 pm, "Daniel Kerr" <blueyon@gmail.com> wrote:

U should have a naming convention for all files.

**Comment by shkabo** [comment]
You have a client that sends you files, it's the least on your mind to use naming convention to rename 1k+ images for the products.
I know that files should be like that but you should not exclude other supported characters for naming convention of the file.

A side from that I'm reporting this bug as you probably have non technical users of OpenCart. OpenCart should be easy to use, and should not have these type of restrictions.

I can fix this on my own. I'm reporting this so that OpenCart can become better and bug free ...

**Comment by lucasjkr** [comment]
It's not a bug. Some characters should be disallowed in filenames, otherwise users could knowingly or unknowningly break their own sites.

For instance `&` is used as a GET parameter, and could cause unpredicable behavior

For the same reason, with a `/` could also cause confusion (the browser will be requesting a file from a certain directory), and files with `<`, or `>` in their names could, again, inadvertently (or intentionally) break a site when the browser tries to render it.

Much better to train the non-technical users to use a certain naming convention, rather than have OC (or any other web application) serve user data that could be unsafe.
