### ISSUE TITLE
Google Sitemap extension lastmod error

### ISSUE THREAD

**Issue by tanerinanir** [opencart/opencart#5959]
Hola,
problem file: opencart/upload/catalog/controller/extension/feed/google_sitemap.php
line 18 : $output .= '  <lastmod>' . date('Y-m-d\TH:i:sP', strtotime($product['date_modified'])) . '</lastmod>';

if date_modified default date then create invalid date
<lastmod>-0001-11-30T00:00:00+01:50</lastmod>

**reason :** create thread date_modified column  default 0000-00-00 00:00:00

**solution, workaround :**
$last_change_date = ($product['date_modified'] == '0000-00-00 00:00:00') ? $product['date_added'] : $product['date_modified'];
$output .= '  <lastmod>' . date('Y-m-d\TH:i:sP', strtotime($last_change_date)) . '</lastmod>';
or
if date_modified is 0000-00-00 00:00:00, lastmod line not show

**Comment by AlexChanHK** [comment]
I had just tested in localhost with the master version,
however even I manually edit the date_modified to 0000-00-00 00:00:00 it still did not exist issue.
<lastmod>1970-01-01T00:00:00+00:00</lastmod> <-result

Also the last modified should not possible to be 0000-00-00 00:00:00 unless someone edit the time
or the system exist issue when getting the time of it.
But in that case the date_added may be 0000-00-00 00:00:00 also,(due to get time fail when adding)
therefore the solution may need to change if it really happened.

I think this **issue can be closed**. If this case is same, you can share some example for us to understand.

**Comment by tanerinanir** [comment]
people who are in error
http://forum.opencart.com/viewtopic.php?f=191&t=166708
http://forum.opencart.com/viewtopic.php?f=188&t=166600
example screenshot : https://i.hizliresim.com/g9grg0.png

 and..

**original google_sitemaps extesion code** : https://hizliresim.com/NOXnBg
**my solution** : https://i.hizliresim.com/ZO6XB3.png

**Comment by danielkerr** [comment]
ok fine pm me your paypal email

**Comment by ADDCreative** [comment]
@AlexChanHK Prior to 3.0.2.0 it was possible for date_modified to be 0000-00-00 00:00:00 (which generates the incorrect <lastmod>1970-01-01T00:00:00+00:00</lastmod>). This happened if you added a product and never modified it. The date_added will be correct, but not date_modified. This was fixed in 3.0.2.0 by https://github.com/opencart/opencart/pull/5747.

The issue still may exist where there has been an upgrade from a previous version.

**Comment by AlexChanHK** [comment]
Hi @ADDCreative,
I understand what you are talking about, but as you mention it was fixed in 3.0.2.0 by #5747.
So this issue should be solved already?

**Comment by ADDCreative** [comment]
@AlexChanHK Not entirely. There is still the situation where products have been added using older version without them ever being modified and the store has been upgraded to 3.0.2.0 later.

**Comment by AlexChanHK** [comment]
@ADDCreative, I understand there are some case that the solution can not recover,
but I think we supposed to post the current issue in master version or latest released version in here,
and try to solved it together, not discussing the issue that we had fix already.

For the user in the case that you mention, I suggest that we can ask that them in update the product without any edition and try to submit the sitemap again.
