### ISSUE TITLE
OC 3.0.2.1 - Returns not sending mail

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#6074]
If 
- a customer send returns or 
- a admin is changing a return (e.g. History)
- with Notify Customer activated 
there is no mail sent.
(tested on PHP5.6 and PHP7)

**Comment by straightlight** [comment]
Since this is a transaction that may be started by a customer and modified by the merchant, a great solution to have, since the enquiry above is not a bug but rather a missing feature, would be to call the API from the admin/controller/sale/return.php file right above the JSON success message then to move the JSON success message via the API. This methodology would allow the customer and the merchant to rely on the same functionality in order to declare / manipulate the returns.

**Comment by danielkerr** [comment]
@straightlight do u not rteest any of the reported issues? there is a mail set to go out when the return history is updated,

**Comment by danielkerr** [comment]
even ttrigger is

admin/model/sale/return/addReturn/after

should be

admin/model/sale/return/addReturnHistory/after

**Comment by danielkerr** [comment]
UPDATE `oc_event` SET `trigger` = 'admin/model/sale/return/addReturnHistory/after' WHERE `oc_event`.`event_id` = 32;
