### ISSUE TITLE
Option values problem with update

### ISSUE THREAD

**Issue by stanislavdavid** [opencart/opencart#6082]
Simple example - 
I have multiple option groups and I want to add one option value to one of them.
But when I save it, in admin/model function editOption is made like delete all values and save all values. It will save everything but with absolutely different option_value_ids.
So I must go to every product which use this option group and alter all option values
I do not think, that this approach is ok

**Comment by danielkerr** [comment]
are u using the master branch?
nit sure which versionm you are using but its setup[ to save prioduct val;ue ids

this piece of code

<input type="hidden" name="option_value[{{ option_value_row }}][option_value_id]" value="{{ option_value.option_value_id }}"/>


thje model

$this->db->query("INSERT INTO " . DB_PREFIX . "option_value SET option_value_id = '" . (int)$option_value['option_value_id'] . "', option_id = '" . (int)$option_id . "', image = '" . $this->db->escape(html_entity_decode($option_value['image'], ENT_QUOTES, 'UTF-8')) . "', sort_order = '" . (int)$option_value['sort_order'] . "'");

ask in the forums because this has not been an issue for a very long time.

**Comment by stanislavdavid** [comment]
sorry, my fault
