### ISSUE TITLE
[v3.0.2.0 - Fix] - Two class names fixed from the twig recurring extension files in catalog

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6092]
A new topic has been created on the forum regarding these fixes: https://forum.opencart.com/viewtopic.php?f=201&t=194411#p694548

**Comment by AlexChanHK** [comment]
After watch the example in [w3schools](https://www.w3schools.com/bootstrap/bootstrap_alerts.asp)
I found that alert-dismissible of the alert tag is not very important.
(mean will not affect the function of it and misunderstand)

Some payment model was develop by other developer,
therefore the styles are difficult to unite.
(not sure if it is careless and deliberately to not using alert-dismissible)
You can replace that if you want.

Since it is not a issue that directly affect the system, **this issue can be closed.**
