### ISSUE TITLE
Image manager opening on 2.3.0.2

### ISSUE THREAD

**Issue by wrayvon** [opencart/opencart#6178]
Whenever I click the thumbnail of an image, then the edit pencil nothing happens. I have checked my console and can see this error:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/admin/index.php?route=common/filemanager&token=vfM7D32ArDnFi5rlmfzkiTIPrDUeiBNb&target=input-image&thumb=thumb-image

**Comment by py4object** [comment]
having the same issue

**Comment by py4object** [comment]
Hey looks like it's a memory problem ,I solved it by increasing the allowed memory size

**Comment by wrayvon** [comment]
Do you mean in the php.ini file? 

I have tried changing the memory_limit to 512m but to no avail.

**Comment by osworx** [comment]
Usually a server error 500 means something went wrong.
Either inside a php.file or javascript.
Could be also that this action need to long (time).

If it would be a memory issue, the message would state this.

I recommend to enable the error output like:
`error_reporting( E_ALL );
ini_set( 'error_reporting', E_ALL );
ini_set( 'display_errors', 'On' );`
Place that either inside the admin index.php or startup.php and see what is the real error.

Beside this, a php.ini is not allowed on all servers, check before with your provider if possible.
If everybody could use his own php.ini with obstruse values, customers serves would'nt be possible.

And memory_limit is not the only value you have to check, these also:
**post_max_size**
and
**upload_max_filesize**

All 3 have to be defined correct.

**Comment by wrayvon** [comment]
This is the error I get:
"Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 3252 bytes) in /home/sites/britishcountrycollection.co.uk/public_html/system/library/image.php on line 26"

Does indeed look like a memory issue but I'm not sure what else to change. 

In my admin folder, I have a php.ini with the following settings:
magic_quotes_gpc = Off;
register_globals = Off;
default_charset	= UTF-8;
memory_limit = 64M;
max_execution_time = 18000;
upload_max_filesize = 999M;
safe_mode = Off;
mysql.connect_timeout = 20;
session.auto_start = Off;
session.use_only_cookies = On;
session.use_cookies = On;
session.use_trans_sid = Off;
session.cookie_httponly = On;
session.gc_maxlifetime = 12000000;
allow_url_fopen = on;

Any suggestions as to what I should change @osworx ?

Thanks!

**Comment by wrayvon** [comment]
Ignore that, I increased the memory limit to 128 and it now seems to be working :)

**Comment by lukeyates1981** [comment]
This often happens if you have an image in the image manager that is too large (file size or pixel dimensions).

Increasing memory is one way to fix it, but you should instead resize the images so they are smaller. Images dont need to be bigger than the largest image setting for your site (check theme settings).

**Comment by osworx** [comment]
@wrayvon If you look at the message, you should know which value has a too small value:

> Allowed memory size of 67108864 bytes

On the other side, wtf needs an image bigger 67 MB ???
How many screens and browsers you intend to fullfill?
As @lukeyates1981 commented: images should not exceed the size as defined for the biggest images for your template.
Which is mostly around 800x600 px.
Which will lead to a very good quality and a size of max. 3.8 MB (not optimized).

btw: who you want to impress with that:

> max_execution_time = 18000;
upload_max_filesize = 999M;

Wonders me if your hoster will allow such stupid settings ..

**Comment by zemguru** [comment]
@osworx - Yes, You are right - the ancient 800x600px images are not a huge requirements for memory (anyway - today we are using full HD and retina (2x and 4x) screens, so these settings are from previous century).
but - @wrayvon - the problem appears, most probably, because You are uploading fullsize images, not-resized for web at all. But this is also todays "problem", because any smartphone makes great pictures, and resizing anything above 10Mpixels can lead to huge memory consumption:
take a look here: http://www.dotsamazing.com/en/labs/phpmemorylimit

**Comment by osworx** [comment]
@zemguru What for I will need a 3600 x 2700 pixel image - maybe in 24 bit .. - when I show it only with 120 x 80 px (for example).
And if possible as .png instead of .jpg
No matter if HD, QHD, UHD, shitty *phone or anything else.

But you - unfortunetaly - completey correct: every DAU can make pictures with his supadupaphone and download it directly into the shop.

**Comment by ChrisLancs** [comment]
I think this needs looking into then, hitting a server error would not happen if the file sizes etc were checked before doing attempting to do anything with the file.

Upload to tmp > check file dimensions/filesize return a message or proceed with resize. It should already be doing it but if you are getting those errors then clearly its not.

**Comment by zemguru** [comment]
@ChrisLancs good idea, 
1. check the available RAM for php process
2. calculate `image_pixels * some_coef_for_png_dpi <-> available PHP ram `
and display error if hit the limit

**Comment by ChrisLancs** [comment]
To be fair, I was thinking more along the lines of a flat out cap on the file size, osworx was correct, you dont need massive files uploading to the server, just one that is as large as your image settings requires, If you were to say 5MB size limit, then check the file is within the image size parameters plus lets say for argument 25% to allow for images that are otherwise outside of aspect ratio (although you should be sorting this out before upload to ensure a uniform look across your website) then these errors can be eliminated in all but a few odd cases.
