### ISSUE TITLE
[OC 3.0.2.0] HTML link tags in wrong places

### ISSUE THREAD

**Issue by mhcwebdesign** [opencart/opencart#6188]
Some templates, such as the **admin/view/template/catalog/product_form.twig**, have the HTML link tags in the wrong places. it is only allowed in the HTML head section!

Suggested fix: Add this code into the controller:

```
		$this->document->addScript( 'view/javascript/summernote/summernote.js' );
		$this->document->addStyle( 'view/javascript/summernote/summernote.css' );
		$this->document->addScript( 'view/javascript/summernote/summernote-image-attributes.js' );
		$this->document->addScript( 'view/javascript/summernote/opencart.js' );
```

And remove this from the template file:

```
  <script type="text/javascript" src="view/javascript/summernote/summernote.js"></script>
  <link href="view/javascript/summernote/summernote.css" rel="stylesheet" />
  <script type="text/javascript" src="view/javascript/summernote/summernote-image-attributes.js"></script>
  <script type="text/javascript" src="view/javascript/summernote/opencart.js"></script>

```

**Comment by lucasjkr** [comment]
Problem with doing what you suggest is that 3rd party templates that don't use these javascripts will still be forced to load them. That doesn't seem optimal either.

Probably just have the header.twig load all the scripts that a template will use, whether or not they're used on a specific page?

**Comment by mhcwebdesign** [comment]
If a 3rd party template really doesn't want to use them they can always use an event handler to disable them.

Having said that, we are dealing with summernote here which on a standard OpenCart is only used in the admin backend, whereas 3rd party templates from web themes are mainly on the frontend. My suggested code is to be added to certain controllers only, such as **admin/controller/catalog/product.php** or **admin/controller/catalog/category.php** etc, not to every one, and even then only in the **getForm** methods.

Besides, I wouldn't worry about 3rd party web themes here, most of them are rubbish, see e.g. Journal2 or other terrible themes.

**Comment by lucasjkr** [comment]
True, I wasn't thinking of it being on the admin side, rather than the catalog side. In that case, putting it directly in the controller doesn't seem like a bad thing. So agreed on that point.

Is there a downside to just including those scripts in the header.php controller, rather than picking and choosing where they appear? Once the admin loads the page, they should be in cache anyways,  so there's no impact moving forward. Just seems more consistent.

As for 3rd party templates - yeah, I only really like them to use as starting points. But still, if a template wants to do without scripts that are used by the default, it shouldn't be forced to load them. And having to use an event handler to do that seems like an unnecessary extra step. Anyways, its a moot point since you're only referring to the admin template. :)

**Comment by danielkerr** [comment]
maybe better being on the php side as these files can be overridden.
