### ISSUE TITLE
HEAVY load on MySQL server after #46

### ISSUE THREAD

**Issue by msva** [opencart/opencart#62]
Hi there!
I've get VERY HEAVY load on MySQL server after last upgrade. It is something about 6k products in the shop and some of top-level categories has ~1-1.5k products and ~20 subcategories inside. It is also two languages, so II.
So it is impossible to use shop, since opening index page takes about 5 minutes (!) sometimes.
Mostly strange thing, that OpenCart did hard work on MySQL server even with disabled (!!!) items counting.

I've also tested on shop with ~50-100 items and it is not so heavy load, but it still hurts server.
So, I suggest you to rollback that patch from #46.

**UPD**: Disabling category module reduces load on MySQL server. Shop pages loads faster, then with enabled one, but MySQL server "eats" 50-90% cpu in peak on each page load.

**Comment by webzstore-sahel** [comment]
My opencart version is 2.1.0.1
My server administrator highlights these below points 

large amount of the server's CPU resources
According to the statistics the average time your PHP scripts execute for is over 8 seconds. Keep in mind that in general PHP scripts should not take more than 1 second to complete their execution
The issue is very slow PHP scripts (average execution over 8 seconds). Your PHP scripts also generate a lots of MySQL queries which stack up:
Code:
+----------+------------------+-----------+-------------------------+---------+------+------------------------------+------------------------------------------------------------------------------------------------------+-----------+---------------+
| Id | User | Host | db | Command | Time | State | Info | Rows_sent | Rows_examined |
+----------+------------------+-----------+-------------------------+---------+------+------------------------------+------------------------------------------------------------------------------------------------------+-----------+---------------+
| 71492181 | myorga8_mofs | localhost | myorga8_mofs | Query | 82 | Waiting for table level lock | UPDATE oc_product SET viewed = (viewed + 1) WHERE product_id = '36232' | 0 | 0 |
| 71492688 | myorga8_mofs | localhost | myorga8_mofs | Query | 59 | Waiting for table level lock | UPDATE oc_product SET viewed = (viewed + 1) WHERE product_id = '25065' | 0 | 0 |
| 71492756 | myorga8_mofs | localhost | myorga8_mofs | Query | 1 | Sending data | SELECT COUNT(DISTINCT p.product_id) AS total FROM oc_category_path cp LEFT JOIN oc_product_to_catego | 0 | 0 |
| 71492784 | myorga8_mofs | localhost | myorga8_mofs | Query | 0 | Sending data | SELECT COUNT(DISTINCT p.product_id) AS total FROM oc_category_path cp LEFT JOIN oc_product_to_catego | 0 | 0 |
| 71492806 | viajesyc_wo6144 | localhost | viajesyc_wo6144 | Sleep | 2 | | | 0 | 1 |
| 71492813 | myorga8_mofs | localhost | myorga8_mofs | Query | 1 | Sending data | SELECT COUNT(DISTINCT p.product_id) AS total FROM oc_category_path cp LEFT JOIN oc_product_to_catego | 0 | 0 |
| 71492848 | intelliv_E69N6 | localhost | intelliv_865Tu | Sleep | 0 | | | 0 | 0 |
| 71492944 | myorga8_mofs | localhost | myorga8_mofs | Query | 1 | Sending data | SELECT COUNT(DISTINCT p.product_id) AS total FROM oc_category_path cp LEFT JOIN oc_product_to_catego | 0 | 0 |

Can you guide me the suggestion how can I fix the issue.

**Comment by krokodylowy** [comment]
Its easy and your admin gave you proper infor
- comment out line with update conter if you have high load
- comment out unnecessary counters if you have no index

**Comment by stalker780** [comment]
Actually this
 UPDATE oc_product SET viewed = (viewed + 1) WHERE product_id = '25065'
must be in a separate statistics innodb table, but not in oc_products. And statistics should be joined only where it is needed.

Cause
1. On MyISAM it blocks the whole oc_product table on each product view, so if you have some import running and clients are visiting products pages you will have problems.
2. This updates a product row on each view, so it will never get cached by MySQL.
3. This information is used only by module "most viewed" and statistics page in admin, but requires a lot of resources on some websites with lots of visitors.
