### ISSUE TITLE
Multi language website OC3 duplicate content

### ISSUE THREAD

**Issue by Manitoou** [opencart/opencart#6208]
I think that in my previous posts [#6189](https://github.com/opencart/opencart/issues/6189)  I didn't explain properly the issue, I see that there is a problem, OC3 create duplicate content:
Case 1: Take for example a website with English default language, and Search engines already are indexed your Eng URLs, and you want add Spanish but English still the default language, here there is no problem because SE didn't have Spanish links and only your visitors can see them;
But if :
Case 2: Take the same website with English default language, and Search engines already are indexed your Eng URLs, and you add Spanish but in this case Spanish will be your default language, here there is a problem when SE come to index your Spanish URLs and check the Eng URLs in the same time they will find that the content is the same.
I hope I was clear.
THX

**Comment by xguntis** [comment]
Why would the content be duplicate. Spanish and English are different languages and the content will be different, unless you have English content in Spanish pages.

**Comment by zemguru** [comment]
@xguntis because! :D I just checked, it's just silly!

Opencart does not use different links for different languages.

And it does not matter - do You use SEO or not - the language is still switched only by "POST" value, and in this case - there is no way for search engines to separate content for different languages:
`index.php?route=product/product&product_id=28`
`/htc-touch-hd` << for EN
`/htc-touch-hd-2` << for LV

when You open any link, it will still use the default language (if not detected by Opencart language detection). And that's it!

@danielkerr has not fixed/changed this from the 1st version of Opencart. May be there is some reason for that, but for SEO friendly shops, Opencart should not be used without some specific extensions.

Correct me if I am wrong.

**Comment by danielkerr** [comment]
because its a non issue!

**Comment by Manitoou** [comment]
@danielkerr  You are the boss, and the boss says that there is no issue, so there is no issue. 
I lost more than 4 years trying to convince my self that OC is good for me, but I just realize my error and limits of my choice.
Smile and don't be such an arrogant and "Mr I know all". Good luck with your business.

**Comment by danielkerr** [comment]
another rude clown who doesn't get what the want so you critisise and throw names around!

grow up! and fuck off!
