### ISSUE TITLE
Tracking Number

### ISSUE THREAD

**Issue by DemonRem** [opencart/opencart#6246]
can I supply tracking number and when the customer buy any product
he can track after his package with carrier name ?

**Comment by straightlight** [comment]
Not a bug topic inquiry.

**Comment by AlexChanHK** [comment]
There should be some extension providing the kind of function,
you can search in the [marketplace](https://www.opencart.com/index.php?route=marketplace/extension&filter_search=Tracking) and try the demo of extension to see if it is stable for you.
For this kind on enquiry, **better to ask and discuss in the forum next time!**
Since the it is related to some issue of Opencart system, **this issue can be closed**.

**Comment by danielkerr** [comment]
it is a feature that will be added. i just need some time to research it.

**Comment by bzark** [comment]
In the interim just use order history and tick the Notify Customer box.

**Comment by OC2PS** [comment]
@danielkerr In case it helps: https://docs.aftership.com/api/4/trackings

**Comment by OC2PS** [comment]
@bzark Yeah, but since most shipping companies use GET request, and therefore provide a way to put the tracking number in the URL to track,
it may be a good idea, if OpenCart enabled shipping extensions and/or store admins to associate `tracking` URLs with shipping methods. And in the order, there were a tracking number field.
So that when in order history or elsewhere, when the tracking number field is populated for an order, then the tracking number is appended at the end or the traking URL based on the order's shipping method, and the URL sent out to customer.

**Comment by OC2PS** [comment]
P.S. https://track.aftership.com/trackingnumber would work for a bunch of couriers

**Comment by Felix-Ho** [comment]
@DemonRem We have integration with Aftership which can provide tracking feature to your store.
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=8870
You can try their service.
And here is the documentation
https://help.aftership.com/hc/en-us/articles/115008508348-How-to-connect-my-OpenCart-store-to-AfterShip
Hope this help!
