### ISSUE TITLE
Feature request: Tracking extension installs

### ISSUE THREAD

**Issue by nchankov** [opencart/opencart#6249]
Hi guys, I've been advised to post this as feature request, so here it is:

I have a feature idea for the module/extension functionality. Basically I did this at the moment by using install.php in the extension zip, but since from v3+ you abandon this and even don't approve modules having this file in the zip I thought it's a nice to have feature.

Basically at the moment when someone install my extension in install.php I have a simple mail() function which send the domain as well as the admin email. I am not collecting the emails for spam reasons though, but in case I would like to contact the user like to remind him to purchase the extension, rather than to use a copy from some other forums (never did it so far, though).

Anyway. The idea is. in the install.xml the extension author could add a tag <extension_id> which will be the id of the extension in the Extension Market.

Then when installing the extension the script could make a simple curl call to your server passing at least the domain where the ocmod is installed (assuming that in the install.xml there is extension_id).

In the extensions there could be a section "installs" were authors could see the installs of their extension. This could be also included in the frontend of the extension's store by a number e.g. "extension installs: 1000 times"

if you get this further (by collecting the email of the installation) you could have a button like &quot;contact the user&quot; so the authors could try to contact the users and reminding them to pay the extension if they think it's unlicensed.

I am aware (from my experience) that some users try to install the extension multiple times or install it to some opencarts which are test instances (or placed on localhost), but at least the authors could have a fair idea who installs their extension. For example I have at least 5-10 installs each day of my extension, but this doesn't reflect on the sales, so I could assume that some of them are taken from somewhere else. :)

Anyway, I hope this make sense and you will implement it

**Comment by osworx** [comment]
> Basically at the moment when someone install my extension in install.php I have a simple mail() function which send the domain as well as the admin email. I am not collecting the emails for spam reasons though, but in case I would like to contact the user like to remind him to purchase the extension

From where are you from that you think you are allowed to send such emails??
Not to talk about collecting data nobody accepted ??

**Comment by nchankov** [comment]
I am not from here, earthling ... coming from a galaxy far, far away :) 

I've been told to post the issue here from the opencart support team (the site). I am aware the issue is not opencart feature, rather than opencart website feature, but that's what I've been advised to do, so I did it.

I agree email could be too much, but speaking from extension developer point of view having a way to see who install your extension is not bad idea.

**Comment by AlexChanHK** [comment]
Well, the developer removed to read install.php and install.sql in the extension installer,
but you can design to run this code in another way. (extension model install and uninstall method.)

As you can understand the extension is not complete activated after upload the ocmod with installer.
The user still need to go the admin panel->extension->extension->extension type and install the model.
(some developer placed the licence check method in here and tracking code to check who are using.)
The system will call the install method for create the database record and running the code in it.
You can place your code in install.php in it.

For the licence manage of the extension, it should be manage and design by the developer themselves,
therefore I will not discuss too much about it.
**Since this issue is related the licence manage of the extension developing only, and we had provide the solution suggestion already, I think the issue can be closed.**

**Comment by danielkerr** [comment]
its betyter to send a curl request with the domain name.
