### ISSUE TITLE
No event triggers on catalog/controller/startup/seo_url.php

### ISSUE THREAD

**Issue by mehov** [opencart/opencart#6339]
We need to add custom processing to [`ControllerStartupSeoUrl::rewrite()`](https://github.com/opencart/opencart/blob/2.3.x/upload/catalog/controller/startup/seo_url.php#L68). vQmod slows down the site and isn't an option. 

There seems to be no event triggers available on any of the [`ControllerStartupSeoUrl`'s](https://github.com/opencart/opencart/blob/2.3.x/upload/catalog/controller/startup/seo_url.php) functions, probably because it's being loaded through `action_pre_action` in [`system/config/catalog.php`](https://github.com/opencart/opencart/blob/2.3.x/upload/system/config/catalog.php#L33) and then [`system/framework.php`](https://github.com/opencart/opencart/blob/2.3.x/upload/system/framework.php#L139). Checked by doing a `var_dump($event)` inside [`Event::trigger()`](https://github.com/opencart/opencart/blob/2.3.x/upload/system/engine/event.php#L20).

We're using 2.3, but this doesn't seem to have been changed in 3.x

**Comment by Felix-Ho** [comment]
@mehov : Yes, we recommend you use ocmod to create method insert event detail such as code, trigger into the event table so that it can be trigger.

If you require more information about how to develop that.
Please visit our blog on how to use event system.
https://www.opencart.com/index.php?route=cms/blog/info&blog_id=174
Which post by Dreamvention

Hope this help!

Best Regards,
Felix
