### ISSUE TITLE
Unable to install multiple languages in admin version 2.3.0.2

### ISSUE THREAD

**Issue by Gewaagemstones** [opencart/opencart#6365]
I have devoured all the treads and answers related to this problem. In the admin panel I am unable to set up language code( pup up menu shows only en-gb) or the locale. Already FTP the language files . Please help.

**Comment by Felix-Ho** [comment]
@Gewaagemstones This is not a bug from opencart.
issue coming from the language pack probably not fully translate all the text field.

I install a Chinese language pack on opencart V2.3.0.2 today.
Working fine.
![language](https://user-images.githubusercontent.com/6228720/35266590-ac1a2710-005e-11e8-8bde-f4267acadc8f.png)

If you still have issue, using the contact us form from opencart.com to get support team to get help from you.

**Comment by Gewaagemstones** [comment]
Hi,
You did not understand my problem. In the c panel I am not able to modify
the locale since is a drop down menu and I have no file location field nor
image location field.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mentes
a vírusoktól. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-23 10:00 GMT+01:00 Felix <notifications@github.com>:

**Comment by Gewaagemstones** [comment]
Since you delete my tread please answer. I downloaded a trusted pack of
Hungarian language , FTP it to the appropriate folder. went to localisation
- languages -add language. I can not write the language code respectively
hu-HU because there is a dropdown menu that contains only the eanglish
language code. Please help me.

2018-01-23 10:34 GMT+01:00 Gems Gewaa <gewaa.gems@gmail.com>:

**Comment by Gewaagemstones** [comment]
![kep](https://user-images.githubusercontent.com/35723493/35275910-97d3ac76-0041-11e8-85b9-d7c01ac4b070.PNG)

**Comment by osworx** [comment]
First: Language Packs should be always free
Second: Language Packs for 2.x and 3.x should be able to be installed with the integrated installer AND NOT via FTP
Third: you copied all files via FTP, seems that you have copied them to the wrong folders
Because if the would be in the correct (language) folder, you should see the new Language in the dropdown.

For example: try to install this Language Pack (German):
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31048

And least: ask in the forum, you problem has nothing todo with the core.
