### ISSUE TITLE
[v3.0.2.0 git master branch] Add to cart button javascript error on product page

### ISSUE THREAD

**Issue by ramiax** [opencart/opencart#6390]
Hi,
there is a bug on default opencart v3.0.2.0 git master branch installation on product page that if you press "Add to cart" button javascript error alert box comes out. Chrome console gives this info:
**GET https://decodude.lt/index.php?route=checkout/cart/info 404 ()**

You can try this yourself on my v3.0.2.0 git master branch .lt domain website:
https://decodude.lt/index.php?route=product/product&language=en-gb&product_id=40

I have installed v3.0.2.0 version downloaded from your website on .com domain and it works just fine:
https://decodude.com/index.php?route=product/product&language=en-gb&product_id=40

P.S. Already tried to force https thru htaccess, turn off sass/theme cache and SEO URLs.

Can you help me fix this? Thanks.

Screenshot:
![tothegithub](https://user-images.githubusercontent.com/10676575/35832546-5abb6e4c-0ad6-11e8-966d-6e657de1c249.png)

**Comment by Felix-Ho** [comment]
@ramiax Yes, it was a bug from the github master branch of opencart system.
The reason is this is a development version of opencart.
Also, we have fixed this bug already.

If you would like to use opencart as your store, please download it from opencart.com
[Download Link](https://www.opencart.com/index.php?route=cms/download)
Which is a stable version for production.
Hope this help!
