### ISSUE TITLE
theme_path variable not recognised (3.0.2.0)

### ISSUE THREAD

**Issue by theJoff** [opencart/opencart#6391]
Hi,

This might simply be a theme issue but the support at Zemez are currently puzzled about this.

I installed Opencart 3.0.2.0 with the Zemez theme TechPower (https://www.templatemonster.com/opencart-templates/techpower-hardware-shop-opencart-template-66882.html).  It uses loads of 'JETIMPEX' modules.

Initially the site worked fine but at some point it completely broke:

http://s678184701.websitehome.co.uk/public_html/opencart/

I've noticed that the _theme_path_ variable in the twig template is returning nothing, for instance:
http://s678184701.websitehome.co.uk/public_html/opencart/catalog/view/theme//stylesheet/material-design.css
(Note the // between the theme and stylesheet folder.)

There may be other issues (i.e. this might only be symptomatic) because when I manually define the theme_path in the footer and header twig it only fixes some of the issues.

Between the site working fine and the errors, all I did was:

- Remove Russian and German languages (I only need English at the moment)
- Remove all the dummy products, categories and attributes
- Add new categories and attributes (and filters)
- Install the 'FixFilter OC2x - fixes default Opencart filter' (it is compatible with 3x, in case you ask)

I then uninstalled that filter module in case it was the cause - no change.

I've deleted all caches in the storage folder and refreshed the mods and refreshed the theme cache (and turned it off) and the SASS cache.  All to no avail.

I talked to Zemez live chat.  Although friendly, they had no idea (they told me to change the permissions on one CSS file...)

I've now raised a ticket with them and their first question was asking me what actions I made before the site broke.  This suggests they don't have much of an idea, which makes me think it could be an Opencart issue.

Thanks,

Joe

**Comment by Felix-Ho** [comment]
@theJoff Yes, this is a template issue because we don't have any bug from the template system.
Also, the compatibility is match from their website.

Here is my recommendation about your situation.
Using FTP to connect to your hosting and check the opencart system folder
under root directory/opencart/catalog/view/theme/
and check if your template folder is placing here correctly.
Also, please keep in mind that take a look from your new template folder's name.

If everything looks ok, then it probably a template issue and you can try uninstall and install it again.
Hope this help!

If you still have any issue, please make use of our contact us form from
https://www.opencart.com/index.php?route=support/contact
Because this is not the right place to discuss system usage question.

**Comment by theJoff** [comment]
Felix-Ho,

Thanks for your quick response.  The template folder is where it should be.  I'll get on at the template builders to fix.
