### ISSUE TITLE
Refactoring and cleaned duplicate code

### ISSUE THREAD

**Issue by konorws** [opencart/opencart#6448]
Good afternoon. I apologize for what I might have written in the wrong section.
But you have already released version 3. And I have two questions to the developers.
1) Why for three versions, no one has been engaged in code refactoring, because there are so many mindless and duplicated code that it's just horror. After refactoring, you can reduce some files size 3-4 times, which is quite a lot. Yes, and read will be more convenient.
2) Why is not PHPDoc? Practically not one IDE can not consider the structure of an project, it would help the development of a project several times.

**Comment by straightlight** [comment]
Because Opencart hasn't been developed with a workflow process which causes either wanted / unwanted repetitions in the codes.

**Comment by voku** [comment]
@konorws Yep, I also think that the php code need some refactoring. I haven't any experiences with opencart but if the IDE / quality-ensuring-tools has no auto-complete because of bad php code, then we need to refactoring that.

e.g.:

```php
// Totals
$this->load->model('setting/extension');
//...
$results = $this->model_setting_extension->getExtensions('total');
foreach ($results as $key => $value) {
    $sort_order[$key] = $this->config->get('total_' . $value['code'] . '_sort_order');
}
```

Why can't we use local objects here? 

Why we get an array instead of a object from this class? And why are all "Model"-classes are factories instead of models? Maybe we can rename all the model classes e.g. ```ModelSettingExtension``` into ```FactorySettingExtension```? 

Then add a real "```ModelSettingExtension```" with properties from the db, so we will have auto-complete in the IDE. And this class (array of classes) will be returned from the new "```Factory*```"-classes.

```php
/* @var $totals ModelSettingExtension[] */ 
// <- this can be moved into phpdoc in the "getExtensions()" methode
$totals = (new FactorySettingExtension($this->registry()))->getExtensions(FactorySettingExtension::TYPE_TOTAL);
foreach ($totals as $indexTmp => $total) {
    $sort_order[$indexTmp] = $this->config->get('total_' . $total->code . '_sort_order');
}
```

**Comment by berushka7** [comment]
in file security.php (in admin/language/common) is duplicated item text_admin

**Comment by konorws** [comment]
@straightlight You see here the problem is that it does not matter how it was conceived. After all, I'm not talking about how to build a big complex. system and just make the development more pleasant. Here's the brightest measure:
This generation of URLs in the admin panel in each file is repeated in some even 10 times. After all, this can be greatly simplified
`$url = '';

			if (isset($this->request->get['filter_name'])) {
				$url .= '&filter_name=' . urlencode(html_entity_decode($this->request->get['filter_name'], ENT_QUOTES, 'UTF-8'));
			}

			if (isset($this->request->get['filter_email'])) {
				$url .= '&filter_email=' . urlencode(html_entity_decode($this->request->get['filter_email'], ENT_QUOTES, 'UTF-8'));
			}

			if (isset($this->request->get['filter_customer_group_id'])) {
				$url .= '&filter_customer_group_id=' . $this->request->get['filter_customer_group_id'];
			}

			if (isset($this->request->get['filter_status'])) {
				$url .= '&filter_status=' . $this->request->get['filter_status'];
			}

			if (isset($this->request->get['filter_approved'])) {
				$url .= '&filter_approved=' . $this->request->get['filter_approved'];
			}

			if (isset($this->request->get['filter_ip'])) {
				$url .= '&filter_ip=' . $this->request->get['filter_ip'];
			}

			if (isset($this->request->get['filter_date_added'])) {
				$url .= '&filter_date_added=' . $this->request->get['filter_date_added'];
			}

			if (isset($this->request->get['sort'])) {
				$url .= '&sort=' . $this->request->get['sort'];
			}

			if (isset($this->request->get['order'])) {
				$url .= '&order=' . $this->request->get['order'];
			}

			if (isset($this->request->get['page'])) {
				$url .= '&page=' . $this->request->get['page'];
			}`

**Comment by straightlight** [comment]
The only problem by sanitizing the URL variables into generic tracking would be with the installed extensions users would be using since OCMod and VQMod both needs to search for specific lines. If only a single way would be needed to rectify the issue based on keys sanitizing, then extension developers would have a hard time to publish their extensions due to the lack of line tracking versus the mount of published extensions on the Marketplace and / or on 3rd party websites.

I did mentioned my point of vue last year on the forum regarding a parallel functionality based on the core and the extension events. This would greatly help to make the users understand the source of origin to know whether these errors would originate from the core or from an installed extension rather than relying on the server path specifically. Although, again, the only downside by simplifying the URL keys would also create more limited tracking from the XML files since Opencart does not contain a library to purely sanitize those values from the URL and even by adding a library, in this case, it would not suffice based due to remote API requirements that are either in use or not yet in use in Opencart.

**Comment by straightlight** [comment]
In addition, since your inquiry is not about bug fixes but rather a concept change, please post your request with codes in the Pull Requests section or in the Concepts section of the Opencart forum.
