### ISSUE TITLE
twing.php error after modification button in modification section

### ISSUE THREAD

**Issue by HuseyinYucel** [opencart/opencart#6453]
Hay,
When we say "refresh" in the modification section, the pages become inaccessible. and I get the following error in the code. Can you help solve the problem?
Good work,

[09-Mar-2018 ...] PHP Fatal error:  Class &#039;Twig_Loader_Filesystem&#039; not found in /home/aaa/storage/modification/system/library/template/twig.php on line 14

**Comment by straightlight** [comment]
Your storage folder may still be inside your public_html folder. Follow these instructions: https://forum.opencart.com/viewtopic.php?f=202&t=201745#p713479

**Comment by Vibrat** [comment]
@straifightlight Is this because the file permission is restricted in accessing to system/storage? I have problems with files permission in cache and logs when moving from local computer to server. Do you know sources for digging more into file permission rules?

**Comment by HuseyinYucel** [comment]
Hello,
As you can see in the picture, the paths specified in my system are working differently.
I also checked the file directory permissions. I did not see any problems.
admin -> dashboard and from admin -> extensions -> modifications -> refresh button, I keep getting this error. I had to come back from the backup of the server.
What else do you recommend?

![resim](https://user-images.githubusercontent.com/17760101/37401750-28e6cd36-279a-11e8-98b7-567761c5ea70.png)

**Comment by AlexChanHK** [comment]
Well, it is better to send a support ticket for OpenCart staff to do some basic checking for you.
https://www.opencart.com/index.php?route=support/contact
Normally, the case will not exist in flesh installation on released version, maybe it is extension issue .

Also, I always test to install extension without moving the storage folder outside the system,
therefore I think the issue is not related to that.

**Comment by straightlight** [comment]
The issue is caused by the automatic option selected from the Security Modal window in the OC admin. Do not select the automatic option, always choose manual. This has been discussed many times on the OC forum as I did provided the instructions several times to the users.

Yes, this is caused idealistically by the Opencart dev team since this option should not be integrated. Although, since this issue can be reproduced between users in a persistent way but cannot be reproduced to all users, it is still up to the users not to select this option even though the core suggests to use it from fresh installation of OC.

**Comment by straightlight** [comment]
A post has now been created to follow either possibilities when that happens: https://forum.opencart.com/viewtopic.php?f=176&t=200804#p717782

**Comment by AlexChanHK** [comment]
@straightlight
What kind of automatic settings are you talking about?
Can you provide some example or screenshot?

**Comment by danielkerr** [comment]
this issue is because of storage folder does not have correct permissions.
