### ISSUE TITLE
[v3.0.2.0 - Fix] - catalog\controller\startup\session.php file

### ISSUE THREAD

**Issue by kid1194** [opencart/opencart#6471]
Sometimes the $this->request->get['api_token'] returns NULL because it doesn't exist. I faced this error in the not_found page. So my solution was:

To change this: 
$api_query = $this->db->query("SELECT DISTINCT * FROM `" . DB_PREFIX . "api` `a` LEFT JOIN `" . DB_PREFIX . "api_session` `as` ON (a.api_id = as.api_id) LEFT JOIN " . DB_PREFIX . "api_ip `ai` ON (a.api_id = ai.api_id) WHERE a.status = '1' AND `as`.`session_id` = '" . $this->db->escape($this->request->get['api_token']) . "' AND ai.ip = '" . $this->db->escape($this->request->server['REMOTE_ADDR']) . "'");

Into this:
$api_token = (isset($this->request->get['api_token'])) ? $this->request->get['api_token'] : 0;
$api_query = $this->db->query("SELECT DISTINCT * FROM `" . DB_PREFIX . "api` `a` LEFT JOIN `" . DB_PREFIX . "api_session` `as` ON (a.api_id = as.api_id) LEFT JOIN " . DB_PREFIX . "api_ip `ai` ON (a.api_id = ai.api_id) WHERE a.status = '1' AND `as`.`session_id` = '" . $this->db->escape($api_token) . "' AND ai.ip = '" . $this->db->escape($this->request->server['REMOTE_ADDR']) . "'");

I hope that I was helpful.
Best regards

**Comment by AlexChanHK** [comment]
I understand this can prevent some error when $this->request->get['api_token'] is not set.
However, can I know what case will actually cause this issue?
It is better to compare the result before edit and after edit to convince the developer to accept the edition.

**Comment by straightlight** [comment]
Similar solution was posted a few days ago: https://forum.opencart.com/viewtopic.php?f=198&t=202726&p=716825&hilit=api_token#p716825

**Comment by JesseOC** [comment]
@kid1194 Thanks for your report!
But would you please share how to make this issue happened? And let us test it and fixed it well.

**Comment by danijelGombac** [comment]
@JesseOC 

I think it happened every time you use upload/catalog/controller/api/login.php

**Comment by straightlight** [comment]
In addition, the fact that the catalog/controller/common/footer.php file validates in an IF statement if the IP address can be tracked, the catalog/controller/startup/session.php file does not but rather insists of its use during the lookup along with the API token.

**Comment by cyberformed** [comment]
https://github.com/kid1194 

Thanks for the solution. It worked for me.

**Comment by danielkerr** [comment]
this should be fixed now. since i have rewriten how the order editor works.

**Comment by danijelGombac** [comment]
@danielkerr 

This issue is not related to order editor, but "api/login", which is not used in admin side.

If you try to login to the api using contorller "api/login" you need to post username and key, but the api_token is set after the login.

In the controller "startup/session" the system check in the db for alive sessions, if you use route with "api/" in it.

Maybe change in "startup/session":

`if (isset($this->request->get['route']) && substr((string)$this->request->get['route'], 0, 4) == 'api/') {`

with 

`if (isset($this->request->get['api_token']) && isset($this->request->get['route']) && substr((string)$this->request->get['route'], 0, 4) == 'api/') {`

or

`if (isset($this->request->get['route']) && substr((string)$this->request->get['route'], 0, 4) == 'api/' && (string)$this->request->get['route'] != 'api/login') {`

**Comment by straightlight** [comment]
Issue already reported here as on-going: https://github.com/opencart/opencart/issues/6787 . Topic was closed prior due to unverified claim.
