### ISSUE TITLE
[v3.0.2.0 - Bug] Editing existing records at Design > Language Editor (design/translation/edit)

### ISSUE THREAD

**Issue by slavko23** [opencart/opencart#6476]
See https://github.com/opencart/opencart/issues/6009 it still not fixed in OpenCart 3.0.2.0

Main problem - you disabled fields in view (by attribute disabled). As result controller has not this data (from the disabled fields) when user doing the POST request. It throws validate error (because validateForm() method got empty data)
Some variants of a solution:
- set 'readonly' attribute instead 'disabled' on fields
- [use hidden field for 'key' field (for successful validation) || don't do validate or change validation for edit] AND change model (update only field VALUE by translation_id)

**Comment by slavko23** [comment]
I created modification as a temporary solution.
Need to install here Extension > Extension Installer and run here Extension > Modifications.

What did:
- admin/view/template/design/translation_form.twig
changed attribute 'disabled' to 'readonly' in view for 'key' field (it allows to pass validation in the controller)
- admin/model/design/translation.php
changed the method editTranslation(). We update only field VALUE Where certain translation_id
[languageeditorfix.ocmod.zip](https://github.com/opencart/opencart/files/1829466/languageeditorfix.ocmod.zip)

**Comment by AlexChanHK** [comment]
Hi @slavko23,
The issue that you mentioned is exist in version 3020, 
but fixed in master-version already with different method.
(As least it is fine when I had just install and try.)

As it version 3020 is a released version already, the developer can't apply any edition into it.
Therefore it is better to post the OCMOD edition in forum or marketplace for user to install the patch.

Normally, the we only check the issue exist in master version and report in here.

**Comment by slavko23** [comment]
@AlexChanHK Sorry, I did not know that here need to report only about the master branch. Thank you for your answer

**Comment by AlexChanHK** [comment]
It is okay, it was really a issue in Opencart version 3020.
As it is fixed in master version already, the next released version should be fixed also.
