### ISSUE TITLE
system/library/mail.php error handling modification proposal

### ISSUE THREAD

**Issue by pine3ree** [opencart/opencart#654]
When something goes wrong and mail cannot be sent, mail library does:

trigger_error('MESSAGE_HERE');
exit();

but calling exit() stops the rest of the scripts (mail is called within model and controller methods) and this can lead to problems..as incomplete/incorrect ajax responses...etc

wouldn't be better just:

return false;

or 

return 'ERROR_MESSAGE_HERE';

(with a "return true;" at the end of the send method in case of success)
return values false/true can be intercepted by calling methods to give more accurate information back to the system/user instead of just stopping the execution.

es in calling model/controller method 

$result=$mail->send(....);
if (!$result===true) {
$this->log->write($result);
// and/or do other stuff
}

kind regards

**Comment by elleeott** [comment]
Can this issue be re-opened? We're experiencing many problems related to the mail library exiting when mail fails to send.

**Comment by andys2p** [comment]
This is a real issue when developing a payment plugin and you still have to do things if email fails. As a workaround we could overwrite error handling function, but this is not really a solution. Usually functionalities like this should return values or throw errors so we can treat the errors.

Imagine someone pays a product and because of email error order is not updated and we run into problems. If email functionality exists we have always to be sure sending emails is the last action.
