### ISSUE TITLE
SMTP Mail is not going

### ISSUE THREAD

**Issue by KalaiarasanSeetharaman** [opencart/opencart#6574]
I am facing issue in opencart 3.0.2
Please help me mail is not going using smtp
I am using wamp server
smtp i have used gmail
Host : tls://smtp.gmail.com
Port: 587
Gmail username and password given but mail is not going

Same thing i have used in laravel project .. There mail going fine . But in opencart i can't
![issue](https://user-images.githubusercontent.com/16400150/38559414-923081cc-3cf0-11e8-916c-2c039fe46e01.png)

**Comment by lucasjkr** [comment]
Have you made changes to your smtp.php file?

Because your errors aren't lining up. SSL error is occuring on line 140, and your uncaught exception at 157.

I just tried myself, also on a local install with a gmail account with the same exact settings your referenced in your post. I had to change the Gmail settings to "Allow Less Secure Apps", but after that, it worked fine. Even before I changed that setting, i got a different error: `Error: AUTH LOGIN not accepted from server! `

This is most certainly something specific to you. Revert the changes that you've made to that file.

Also, just realized, insure that your WAMP environment can reach the internet.

**Comment by Pelham81** [comment]
May I ask why is it a necessity for you to test your emails through your actual gmail for a local test server? If you're just testing your emails and their format/templates, you can just use something like **Test Mail Server Tool**: https://toolheap.com/test-mail-server-tool/ 

Download it, run it, and voila - whatever email you have set for OC settings will emulate outgoing emails with it. It's just far faster to setup and test outgoing emails that way. I have mine set up to work with Mozilla Thunderbird. OC also by default has SMTP port listed as 25 in admin/settings, and the tool by default is set to 25.

**Comment by JesseOC** [comment]
Sorry that it is not the bug of OpenCart project.
For the suggestion, maybe you can create a new topic on https://forum.opencart.com.
