### ISSUE TITLE
Postcode not properly escaped in Square Up payment module

### ISSUE THREAD

**Issue by miklcct** [opencart/opencart#6603]
The post code field is not properly escaped in the Square Up module, making script injection a possibility.

Steps to reproduce:
1. Configure and enable the square payment module
2. Add something to shopping cart and make a guest order
3. Enter `');alert('test');('` into the post code field when entering the shipping address
4. Choose Credit / Debit card (square) as the payment method.

The result is an alert box saying 'test' has pop up.

**Comment by straightlight** [comment]
No OC version posted. Could not find specified line with alert('test'); in TWIG files from v3.0.2.0 or v3.0.3.0b

**Comment by miklcct** [comment]
This above procedure is done on master, and `');alert(test);('` is something the customer enters as the postcode

**Comment by straightlight** [comment]
From which file on the master files do you see this line of code?

**Comment by ADDCreative** [comment]
The issue is this line. https://github.com/opencart/opencart/blob/3.0.2.0/upload/catalog/view/theme/default/template/extension/payment/squareup.twig#L130
Which should probably be something like.
```php
paymentForm.setPostalCode('{{ payment_zip|escape('js') }}');
```

**Comment by straightlight** [comment]
This issue is related to UTF-8 encoding with the postal code. Either using the suggestion above or using the html_entity_decode, ENT_QUOTES, UTF-8 may also fix the issue.

**Comment by ADDCreative** [comment]
@straightlight It has nothing to do with UTF-8 encoding and html_entity_decode will not fix the issue.

**Comment by Pelham81** [comment]
There should really be some sort of validation for the zipcode being entered through the controller files imo. However, you can also implement a client-side check for non numerical/letters. But, anyway, I looked at the catalog/model/extension/payment/squareup.php file. At line 66ish for public function addTransaction, shouldn't the billing address zip for instance be something like: 

`"', billing_address_postcode='" . $this->db->escape((string)$address['postal_code'])`

**Comment by simo-vt** [comment]
This report seems like a general sanitization issue in OpenCart, not Square. This is because the Postcode field is inserted in a controller which is not related to any payment extension.

The JavaScript code will be dangerous if it gets executed in the admin panel for example, which does not happen. Try completing the guest order and then access the admin panel to see that the Postcode field will display as `');alert('test');('`, but this is not inside a `<script>` tag, meaning there is no actual danger. Please correct me if I am wrong.

Nevertheless, I will soon submit a pull request with the TWIG escape `{{ payment_zip|escape('js') }}` just in case.
