### ISSUE TITLE
Slow query on orders report

### ISSUE THREAD

**Issue by RhuanGonzaga** [opencart/opencart#6612]
Hi, when I try to acess my Admin > Reports > Sales > Orders my site (https://www.myopencart.com/admin/index.php?route=report/sale_order&token=XXX) makes a long and heavy query:

`SELECT MIN(o.date_added) AS date_start, MAX(o.date_added) AS date_end, COUNT(*) AS `orders`, SUM((SELECT SUM(op.quantity) FROM `oc_order_product` op WHERE op.order_id = o.order_id GROUP BY op.order_id)) AS products, SUM((SELECT SUM(ot.value) FROM `oc_order_total` ot WHERE ot.order_id = o.order_id AND ot.code = 'tax' GROUP BY ot.order_id)) AS tax, SUM(o.total) AS `total` FROM `oc_order` o WHERE o.order_status_id > '0' AND DATE(o.date_added) >= '2018-04-01' AND DATE(o.date_added) <= '2018-04-27' GROUP BY YEAR(o.date_added), WEEK(o.date_added) ORDER BY o.date_added DESC LIMIT 0,100;`

On my slow query mysql log:

```
Time                 Id Command    Argument
# Time: 180427  9:10:46
# User@Host: user @ localhost []
# Thread_id: 7  Schema: db3  QC_hit: No
# Query_time: 174.424562  Lock_time: 0.000151  Rows_sent: 0  Rows_examined: 119123553
# Rows_affected: 0
use db;
SET timestamp=1524831046;
SELECT MIN(o.date_added) AS date_start, MAX(o.date_added) AS date_end, COUNT(*) AS `orders`, SUM((SELECT SUM(op.quantity) FROM `oc_order_product` op WHERE op.order_id = o.order_id GROUP BY op.order_id)) AS products, SUM((SELECT SUM(ot.value) FROM `oc_order_total` ot WHERE ot.order_id = o.order_id AND ot.code = 'tax' GROUP BY ot.order_id)) AS tax, SUM(o.total) AS `total` FROM `oc_order` o WHERE o.order_status_id > '0' AND DATE(o.date_added) >= '2018-04-01' AND DATE(o.date_added) <= '2018-04-27' GROUP BY YEAR(o.date_added), WEEK(o.date_added) ORDER BY o.date_added DESC LIMIT 0,100;
```

I think this query maybe need some attention for rows_examined: 119123553.
Is it possible optimize this ? Thank you!

**Comment by lucasjkr** [comment]
Best solution would be to add `subtotal`, `shipping`, `total` and `tax` columns to the orders table, instead of having the `order_total` table. Then your whole report could be done in a single query rather than what looks like 1 query _plus 2 queries per order_.

That wouldn't necessarily show the total products ordered in the time period, but that's probably not the best metric either. No idea of such a pull request would be accepted, since it such a change would touch on so many different pieces of code.

Actually, it doesn't look so bad.

The installation SQL plus 8 files, potentially.

**Comment by lucasjkr** [comment]
The indexing isn't the issue that @RhuanGonzaga is having. They apparently administer a very active store - this query won't be spread up that much even with perfect indexes - it's the volumes  of subqueries that's killing it. The Orders table contains the value for `total` already, and `commission`, no reason why `subtotal`, `tax` shouldn't have been there as well. Instead of the oc_order_total table

@RhuanGonzaga - out of curiosity (so I can replicate your conditions): 

How many rows are in the following tables:

`oc_order`

`oc_order_product`

`oc_order_total`

**Comment by RhuanGonzaga** [comment]
Hi, yes!

oc_order = 5,278
oc_order_product = 70,654
oc_order_total = 15,955

This is a new store running opencart 2.3.0.2 the oldest has:

order = 210,588
order_product = 2,721,983
order_total = 655,491

Thank you for all support!

**Comment by lucasjkr** [comment]
Hi. Out of curiosity do you have a development server you can test on?

I have a query logger on the Opencart Extension Store:

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=30729&filter_license=0&filter_download_id=55&page=19

I'd be very curious to know how many queries are executing when you build a report on either of these?

It needs VQMOD, and creates a new file in your storage directory.... The count isn't explicit, but we can tell by the number of lines.

Again, don't run it on your production server - it adds a little overhead from the IO operations AND dumps all the queries, including sensitive information, to a text file that could be exposed. 

I'm looking at the DB, and if my thought that it's the sheer number of queries is correct, then there won't be an easy solution. My inclination is to get rid of the order_total table, and refactor the code around it so that data is put in the order table. This won't be a solution for you, though, since even if a pull gets accepted, it'll be in the current OC version, not the version your store is on.

At this point, seeing the volume of records you're dealing with (congrats on a successful store!), i don't know if there's an easy solution... As @Pelham81 pointed out, you might have much better results from your current situation by looking at the extension store for a solution, even though it will cost a few dollars.

**Comment by danielkerr** [comment]
@Pelham81 you want to lie you will get a ban! every table is indexed!

**Comment by lucasjkr** [comment]
@danielkerr - would you be open to a pull request encompassing what I suggested?

**Comment by dyslexicdrakness** [comment]
@RhuanGonzaga 

If you or anyone cares to add _additional_ indexes themselves here's what I added to speed things up:

```
ALTER TABLE `oc_order` ADD INDEX `order_report_index` (`order_status_id`, `date_added`);

ALTER TABLE `oc_order_product` ADD INDEX `order_product_index` (`order_id`);
```

obviously this is an optimization not a solution... damn your stores sell a lot.

**Comment by danielkerr** [comment]
i think they are working now.
