### ISSUE TITLE
[v3.x - FIX] - system/library/encryption.php file - Vector IV

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#6661]
There has been multiple reports on the forum in the past regarding the Vector IV parameter not being structured properly when instantiating encryption / decryption methods. Followed is a fix that will help to resolved most of the issues: https://forum.opencart.com/viewtopic.php?f=198&t=204707&p=725370#p725077 .

However, there also has been discussion about this addressed issue on the forum that programmers should also pay attention with the ways to instantiate the encryption and decryption requiring Vector IV which also includes the facts that API developers from the providers can periodically make some changes to their APIs. That being said, there are ways to test these behaviors so not to affect users.

Using the addressed modifications allows to test the length of the OpenSSL despite the way the Vector IV parameter has been instantiated (and even empty) - a very similar way when testing XML / JSON objects when needing to validate their lengths when capturing an API response. Rather than returning an error handler message while the customer is about to complete its transaction during checkout,, it would be suggested to add a method that would actually allow OC developers / extension developers to test the length by adding a length method into the Encryption class in order to generate a more human error message to customers as it would also ease troubleshooting to forum supporters.

**Comment by danielkerr** [comment]
switched to openssl

**Comment by ADDCreative** [comment]
@danielkerr the problem is with openssl_encrypt. You are currently using aes-128-cbc with requires an IV as the fourth parameter.
https://github.com/opencart/opencart/blob/7d156508fd2cf6b1d12313db5c7b8e8c4291cbc3/upload/system/library/encryption.php#L23

See example 2 at. https://www.php.net/manual/en/function.openssl-encrypt.php#example-1001

As PHP 7.1 is a minimum it may be better to switch from aes-128-cbc to something better anyway.
