### ISSUE TITLE
[v3.1.0.0alpha] - Modification system no longer works

### ISSUE THREAD

**Issue by nmpetkov** [opencart/opencart#6668]
Modification system no longer works because of changes in /system/library/template/twig.php after this commit:
https://github.com/opencart/opencart/commit/6e30f9bd034fb721af94ee2f6e9d50d4f00dd94c#diff-5680586052269661abae93becdab4794

After pressing refresh button (even without any modifications installed), in log we see:
```
FILE: system/library/template/twig.php
CODE: $loader = new \Twig_Loader_Filesystem(DIR_TEMPLATE);
NOT FOUND - OPERATIONS ABORTED!
```

**Comment by melihtas** [comment]
Actually, modification system works normally. It creates modified files including twig files. However, since the changes in system/library/template/twig.php, modified twig files are ignored and original twig files are loaded. 

I don't understand why opencart needs a modification.xml to modify its own system file.

**Comment by danielkerr** [comment]
its working. altered the system to read the modified file if there is one.
