### ISSUE TITLE
[v3.0.2.0] Special price not showing for $0

### ISSUE THREAD

**Issue by Skulldancer** [opencart/opencart#6743]
If a product's price is set to $0 in the specials tab, it does not show the special price on the front-end product or checkout, even though it charges the correct amount. Tried setting the price to 0.0001 however the free checkout option no longer appears.

**Comment by andrei-bogdan** [comment]
Throughout the project, this is the condition that hides this specific special price:
`if ((float)$result['special']) {`
by setting
`price = false;`
if condition is not met.

If the price is 0, then it will not pass the condition, since it needs a number higher than zero.
I can modify all the Special price sections to pass for 0 price value, but further approval I think is needed, @jamesallsup ?

**Comment by prabhatkumaroc082** [comment]
fix #8985
