### ISSUE TITLE
SEO replace 'checkout/cart' and 'checkout/checkout'

### ISSUE THREAD

**Issue by danijelGombac** [opencart/opencart#6769]
> SEO URL's can now replace any normal URL query and not just pre defind ones link product, category, manufacturer pages.

If you replace route 'checkout/cart' and 'checkout/checkout', then this lines doesn't work anymore:

https://github.com/opencart/opencart/blob/d572831caca12926b32652a4f354cd196a5b719d/upload/catalog/view/javascript/common.js#L198-L202

https://github.com/opencart/opencart/blob/d572831caca12926b32652a4f354cd196a5b719d/upload/catalog/view/javascript/common.js#L222-L226

**Comment by jamesallsup** [comment]
@danijelGombac Which versions did you find this from?

**Comment by danijelGombac** [comment]
Version 3.1.0.0_a1

In admin design/seo_url add new seo

Query: route=checkout/cart
Keyword: cart
Push: route=checkout/cart

The result in catalog http://localhost/oc_3/en-gb/cart instead http://localhost/oc_3/en-gb?route=checkout/cart

But in common.js the system check for

`if (getURLVar('route') == 'checkout/cart' || getURLVar('route') == 'checkout/checkout') { `

**Comment by danielkerr** [comment]
not important. there is no need to add seo urls to checkout. search engines do not read the checkout page.

**Comment by vivek-webkul** [comment]
For the search page there should be language_code:
"var url = $('base').attr('href') + 'index.php?route=product/search';" 

#6907

**Comment by mdbatruch** [comment]
Version 3.0.2.0

You could add it through the Source by adding a couple of more else-ifs in the foreach loop after line 87 in catalog/controller/startup/seo_url.php:

 **elseif ($data['route'] == 'checkout/cart') {				
	$url .= '/Cart';
		unset($data[$key]);

} elseif ($data['route'] == 'checkout/checkout') {				
        $url .= '/Checkout';
	unset($data[$key]);

}**

The only issue is that in order to edit this you'll need to go into the Source files and won't have the option to do this from the SEO URL Admin Page.
