### ISSUE TITLE
[3100_a1] checkout/cart Coupon added and deleted – cart still shows Coupon, checkout not

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#6773]
Applied a Coupon – all fine with the Totals.

<img width="1140" alt="bildschirmfoto 2018-07-28 um 14 17 21" src="https://user-images.githubusercontent.com/837404/43356469-730cc5a4-9271-11e8-952e-2687c85342ea.png">

Then i deleted the value, applied that, got error message, Totals still have Coupon added:

<img width="1140" alt="bildschirmfoto 2018-07-28 um 14 17 41" src="https://user-images.githubusercontent.com/837404/43356492-c1453738-9271-11e8-91f3-7d6891d77cec.png">

Now click on checkout or other link, Coupon goes away, mini cart increase immediately.

My comment to this:

I see here at least a bug, that the value isnt consistent between cart and checkout.
Generally it would be nice to delete an applied coupon -> sometimes customer have not just 1 and he cant calculate ;-).
That needs some langfile adjustments to explain it to the customer.

**Comment by Urs-Bruelhart** [comment]
Same test with cart Gift Certificate gives error message for the empty field, but holds the applied voucher into the checkout.

**Comment by straightlight** [comment]
See this new solution with the coupon: https://forum.opencart.com/viewtopic.php?f=201&t=206010

**Comment by straightlight** [comment]
It may be possible that the similar steps may need to be applied to other total files. However, I fail to see how a voucher code could be removed after adding it, as compared to the coupons in this case, since this feature does not reflect the same aspect as the use of the coupons. For instance, when going at the store and providing a certificate code, it would be normally non-reversible while some coupon systems may be able to revert the transactions.

Since this particular feature is more based on Marketing strategies, I will leave the decision to the OC team at this point.

**Comment by Urs-Bruelhart** [comment]
@straightflight

Patch is Okay.

**Comment by straightlight** [comment]
Outstanding. Thanks for the update.

**Comment by Urs-Bruelhart** [comment]
Thank you for the instant fix ;-).
