### ISSUE TITLE
[3100_a1] Affiliate closing an Account

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#6779]
Customer/Affiliate nor Admins cant close an Affi-Account.

**Comment by danielkerr** [comment]
just tested and it works fine. there was an issue to create an affiliate account if you had custom fields but just tested and fixed.

deleting affiliate account works fine.

**Comment by vivek-webkul** [comment]
There are some issues on customer affiliate:
#6917

[Fixed 1: The customer field is required, but there is no check for customer_id.]
[Fixed 2: Customer can't make changes in their affiliate details on edit action, showing:
Warning: Customer is already registered as an affiliate! .]
[Fixed 3: All tab's content is showing in the general tab, due to extra </div> tag in affiliate_form.twig.]

**Comment by danielkerr** [comment]
ok all fixed.

**Comment by vivek-webkul** [comment]
@danielkerr - Have you checked for the customer_id validation? Because Customer is a required fields and there is no check for the customer_id in validateForm() .

Please check:
https://github.com/opencart/opencart/pull/6917/conflicts
