### ISSUE TITLE
[3100_a1] Admin route=customer/customer/edit Transactions -> Adding empty values

### ISSUE THREAD

**Issue by Urs-Bruelhart** [opencart/opencart#6782]
<img width="1210" alt="bildschirmfoto 2018-07-29 um 13 32 01" src="https://user-images.githubusercontent.com/837404/43365873-ce808886-9333-11e8-81e7-a7c80d71e585.png">

With succes message.

**Comment by straightlight** [comment]
I fail to see where an amount of 0.00 would be a bug in this case since OC does allow the use of Free Checkout when activated so that the customer's transaction amount would still be 0.00 …

As for the description field, it would be agreeable to state that each applied transactions should involve a reason as much as the order comments already has. To rectify this issue, in your admin/controller/customer/customer.php file,

find:

`if (!$this->user->hasPermission('modify', 'customer/customer')) {
			$json['error'] = $this->language->get('error_permission');`

add below:

`} elseif (empty($this->request->post['description'])) {
			$json['error'] = $this->language->get('error_description');`

Then, in your admin/language/en-gb/customer/customer.php file, add at the bottom of the file:

`$_['error_description']		= 'Please fill in the description before creating a new transaction!';

Then, not to forget to apply these steps: https://forum.opencart.com/viewtopic.php?f=176&p=730051&sid=6cf83ed4a56b4127d30346d895883840#p718325 

This should resolved the issue.

**Comment by danielkerr** [comment]
not 100% required. just dont hit the transaction button by mistake.
