### ISSUE TITLE
Twig inheritance for layout

### ISSUE THREAD

**Issue by vaiil** [opencart/opencart#6839]
Opencart doesn't use twig inheritance ('extends' directive). Why?
It prevents duplicate code in templates (breadcrumbs, columns, calculation of main block class, header and footer).
In addition, now some elements (e.g. html and body) are opened in header.twig and are closed in footer.twig. They could be joined in one file by using twig inheritance (e.g. layout.twig).

P.S. I've not used Twig, but I've used inheritance in other template engines, maybe I am wrong, but inheritance seems a good solution.

**Comment by danielkerr** [comment]
the controllers are used to load the components of the page not the template layer!

**Comment by vaiil** [comment]
Ok, but current structure makes troubles when I want to change something, for example left column size or when I want to delete last link from breadcrumbs (to avoid cycle links). It makes opencart inflexible and hard to support.

**Comment by panreach** [comment]
I've had a lot of experience with twig inheritance/partials.  After I'm finished with #6833 I could propose something that makes since.  I think a good (first) test case would be to test out the datetimepickers that I'm working on in #6833.  If we had a partials directory?  ie. `/upload/catalog/theme/default/partials/` and `/upload/admin/view/template/partials/`.  Then we could create a `datetimepicker.twig` file that we can use Twig's include (https://twig.symfony.com/doc/2.x/tags/include.html) and pass in variables for use.  Passing in row and columns (or not) for instance.

**Comment by richardeth** [comment]
@danielkerr I dont understand what your answer had to do with what he says cause it you dont have to templates?

@vaiil ll I use extends in my custom code

Here is a controller in admin: 
```
<?php
class ControllerCommonTest extends Controller {
    
	public function index() {

		$this->document->setTitle('test');

		$data['breadcrumbs'] = array();

		$data['breadcrumbs'][] = array(
			'text' => $this->language->get('text_home'),
			'href' => $this->url->link('common/dashboard', 'user_token=' . $this->session->data['user_token'])
		);

		$data['breadcrumbs'][] = array(
			'text' => 'test',
			'href' => $this->url->link('common/test', 'user_token=' . $this->session->data['user_token'])
		);

		$data['user_token'] = $this->session->data['user_token'];

        $data['header'] = $this->load->controller('common/header');
		$data['column_left'] = $this->load->controller('common/column_left');
		$data['footer'] = $this->load->controller('common/footer');

		$this->response->setOutput($this->load->view('marri/test', $data));
	}
}
```
the an example layout.twig:

```
{{ header }}{{ column_left }}
<div id="content">
  <div class="page-header">
    <div class="container-fluid">
      <div class="float-right"><a href="{{ add }}" data-toggle="tooltip" title="{{ button_add }}" class="btn btn-primary"><i class="fas fa-plus"></i></a>
        <button type="button" data-toggle="tooltip" title="{{ button_delete }}" class="btn btn-danger" onclick="confirm('{{ text_confirm }}') ? $('#form-layout').submit() : false;"><i class="fas fa-trash-alt"></i></button>
      </div>
      <h1>{{ heading_title }}</h1>
      <ol class="breadcrumb">
        {% for breadcrumb in breadcrumbs %}
          <li class="breadcrumb-item"><a href="{{ breadcrumb.href }}">{{ breadcrumb.text }}</a></li>
        {% endfor %}
      </ol>
    </div>
  </div>
  <div class="container-fluid">
    {% if error_warning %}
      <div class="alert alert-danger alert-dismissible"><i class="fas fa-exclamation-circle"></i> {{ error_warning }}
        <button type="button" class="close" data-dismiss="alert">&times;</button>
      </div>
    {% endif %}
    {% if success %}
      <div class="alert alert-success alert-dismissible"><i class="fas fa-check-circle"></i> {{ success }}
        <button type="button" class="close" data-dismiss="alert">&times;</button>
      </div>
    {% endif %}
    <div class="card">
      <div class="card-header"><i class="fas fa-list"></i> {{ text_list }}</div>
      <div class="card-body">
          {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</div>
{{ footer }}
```

and since the admin controller calls the route marri/test it should call the template marri/test.twig and this is it:

```
{% extends "marri/layout.twig" %}

{% block content %}
    <p class="important">
        Welcome on my awesome homepage. Content block.
    </p>
{% endblock %}
```

And that's it. 

@panreach you absolutely right :)
