### ISSUE TITLE
OC 3.0.2 - Email send to client on failed payment

### ISSUE THREAD

**Issue by soulraven** [opencart/opencart#6947]
hi,
please help me to understand way the confirmation email is sent to customer even if the payment gateway refuse the payment and return the status is 10.

**Comment by jgan96** [comment]
What payment gateway?

**Comment by soulraven** [comment]
is a payment portal that i have try to migrate from OC 2. From LibraBank Romania.

**Comment by soulraven** [comment]
any reason that the issues is closed?

**Comment by florinsith** [comment]
Because its an issue with the payment extension, not opencart. However, I would not say this is an issue at all, some payment methods activate the order before the payment is done so the admin doesnt miss the order in case the ipn fails. If you set the initial status to 'Awating Payment' then you have a pretty normal situation.

**Comment by soulraven** [comment]
ok, thx. i understand. the status is the reason
