### ISSUE TITLE
MyISAM - and not InnoDB > why?

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#7060]
While we are writing soon 2019, OC is using still MyISAM as engine.
Only oc_cart use InnoDB, what not all tables?
That has been already highlighted several times since 2016 but nothing has been changed - still the latest (beta) release is using this outdated engine.

**Comment by danielkerr** [comment]
because its about using the correct engine for the correct type of data. innoDB is not required nor should it be used for tables such as country as its not rarely updated and does not require to be stored in ram.

**Comment by MrPlow254** [comment]
I'm agreeing with danialkerr. This is just a comment for other users that come across this. Below explains why oc_cart is InnoDB, yet the majority of the tables use MyISAM.

Unless you’re creating a very simple, read only for the most part, or an experimental database, MyISAM almost certainly is the wrong choice. MyISAM doesn’t support foreign key constraints or transactions, which are essential for data integrity. In addition, the whole table is locked whenever a record is inserted or updated; this causes a detrimental effect on performance as usage grows.

A READ lock is implicitly acquired before, and released after execution of a SELECT statement. Notice that several concurrent, simultaneous, SELECT statements could be running at the same time, because several sessions may hold a READ lock on the same table.

Conversely, a WRITE lock is implicitly acquired before executing an INSERT or UPDATE or DELETE statement. This means that no read (let alone a concurrent write) can take place as long as a write is in progress*.

* However, these locks are not always required thanks to this clever trick:

The MyISAM storage engine supports concurrent inserts to reduce contention between readers and writers for a given table: If a MyISAM table has no free blocks in the middle of the data file, rows are always inserted at the end of the data file. In this case, you can freely mix concurrent INSERT and SELECT statements for a MyISAM table without locks.

[Internal Locking methods](https://dev.mysql.com/doc/refman/5.6/en/internal-locking.html)
[READ vs WRITE lock](https://dev.mysql.com/doc/refman/5.6/en/lock-tables.html)

**Comment by tjapro** [comment]
Question answered in 2021 !!!

**Comment by zx1986** [comment]
Question answered for 2022 OC user !!!
