### ISSUE TITLE
Cant login to admin 

### ISSUE THREAD

**Issue by mrhili** [opencart/opencart#7073]
V3

Hi iam in infinity free server and when i am trying to login i can not be redirected

there the link they be written when i enter the correct login and pass:

http://www.elmahal.epizy.com/admin/index.php?route=common/dashboard&user_token=zaS3aB6KZGtmZD37TXu3hxTewDDif2ZX

**Comment by underr-ua** [comment]
https://forum.opencart.com/viewtopic.php?p=739529#p739529

**Comment by ftrentini** [comment]
Same thing here happens when I change timezone. Then when I change back to UTC directly on mysql, I'm able to login as admin again.

**Comment by straightlight** [comment]
Sessions have been re-worked on the master branch recently. This was also a on-going reported issue with v3.0.3.2. Since the fix on the master branch, incident requests seem to have stopped regarding authentication issues.

Since our main focus is on the OC v3.0.3.2 and the master branch. this commit will now be closed.
