### ISSUE TITLE
[OpenCart 3.x] Input type=radio elements do not change the "checked" attribute

### ISSUE THREAD

**Issue by simo-vt** [opencart/opencart#7079]
**OpenCart Version**
3.0.2.0, 3.1.0.0_b

**Bug Description**
It seems like switching between Yes / No does not affect the hidden radio buttons' "checked" attribute.

**To Reproduce**

First open up the Developer Tools to inspect the markup changes.

1. Go to 'Admin > System > Settings > Edit > Option > tab Products'
2. Change the value of 'Category Product Count'
3. Notice that the input "checked" attribute does not switch between the enabled / disabled input radio buttons.

**Expected behavior**
Clicking on any of the Yes / No options is expected to change the "checked" attribute of the input fields.

**Screen recording**
https://drive.google.com/file/d/1OYk1xXOi5BoaQZFxeML6lT56HsSTSEDJ/view

**Server / Test environment:**
 - Deployed to a web server
 - Linux version 2.6.32-896.16.1.lve1.4.51.el6.x86_64
 - PHP 7.2
 - Browser(s) tested with: Google Chrome
 - Version: 69.0.3497.92 (Official Build) (64-bit)

**Comment by stalker780** [comment]
You will be surprised, but radios in OC 3.0.2.0 behave the same.

**Comment by MrPlow254** [comment]
Have you checked what a console log javascript output says? Sometimes data like this isn't updated in the browser; mainly happens with jquery data associated with an element.

**Comment by simo-vt** [comment]
@stalker780 Yes, you are right. I will update the description of the issue.

@MrPlow254 I checked and I see no output.

**Comment by MrPlow254** [comment]
@simo-vt You have to put the console log JavaScript code into the view yourself; there isn't one in the console log by default.

The fact that the correct radio value is saved to the database proves that it is changing just not in the browser. It isn't Opencart causing the issue. The checked="checked" is correct HTML5 code. It is only the browser not updating this code, since it is predefined code.

For future reference with other variables like I mentioned (jquery data attributes) that don't change in the browser you change check it with console log outputs. For the one you describe you can check it by the following.
You will have to do an onclick function call on the two radio buttons and do a $().is( ":checked" ) if statement on the opposite radio you click. Example if you click value="1" radio it will output the console log of value="0" to test if it changes or not. It should always output false if you have the text in there to say false, since you are always clicking the output that is checked.

**Comment by simo-vt** [comment]
@MrPlow254 Thanks for the thorough elaboration. I see what you mean.

In this case, I believe it is safe to mark this issue as closed.
