### ISSUE TITLE
Product Variant Developer Input Required

### ISSUE THREAD

**Issue by danielkerr** [opencart/opencart#7096]
Guys I'm trying to add product variants to opencart and need some professionals input on creating these.

So far what I know about product variants are:

1. They are pre-defined options.
2. At checkout they minus the stock from the product and the variant.

After looking at other solutions I find the issue of defining options does not take into account other differences such as weight, sizes, different images, different specials, etc.. 

I can fix all these issues by setting a variant_id in the product table. One variant product can have a master product that manually copies the product data to its self. At the end of checkouts it will minus stock from both products.

Need some suggestion what the ultimate or best product variant system.

**Comment by florinsith** [comment]
Do you mean that the variants will be stored in the product table as well?

That does seem like a good ideea  and I like that it would give you a lot of customization options for variants. It might introduce some confusion having them stored this way.

Another way I think might work is having the variants in a separate table with only relevant columns that could change, the things you mentioned. 
In admin, you would have a new tab for variants and variants would be based on product options. They would not be automatic, you could create variants only for the option combos you want because maybe not all options are relevant to inventory keeping. 
This I think would imply removing quantity, weight and price on options as they are now and only have that on variants. In frontend, the variant could be displayed based on option selection. Option combos that do not resolve to a variant would just be the default product.

Its similar to how shopify handles them but it gives you more flexibility by allowing you to have options without variants as well.

**Comment by danielkerr** [comment]
> Do you mean that the variants will be stored in the product table as well?

yes

> Another way I think might work is having the variants in a separate table with only relevant columns that could change, the things you mentioned.
> In admin, you would have a new tab for variants and variants would be based on product options. They would not be automatic, you could create variants only for the option combos you want because maybe not all options are relevant to inventory keeping.
> This I think would imply removing quantity, weight and price on options as they are now and only have that on variants. In frontend, the variant could be displayed based on option selection. Option combos that do not resolve to a variant would just be the default product.

I don't want to end up replicating tables and the whole admin product page.

Not sure yet how to handle the options. maybe if i added a system to allow hidden fields and customized option value set by the admin.

**Comment by florinsith** [comment]
I see what you mean, I think maybe you could just leave the options as they are but only for the main product and keep them separate from variants, variants would just display on the product page similar to related products (only that they would be near the add to cart).

**Comment by danielkerr** [comment]
@florinsith 

You might be right. we have product options. then you setup the a pre defined product option (the variant) then select the variants from the product page.

**Comment by danijelGombac** [comment]
@danielkerr 

I think the variants should be based on attributes, not options.

Product variations are the attribute used during checkout to identify specific products.

Product options, on the other hand, are individual products that can be altered in some manner upon customer’s request.

**Comment by danielkerr** [comment]
They are pre-defined options. Only one store i can find using your method. all the others is done at the option level. this is also where the stock is.

**Comment by davidfranks** [comment]
@danielkerr This is by far the best options/variants extension - https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31605 

This one is also pretty good - https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=14468

**Comment by danielkerr** [comment]
@davidfranks those extensions are for options not variants.

**Comment by straightlight** [comment]
The variant_id could be indexed the same way the category_id and the parent_id are already working together on the categories table. This methodology also avoids on duplicating database tables and data redundancies.

**Comment by danielkerr** [comment]
ok finished it
