### ISSUE TITLE
Paypal Express issue - confirm order button - Opencart Version 3.0.3.1

### ISSUE THREAD

**Issue by Amir-SSDC** [opencart/opencart#7154]
Opencart Version 3.0.3.1

problem with paypal express on checkout page, the confirm order button is not active to click, i had it working perfectly on opencart Version 3.0.2.0

**To Reproduce**
1. add any product to cart
2. go to checkout
3. select paypal express and fill information
4. confirm order button is not working ( not active to click)

https://www.useloom.com/share/41bbbcf9c79c4951b5a951379addc39a

**Server / Test environment (please complete the following information):**
 - Deployed to a web server
 - Operating system Centos 7
 - PHP version 7.2
 - Apache version - Apache/2.4.37 (cPanel) OpenSSL/1.0.2q mod_bwlimited/1.4
 - Browser tested - chrome

**Comment by jamesallsup** [comment]
You are using a 1 page checkout which is not loading the new smart button solution PayPal is now providing for Express Checkout

`Uncaught ReferenceError: paypal is not defined
    at eval (eval at globalEval (jquery-2.1.1.min.js:2), <anonymous>:2:7)
    at eval (eval at globalEval (jquery-2.1.1.min.js:2), <anonymous>:41:7)
    at eval (<anonymous>)
    at Function.globalEval (jquery-2.1.1.min.js:2)
    at n.fn.init.domManip (jquery-2.1.1.min.js:3)
    at n.fn.init.append (jquery-2.1.1.min.js:3)
    at n.fn.init.<anonymous> (jquery-2.1.1.min.js:3)
    at n.access (jquery-2.1.1.min.js:2)
    at n.fn.init.html (jquery-2.1.1.min.js:3)
    at Object.success (checkout.js:2)`

The code is handled in the PayPal Express template to setup the in-context flow rather than redirect off-site. There is also an event which should be triggered when the checkout (not basket) flow is started to ensure the JS is loaded well before the ajax request is initiated.

As you are using a 3rd party module for 1 page checkout and also it looks like Journal theme - you will need to modify these to work with the new solution.

**Comment by Amir-SSDC** [comment]
but i have been using the same with opencart Version 3.0.2.0 and it was working fine, the problem starts only when i upgraded to 3.0.3.1
so why is that happened?

**Comment by jamesallsup** [comment]
> the new smart button solution PayPal is now providing for Express Checkout

PayPal EC has been updated - https://developer.paypal.com/docs/checkout/

Dynamic payment options based on merchant / buyer locations

**Comment by Amir-SSDC** [comment]
thank you very much for explaining. :)

**Comment by soydemadrid** [comment]
Hi I have this problem too. I use Simplica theme but the theme Author says this isn't a theme issue.

Does anyone know the correct edits to make to get it fixed and working again please?
