### ISSUE TITLE
Parameter must be an array or an object that implements Countable in Module.php on line 346

### ISSUE THREAD

**Issue by seopower** [opencart/opencart#7173]
I am getting this error in error.log continuously:
 
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /system/library/template/Twig/Node/Module.php on line 346

Server Info:
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )

Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies with Zend OPcache v7.2.10-0ubuntu0.18.04.1

**Comment by danielkerr** [comment]
page?

**Comment by seopower** [comment]
Its on all pages if Display Errors is set to Yes and  in error log if Display Error is set to No.

**Comment by straightlight** [comment]
This may be caused by a failed upgrade process or corrupted images during uploads. Not an issue with OC specifically. However, if you're using an extension that is part of custom theme, see this solution: https://forum.opencart.com/viewtopic.php?t=211540#p754154 . The filename location is located right above the specified post of the addressed topic.

This commit will now be closed.
