### ISSUE TITLE
a non numeric value encountered category pagination 7.1

### ISSUE THREAD

**Issue by ravilrrr** [opencart/opencart#7218]
a non numeric value encountered in category.php if page=

`$page = $this->request->get['page'];`

replace

`$page = (int)$this->request->get['page'];`

**Comment by ravilrrr** [comment]
and manufacturer and etc

**Comment by straightlight** [comment]
One point I may need to address here is that the $page variables being passed into the common/pagination.php file are not an issue but only when it's not being passed into that controller becomes an issue since the $page variable is not sanitized and may need to be …

As for the manufacturer, I am not quite sure what you are referring to specifically.

**Comment by ravilrrr** [comment]
see
`'start'                  => ($page - 1) * $limit,`
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/product/category.php#L158
https://github.com/opencart/opencart/blob/master/upload/catalog/controller/product/manufacturer.php#L148

if page as string (&page={user deleted it himself}) you see Warning 
a non numeric value encountered

**Comment by ravilrrr** [comment]
http://php.net/manual/en/migration71.other-changes.php

**Comment by straightlight** [comment]
I see what you mean. However, setting a straight (int) at the front of the requested page number could lead to 0 while the default page value is 1.

Perhaps, this should help:

`if (isset($this->request->get['page']) && is_numeric($this->request->page['page'])) {
			$page = (int)$this->request->get['page'];
		} else {
			$page = 1;
		}`

**Comment by ravilrrr** [comment]
You are right.

**Comment by IP-CAM** [comment]
works also in v.1.5.6.4+5 Versions, as shown by straightlight

**Comment by schiggi** [comment]
Yes, this problem also exists at least on OC 2.3, probably on lower versions as well.

**Comment by straightlight** [comment]
Your code above suggests to check for an empty integer but as well for other variable types which the page query only requires an integer compared to my above code where it checks if the page key is set and that the converted page key to an integer has a page number higher than 0; otherwise - the page default value is 1.

**Comment by schiggi** [comment]
Fair enough. Negative values would be a problem in my suggestion.

**Comment by danielkerr** [comment]
solved it by 

		if (isset($this->request->get['page'])) {
			$page = (int)$this->request->get['page'];
		} else {
			$page = 1;
		}

**Comment by straightlight** [comment]
By using the code above, the 0 (zero) value won't be discarded as the default page=1 won't appear on the browser since page 0 is invalid. A book contains at least 1 page. A book can't be considered a book if there are no pages to show inside it.

**Comment by straightlight** [comment]
The only downside of using my suggestion is that it would involve page redirection. I believe why the simple isset validation without sanitizing the value in the IF condition has not been set is to avoid page redirection on a page product where search engines already tracks its media.

In this case, rather than regrouping the products per page by the browser with forced redirection whenever an invalid page number is involved; than to address the error/not_found page instead. This would also provide an understanding to the bots that these pages would indeed be invalid without forcing redirection.

**Comment by straightlight** [comment]
In the catalog/controller/common/pagination.php file, it would seem my suggestion already exists:

`if (isset($setting['page']) && $setting['page'] > 0) {`

It could simply, however, be replaced with:

`if (isset($setting['page']) && (int)$setting['page'] > 0) {`

This would solved all the problems with the Github version.

**Comment by straightlight** [comment]
I have provided a better and definite solution on the OC forum: https://forum.opencart.com/viewtopic.php?f=24&t=210459#p748892 . This solution also converts all page=0 queries back to 1 despite of the URL length.

**Comment by kg0925** [comment]
> I have provided a better and definite solution on the OC forum: https://forum.opencart.com/viewtopic.php?f=24&t=210459#p748892 . This solution also converts all page=0 queries back to 1 despite of the URL length.
> 
> Resolution confirmation: https://forum.opencart.com/viewtopic.php?f=24&t=210459&p=748912#p748907

i have tried above solution but i am still getting a non numeric value error on pagination, manufacturer, category and on search.php

**Comment by straightlight** [comment]
> I have provided a better and definite solution on the OC forum: https://forum.opencart.com/viewtopic.php?f=24&t=210459#p748892 . This solution also converts all page=0 queries back to 1 despite of the URL length.
> Resolution confirmation: https://forum.opencart.com/viewtopic.php?f=24&t=210459&p=748912#p748907
> 
> i have tried above solution but i am still getting a non numeric value error on pagination, manufacturer, category and on search.php

Daniel's solution would be the right course of action in this case: https://github.com/opencart/opencart/issues/7218#issuecomment-469652397 . All controller files involving this validation must include this change throughout the entire platform.
