### ISSUE TITLE
system/library/url.php ssl error

### ISSUE THREAD

**Issue by durrasell** [opencart/opencart#7256]
public function link($route, $args = '') no ssl option so catalog is always http only

**Comment by jktoole** [comment]
In 3.0.3.1, it looks like this:

    public function link($route, $args = '', $secure = false) { 

..which is immediately followed by a check of $secure to decide between using 'ssl' and 'url'.

I think this was removed in master (https://github.com/opencart/opencart/blob/master/upload/system/library/url.php#L49) with the aim of it *always* being ssl rather than never ssl. E.g. further up in the same file, "$this->ssl = $ssl;" has been removed because $url is always expected to start with 'https'.

Have you tested an installation of master and found that it's using http rather than https?

**Comment by danielkerr** [comment]
it was removed because the web has changed from having only form data being ssl to ssl for every page. happened about 2 years ago. google will drop your ranking if all pages are not ssl.

**Comment by durrasell** [comment]
i tried to make https only, but in my pack it was only http version. due to this i could not make links with https. Part of crm was with https and part only http. i added $secure = true as one of params to enable https version of links

**Comment by danielkerr** [comment]
edit the config.php so both are ssl

**Comment by durrasell** [comment]
i understand that i can solve it by several different ways. I just point to legacy code, which needs refactoring
