### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by julian70400** [opencart/opencart#7296]
Opencart 3.0.2.0

My total cart is not correct, 0,1€ is missing in a particular case ! Only with 5,5% taxe and 5€ price with a defined quantity, not more, not less.
I saw this because sometimes PayPal do a same calcul but had a different price regarding Opencart one.. I tryed to reproduce the problem with a simple exemple : 

If a add 130 items with 5.5% of taxe with a price of 5€ ==> everything is fine (total price is 645.00€ )
If a add 129 items with 5.5% of taxe with a price of 5€ ==> 0.1cents is missing on final price (total price is 649,99€, WRONG, it should be 650.00€)
If a add 129 (and more) items with 20% of taxe with a price of 5€ ==> everything is fine
If a add 129 items (and more) with 5.5% of taxe with a price of 6€ (and more or less) ==> everything is fine

Got a video of another exemple, please, have a careful look to the both exemples with sub total + taxes : https://pasteboard.co/I7ueDrj.gif

PHP 5.6
Nginx 1.4.6

THanks for your help

**Comment by zemguru** [comment]
This has been an issue for ages and always have been marked as "won't fix". There are other frameworks developed with latest changes with "correct" calculation You could check. 

The correct fix requires full cart rewrite :(

https://forum.opencart.com/viewtopic.php?f=202&t=192112
https://github.com/opencart/opencart/issues/5657

https://github.com/copona/copona/commit/19591f3de7c59fd11ecb8ce3c748c29a37d6454b
https://github.com/copona/copona/issues/196
https://github.com/copona/copona/commit/5e2745db1e27344098da9e0cc57d4fff677d59ef

These are 5 main files, requiring change.s 
I personally like an approach, when you have much as you can in one - `system/library/cart/cart.php` and get all needed data afterwards with methods. Instead of using "calculating totals" in every controller.

`$this->cart->getTotals()` also must be used in other controllers, not only in these 5 files.

This is raw solution from another engine, but it WORKS (you will need to adapt for Opencart3, of course! But give it a try! :)

```
catalog/controller/checkout/cart.php
catalog/controller/checkout/checkout.php
system/library/cart/cart.php
system/library/cart/currency.php
system/library/cart/tax.php
```

**Comment by danielkerr** [comment]
its hard to fix when you are dealing with multiple currencies and 8 decimal places.
