### ISSUE TITLE
[v3.0.3.2 - and Github files] - OC database - UK zone names

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7328]
While I am not from around the UK section, there seem, however, to miss the following zone names on the opencart.sql file:

`North Humberside`
`Perthshire`
`Isles of Scilly`

**Comment by ADDCreative** [comment]
They are there, just under different names.
North Humberside = East Riding of Yorkshire
Perthshire = Perth and Kinross

Isles of Scilly is not a postal county, but actually a post town so does not need a county in the address or could be part of Cornwall. However there are some, but not all, post towns in the zone list. So might be worth adding, although the address will just up looking like "Address 1, Address 2, Isles of Scilly, Isles of Scilly, United Kingdom".

I have looked into correcting the UK zones, but it's a bit of a nightmare. Counties haven't required for addresses since 1996, so Royal Mail don't include if in the address list and it's had to find two lists the same.

Other countries will have the same issue of the zone name not making sence in an address. It would be nice if the zone could be configured for each country from one of the following. 1. Required from list (as it is now) 2. Optional text input 3. Not required. But that would require a lot of changes.

**Comment by straightlight** [comment]
For option 2, I used an alternate solution for PayPal Express Checkout extension payment as I provided the solution on a commit as well as on the Opencart forum. With the help of the new tab feature: 'Unrelated zones' , things seems to run more easily for users in order to maintain their SLAs - especially due to the size of the codes of that extension. This is exactly what it's doing now; to analyze zone codes per basis of every possible listed countries between the stores and their providers.

I am hoping to see that idea expanding for other extension payment modules (shipping extension modules as well?) in order to fully compare by zones instead of entire countries where specific zones can be restricted by providers.

**Comment by straightlight** [comment]
As for the different zone names that you've described above, that is good information. Indeed, this may definitely create transaction issues between providers where zone names could differ on one-and-another. Which is why, everything zones needs to be compared by codes rather than names with the exception of the insistence of providers to pass these parameters as zone names with their APIs.

**Comment by straightlight** [comment]
I really can't believe this one as been closed without closure notes. This commit is about a political issue persisting on OC where different payment providers may use various ways to validate regional settings.

**Comment by danielkerr** [comment]
.because its v3.0.3.2, if its required for the master branch then open a new issue.

**Comment by straightlight** [comment]
This is an on-going political issue for the regional settings validations despite the mount of extensions that will be used and the OC version excluding the payment service providers that handles address verification such as PayPal Express Checkout (and hopefully a few others). Otherwise, store owners will never be able to complete their transactions with a whole centralized country and zone tables due to the service providers differences. Localisation tables needs to be set per payment (and shipping?) providers.
