### ISSUE TITLE
[OC v3.0.3.2] - $frequencies array

### ISSUE THREAD

**Issue by straightlight** [opencart/opencart#7423]
All files that contains the $frequencies array inside the foreach statement:

- catalog/controller/checkout/cart.php
- catalog/controller/checkout/confirm.php
- catalog/controller/extension/payment/pp_express.php

They should be moved before the first foreach statement of that area when using the array:

$frequencies = array(
					'day'        => $this->language->get('text_day'),
					'week'       => $this->language->get('text_week'),
					'semi_month' => $this->language->get('text_semi_month'),
					'month'      => $this->language->get('text_month'),
					'year'       => $this->language->get('text_year'),
				);

**Comment by webkul-dilip** [comment]
catalog/controller/checkout/cart.php-- version-3.0.3.6
I agree with you but it also depends upon the condition if we move the $frequencies above the foreach loop in this case if the cart does not have the recurring product then $frequencies will be useless because $frequencies only use when the product will recurring.
