### ISSUE TITLE
unable to search 3.0.3.1.

### ISSUE THREAD

**Issue by katerina233** [opencart/opencart#7468]
**What version of OpenCart are you reporting this for?**
3.0.3.1
website: http://q-sissi.com/

**Describe the bug**
I am not too sure whether it is a bug or not, but since my installation of opencart 3.0.3.1, whenever I search any products or categories in the search bar it always jumps to the search page with no results, I did move position of the search but however it was not working from the beginning.

**To Reproduce**
go to frontpage, header-floating menu, search for either earrring or 1234, it will jump to search page with no search result

**Expected behavior**
Able to search all categories and all products...

Many thanks to all helpers and viewers.

**Comment by straightlight** [comment]
OP reports an issue with URL about a custom theme for an older OC version. Github is to report persistent issues occurring or to post about issues with the master branch. Please post on the forum for prior OC versions than v3.0.3.2 or if you are not sure if the reported issue is about a persistent one.

**Comment by katerina233** [comment]
> OP reports an issue with URL about a custom theme for an older OC version. Github is to report persistent issues occurring or to post about issues with the master branch. Please post on the forum for prior OC versions than v3.0.3.2 or if you are not sure if the reported issue is about a persistent one.

I am sorry but I don't think I understood you, I am talking about v3.0.3.1, which in your quote, is prior OC version than v3.0.3.2, and as for the whole persistent issue, well, the problem was there since I installed it, not before I customized it, so your reply is really confusing to me, you mean I should contact opencart? I don't really understand

**Comment by straightlight** [comment]
`as for the whole persistent issue, well, the problem was there since I installed it,`

It has nothing to do with confusion. You are indicating that the problem was there since you installed it based on a prior version of OC that may have been fixed already on the master branch. This namespace is for development, not for past issues. Unless you are able to reproduce the issue on, either, OC v3.0.3.2 or from the master branch or an on-going issue 'since prior releases' that can be reproduced on the master branch, please post on the OC forum for prior releases.

**Comment by katerina233** [comment]
> `as for the whole persistent issue, well, the problem was there since I installed it,`
> 
> It has nothing to do with confusion. You are indicating that the problem was there since you installed it based on a prior version of OC that may have been fixed already on the master branch. This namespace is for development, not for past issues. Unless you are able to reproduce the issue on, either, OC v3.0.3.2 or from the master branch or an on-going issue 'since prior releases' that can be reproduced on the master branch, please post on the OC forum for prior releases.

What I mean is that you are confusing me, I am literally reading your words word by word trying to understand what you mean, and by the way, I am still very new to this forum and opencart, so please be patient as I can read that you are getting really aggressive.

So what I am thinking you meant was that it was posted in the forum in the past, if that's so, I posted this post because I did not find the resolution, and if you are saying that the new version is already fixed, well, its not, I downloaded the fresh version from opencart, overwritten the javascript file, it is not working. If you are suggesting this is the wrong forum group that I am posting, please direct me to the other group so I can resolve this problem as soon as I can.

Thanks

**Comment by straightlight** [comment]
`I posted this post because I did not find the resolution`

Exactly. Which is why my previous posts indicates that the Github Opencart namespace is about people that do know Opencart. Since you did not find the resolution as I predicted, then you need to post your inquiry on the OC forum with the exception on noticing the same issue with the master branch where resolutions can be posted on this namespace.

`I downloaded the fresh version from opencart, overwritten the javascript file, it is not working.`

Not only it is indicating that it is 'not working' without providing the actual results, you also indicate that you have downloaded the fresh version from opencart while Github Opencart namespace, again, is about the master branch or the latest OC v3.0.3.2 release that can both be compared as an error during an event that may be reproduced. So far, you have not provided any indication of those claims. Which is why, if you are unsure what might be the source of the problem, please post on the OC forum since Github Opencart is for development, not for indicating that it's not working without detailed reasons.

In the mean time, if you're looking to resolved issues as soon as you can, another reason to use the Commercial Support section of the OC forum to get this done as a custom job or to contact the OC site support for OC partners to resolved the issues for you.

**Comment by agatha65** [comment]
@katerina233 This is not a bug.
Just replace in your common.js
var value = $('header #search input[name=\'search\']').val();
with
var value = $('#search input[name=\'search\']').val();
And use the forum for these custom issues.

**Comment by katerina233** [comment]
> @katerina233 This is not a bug.
> Just replace in your common.js
> var value = $('header #search input[name='search']').val();
> with
> var value = $('#search input[name='search']').val();
> And use the forum for these custom issues.

Hi there, thank you so so much for the resolution, it worked, but because it was not working before I even customize the page (freshly installed opencart) which was the reason why I thought it was a bug, but thank you very much again. Hope you have a good day! :） 👍
