### ISSUE TITLE
Information about OpenCart 3.1.0

### ISSUE THREAD

**Issue by By-oussef** [opencart/opencart#7469]
Hi, 
I want to know if the beta version 3.1.0 will be updated soon ?

Because I just consulted the historical Github and I noticed that it goes back to July 24, 2018 and since nothing more.
I like this version because it has features that are not supported by the stable version of OC.

Thank You for your answers.

**Comment by danielkerr** [comment]
it was updated last night!

**Comment by danielkerr** [comment]
admin	changed the multiple select system to use tables	yesterday

**Comment by danielkerr** [comment]
yes trying very hard. there is a lot of stuff i have to do in the background. i have 6 major preojects i have to manage. all opencart related. the last release i think was last month.

**Comment by danielkerr** [comment]
the next major release is close.

this is whats left

1. Fix statistic events
2. Add opencart account for admin marketplace (80%)
3. Add sql entry for current built in extensions so they can be uninstalled.
4. Finish product variants
5. fix design/seo_url

**Comment by falconkirtaran** [comment]
Glad to hear it's close!

It'd be real neat if you could throw the square fixes I put in https://github.com/opencart/opencart/pull/7315 in there too, since right now the builtin square plugin doesn't work at all.

Also https://github.com/opencart/opencart/pull/7331.  I'm using the updated dependencies in there in prod without issue, and it made a lot of PCI scanner kerfuffle go away.

Maybe https://github.com/opencart/opencart/pull/7166, https://github.com/opencart/opencart/pull/7329 and https://github.com/opencart/opencart/pull/7465 if you want a couple new features too.

**Comment by diegospm** [comment]
> the next major release is close.
> this is whats left
> 
> Fix statistic events
> Add opencart account for admin marketplace (80%)
> Add sql entry for current built in extensions so they can be uninstalled.
> Finish product variants
> fix design/seo_url

Hi @danielkerr 

I do not want to give the impression that my pull is more important or better than the other devs, because after all everyone wants to help. But the following pull can contribute a lot to future maintenance on the project: #7398 

If implemented it will reduce many lines of code and the breadcrumbs class follows the same logic of paging class.

As I mentioned in the pull, if my suggestion is accepted, I propose to edit the files pertaining to the modifications and send the pull request to the merge :)

**Comment by rsuchovsky** [comment]
Hello, is new release info for new version?

**Comment by rsuchovsky** [comment]
When can we expect a new version? 
I feel that development has stopped completely 2 months ago..
