### ISSUE TITLE
Download dependency

### ISSUE THREAD

**Issue by stasdrvn** [opencart/opencart#7511]
Opencart 3 

Delete download function doesn't remove row from product_to_download table.

admin/model/catalog/download.php

```
public function deleteDownload($download_id) {
		$this->db->query("DELETE FROM " . DB_PREFIX . "download WHERE download_id = '" . (int)$download_id . "'");
		$this->db->query("DELETE FROM " . DB_PREFIX . "download_description WHERE download_id = '" . (int)$download_id . "'");
	}
```
It should be like this:

```
public function deleteDownload($download_id) {
		$this->db->query("DELETE FROM " . DB_PREFIX . "download WHERE download_id = '" . (int)$download_id . "'");
		$this->db->query("DELETE FROM " . DB_PREFIX . "download_description WHERE download_id = '" . (int)$download_id . "'");
		$this->db->query("DELETE FROM " . DB_PREFIX . "product_to_download WHERE download_id = '" . (int)$download_id . "'");
	}
```

**Comment by straightlight** [comment]
admin/model/catalog/product.php file:

`$this->db->query("DELETE FROM " . DB_PREFIX . "product_to_download WHERE product_id = '" . (int)$product_id . "'");`

Either you delete by product or you delete by download, the results should be the same. Besides, when deleting a download_id, you are also affecting the products that comes with those downloads without necessarily knowing which products would be affected during removals.

**Comment by stasdrvn** [comment]
Why should I store these rows in the database if the download has been deleted?

**Comment by straightlight** [comment]
Nowhere to be said that you shouldn't but was has been addressed on the above is that by deleting the download_ids, you are also deleting the associated and downloadable products as you won't know which ones especially based on a mass list of downloads since no lists are being provided altogether other than lookup for the results that you need before deleting your associated products from the downloads based on your example.

**Comment by dmitriyzhuk** [comment]
I think there is a misunderstanding here.

The issue is that when deleting the DOWNLOAD, we still keep the associated download_id with the product_id. 

it is simply redundant and should be cleared. so adding this line of code 

```php
$this->db->query("DELETE FROM " . DB_PREFIX . "product_to_download WHERE download_id = '" . (int)$download_id . "'");
```
should fix this. it is not nessesery a bug, rather good practice.

**Comment by straightlight** [comment]
By deleting the product_to_download from the downloads, the related product IDs will also be deleted and users won't understand which products have been removed in the process since there are no detailed list providing their associations from the OC admin. Users must manually see those associated products from the admin - > catalog - > products page unless using an extension.

**Comment by stasdrvn** [comment]
Yeap, you are right. My fault.
Sorry for being persistent. 
Have a good day.
