### ISSUE TITLE
?page=1

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#7571]
/index.php?route=product/category&path=80&page=5

We get a list of pages, the first in list  /index.php?route=product/category&path=80&page=1

Because
if ($i === 1) {

Type $i is float
Because
for ($i = $start;

Where $start = $page - floor($num_links / 2);
but   floor - return float value (https://www.php.net/manual/ru/function.floor.php)

Therefore

if ($i == 1) {

OR

if ((int)$i === 1) {

**Comment by diegospm** [comment]
What version are you reporting to?

**Comment by chulcha** [comment]
>= 2.3

**Comment by mesili** [comment]
Still present in the master branch : 
https://github.com/opencart/opencart/blob/ccce1d98bd632d9943a94ddb3d6c54fef6939f85/upload/system/library/pagination.php#L80
https://github.com/opencart/opencart/blob/ccce1d98bd632d9943a94ddb3d6c54fef6939f85/upload/admin/controller/common/pagination.php#L67
https://github.com/opencart/opencart/blob/ccce1d98bd632d9943a94ddb3d6c54fef6939f85/upload/catalog/controller/common/pagination.php#L67

Quick test to see how this issue is relevant : 
```
php > $a = floor(4/3); for($i = (int)$a; $i<3;$i++) { print "\n". gettype($i) . "$i === 1 ? " . ($i === 1 ? 
'true' : 'false') ; }

 integer1 === 1 ? true
 integer2 === 1 ? false

php > $a = floor(4/3); for($i = $a; $i<3;$i++) { print "\n". gettype($i) . "$i === 1 ? " . ($i === 1 ? 'true' : 'false') ; }

 double1 === 1 ? false
 double2 === 1 ? false

```

And the more I dig into opencart, the more I wonder where is the need to have 3 versions of the same code here and there ? 

It would be a good fix to take the controller code, apply the `(int)`, then put it in the system/library and then importing the library in each controllers. 
(because in the current state the library/pagination is not even used and could be removed)

**Comment by diegospm** [comment]
It would be good to use objects for classes that use the same functions, such as pagination. This makes maintenance much easier and faster.

I didn't understand why the OC team decided to use the paging class in the common folder, but since it's just two classes it's not that serious in terms of maintenance.

The team did an amazing job on the engine and library using objects, although some interfaces are missing. But all this work is not repeated in the daughter classes of controllers, with unnecessary repetitions...

**Comment by jeffreyeng-opencart** [comment]
The pagination will get a revision on 3.1.x.
