### ISSUE TITLE
datetimepicker is outside the viewing window in the Admin > Customers > GDPR page

### ISSUE THREAD

**Issue by WebkulOc** [opencart/opencart#7586]
**What version of OpenCart are you reporting this for?**
Version 3.1.0.0_b

**To Reproduce**

1. Go to admin panel
2. Go to Customers -> GDPR and on the same page
see bug the datetimepicker is outside the viewing window

**Expected behavior**
All the dates should be visible to change so that every date would be available 

**Screenshots / Screen recordings**
![image](https://user-images.githubusercontent.com/52024848/64439670-2566e080-d0e8-11e9-96e8-fb3ce3017447.png)

**Comment by condor2** [comment]
What resolution?

**Comment by anantnegi** [comment]
Hello,

As i have raised the issue 
https://github.com/opencart/opencart/issues/7586 and from the screenshot 
it is visible that the datepicker is not visible fully so that the admin 
can change the date so i done changes in the code and after that the 
datepicker is visible with all dates as you can see in the below screenshot.

Thanks

**Comment by condor2** [comment]
On full hd resolution is ok

**Comment by anantnegi** [comment]
Yes but as not all of them would be having same resolution to work on so 
if someone has less resolution ( same as currently that i have checked 
for ) then it would create an issue to select the date.

**Comment by danielkerr** [comment]
fixed in master
