### ISSUE TITLE
If smtp email fails, the order is missing

### ISSUE THREAD

**Issue by dimkoss** [opencart/opencart#7633]
Before customer is redirected to success page, opencart is sending order's confirmation emails to customer and administrators. But if for any reason the smtp connection fails, the program breaks  and the customer doesn't know that he made a successfully online payment.

In system/library/mail/smtp.php the throw new \Exception code just raises the exception and breaks the program. This should be handled in a different way to avoid double orders or payments.

**Comment by danielkerr** [comment]
make sure your smtp or php mail settings are setup correctly.

**Comment by danielkerr** [comment]
also yuou can find missing orders from the admin order page.

**Comment by simkalp82** [comment]
yes. my smtp configs correctly. 
I sell 500-1000 products daily. 50 missing order per day. 

Your solution check 50 order per day?
> "also yuou can find missing orders from the admin order page."

waste time! 

Opencart is a simple software. if you are a big company use another software..

**Comment by simkalp82** [comment]
> also yuou can find missing orders from the admin order page.

yes. my smtp configs correctly.
I sell 500-1000 products daily. 50 missing order per day.

Your solution check 50 order per day?

"also yuou can find missing orders from the admin order page."

waste time!

Opencart is a simple software. if you are a big company use another software..

**Comment by osworx** [comment]
> Opencart is a simple software. if you are a big company use another software..

I would ask myself: "**why do I have so many missing orders?**"

Maybe your checkout is a crap, maybe your products, maybe your prices, maybe something other ..
Not "recommending" other software, that is a bad advice!

**Comment by simkalp82** [comment]
> > Opencart is a simple software. if you are a big company use another software..
> 
> I would ask myself: "**why do I have so many missing orders?**"
> 
> Maybe your checkout is a crap, maybe your products, maybe your prices, maybe something other ..
> Not "recommending" other software, that is a bad advice!

Because If smtp email fails, the order is missing.. 
Opencart order system = smtp mail..

**Comment by danielkerr** [comment]
IT COULD BE THE site IS NOT RECEIVING A CALLBACK FROM THE  PAYMENT GATEWAY.

or could be you deleted a order status that is still used by the order. u should ask in the forums or pay some one for support.

**Comment by ADDCreative** [comment]
This can be an issue, I've also seen it happen. As the exception will stop execution of the rest of the code and the trigger for the mail event is before (catalog/model/checkout/order/addOrderHistory/before). It means the order status doesn't get updated, so the order goes as missing.

@simkalp82 If you are seeing this happen a lot a probably means the mail server you are using could be very unreliable.

**Comment by head-dunce** [comment]
I've started to move the SMTP sending to an external script that PHP can call so that it doesn't hold up the calling scripts on the checkout no matter what happens with the email sending. Pretty simple update since all the heavy lifting is already coded in OC. Here's where I'm at right now (Sunday night, will work on it more when I have time - suggestions welcome)

Basically....
copy /var/www/html/system/library/mail/smtp.php
to say /var/www/html/system/library/mail/smtp-send.php

smtp.php gets this in the send() function and delete the rest

$shellsend = "php /var/www/html/system/library/mail/smtp-send.php --smtp_hostname='".$this->smtp_hostname."' --smtp_port='".$this->smtp_port."' --smtp_timeout='".$this->smtp_timeout."' --smtp_username='".$this->smtp_username."' --smtp_password='".$this->smtp_password."' --server_name='".getenv('SERVER_NAME')."' --from='".$this->from."' --to='[need to set up to for array]' --subject=".escapeshellarg($this->subject)." --sender='".$this->sender."' --reply_to='".$this->reply_to."' --html=".escapeshellarg($this->html)." --text=".escapeshellarg($this->text)." ";
exec($shellsend . " > /dev/null &");


smtp-send.php comment out the class and function and pick up the vars from the command line

$this_smtp_hostname = (getopt(null, ['smtp_hostname:'] ))['smtp_hostname'];
$this_smtp_port = (getopt(null, ['smtp_port:']))['smtp_port'];
$this_smtp_timeout = (getopt(null, ['smtp_timeout:']))['smtp_timeout'];
$this_smtp_username = (getopt(null, ['smtp_username:']))['smtp_username'];
$this_smtp_password = (getopt(null, ['smtp_password:']))['smtp_password'];
$server_name = (getopt(null, ['server_name:']))['server_name'];
$this_from = (getopt(null, ['from:']))['from'];
$this_to = (getopt(null, ['to:']))['to'];
$this_subject = (getopt(null, ['subject:']))['subject'];
$this_sender = (getopt(null, ['sender:']))['sender'];
$this_reply_to = (getopt(null, ['reply_to:']))['reply_to'];
$this_html = (getopt(null, ['html:']))['html'];
$this_text = (getopt(null, ['text:']))['text'];
$this_attachments = [];
$this_verp = '';

Then edit the vars to change up $this-> to basically $this_
Eh, that's where I'm at now, and it's working. Cheers!

**Comment by head-dunce** [comment]
I changed the code and am impressed about how much faster the checkouts are now happening. Is there ever a time that OC sends email attachments? I see it's in the smtp.php code, but I don't know if that code is ever used? I currently just default it to empty.

**Comment by RicLeP** [comment]
We had this issue. If the SMTP server tripped up check failed and customers then tried ordering again causing multiple payments. Really emails should be able to be pushed onto a queue so this critical functionality doesn’t get broken by a third-party system.

**Comment by Bigben83** [comment]
@head-dunce have you made any changes to the mod you suggested above.?
