### ISSUE TITLE
catalog/controller/startup/seo_url.php

### ISSUE THREAD

**Issue by jeffreyeng-opencart** [opencart/opencart#7660]
**Line 19:**
**Currently**
`$this->regex[$result['key']][] = '/' . $result['regex'] . '/';`

**Error:**

> Notice: Undefined index: key in C:\xampp\htdocs\opencart_master\catalog\controller\startup\seo_url.php on line 19

**Previously**
`$this->regex[] = $result['regex'];`

No error.

**Comment by bodo-hugo-barwich** [comment]
The SEO URL Rewrite() Method worked for me with the Table `seo_url`
with the changes published in
https://github.com/opencart/opencart/pull/7816
I could not find documentation about what is the purpose and the functionality that would provide the Table `seo_regex` but the site administrator is always forced to chose a `seo_url` keyword in order to add a new item to the catalog.

**Comment by danielkerr** [comment]
already fixed in master branch
