### ISSUE TITLE
Stored Cross Site Scripting - (Authenticated) on Opencart Admin Dashboard

### ISSUE THREAD

**Issue by corrupted-brain** [opencart/opencart#7810]
**What version of OpenCart are you reporting this for?**
Opencart 3.0.3.2
**Describe the bug**
Stored Cross Site Scripting (XSS) - Authenticated is found in users image upload section in opencart admin panel. Opencart is accepting filenames with arbitrary code in it and not escaping them so the JavaScript get executed. Malicious script in the admin dashboard can be injected permanently and can be used to steal the user’s sensitive information like cookies, keystrokes, account information etc

**To Reproduce**
1. Go to localhost.com/opencart/admin and login with credentials.
2. Then navigate to System>Users>Users and click on Action button on top right corner.
![Screenshot from 2020-01-09 09-46-46](https://user-images.githubusercontent.com/17331670/72037220-77518a00-32c5-11ea-88b6-9ee94181bb98.png)

3. Now in image field , click on image and upload a new image. Before this select any image file and rename with this XSS payload *"><svg onload=alert("XSS")>* and then upload it as new user profile image.
4. After the upload completes the XSS pop-up executes as shown below and it will gets executed each time someone visits the **Image manager** section.
![Screenshot from 2020-01-09 09-58-24](https://user-images.githubusercontent.com/17331670/72037961-ed56f080-32c7-11ea-9ac8-a83017d162c7.png)

**Expected behavior**
Escaping and sanitation of  HTML tags/ Special characters before storing or processing them, so that the code does not executes. Although XSS was strictly filtered on other sections, here we were able to execute it because of filename so filenames, file extensions and headers should be analyzed to prevent XSS and other file upload vulnerabilities.

**Screenshots / Screen recordings**

[opencart stored XSS.zip](https://github.com/opencart/opencart/files/4038533/opencart.stored.XSS.zip)

**Server / Test environment (please complete the following information):**
 - Kali Linux 4.19.0
- PHP version: 7.1.32
 - Apache version: 2.4.41
 - Browser(s) tested with: Mozilla Firefox Latest Build

**Comment by straightlight** [comment]
I like this solution for single-dots aside from the fact that XSS vulnerabilities could be used with uploaded filenames: https://stackoverflow.com/a/17625652.

Let's try it and see if you can reproduce the same issue as described above:

In admin/controller/common/filemanager.php file,

find:

``$filename = basename(html_entity_decode($file['name'], ENT_QUOTES, 'UTF-8'));``

replace with:

``$sanitize = array('([^\w\s\d\.\-_~,;:\[\]\(\)]|[\.]{2,})',
									  '~XSS~i'
									 );
					
					$filename = preg_replace($sanitize, '', html_entity_decode($file['name'], ENT_QUOTES, 'UTF-8'));					
					
					$filename = basename(html_entity_decode($filename, ENT_QUOTES, 'UTF-8'));``

**Comment by corrupted-brain** [comment]
Hi , I used following regex to remove special characters from the filename, allowing dots, hyphen, A-Z, 0-9. 
```
// Sanitize the filename
$filename = basename(html_entity_decode($file['name'], ENT_QUOTES, 'UTF-8'));
//Using regex to filter filename
$filename=preg_replace('/[^A-Za-z0-9\-\.]/','',$filename);
// Validate the filename length
if ((utf8_strlen($filename) < 3) || (utf8_strlen($filename) > 255)) {
$json['error'] = $this->language->get('error_filename');
}
```
And It worked,  special characters were removed and file uploaded as shown below.

![Screenshot from 2020-01-10 14-07-25](https://user-images.githubusercontent.com/17331670/72137482-fc669d00-33b2-11ea-8bff-b19f3fcd41d9.png)

Initially filename was *"><svg onload=alert("XSS_By_Kailash")>.jpg* . I hope it has been resolved.

**Comment by ADDCreative** [comment]
The payload also works if entered as a New Folder name. The real issue is lack of escaping before sending the data to the template at the following lines (for 3.0.3.2, now slightly different in the master branch).

https://github.com/opencart/opencart/blob/4ba536198a4638b6d3902a7c720ce8503b0dc394/upload/admin/controller/common/filemanager.php#L80-L82

https://github.com/opencart/opencart/blob/4ba536198a4638b6d3902a7c720ce8503b0dc394/upload/admin/controller/common/filemanager.php#L87-L91

Any line from the above that uses ```$name``` or ```$image``` should be wrapped in htmlspecialchars() (or maybe urlencode() in one case), as below. This will also fix other minor issues caused by special characters (such as parent folder being deleted if the sub folder to be deleted starts with a double quote).
```php
htmlspecialchars('name'  => implode(' ', $name), ENT_QUOTES, 'UTF-8'),
```

There also looks like an attempt to filter in the master branch.
https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/admin/controller/common/filemanager.php#L248

https://github.com/opencart/opencart/blob/e6a0b984234deb6d58f23e6d0027417345828f20/upload/admin/controller/common/filemanager.php#L326

However, the expression is wrong. Maybe it should of been ```'/[\/\?%*:|"<>]*/'```. Even if the expression was correct, it would not help where the payload was already there, delivered via FTP or an extension that uploads images.

**Comment by straightlight** [comment]
While the analysis above might be true, the only downside by adding a star lookup at the end, whether it's for FTP or an extension that uploads images, the directory structure name also gets renamed along with the filename by using the master branch and also checks for existing folder names. Any change of state not being identified within the $json['success'] becomes a renamed folder name where the admin is not consent about the returned file name since sprintf is not being used with the text_directory key of the $this->language->get . Therefore, the admin may not realize if the folder name originates from the file manager or by ... another source of origin especially since CHMOD 077 is being implied in the codes.

That being said; to add a sprintf function to notify the admins regarding the new created folder name would be highly recommended.

As for the regular expression, may be the following could be used:

``preg_replace('/[^a-zA-Z0-9\s\-_\.\?/', '', basename(html_entity_decode($this->request->post['x'], ENT_QUOTES, 'UTF-8')));``

where 'x' would be the folder and the filename wherever they need be.

**Comment by straightlight** [comment]
An alternative would be to use filter_var based on the provided URL above.

**Comment by ADDCreative** [comment]
Yes, the asterisk was superfluous. I should of just said the expression was missing delimiters.

I think the aim of the santise filters are to make the names safe for writing to the file system (thinking Windows reserved characters), not to prevent XSS. You won't find a filter_var filter for that.

**Comment by straightlight** [comment]
If no filter_var could be found for sanitizing filters, then users relying on the filter_var validations being used with custom fields with the REGEXP case would be all screwed, I presume. Granted, there has been reports regarding odd results regarding the regular expressions being used in there as well. However, workarounds were also provided in their commits accordingly.

**Comment by ADDCreative** [comment]
There are no filter_var filters to sanitize a filename. The custom fields are using filter_var to validate not sanitize. There is a difference.

**Comment by ADDCreative** [comment]
@corrupted-brain I see you have closed this issue. Has a patch been added to the master branch?

**Comment by corrupted-brain** [comment]
No it's not. Sorry I was unaware of this procedure and closed the issue.

**Comment by danielkerr** [comment]
this issue missed my attention. 

you are wasting every ones time!!!!!! you clown! how are hackers supposed to upload code when they need the admin access!!!! the big what if! stop wasting peoples time. you should not be giving advice out to anyone! concentrate on your own life because you are not smart enough to be successful as a coder!

**Comment by corrupted-brain** [comment]
Sir have you heard about CSRF attacks ? Issues like this can be chained with CSRF.  Where a authenticated user can be exploited with a single click and performing request from victims (here admin's) side. I'm not smart to do secure coding but I think I found common coding mistake where basic user input validation is not done. This is not the advice, I get to know about this from OWASP. Sorry for wasting 2 more valuable minutes of your life.

**Comment by danielkerr** [comment]
narcissist
