### ISSUE TITLE
Checkout gets stuck on Payment Method with Warning: Payment method required!

### ISSUE THREAD

**Issue by aggies99** [opencart/opencart#7811]
**What version of OpenCart are you reporting this for?** 3.0.3.2 (from A2 Hosting)

**Describe the bug**
I installed OpenCart today on A2 Hosting.  I have added a few products to try to test out the cart.  I added a product to the cart.  Now I want to checkout.  All options I try to checkout fail as I get to the payment method message of "Warning: Payment method required!"

Steps:

1. Homepage...Checkout in the header
2. Homepage...Shopping cart in the header...Checkout
3. Homepage...Black cart button...checkout
4. Homepage...Black cart button...shopping chart...checkout

I have reviewed issue #6600 but have not found the solution mentioned with this issue as it was closed.  It appears my files for commit fd06704f935854ff191122fc3e5a98f3d9e47f40 are already applied to 3.0.3.2. (updated the checkout system using chaining ajax calls to avoid session overwriting.)

 - A2 Hosting installation
 - PHP version: 7.1
 - Browser(s) tested with: Chrome, IE11.914.17763.0
 - Version: 3.0.3.2

![error](https://user-images.githubusercontent.com/2520675/72041326-e05ae280-3270-11ea-9cad-b24f15fbb3f6.jpg)

**Comment by aggies99** [comment]
My store: https://tx-d38-ll.a2hosted.com/nhll_store/

**Comment by afc-za** [comment]
I have the same problem as described above.
Seriously frustrating. Remedies in Opencart Forum also does not help.
If anybody has a solution, PLEASE.

**Comment by aggies99** [comment]
After trying various scenarios, I learned that I need to ensure that I had fully localized my cart before I started making any changes to the Extensions.  I am not sure where the failure was before exactly as I did not dig deep into the code.  However, after configuring my store with the correct options, I have not see the failure again.  I am going to close this issue.

**Comment by redochka** [comment]
Any one still suffering from this issue here is a simple fix:

Edit `catalog/controller/checkout/register.php` and add the following at almost the end of the `save` function:

```
unset($this->session->data['payment_methods']);
//new: 
$this->session->close();
$this->session->data['session_closed'] = true;
```

Edit `system/library/session.php` and change the `close` function to the following:

```
public function close() {
    if(empty($this->data['session_closed'])) {
        $this->adaptor->write($this->session_id, $this->data);
    }
}
```

Enjoy!

**Explanation:**
The problem is indeed quick successive ajax requests, in our example:

- In the `checkout/register.php#save`, the json is outputted, but process is not yet done.
- `checkout/payment_method.php#index` is called by ajax onSuccess. Payment methods are set in the session
- Now: our previous `checkout/register.php#save` process finishes and persists the session to disk (now payment_methods are empty)
- `checkout/payment_method.php#save` reads payment_methods from session and find them empty which leads to the error message "Payment method required"

The solution is to save the session (by calling `close`) before outputting the json response and set the `session_closed` to avoid another session write (registered in session.php using `register_shutdown_function(array($this, 'close'));`)
