### ISSUE TITLE
Duplicate language file read

### ISSUE THREAD

**Issue by reetp** [opencart/opencart#7812]
**What version of OpenCart are you reporting this for?**

Master from github - https://github.com/opencart/opencart/commit/e6a0b984234deb6d58f23e6d0027417345828f20

**Describe the bug**

More a small speed improvement. Whilst debugging another issue I just happened to notice the language file function 'load' unnecessarily reads the same file twice:

```
	public function load($filename, $prefix = '') {
		$_ = array();

// if $this->default = $this->directory then you don't need to run both these sections - it just reads the same file twice

		$file = DIR_LANGUAGE . $this->default . '/' . $filename . '.php';

		if (is_file($file)) {
			require($file);
		}

		$file = DIR_LANGUAGE . $this->directory . '/' . $filename . '.php';

		if (is_file($file)) {
			require($file);
		}
```

And then if they are the same you don't need to run this:

`		$this->data = array_merge($this->data, $_);`

Not sure which way is fastest - running require twice/array merge or checking $this values.

**Comment by straightlight** [comment]
That would be incorrect since the __construct method has the option $directory variable that can be defined. In your explanation above, if the $directory variable would be an enforced entry in the parameter, then it would be a different story.

However, the $this->directory should still be validated whether the $file variable needs to rely on the $this->default or with the $this->directory instanced variable.

**Comment by reetp** [comment]
Whatever. I'm no coder.

I just happened to notice as I step debugged that it ran through the same file twice which is just a waste of CPU cycles so I logged it.

**Comment by WebkulOpencart** [comment]
@straightlight Yes, you are correct so closing this case
