### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by Grumvol** [opencart/opencart#7830]
I apologize for the errors, I use a translator. You need to change the logic of user groups.

1. There should be an option "all groups", for example with id = 0. With the current implementation, for example, if I have 4 user groups and 5000 products, then for each product I must select all 4 groups for the promotional price. Moreover, if then I add another group and for each product I will have to add it.

2. There should be an option "user group by default". Now she is config_customer_group_id. This group is assigned to unauthorized users (guests).

3. You need to add a default group to register users with config_register_group_id. This group must be in the config_customer_group_display list, not config_customer_group_id.

4. Violation of the logic of work. The file catalog / controller / api / customer.php line 58. You need to check for a user group among all groups, and not among config_customer_group_display. For example, I can transfer a user from one group to another (which is not among those that are available during registration, that is, among config_customer_group_display).

**Comment by Grumvol** [comment]
3.1

**Comment by straightlight** [comment]
The problem for aspect no. 4 is even though all groups would be checked, the customer_group_id is not assigned to any store_ids neither which could also be seen as a violation as opposed to validate the customer group displays since the customer group IDs of those displays are associated based on the selected store from the store owners that has the access to use the APIs.

As for the other aspects, please specify their locations with screenshots to describe 'each' aspects. More information is needed.

**Comment by straightlight** [comment]
Since there are no updates on this commit, this commit will now be closed.
