### ISSUE TITLE
Recurring payments fail with SagePay Server

### ISSUE THREAD

**Issue by gRoberts84** [opencart/opencart#7843]
**What version of OpenCart are you reporting this for?**

3.0.3.2

**Describe the bug**
Checks within `catalog/model/extension/payment/sagepay_server.php` fails to correctly identify the subscription end and next payment dates. If statement is comparing two DateTime instances, which upon further inspection, are actually different due to milliseconds:

```
2020-01-27 5:40:57 - ControllerStartupRouter::index - Pre Subscription Date Selection: {"trial_end":{"date":"2020-01-27 05:40:57.914688","timezone_type":3,"timezone":"UTC"},"subscription_end":{"date":"2020-01-27 05:40:57.914694","timezone_type":3,"timezone":"UTC"},"recurring_duration":"0"}
```

As a result, the subscription is immediately ended and never renews.

**To Reproduce**
1. Configure SagePay Server.
2. Create a recurring payment profile (daily, no end date, no trial.)
3. Associate recurring payment profile with product.
4. Purchase product.

**Expected behavior**
Expect a successful payment every day in line with the payment profile.

**Screenshots / Screen recordings**
N/A

**Server / Test environment (please complete the following information):**
 - Local development
 - Operating system: OSX
 - PHP version: 7.2.3

**Additional context**
Seems a lot of problems with the SagePay Server integration. Recommend either overhauling or removing from production to avoid confusion.

**Comment by gRoberts84** [comment]
Unfortunately it seems there are more issues, as the cron based scheduler for SagePay Server is using session variables which wouldn't exist, i.e. 

`$payment_data['Amount'] = $this->currency->format($price, $this->session->data['currency'], false, false);`

This was strangely causing my `9.95` recurring value to be sent to SagePay as `10`. 

When I updated it to use the `$order_info['currency_code']` instead it worked correctly.

**Comment by straightlight** [comment]
The downside of using the $order_info['currency_code'] in this case would be for store owners using currency auto-updates on their store where it reflects the change on the $this->session->data['currency'] super global array while the $order_info['currency_code'] may still capture the previous rate of that auto-updated change since the time period where that specific order may have been stored. Which is why, you may have ended up with 10 instead of the 9.95 value.

If not the case in your situation, this case may be reflecting others however since there are extensions that allows to auto-update currency values from their store-front end.

**Comment by gRoberts84** [comment]
Unfortunately in this case, that isn't so. 

Taking aside that `$payment_data['Amount'] = $this->currency->format($price, $this->session->data['currency'], false, false);` uses the auto-updated value, I am using a currency that is set to 1.000, so never changes. 

What makes this even more strange, is that the default currency is the same as the currency being charged so in this case, you'd expect `$this->session->data['currency']` to be the same as `$order_info['currency_code']` yet they both produce different results.

**Comment by gRoberts84** [comment]
The list goes on unfortunately :( 

Despite numerous tests, even after recurring payments have been made, the status never changes from 6.

**Comment by straightlight** [comment]
I have addressed this issue to Daniel today. That is because the transaction uses the current language ID rather than the order language ID where the order status ID needs to match with the created order upon order status updates from the admin API, during checkout and from the events (where needed).

**Comment by danielkerr** [comment]
i have asked sagepay to sort any issues with the extension

**Comment by danielkerr** [comment]
i have removed this e4xtension in the master branch
