### ISSUE TITLE
Stored Cross Site Scripting(XSS) on Opencart Admin Dashboard

### ISSUE THREAD

**Issue by exp-db** [opencart/opencart#7878]
**What version of OpenCart are you reporting this for?**
Opencart 3.0.3.2
**Describe the bug**
In the admin pane, enter the description field  of the Categories/Product/Information pages . Select Submit, use proxy to modify the description field and eventually lead to Stored Cross Site Scripting(XSS). With XSS we can read any data the attacked user has access to.

**To Reproduce**
1. log-in to admin-panel
2. Navigate to Catlog and then Categories / Products / Information and select any.
3. Set a proxy for the browser (such as Burp)
4. Enter any characters in the description field (will be modified to XSS Payload later),then click the save button.
![pic1](https://user-images.githubusercontent.com/26398572/77335623-5b587300-6d61-11ea-8ccb-991df2150f90.png)
5. Use burp proxy to change to the description field in the following Post data.
<img width="1067" alt="pic2" src="https://user-images.githubusercontent.com/26398572/77336557-a6bf5100-6d62-11ea-891d-9471a96dfd0b.png">
6. After you submit it successfully, visit the modified page of your public website. A Stored XSS payload will execute.
<img width="992" alt="pic3" src="https://user-images.githubusercontent.com/26398572/77338934-0539fe80-6d66-11ea-973d-8968a4f58d36.png">

**Expected behavior**
Although the input characters have been filtered on the front end, the front end protection can be bypassed by proxy, and XSS filtering on POST characters is also required after receiving by PHP.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Ubuntu 16.04
 - PHP 7.0
 - Apache 2.4.7
 - Browser(s) tested with Chrome Latest Build

**Comment by ADDCreative** [comment]
You can just use the code view to add JavaScript. I believe that the store administrator being able to add JavaScript to the content is by design. You will find this feature in most other CMSs, including the most popular one in use, WordPress. It's useful for using active content in the design.

If you are referring to the script executing on the admin side then it's a duplicate of https://github.com/opencart/opencart/issues/4571. Which was fixed in the master branch with https://github.com/opencart/opencart/commit/d79860ca28304947ef60467d984296e9f6d3318d.
