### ISSUE TITLE
coupon code not limiting to 1 single category.

### ISSUE THREAD

**Issue by ankitjn227** [opencart/opencart#7927]
I have created a coupon code for 1 category, to provide discount in that category.

But, here coupon code is working in all categories on portal.

How to restrict it.

**Comment by straightlight** [comment]
For which OC version are you reporting this issue?

**Comment by ankitjn227** [comment]
@straightlight 

OC 3.0.3.2

**Comment by danielkerr** [comment]
it does work but it includes sub categories

**Comment by ankitjn227** [comment]
Issue not resolved...

still facing the same issue ..

Generate Coupon code for Sub-Catagories only....

but including that sub-category, coupon is working on primary catergory as well as other categories also..

**Comment by ankitjn227** [comment]
> it does work but it includes sub categories

Issue not resolved...

still facing the same issue ..

Generate Coupon code for Sub-Catagories only....

but including that sub-category, coupon is working on primary catergory as well as other categories also..

**Comment by straightlight** [comment]
Since you are using OC v3.0.3.2, are you reporting this issue as well for the master branch? As Daniel indicated on the above, however, it does seem to work as intended. The issues tab on this page only regards everything about the master branch or persisting issues from previous versions that are still encountered on the master branch.
