### ISSUE TITLE
[All 3.x version] SQL converting url_alias to seo_url missing from upgrade model's

### ISSUE THREAD

**Issue by condor2** [opencart/opencart#7949]
**What version of OpenCart are you reporting this for?**
All 3.x version

**Describe the bug**
SQL command to convert url_alias in seo_url missing from any of upgrade model's. So every time when someone upgrade from 2.3.0.2 to 3.x version url_alias should be manually changed in to seo_url

**Additional context**
I don''understand why this wasn't added in any of 3.x version even in Master Branch...

**Comment by straightlight** [comment]
Due to the possible multiple language IDs being involved, how could one being able to tell which language IDs will be relative with the store ID when, previously with the url_alias table, those readings were not present becomes the question.

Since there are no definite ways to know at this point, this commit will now be closed.
