### ISSUE TITLE
Opencart Login Without Any User Info

### ISSUE THREAD

**Issue by ofbozkurt** [opencart/opencart#8015]
I'm having a serious problem with admin panel. In the admin login page (page to the dashboard), even if i don't enter username or password I can login to admin panel. I have a website that is using opencart 3.0.3.2. I'm using Journal theme and it's version is 3.0.46.

I tried different browsers, logging out-in but they didn't work for me unfortunately.

Any suggestions?

**Comment by cartbinder** [comment]
**You have either a cache issue or some compromise done with your login files.** 

It best to contact the opencart developer or create a topic here:
https://forum.opencart.com/viewforum.php?f=202

So someone can help you on the forum.

**Comment by straightlight** [comment]
This namespace is either for the master branch or the pre-release version. If you have issues with OC versions prior than those, please use the forum. Since you are also using Journal, however, please do not use the forum since Journal extension is not supported on the forum. Rather, contact the Journal Support team to rectify the incident request you are addressing about.

Therefore, this commit will now be closed.

**Comment by ofbozkurt** [comment]
Update: I followed this: https://blog.sucuri.net/2016/12/unrestricted-backend-login.html and problem is gone.
