### ISSUE TITLE
card.add(), wishlist.add(), compare.add() w/o parms in product thumbs 

### ISSUE THREAD

**Issue by githubertus** [opencart/opencart#8023]
**What version of OpenCart are you reporting this for?**
3.0.3.4-core-pre
**Describe the bug**
no action when clicking any of the 3 icons of a product thumb

line 424 of catalog\controller\product\product.php is passing a simple array
`$this->load->controller('product/thumb', $product_data);`
while thumb.twig is expecting values like `{{ product.array_element }}`

Thus either the twig file needs to be adapted to use just `{{ array_element }}`
or $product_data needs to be stuffed into an extra 'product' array

**Comment by straightlight** [comment]
Ok, spotted. Fixed. Well done.

**Comment by straightlight** [comment]
One thing I did noticed is the featured extension module when using the add-to-cart button, the quantity is not increasing from the common/cart object at the header menu. This issue might be linked to something else for quite sometime since there were some users on the Opencart forum stating this as well in the past. Will have to dig more into this later on.

**Comment by githubertus** [comment]
oops, yes: the second (minimum) parameter of card.add() is missing here ... ;)
adding `($result['minimum'] > 0 ? $result['minimum'] : 1),`
near line 55  of catalog\controller\extension\module\featured.php
does the trick.
same goes for bestseller, latest and special

**Comment by straightlight** [comment]
```$result``` won't work for featured since it uses ```$product``` as the array name. I will update the package in a few minutes.

**Comment by straightlight** [comment]
Ok, fixed.
