### ISSUE TITLE
 Invalid token session. Please login again

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#8133]
**What version of OpenCart are you reporting this for?**
master branch
**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

either system/config/default.php line 42:
`$_['session_expire']       = 360000;`
or php.ini line 15:
`session.gc_maxlifetime = 9999998`
does not work.

Although the above configures exist, actually session lasting time is not enough to complete some job for admin user or online writer, for instances, fill out all product fields including long description, information article, etc. If your work is in the middle, opencart happens request you login again, you do login, but you are not in your previous scenario, you have to do again.

What else config is missing?

**To Reproduce**
1. Go to 'admin/index.php?route=catalog/product&user_token='

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by NancySavage** [comment]
I believe after reading the recent commits involving the session and php changes, that the intention appeared to be to expire it in an hour? However, I am looking at the session table in my DB and each time I log in, the session is set to expire exactly within 24 minutes.

![session](https://user-images.githubusercontent.com/68765132/88669930-7c83f400-d0b2-11ea-8a1c-235541eef3a9.PNG)

It's sort of annoying. If you don't actually save/update anything in the dashboard within 24 minutes, you get logged out.

**Comment by cgcmart** [comment]
I searched the issue on forum.opencart.com. It's a persisting issue often raised without official or solid solution since opencart 1.5.

**Comment by NancySavage** [comment]
Eh, I figured it out which I did before but I forgot that I had to redo my server with a new php installation. This has been mentioned on the boards, too. Some servers will not allow you to overwrite the settings (meaning, using the php.ini file in the OC directory). You need to go to your server's actual php file to edit it. Also, if you use a shared host plan (like the cheapy ones), you may have to beg the provider to change it if you can't override it.

So even if you have: session.gc_maxlifetime = 9999998 in opencart's php.ini file, if you go to your server's actual php file, it could be set to 1440. Hence, why I saw the expiration for exactly 24 minutes when looking at my DB for the session.

You can see a screenshot of my localhost php file for example where the same thing holds true in this case. I had to change it to be an hour (or 3600 value).

![sessionset](https://user-images.githubusercontent.com/68765132/88755112-569c3500-d12e-11ea-9eea-85b1c571658b.PNG)

I don't feel this is really an OC issue as a result, but someone else can chime in if there is another way to override for people who are too novice to edit the server php file. It's been the case with other things I had to install both locally and on a live server.

After I made the change directly, i went back into my DB and sure enough, it was set for an hour to expire rather than the original 24 minutes.

**Comment by cgcmart** [comment]
I use cpanel server, ea-php73, that is, php 7.3
Cpanel MultiPHP INI Editor Configure PHP INI basic settings show
`session.gc_maxlifetime = 9999998`

**Comment by NancySavage** [comment]
Did you restart apache after making the changes? It's required if you're doing that.

**Comment by danielkerr** [comment]
ok changed max-age back to expire.

**Comment by danielkerr** [comment]
i think the expire time issue with session is because the db and php time settings are not synced properly.

**Comment by danielkerr** [comment]
maybe i need to replace all the NOW statements with php date();

**Comment by cgcmart** [comment]
@danielkerr Currently master branch changes works.

**Comment by danielkerr** [comment]
should be working now.

**Comment by cgcmart** [comment]
Yes, it's. Website complete seo urls show as expected.

**Comment by danijelGombac** [comment]
What I tested the "error not found" is not working as expected. The home page is loaded instead.

**Comment by cgcmart** [comment]
https://github.com/cgcmart/opencart/commit/651addc703b35f9a25584ced785a440ea6f66ace

**Comment by danijelGombac** [comment]
After last change for seo

`http://localhost/oc_4/en-gb/laptop-notebook `is ok
`http://localhost/oc_4/en-gb/laptop-not` home page, should be error not found
`http://localhost/oc_4/en-gb?route=account/login` home page, because language seo profile remove route

**Comment by cgcmart** [comment]
admin->design->seo->seo url
add them, to see what happens
my site home page: https://www.wenbo.world/en-gb/home

**Comment by danijelGombac** [comment]
Why this link https://www.wenbo.world/en-gb/chinese-herbal-rem does not lead to error/not_found

**Comment by cgcmart** [comment]
when you add category and product, you also fill out seo field.

**Comment by mhcwebdesign** [comment]
cgcmart: Your wenbo.world site has many other more severe issues, at the moment it would take more than 10 or 20 minutes to load, especially for the images.

**Comment by cgcmart** [comment]
I noticed. I just managed to install oc 4 master on Sunday. Probably internet traffic, local connection slow, or cache issue. I use Alibaba cloud.

Another site https://cgcmart.com/ is good. I use Google cloud.
