### ISSUE TITLE
twig 'include' does not work in Opencart 3.0.3.6

### ISSUE THREAD

**Issue by kopitoshka** [opencart/opencart#8134]
Twig has 'include' functions which worked well in the past versions. Since twig loader was changed to ArrayLoader from FileSystem Loader the twig 'include' functions stopped working.

Could you add support of twig include functions? Maybe it is worth to use ChainLoader instead of using just one of loaders above?

https://twig.symfony.com/doc/3.x/api.html#twig-loader-chainloader

**Comment by Eco1973** [comment]
I second that, getting: PHP Fatal error:  Uncaught Error: Class 'Twig\Loader\ArrayLoader' not found

**Comment by bluegeeks1988** [comment]
I not sure if i am correct in this but inside folder: system/library/template/ the actual Twig folder is not there in 3.0.3.6? but its there in 3.0.3.5? has there been a change how it loads now?

**Comment by luisvelazquez** [comment]
Do you know of an alternative solution instead of placing all code in the same file?
I was using `{{ include('file.twig') }}` to make it more readable.

**Comment by MikhailShemelin** [comment]
> Do you know of an alternative solution instead of placing all code in the same file?
> I was using `{{ include('file.twig') }}` to make it more readable.

Have you tried it in 3.0.3.6 ?

**Comment by prabhatkumaroc082** [comment]
fix #9096

**Comment by mhcwebdesign** [comment]
As far as I know the core OC twig files don't contain include-tags.
For extensions, rather than using an include-tag in twig, use a variable

`$data['file'] = $this->load->controller('file',$data);`

in your main controller, and a separate controller for file, and

`{{ file }}`

in your main twig file. This makes it more compliant with the MVC design.

**Comment by MikhailShemelin** [comment]
> As far as I know the core OC twig files don't contain include-tags.
> For extensions, rather than using an include-tag in twig, use a variable
> 
> `$data['file'] = $this->load->controller('file',$data);`
> 
> in your main controller, and a separate controller for file, and
> 
> `{{ file }}`
> 
> in your main twig file. This makes it more compliant with the MVC design.

Using twig include-tags is useful, because:
- it allows to use the actual template enviroment/scope in included templates
- it simplifies the code of controllers (no necessity to pre-render all template parts)
- it helps to have less code duplication

For example, many of the default opencart theme templates have code like this (so it is duplicated many times)
```
{% for breadcrumb in breadcrumbs %}
      <li class="breadcrumb-item"><a href="{{ breadcrumb.href }}">{{ breadcrumb.text }}</a></li>
{% endfor %}
```
If you need to change the view of breadcrumbs on the website (and CSS functionality is not enough), you have to change every template file containing breadcrumbs (etc., all the issues code duplication caused are here). 

To get rid of this code duplication using the twig include-tag it is enough to create a specific template file for rendering breadcrumbs and just include it in all the necessary templates, something like
```
{{ include('common/breadcrumbs.twig') }}
```

Without using the twig-include tag is it necessary not only to created the breadcrumb twig template and to put a code like this to all mentined templates
```
{{ breadcrumbs }}
```
but also add additional rendering code to all appropriate controllers
```
$data['breadcrumbs '] = $this->load->controller('common/breadcrumbs',$data);
```
So it gives more code, more duplication and more complicity all together.

**Comment by mhcwebdesign** [comment]
This is a poor example because the breadcrumb is used in the admin pages only. You don't do styling to the admin pages.
Twig in general, especially the version as implemented from the Symfony framework, was a poor fashion choice because PHP already is a better template language. 

And if you are so desperate to implement one of those many poor frontend web theme with excessive twig features, you can always enable the include-feature by using Symfony's Twig array loader, e.g. something like this in the **system/template/twig.php**:

```
			$loader1 = new \Twig_Loader_Array(array($filename . '.twig' => $code));
			$loader2 = new \Twig_Loader_Filesystem(array(DIR_TEMPLATE)); // to find further includes
			$loader = new \Twig_Loader_Chain(array($loader2, $loader1));		
			$twig = new \Twig\Environment($loader, $config);
			return $twig->render($filename . '.twig', $this->data);

```

**Comment by MikhailShemelin** [comment]
> Twig in general, especially the version as implemented by the Symfony framework, was a poor fashion choice because PHP already is a better template language.
> 
May be. But twig (like many other template engines) still helps to force less qualified developers to use templates as templates only (it is not convenient to code application logic in twig and normally it does not allow or at least makes difficult to load controllers/models/libraries/etc. in templates). So it's worth it.

> And if you are so desperate to implement one of those many poor frontend web themes with excessive twig features
Any well-developed theme should avoid code duplication similar to the breadcrumb duplication currently existing the default opencart theme. And twig gives a convenied instrument for this ("include-tag").

>, you can always enable the include-feature by using Symfony's Twig chain loader, e.g. something like this in the **system/template/twig.php**:
> 
> ```
> 	$loader1 = new \Twig_Loader_Array(array($filename . '.twig' => $code));
> 	$loader2 = new \Twig_Loader_Filesystem(array(DIR_TEMPLATE)); // to find further includes
> 	$loader = new \Twig_Loader_Chain(array($loader2, $loader1));		
> 	$twig = new \Twig\Environment($loader, $config);
> 	return $twig->render($filename . '.twig', $this->data);
> ```
Yes, and it is the way I think it should be impelented in opencart by default (in its stock version). 

Otherwise every second developer will implement it by his own (as a kind of modification), then different implementations will met each other on opencart websites using extensions/themes created by different developers and it will cause conflicts (bad experience for users, additional work for developers).

**Comment by WhereJuly** [comment]
What is the reason of using a template engine and not using its built in capabilities of simple template extensibility and inheritance? Those in fact any template engine is built for.

**Comment by mhcwebdesign** [comment]
Twig is a prime example how not to design a proper template engine. It's syntax is poor, they haven't even bothered to implement a clean LALR(1) syntax. It has crazy binary operators like 'b-or', 'b-and', 'b-xor' instead of the normal '|', '&', '^'. It doesn't even use proper keywords in its language syntax, quite often these can also be used as e.g. variable names. And in several cases the wheel got invented multiple times, such as the include-tag and the include function. Several tags should be deprecated and removed because they add no new functionality.  Sorry, but there are better template engines out there. BTW.: The Twig template inheritance is just a fake, it's not a genuine object-oriented class extension, the usage of blocks in a child template is a very crude construct. And why does it silently ignore non-existing variables by default, unlike PHP? And where it does generate error messages, more often than not it won't show the correct line number of the template causing the error.

**Comment by Stanislav93** [comment]
How to work with macros now? "import" required

**Comment by Stanislav93** [comment]
It used to work
{% import "extension/extension/tool/macros.twig" as forms %}
{{ forms.addTabJsA1('tab_changelog', '.panel-body', '<i class="fa fa-code-fork"></i> ' ~ text_tab_changelog, 'changelog', viewTabBody) }}
