### ISSUE TITLE
Secure Trading Payment needs updating in opencart to v2 

### ISSUE THREAD

**Issue by w33ty** [opencart/opencart#8166]
Open Cart Version 2.3.0.2
**Describe the bug**
The version of the script that's built into open cart  uses version 1 of the template that secure trading us which is not mobile responsive they say that it needs updating to version v2 so it calls that payment up for this too work

**Screenshots / Screen recordings**

Add
![same_on_novatec_ to](https://user-images.githubusercontent.com/4239137/89122244-a1ff6c00-d4bd-11ea-8550-0d112e7296dc.PNG)

**Comment by chongshengdz** [comment]
Open Cart Version 2.3.0.2 was discontinued a long time ago.

**Comment by IP-CAM** [comment]
> Open Cart Version 2.3.0.2 was discontinued a long time ago.
Depends on what you understand with 'a long time ago' ...
Better read here about it, it still belong to the best Versions ever ...
[url]https://forum.opencart.com/viewtopic.php?f=190&t=215529&p=773505#p773505[/url]

**Comment by condor2** [comment]
Very funny =)))))). Not responsive.
Maybe now you understand what is not responsive...

![securetrading](https://user-images.githubusercontent.com/14251939/89128903-9170e500-d501-11ea-9432-2d26ef979b3a.png)

**Comment by ADDCreative** [comment]
> Open Cart Version 2.3.0.2 was discontinued a long time ago.

The payment module is still included in 3.0.3.6 which was release in July 2020. So the issue is still valid.

> Very funny =)))))). Not responsive.
> Maybe now you understand what is not responsive...

You have misunderstood the issue. The payment module in OpenCart needs updating to tell Secure Trading to use a responsive payment page.

This line need changing to use version 2.
https://github.com/opencart/opencart/blob/e9522c4db446f219cda7392bb8ca93c244ac1e97/upload/catalog/view/theme/default/template/extension/payment/securetrading_pp.twig#L7

As well as updating some of the fields passed.
https://docs.trustpayments.com/document/toolbox/ppg-fields/

**Comment by condor2** [comment]
Interesting method to detect a responsive page.
I think better was to be checkbox in settings or based opencart version.

**Comment by ADDCreative** [comment]
It's not a method of detection a responsive page. Version 1 of their form (probably deprecated) doesn't support small screens, version 2 does. The OpenCart module need updating to use version 2 for their form.

**Comment by prabhatkumaroc082** [comment]
fix #9037
