### ISSUE TITLE
Security Update jQuery

### ISSUE THREAD

**Issue by osworx** [opencart/opencart#8221]
Because of jQuery vulnerability [CVE-2020-11022](https://nvd.nist.gov/vuln/detail/CVE-2020-11022) and [CVE-2020-11023](https://nvd.nist.gov/vuln/detail/CVE-2020-11023) the jQuery library should be updated asap!

And because of many 2.x installations, a fix should be provided for those versions also.
For 1.5. it would be also not a bad idea.

**Comment by ADDCreative** [comment]
Looking at the full details, which also links to the fixes. https://mksben.l0.cm/2020/05/jquery3.5.0-xss.html I can't see that OpenCart would be affected as it doesn't sanitise HTML in that way (can't say for themes or extensions). Please correct me if I am wrong.

Not that it shouldn't be updated. Are there any breaking changes in the latest version of jQuery when used in Opencart 2.x and 1.5.x?

**Comment by NancySavage** [comment]
This has already been a discussion here: https://github.com/opencart/opencart/issues/8184 but I agree it needs to be updated for the other versions, too. I think OC is fine, but the problem is that your store will fail PCI scans regardless. It is mandatory to be PCI compliant if anyone steps foot on your website and tries to enter a credit card (regardless of where the credit card is being stored, paypal may be different though if you entirely redirect someone away from your site).
