### ISSUE TITLE
package react is missing tag/3.0.3.6

### ISSUE THREAD

**Issue by wtabata** [opencart/opencart#8272]
./root/upload/storage/vendor/react/promise/?

files is missing!!

**Comment by WebkulOpencart** [comment]
you can follow the below blog to install the OpenCart 3.0.3.6 version

[https://webkul.com/blog/how-to-install-opencart-in-3-0-6-0-version/](https://webkul.com/blog/how-to-install-opencart-in-3-0-6-0-version/)

**Comment by condor2** [comment]
@WebkulOpencart this should be fixed. in the package......and not to close the issue....

At this moment if you run composer update react/promise will not be generated.
As the minimum PHP version is now 7.3, you need to change same in composer.

`"php": ">=7.3.0",`

By changing php version in composer you can't update vendors because of some dependencies and Klarna should be removed to generate.

In the end composer.json shoould be
`{
	"name": "opencart/opencart",
    "type": "project",
    "description": "OpenCart",
    "keywords": ["opencart", "ecommerce", "framework", "opensource"],
    "homepage": "http://www.opencart.com",
    "license": "GPL-3.0+",
    "config": {
        "vendor-dir": "./upload/system/storage/vendor/"
    },
    "require": {
        "cardinity/cardinity-sdk-php": "2.1",
        "braintree/braintree_php" : "5.3.1",
        "scssphp/scssphp": "1.4.0",
        "divido/divido-php": "1.15",
        "php": ">=7.3.0",
	    "twig/twig": "^2.4.8",
        "zoujingli/wechat-php-sdk": ">=1.3.18"
    }
}`
