### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8578]
Latest version v3.0.3.6.

Account has been created via My Account > Register.

Error appear in My Account:
Notice: Trying to access array offset on value of type bool in/catalog/controller/startup/startup.php on line 166

**Comment by straightlight** [comment]
File no longer valid in the master branch for startup.php file. The original codes may have been moved into another file location on the same folder already.

**Comment by straightlight** [comment]
See this PR: https://github.com/opencart/opencart/pull/8439 .

**Comment by WhereJuly** [comment]
@straightlight, @danielkerr Hello colleagues,

First thanks for the great code. After some years with WP and some Magento your code is just a gulp of fresh air.

I believe something is missing in the process of installation the fresh OpenCart 3.0.3.6 with regard to this issue.

I use OC with PHP 7.3 on my local development machine and with PHP 7.4 on my web server. 

Shortly the issue is the OC [master branch `catalog/controller/startup`] (https://github.com/opencart/opencart/tree/master/upload/catalog/controller/startup) folder content does not match the respective folders neither in OC archive source nor in OC downloaded with Composer.

Here are the details:

1. I downloaded (locally) OC 3.0.3.6 via its archive [standard download page](https://www.opencart.com/index.php?route=cms/download). 
2. I as well downloaded it to the other folder with `composer create-project opencart/opencart .` 
3. None of those code bases have `catalog/controller/startup/application.php` file in there which at the same time is presented in the GitHub [master](https://github.com/opencart/opencart/tree/master/upload/catalog/controller/startup) branch.  
4. Both archive source and composer project source the folders  `/upload/catalog/controller/startup` have 8 files each, whereas the [master](https://github.com/opencart/opencart/tree/master/upload/catalog/controller/startup) branch has 12 files.

See attached folders content screenshots.

![oc-archive-startup-folder](https://user-images.githubusercontent.com/20369309/104694884-e9508080-571c-11eb-9331-bbb4d549c697.jpg)
![oc-composer-startup-folder](https://user-images.githubusercontent.com/20369309/104694885-e9e91700-571c-11eb-9997-0d5706ab9cd0.jpg)
![oc-github-master-startup-folder](https://user-images.githubusercontent.com/20369309/104694886-ea81ad80-571c-11eb-814a-a5091b906785.jpg)

The question: where should I get the actual public release of the OC that has all the latest bug fixes and other updates etc. that includes [the issue fix #8439](https://github.com/opencart/opencart/pull/8439) ?

Thanks a lot in advance.
