### ISSUE TITLE
checkout/success should not be accessible without an order id.

### ISSUE THREAD

**Issue by WallaceSociety** [opencart/opencart#8640]
**What version of OpenCart are you reporting this for?**
3.0.3.2+

**Describe the bug**
The checkout/success template should not be visible without a valid order id. i.e This link should not tell me I have placed a successful order: https://demo.opencart.com/index.php?route=checkout/success

**To Reproduce**
1. Go to https://demo.opencart.com/index.php?route=checkout/success
2. See error that no order was actually placed

**Expected behavior**
Ideally it would say something like you do not have access to view this page. Log in if you are looking for order details, but I think rerouting to the home page would be fine too. 

**Simple Solution**
Replace the closing bracket on line 21 of  catalog/controller/checkout/success.php with 

```
}else{
   $this->response->redirect($this->url->link('common/home', 'user_token=' . $this->session->data['user_token'], true));
}
```

**Comment by ADDCreative** [comment]
This is a bad idea as the session may have be lost when returning from a payment provider. Now more common due to changes to the default of the SameSite cookie attribute to Lax. This would leave the customer with no idea if the order was successful.

A good example of this is the PayPal Standard payment module in versions before 3.0.3.6. https://github.com/opencart/opencart/pull/8072

**Comment by WallaceSociety** [comment]
What about testing $_SERVER['HTTP_REFERER'] which should never be empty if they just placed an order correct? Except maybe if they are using a proxy???

**Comment by ADDCreative** [comment]
HTTP_REFERER can't be guaranteed as it may be blocked by the customer for privacy. You also can't control the third-party [Referrer-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy).

Also in your example you test user_token which does not exist in the catalog side.

**Comment by WallaceSociety** [comment]
Your correct. I shouldn't have added the user token however I'm not sure why the 3rd part referrer policy would come into play though; unless of course you are using paypal standard, isn't the site redirected from the redirect url returned by the payment processor controller? Meaning the site would be redirected from your domain and not a 3rd party. 

I also get in some edge cases HTTP_REFERER could be null when they actually did place an order, but adding a second check of the session order_id when it does should give the vast majority of users the expected response. Again paypal standard might be an exception here.

**Comment by ADDCreative** [comment]
There are a few payment modules I have seen that return directly to the success page from a third-party domain, not just PayPal Standard. Probably more in the marketplace.

**Comment by straightlight** [comment]
I do not recommend this approach either. This scenario also suggests to pull the user_token without validating it and without knowing its source of origin. The use of events should rather be used to ensure the pulled information of the proper order ID prior to unset it from the checkout/success.php file.

**Comment by WallaceSociety** [comment]
As I mentioned before I was thinking of the admin when I added the user token. That does not need to be in the url redirect. However I don't see how @straightlight 's approach with an event would solve the issue.  But maybe I am misunderstanding the root issue???

As I understand the problem; the order_id which is our flag for a successful order, is stored in the session data and "some" 3rd party vendors use a return url after a successful payment rather than an internal redirect. Paypal standard being the primary culprit here. In this situation the session data could be lost meaning we no longer have access to the order_id in the checkout success controller. If this is correct I don't see how we would have access to the proper data in a success/before event that would allow us to determine the order_id if the session is missing. 

The only valid solution I have come up with would be that 3rd party vendors using a return url would have to add an order id parameter to the return url.  Something like changing line 37 on pp_standard.php then the success controller could look for that parameter in cases where it is missing from the session data. If it's missing from both it should only leave to scenarios. One the payment controller would need to be updated to include the parameter. Or two; what we are trying to determine, the user is trying to access the success page without a successful order. 

Thoughts on issues with this approach?

**Comment by ADDCreative** [comment]
Each payment module will be different, it would be impractical to add checks in the checkout/success for each one that may return directly.

Is it really a problem that a user could go to the checkout/success page. I don't see how they would end up there unless directed there after a successful order.

**Comment by straightlight** [comment]
@WallaceSociety: You seem to be referring about callback URLs. I understand where you're coming from as I have been having similar discussions with Daniel last year about this issue when originating from third-party providers. However, removing the user_token from the URL while using the internal API of Opencart will not solve the issue either since the redirection still needs to have the user_token inside the URL with the last validated user token value while the admin user is still logged in. Otherwise, the admin login validation process will fail when comparing the user tokens.

As for the internal API, the problematic is the fact that the API session IDs are being deleted progressively whenever a new call with the internal APIs needs to be instantiated regardless if a stored session ID is in-place on the database and will also prevent external APIs to revalidate the internal API's session IDs due to these restrictions whenever it's about callbacks and external APIs.

I do have a stored project on my namespace for external APIs. However, I didn't tested it with callbacks yet: https://github.com/straightlight/opencart_contributions/tree/master/upload/api . However, take note that this aside project, I have worked with engwalid last year, that it provides no promises for being integrated into the master branch. It is only an alternative solution while the OC registry object can still be used as one Engine with the external APIs. This should definitely help for external APIs nevertheless. Hope this helps until a definite solution kicks in.

**Comment by WallaceSociety** [comment]
@straightlight thank you for the information and the project link. I will check it out. 

@ADDCreative It is a problem for any conversion tracking script that hooks onto the success page and there are a number of ways a customer could be directed there. Bookmarks, tab open on phone for days that keeps refreshing, etc.

**Comment by ADDCreative** [comment]
What I do is only include any tracking code if there is a valid order_id in the session.

**Comment by straightlight** [comment]
That may not work with callback URLs since it still depends on the service providers being used. The problem being described above is more advanced.

**Comment by danielkerr** [comment]
@ADDCreative  what should it be instead of lax? i haven't finished the cookie system. im still going to check what the best option is.

**Comment by danielkerr** [comment]
yes it should be viewable without an order. this is just your personal opinion.  not an issue

**Comment by WallaceSociety** [comment]
@danielkerr I'm not sure I agree with that. Yes it is my opinion that I don't ever think it is correct to give the user misleading information, but I believe the issue is that certain reporting scripts give false positives because the page can be viewed without placing an order.

**Comment by danielkerr** [comment]
So this is u complaining and wasting my time because u have a script given u false results. Why don't u use the event system and check if the order has a transaction I'd. This stuff is not hard to code around but instead because of ur lack of skill I have to waste my time closing non issues

**Comment by WallaceSociety** [comment]
@danielkerr I already did code around it however I still think it IS an issue. Probably why it's not possible in any other shopping cart system. I apologize if you think addressing the concerns of people using your software is a waste of your time.

**Comment by danielkerr** [comment]
do u have an issue with being told u are wrong by some one with more experience then u. 

use your fucking brain! accept what or just fuck off!! topic locked!
