### ISSUE TITLE
[Master Branch and 3.x] - Order Edit product quantity is wrong calculated

### ISSUE THREAD

**Issue by pemaier** [opencart/opencart#8869]
**What version of OpenCart are you reporting this for?**
Master Branch] and 3.0.3.x

**Describe the bug**
Open an order to edit the quantity of ordered products. 
This is not possible if the quantity of the edited product is not complete on stock. 
The calculation doesn't consider the amount of already removed stock amount within the orders currently changed product.
e.g. 
- Shop hat 12 Nikon D300 on stock 
- Customer already ordered 10 Nikon D300 
- sales manager is getting the information that only 9 on stock
- sales manager open the order for edit 
- go to the product an changes 10 pcs. to 9 pcs.
- then he likes to save but he get the information that the required amount of stock is not available. (Current stock is 2 pcs.)

What section does it affect?
Change of an order is not possible.

**Expected behavior**
It is expected that the shop know that 9 pcs. is less than 10 and after the saving of the corrected order the not required amount of pcs. is added to the stock amount. After the change it is expected to have 3 pcs. on stock.

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server? WS
 - Operating system Linux
 - PHP version 7.3
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable] Firefox 
 - Version [e.g. 22] 83.0.3

**Comment by schiggi** [comment]
That issue was already present in OC2. The problem itself originates from the fact, that generally speaking when you edit an order, you first invalidate the old order (thus putting back all old products back to stock) and create a new order (removing the new amount of products from stock). This happens in OC as well when you click the save button at the end of the order edit process. See related function for the [API](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/order.php#L357) and [model](https://github.com/opencart/opencart/blob/master/upload/catalog/model/checkout/order.php#L48).

However, in the case of OC during the order edit API calls, it doesn't void/cancel the order first, which is correct as sombody else could buy the released stock. But that creates the problem of rechecking all requirements during order recreation on order edit without taking into account that we have the required stock already at hand. Causing all edits to fail because of no available stock where **product qty is not at least double the amount** of ordered stock for the editing order.

Our workaround was to edit [system/cart/cart.php](https://github.com/opencart/opencart/blob/master/upload/system/library/cart/cart.php) and temporary add the editing qtys to the session calls. See omod below.

`	
	
	<file path="admin/view/template/sale/order_form.tpl">
		<operation>
			<ignoreif><![CDATA[url: '<?php echo $catalog; ?>index.php?route=api/cart/products&token=' + token + '&store_id=' + $('select[name=\'store_id\'] option:selected').val() + '&order_id=' + $('input[name=\'order_id\']').val(),]]></ignoreif>
			<search trim="true"><![CDATA[url: '<?php echo $catalog; ?>index.php?route=api/cart/products&token=' + token + '&store_id=' + $('select[name=\'store_id\'] option:selected').val(),]]></search>
			<add position="replace"><![CDATA[		url: '<?php echo $catalog; ?>index.php?route=api/cart/products&token=' + token + '&store_id=' + $('select[name=\'store_id\'] option:selected').val() + '&order_id=' + $('input[name=\'order_id\']').val(),]]></add>
		</operation>
	</file>

	<file path="system/library/cart/cart.php">
		<operation>
			<search trim="true"><![CDATA[
				if (!$this->data) {
			]]></search>
			<add position="after"><![CDATA[
			// If order id is transferred with get request, we are probably in admin order edit mode. If Api id exists, then we are in the backend admin.
			if ( !empty($_GET['order_id']) && isset($this->session->data['api_id']) ) {
				// Getting all ordered products for this order
				$ordered_products_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "order_product WHERE order_id = '" . (int)$_GET['order_id'] . "'");
				$ordered_products = array();
				foreach ($ordered_products_query->rows as $ordered_product) {
					$ordered_products[$ordered_product['product_id']] = $ordered_product;
				}
			}
			]]></add>
		</operation>
		<operation>
			<search trim="true"><![CDATA[
				if (!$product_query->row['quantity'] || ($product_query->row['quantity'] < $cart['quantity'])) {
			]]></search>
			<add position="before"><![CDATA[
					// If order id is transferred with get request, we are probably in admin order edit mode and want to retrieve product infos
					if ( isset($ordered_products[$cart['product_id']]) && !empty($this->config->get('config_fix_edit_order_product_qty')) && !empty($_GET['order_id']) ) {
						// add qty from cart to stock from database in order to see real stock qty during order edit
						$product_query->row['quantity'] = $product_query->row['quantity'] + $ordered_products[$cart['product_id']]['quantity'];
					}
			]]></add>
		</operation>	
	</file>`

**Comment by pemaier** [comment]
Thank you. 
I matched the solution for 3.x and it is working so far that it's possible to change the order. But the stock is not getting updated with the new stock information after the order was updated. This part is missing.


	<file path="admin/view/template/sale/order_form.tpl">
	<operation>
		<ignoreif><![CDATA[index.php?route=api/cart/products&api_token={{ api_token }}&store_id=' + $('select[name=\'store_id\'] option:selected').val() + '&order_id=' + $('input[name=\'order_id\']').val(),]]></ignoreif>
		<search><![CDATA[url: '{{ catalog }}index.php?route=api/cart/products&api_token={{ api_token }}&store_id=' + $('select[name=\'store_id\'] option:selected').val(),]]></search>
		<add position="replace"><![CDATA[url: '{{ catalog }}index.php?route=api/cart/products&api_token={{ api_token }}&store_id=' + $('select[name=\'store_id\'] option:selected').val() + '&order_id=' + $('input[name=\'order_id\']').val(),]]></add>
	</operation>
	</file>

	<file path="system/library/cart/cart.php">
	<operation>
		<search><![CDATA[$product_data = array();]]></search>
		<add position="after"><![CDATA[
		// If order id is transferred with get request, we are probably in admin order edit mode. If Api id exists, then we are in the backend admin.
		if ( !empty($_GET['order_id']) && isset($this->session->data['api_id']) ) {
			// Getting all ordered products for this order
			$ordered_products_query = $this->db->query("SELECT * FROM " . DB_PREFIX . "order_product WHERE order_id = '" . (int)$_GET['order_id'] . "'");
			$ordered_products = array();
			foreach ($ordered_products_query->rows as $ordered_product) {
				$ordered_products[$ordered_product['product_id']] = $ordered_product;
			}
		}
		]]></add>
	</operation>
	<operation>
		<search><![CDATA[if (!$product_query->row['quantity'] || ($product_query->row['quantity'] < $cart['quantity'])) {]]></search>
		<add position="before"><![CDATA[
				// If order id is transferred with get request, we are probably in admin order edit mode and want to retrieve product infos
				if ( isset($ordered_products[$cart['product_id']]) && !empty($this->config->get('config_fix_edit_order_product_qty')) && !empty($_GET['order_id']) ) {
					// add qty from cart to stock from database in order to see real stock qty during order edit
					$product_query->row['quantity'] = $product_query->row['quantity'] + $ordered_products[$cart['product_id']]['quantity'];
				}
		]]></add>
	</operation>
	</file>

**Comment by straightlight** [comment]
Not focusing on the idea above, these instances: ```$_GET['order_id']``` should be: ```$this->request->get['order_id']```

As for the SQL query, it should be:

```$ordered_products_query = $this->db->query("SELECT * FROM `" . DB_PREFIX . "order_product` WHERE `order_id` = '" . (int)$this->request->get['order_id'] . "'");```

as per the master branch.

**Comment by schiggi** [comment]
Oh, reallly? Maybe the approach changed in OC3? From the first look, I do not see a big difference. Basically, the ocmod just adds the edited product quantities to the [stock check](https://github.com/opencart/opencart/blob/master/upload/system/library/cart/cart.php#L226) here so it passes the [api stock check](https://github.com/opencart/opencart/blob/master/upload/catalog/controller/api/order.php#L437). The real quantities are added in [this line](https://github.com/opencart/opencart/blob/master/upload/system/library/cart/cart.php#L260) and should not be affected.

$_GET['order_id'] and $this->request->get['order_id'] are identical if you look at this file ([library/request.php](https://github.com/opencart/opencart/blob/master/upload/system/library/request.php#L25)). But by framework definition, indeed, we should follow it. But I remember there was a reason why we haven't used the helper function.

**Comment by straightlight** [comment]
What helper function?

**Comment by schiggi** [comment]
> What helper function?

[system/library/request.php](https://github.com/opencart/opencart/blob/master/upload/system/library/request.php#L25) - I called it a helper function. :)

**Comment by straightlight** [comment]
Then, the terminology you're using would be the wrong one. The helper functions are located in the system/helper folder, not the system/library. The folder names are identified as is. If you are going to suggest core changes in this repository, I would suggest to get familiarized with the terminologies since Opencart is based as a CMS platform.

**Comment by schiggi** [comment]
Fair enough - The request library. But I am not suggesting to change the request library but to take a closer look on how the edit order function works within Opencart.

**Comment by danijelGombac** [comment]
The function 

`// Void the order first
$this->addHistory($order_id, 0);` 

in upload/catalog/model/checkout/order.php should be called before the order edit page open and not at the end before save the order.

**Comment by schiggi** [comment]
> The function
> 
> `// Void the order first $this->addHistory($order_id, 0);`
> 
> in upload/catalog/model/checkout/order.php should be called before the order edit page open and not at the end before save the order.

The products from the order would be put back to stock and allow others/customers to order it. Sometimes the edit of an order takes a while.

**Comment by danijelGombac** [comment]
@schiggi Yes, that can happen. In your solution is missing stock for options. There is also problems with order totals.

**Comment by schiggi** [comment]
Regarding stock options: That is true. Haven't taken that into account. Maybe somebody can add this?

@danijelGombac What problems have you encountered with the order totals?

**Comment by straightlight** [comment]
It's not a function, it's a method.

The product options should really be handled on its own page like the order > sales > add and view page. There are so many factors product options could have and now that OC uses HTML tables along with DIVs, I think it would be better suited to handle the stocks that way as it would optimize the queries with the pagination controller and the library to maintain those product options page-by-page instead of having to handle all of them by products per individual forms. This would also prevent the need for the users having to play with the php.ini or .user.ini file all the time but also to ease management with product options by using a filter when needed, since there are also a great mount of other pages where filters are being used as product options can become so large in an easy paste.
