### ISSUE TITLE
WebP

### ISSUE THREAD

**Issue by faca5** [opencart/opencart#8963]
Hello.

Resized - cache Images should be saved in modern image format (.webp). 
GD already supported it. Save space and increase speed.

Current resized/cache images go throw GD and it use original format (png, jpg, gif...).

**Comment by stalker780** [comment]
Webp support wad added to Safari this summer.
It works only on latest Macos versions.

There are stil millions of devices with old Apple OSes, which don't support this format.

All other browsers support webp for many years.

Though webp is a promissing image format, and Google search recommends to use it, it will take several years to get full support.

I think shop owners should decide which format to use on their own.

So images must not be resized and stored only in webp format.

Best is to add webp support, so it can be used and assigned in admin area on a par with old formats png/jpg/gif.
So if store owner decides to upload and use webp, he will not meet any obstacles.

I will prepare a pull request, hope Daniel will find it useful.

**Comment by stalker780** [comment]
https://github.com/opencart/opencart/pull/8966

**Comment by Hkr32** [comment]
https://github.com/opencart/opencart/pull/8880

**Comment by stalker780** [comment]
@Hkr32 
> #8880

You need to check your library/image.php
It lacks webp support in __construct function. Also it removes webp transparency on resize.
Don't think your solution will work without errors.

But your solution adds SVG support. Which may also be useful for OpenCart users.

Anyway, I hope Daniel will not be too conservative and will consider allowing users to use modern image formats. 
Especially since it requires minimal core changes.

**Comment by Hkr32** [comment]
If I understood the essence of the error correctly, then I corrected it. Thank you.

**Comment by danielkerr** [comment]
needs --with-webp-dir=/usr  this depends where its being complied
