### ISSUE TITLE
Bug: MySQL 8+

### ISSUE THREAD

**Issue by HaftasArden** [opencart/opencart#8976]
# Error 1

When installing OC 4.0.0.0_b with MySQL 8, I generated the error "Error: BLOB, TEXT, GEOMETRY or JSON column 'body' can't have a default value"
The ([documentation](https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html)) says:

 > The BLOB, TEXT, GEOMETRY, and JSON data types can be assigned a default value only if the value is written as an expression, even if the expression value is a literal.

**Solution**: Change line 22, in file *upload/install/model/install.php* by

```php
$sql .= "  `" . $field['name'] . "` " . $field['type'] . (!empty($field['not_null']) ? " NOT NULL" : "") . (isset($field['default']) ? " DEFAULT ('" . $db->escape($field['default']) . "')" : "") . (!empty($field['auto_increment']) ? " AUTO_INCREMENT" : "") . ",\n";
```
# Error 2

Errors also occur when updating product data.

Ex:
 - The "X" field cannot be null ([code](https://github.com/opencart/opencart/blob/master/upload/system/helper/db_schema.php#L4536))
 - The code does not add a default value when editing or adding a product, causing an error. ([code](https://github.com/opencart/opencart/blob/master/upload/admin/model/catalog/product.php#L248))

# Solution for both cases

**Solution**: Fix all SQL

**Alternative solution**: Use [NO_ENGINE_SUBSTITUTION](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_engine_substitution) - Not recommendation

```sql
SET GLOBAL sql_mode = 'NO_ENGINE_SUBSTITUTION';
```

**Comment by danielkerr** [comment]
linked issues

https://github.com/opencart/opencart/issues/8944
https://github.com/opencart/opencart/issues/8921

**Comment by danielkerr** [comment]
im going to alter the settings so strict mode is off.

**Comment by siarheipashkevich** [comment]
Hi @danielkerr It's still reproduced for fresh installation. Could you please assist how to fix this issue and install fresh OC?

**Comment by mhcwebdesign** [comment]
The issue with zero date is a separate one, and trying use a non-strict MySQL mode for a quick workaround won't be a longterm solution, especially not for MySQL8. See e.g. this article: https://lefred.be/content/mysql-8-0-and-wrong-dates/

**Comment by mhcwebdesign** [comment]
A decision needs to be made of whether to attempt to use the non-strict MySQL mode for a quick workaround which will most likely cause issues with MySQL 8. Or we can address these issues and change the OpenCart code at the appropriate places in order to support the new MySQL default strict mode. I have pretty much a working OC 4.0.0.0.b for the latter, one I have cleaned some outstanding SQL queries involving dates, and using an updated db_schema, as explained in #9004, #9006, and #8824

**Comment by danielkerr** [comment]
Comment out the report mode line in the mysqli adator

**Comment by danielkerr** [comment]
sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION

**Comment by danielkerr** [comment]
does the last commit work?

**Comment by mhcwebdesign** [comment]
Your latest **system/library/db/mysqli.php** doesn't work, it still causes the usual errors because of the MySQL server's using the strict mode. We are using the MySQL Server version: 5.7.32-0ubuntu0.16.04.1 - (Ubuntu).

I then added your suggested sql_mode to the constructor in **system/library/db/mysqli.php**:

```
	public function __construct($hostname, $username, $password, $database, $port = '3306') {
		$connection = @new \MySQLi($hostname, $username, $password, $database, $port);

		if (!$connection->connect_error) {
			$this->connection = $connection;

			$this->connection->report_mode = MYSQLI_REPORT_STRICT;

			$this->connection->set_charset('utf8');
			
			$this->connection->query("SET SESSION sql_mode = 'NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION';");

		} else {
			throw new \Exception('Error: Could not make a database link using ' . $username . '@' . $hostname . '!');
		}
	}

```

And tested it again, that seems to work fine.
I don't have a MySQL8 on hand, maybe somebody can test it for this newer version?

**Comment by danielkerr** [comment]
great!!
