### ISSUE TITLE
[master branchin php 8.0]Warning: Trying to access array offset on value of type null in /public_html/system/storage/vendor/scssphp/scssphp/src/Compiler.php on line 5013

### ISSUE THREAD

**Issue by chongshengdz** [opencart/opencart#8993]
[master branch in php 8.0] Warning: Trying to access array offset on value of type null in /public_html/system/storage/vendor/scssphp/scssphp/src/Compiler.php on line 5013
 when visiting admin=>navigation=>system=>settings, it gives the above error,

**Comment by chongshengdz** [comment]
filemanger also not working, it won't pop-up when editting product.
error message "TypeError: iconv_substr(): Argument #3 ($length) must be of type ?int, string given in /system/helper/utf8.php on line 51"

**Comment by danielkerr** [comment]
ok these are fixable. there is a 1.4 released of scssphp. not sure if it fixes anything.

**Comment by evaland999** [comment]
Dear Mr. Daneil,
I hope you see the contents below,before I public it.
If you can,I hope you can help me



https://webkul.com/
it's very senior script developer in opencart.com since 2012
and me,
As a user of opencart,I have already used OC almost 10 years from OC2.0.2.
I never bought any modules or extensions from webkul
Honestly their modules is very expensive.
So when I found other script developer is much cheaper than webkul.com,I bought others not webkul.com's
Such as isenslab,I bought many modules from them.
Price more cheap and module easy installed and used.

Recently I built a whole new OC 3.0.3.7.
As everybody known,A Good Opencart shopping website need a good cache module.
I think don't need to explain why.

Although OC have it's built cache system,But it is very simple and not well performance.

So I must looking for a good cache system to use on my New OC 3.0.3.7.

At first,I hope to choice isenlab's Nitro cache module,But it's Not updated anymore.

So I found webkul.com's Cache system module.
I searched and learning on it's demo page many days,Then I decided to buy and use it on my website.

But it's Nightmare started.

First:
From webkul.com I Downloaded original file after bought,But it's a bug version.
After installed to my test website,I got blank page in front end page.
At first I thought it's my OC's problem,Maybe some modules  Conflict with each other.
So I installed a Fresh OC to make sure,And confirm it's a bug version.

So of course I ask webkul.com's support team to help,They checked and checked them reported me the original file have bug in it.

It already wasted me more than 30 hours.
I already expressed my strong dissatisfaction at that time

And then Webkul  installed thie cache module to my site ,But still can't run.
They checked and checked,Then found more bugs in this cache module.
And They fixed and fixed again and again.

after waiting more than 60 hours,I thought finally this cache system module can work well.

But I was wrong,This time,webkul's support said "I can't install extra modules"

Then They gave me a conclusion.
I can't install these extra modules,if I insist,Cache system can't have full function to run.

I can't believe to Hear this.

I believe every OC's user very clear to have extra modules to install and used in OC will make OC better.
Because Fresh OC have very few functions built in it.
So after installed a fresh OC ,We must have to buy necessary modules to use.
I can't see any strange point in it.

But today Webkul.com 's support told me,
IF I want their cache can full work,I can't use my installed modules.
PS:I must pointed out,in my product and category page,I have only install 3-5 extra modules.
and these module don't modify any core codes,All bought from opencart's market

I felt very disappointed and ask webkul refund me if they really can't fix the issue ,Just refund me.
PS: I thought they "are don't"  "not can't"  .

And then their skype service and Ticket sevice not reply me anymore.

I have no choice only sent the Argue file to PayPal.

My conclusion is
Webkul.com is a big Website solution company,
And Webkul helped opencart to published OC3.0.3.7
It made The owner of Opencart.com Mr.Daniel recommend people.
https://www.youtube.com/watch?v=a7prc2SGyRY

This is the only reason that I decide buy their expensive module.
Because I believe webkul.com's module must be very good,And must have a professional support to support me after bought.

But truth is I bought a bug's module and got a suck support.

I wrote down my story to share everyone to see.

I don't know if Can I get a refund and must wait how long until paypal  Judge me right.

Hope no one will get the same nightmare.

**Comment by evaland999** [comment]
> 
> 
> ok these are fixable. there is a 1.4 release of scssphp. not sure if it fixes anything.

Dear Mr. Daneil
Do you receive my message few hours ago.
if you ok,
I will public it

**Comment by mhcwebdesign** [comment]
You should get in touch with OpenCart's support on this: https://www.opencart.com/index.php?route=support/contact
Github is for development and reporting/fixing bugs of the core OpenCart only.
