### ISSUE TITLE
Can't disable the theme cache?

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9108]
![image](https://user-images.githubusercontent.com/12296392/104227103-eb36ed00-5459-11eb-9024-ec4523a87818.png)

**Comment by danielkerr** [comment]
it has to create a compiled files thyat are stored in the cache folder.

**Comment by Hkr32** [comment]
@danielkerr, so now for development I can't disable the cache? Do I have to go around and press the refresh cache button every time?

**Comment by stalker780** [comment]
I had no issues with theme cache in OC31-OC4 in last several months.
Looks like it refreshes automatically now, when template is changed. 
Also it works very fast. So I don't think this option is needed anymore.

**Comment by Hkr32** [comment]
Why I asked, because I tried to change the data and they did not update until I went in and pressed the refresh cache button with my hands(

**Comment by iury89** [comment]
After installing version 4 of opencart I can't disable the cache, after a few weeks the storage/cache folder accumulates "9 GIGAS", my server has 10 GB and I have to manually delete it via ftp because the server is overloaded and the site is down, I need to disable this, I don't care if the site slows down, but I want to have the right to choose which was taken away in this new version.

**Comment by danielkerr** [comment]
then u problably have a lot of products

**Comment by iury89** [comment]
Unfortunately the number of products is not reported, the store only has: 133 products, there is an error in the code that is generating thousands of theme cache files, and I'm coming back here after the site hit 10 GIGAS again and left the server out of service. AR, and I am forced to manually clear the cache, I believe that there is a serious error in the code of this new version of oc4 that needs to be resolved because I have been using it for years and this has never happened, and we need to have the power to disable the cache as it was in the past. previous versions, I hope you will consider fixing this in future versions.
