### ISSUE TITLE
Improve the CLS score

### ISSUE THREAD

**Issue by WebkulOpencart** [opencart/opencart#9117]
**What version of OpenCart are you reporting this for?**
master and 3.x.x.x
**Describe the bug**
We can develop the functionality to add the height and width inside the img tag so the CLS score can be decreased.

I search multiple blogs for the same and check by adding the height width in img tag and without the height width attribute you can check the difference the CLS score will be decreased from 0.25 to 0.1 or 0.
You can check the same on the google insights

[https://web.dev/cls/](https://web.dev/cls/)

**Comment by chulcha** [comment]
Yes!  but the problem is that the template is practically not subject to external changes.
Therefore, the decision remains with the third party functionality.

As an example, refusing from $this->load->controller(product/product_thumb, $product)

I need to have several types of images (for responsive images), but I can't get a raw path  to a picture through $product_data

**Comment by danielkerr** [comment]
wasting my time
