### ISSUE TITLE
Roadmap or project

### ISSUE THREAD

**Issue by Hkr32** [opencart/opencart#9541]
It is worth doing either a project for a github or a roadmap. I would like to understand what is being done and what is planned to be done. When to wait for the first beta version.

**Comment by IP-CAM** [comment]
Better just be reasonable, and don't expect someone around OC, to even develop a Roadmap, just to make the Project look like something real 'commercial'. OC is only a 'small Business' type Enterprise, and they really have better things to do, than wasting their time with such. And when it comes to Beta-Versions, every one of the latest Releases is a Beta-Version, waiting, to be tested in real, by those, who can't wait, to find latest Misses and faults.

**Comment by Hkr32** [comment]
> Better just be reasonable, and don't expect someone around OC, to even develop a Roadmap, just to make the Project look like something real 'commercial'

Perhaps everything is there, just not publicly.



> and they really have better things to do, than wasting their time with such

That's where you get the idea that everything is exactly like that? How can you know that? If you think so, you have no place in development...
The path of development of opencart is important not only for ordinary users, but also for developers, as well as contributors, so as not to do unnecessary work and offer unnecessary PRs

**Comment by IP-CAM** [comment]
Well, I have been around Opencart for quite some years, and with 12'500+ OC Forum Postings, I belong to the top scorers.  So, better accept, what I told you about it, and don't dream about things, who just don't exist ...

**Comment by Hkr32** [comment]
> But you're right, I am not a Developer

After this confirmation, the rest may not be read...
We are here to improve the opencart, and not to say that all this is impossible and impracticable.

**Comment by chulcha** [comment]
How long have you waited for version 3?
Then 3.1
And where is she?

Now we are waiting for version 4.
And search for errors and the like.
What do we have as a result?
php 8 and obscurity.
Strong typing and more.
But the global problem with code modification is not resolved
Where is Sql Bidder? And will he be?
Suggestions for improvement are not accepted or discussed, and some contributors are pretending to be unknown. 

And the phrases from Daniel - wait in April, I'll do it every year

**Comment by Hkr32** [comment]
Because if there was a plan, then everyone would see it and it would be possible to delegate some of the tasks to contributors, and then just check and make changes if they are required. And you can write to one person for several years and in the end you never write anything (

**Comment by IP-CAM** [comment]
Better just accept, that Opencart always has been, and will be, a One-Man Show, like it or not. And everybody is free, to either take it, as it comes, or then, go someplace else ...
It's just the way, how OC works, like it or not.

**Comment by chulcha** [comment]
Maybe for one project, you are right. Installed and forgotten.
But for mass projects, including extension modules, there must be a single central kernel system.

**Comment by stalker780** [comment]
> Better just accept, that Opencart always has been, and will be, a One-Man Show, like it or not. 

Alas, but that's true. 
Seems Daniel have no plans for development team. OpenCart is more like his own playground sandbox.

Your project plans are still your plans.

Though project have grown into a rougher big commercial solution it will always stay at this level. Just because it's enough for Daniel.

**Comment by SaifAlSubhi** [comment]
I have noticed that there are contributors and collaborators who had several valid pull requests which need review and verifications; yet pending.
The project plan and roadmap is essential. I think what is missing is assignments who and what.

**Comment by IP-CAM** [comment]
Well, many things about Opencart could be done in different ways, Bulkloads of Code and Wisdom Contributors have been trying hard, in one or the other way, during all those Years. But the Chief of OC Commend ist relatively 'resistent', a rather typical british habit, when it comes to 'follow' someone else's Advise. It would also most likely require another Employee or two, to achieve, what would make OC to a 'real' professional Bases, when it comes to 'Interaction' and 'Communication', with all those, trying to convince OC, to make it's Software as perfect, as it eventually could be. 

But then, OC would possibly no longer just come for free. It's therefore of absolutely no use, to complain about the Situation, as it exists, Professionals can always fix, what's broken, if one depends on a working Software. And the Rest, who cares about them, if they have no Money, to pay for Support,  the Result will, at best, only be 'less' Competition for others. :) 

Still, everybody is free, to actively participate at the github.com/opencart Developer Site, if one cares, to assist, by making OC better than ever before ...

**Comment by stalker780** [comment]
There are dozens of developers, who want to share and contribute.
But after several cases of ignorance they just leave this project.
I can see this for last 10 years.

**Comment by stalker780** [comment]
I don't know... Perhapse Daniel needs some vacancy proposals... :)
I am ready to spend 2-3-4 hours a day to develop OpenCart, to monitor pull requests, to discuss developing strategy... To contribute own ideas, after discussion with him...

Who else is ready to work some time for free or minimal reward?

Hope Daniel reads this eventually.

**Comment by IP-CAM** [comment]
>Hope Daniel reads this eventually ....

Most likely not, if he's not a Masochist, and sure not interested on Discussions on/about Developing Strategies, as I assume. And if one likes to participate, OC is an Open Place, to exchange free Wisdom, up to entire 'privately enhanced' OC Versions, as well as free and paid Opencart Extensions of all kinds. 

But that's about all, one can expect. They sure don't need new advisors, they only frequently need new Versions, to keep their share on paid/sold Extensions on the flow ... :) :)

**Comment by Hkr32** [comment]
> I don't know... Perhapse Daniel needs some vacancy proposals... :)
> 
> I am ready to spend 2-3-4 hours a day to develop OpenCart, to monitor pull requests, to discuss developing strategy... To contribute own ideas, after discussion with him...
> 
> 
> 
> Who else is ready to work some time for free or minimal reward?
> 
> 
> 
> Hope Daniel reads this eventually.

Everyone has free time. If everything were transparent and heard the developers, the tasks could be discussed and divided. This would greatly speed up development!

**Comment by IP-CAM** [comment]
You seem to forget, that Opencart only serves 'commercial' Requirements. The vast majority of OC-Users would never share Knowledge with others, affraid, to eventually enable them, to even get in direct Competition with themselfs. And Opencart already exists for a good while, meaning, that the so-called 'HAM-SPIRIT' is also a thing out of the past already, for most, beeing around Opencart for a while. 

So, better don't expect others, to share their OC Knowledge, just for the plain fun of it, They are around, to hopefully generate some Income out of it, but sure not, to please others, or then help Daniel, to keep alive and well. With a very few Exeptions at least. Some nice Fellows are still around, to frequently assist others for free. But beeing confronted with basically ever the same again, just i a slightly different form, in addition to the Fact, that uncounted Numbers of OC Users are using 'stolen' paid Code, makes it hard, not to loose the Spirit, after a While. I've seen them come and go, in vast Numbers, and it even seems, that OC is slightly loosing ground itself, due to the steady shrinking amount of Wisdom Contributors, tired of, trying to be part of it. 

It's comparable with anything else, after a While, and as more ADULT something get's, the less Spirit is part of it. In addition to the known Fact, that OC Hongkong does not care much about others Feelings and/or Ideas. As I mentioned already, it's a One Man Project, and one Man decides, and if someone does not like that way of doing things, nobody will care about.

So, better don't take it personal, it's just the way, how OC works ... :) :)

**Comment by haxcop** [comment]
As open source as it's it also generates profits, Magento does it for free too at least for a good while now look at then...
Spotify less time on the market better deal...
Perhaps the best Idea it's to fork the project and move along with a new development team as others have done so far and even created their own version and named differently
Just an Idea 
Don't expect from others to move forward

**Comment by mezzat11** [comment]
Any reply @danielkerr  ? We hope to open the door for participation to reach the project to the best, Also have a organized and clear roadmap for the project

**Comment by Hkr32** [comment]
Excellent! https://github.com/opencart/opencart/projects/5

**Comment by danielkerr** [comment]
Yes thx

**Comment by danielkerr** [comment]
It's the road maps for future releases.

**Comment by danielkerr** [comment]
closing this. p future features wil be added here:

https://github.com/opencart/opencart/projects/6
