### ISSUE TITLE
Twig files not updating in 3.0.3.7 front end via upload

### ISSUE THREAD

**Issue by Khaleel** [opencart/opencart#9621]
**What version of OpenCart are you reporting this for?**
3.0.3.7
**Describe the bug**
I am unable to see Twig changes in the default template. Example header.twig, account.twig. I can see them via the admin UI updates but I am not wishing to develop by copy and paste code into a Web UI box. I need the ability to see changes from SFTP on my twig files directly on the server. Old tutorials existed to remove boolean true in twig but with 3.0.3.7 those twig files in system have been updated.

**To Reproduce**
1. Go to '...' SFTP and client coder like Sublime text and edit the direct twig file
4. Cannot see changes on the opencart website

**Expected behavior**
The website should show my changes

**Comment by jpneey** [comment]
@Khaleel after editing your twig files via ftp, go to admin dashboard, theme editor, then select the twig file you just updated, then click reset, this will show your changes from ftp, then hit save

**Comment by Khaleel** [comment]
Hi John. Does this need to be done every single time? Or will resetting the file once then automatically work from then on

Caching Sass and Caching Templates is disabled from the cog btw

Thanks for your comments

**Comment by jpneey** [comment]
@Khaleel unable to see Twig changes in the default template via ftp usually happens when you have edited the twig files **before** using the **opencart dashboard**  so once you've reset it, changes should appear without resetting it again. However, I suggest that resetting it from the dashboard is better just to make sure that your changes are being served rather than the caches

**Comment by prabhatkumaroc082** [comment]
Please discuss and report on OC forum
