### ISSUE TITLE
Summernote localisation js file not found

### ISSUE THREAD

**Issue by Elryndel** [opencart/opencart#9635]
**What version of OpenCart are you reporting this for?**
3.0.3.7 - updated from GIT

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

The summernote not found the localisation js file because the script generate wrong name for it, like:

/admin/view/javascript/summernote/lang/summernote-hu_HU.UTF-8,hu_HU,hu-hu,hungarian-HU_HU.UTF-8,HU_HU,HU-HU,HUNGARIAN.min.js?_=1619789745261

The file is avalible with this link:
/admin/view/javascript/summernote/lang/summernote-hu_HU.min.js

The script runs to 404 error.

![Screenshot 2021-04-30 14 10 33](https://user-images.githubusercontent.com/79720742/116702983-05c1b180-a9ca-11eb-93c4-4996ea3ce310.png)

**Comment by osworx** [comment]
Well that's clear because of that: **hu_HU.UTF-8,hu_HU,hu-hu,hungarian-HU_HU.UTF-8,HU_HU,HU-HU,HUNGARIAN**
You should check the **Hungarian language file** and the correct value for it inside.

**Comment by Elryndel** [comment]
Well, if I change the localisation code in admin site to simple hu_HU it's still worng. In this case it's looking for summernote-hu_HU-HU_HU.min.js


the hu-hu.php file values are:

$_['code']                          = 'hu';
$_['summernote']              = 'hu';
$_['datepicker']                 = 'hu';

**Comment by osworx** [comment]
> 
> 
> Well, if I change the localisation code in admin site to simple hu_HU it's still worng. In this case it's looking for summernote-hu_HU-HU_HU.min.js
> 
> the hu-hu.php file values are:
> 
> $_['code'] = 'hu'; $_['summernote'] = 'hu';
> $_['datepicker'] = 'hu';

All wrong!
Should be **hu-HU**

Beside of this: this is NOT a bug of OpenCart, it's a bug in your translation file - therefore it should be not reported here, better use the OpenCart Forum for such!

**Comment by Elryndel** [comment]
Okay man.. if "it's NOT an opencart bug" as you say, explain me please, how it's work. Here is some screenshot from the actual settings:

Here is the Admin site/System/Localisation/Language/Hungarian menu item settings, you can see the localisation code is hu-HU.
![admin-site](https://user-images.githubusercontent.com/79720742/116823297-f0908280-ab83-11eb-8766-6572cfc25050.png)


Here you can see the original en-gb.php file from the admin language/en-gb folder, there is 2 localisation entry in the file (code and datepicker):
![eng-file](https://user-images.githubusercontent.com/79720742/116823354-541ab000-ab84-11eb-83d6-84c408ed96cd.png)


Here is the hungarian summernote filename in FTP and the localisation entrys in the language/hu-hu/hu-hu.php file (code, summernote and datepicker):
![hungarian-filenames](https://user-images.githubusercontent.com/79720742/116823377-77455f80-ab84-11eb-8cce-e38e60be499d.png)


And here is the result:
![result](https://user-images.githubusercontent.com/79720742/116823389-87f5d580-ab84-11eb-95b8-5b9d90cec86f.png)

I tested it without the summernote entry, but it's not helped, the result is the same. So.. where is the problem with the translate file?

**Comment by osworx** [comment]
Okay man .. it's not an OpenCart bug!
First of all, I don't know which version you are using - as it seems not an official one.
Because the latest official release (3.0.3.7) does NOT load minified javascript files.
Those minified files are added one month ago - after the release of 3.0.3.7 - to the current repo.

And that means, you are using the .. what?

Second, in the official release the summernote language files are called inside the **opencart.js**:
`$('head').append('<script type="text/javascript" src="view/javascript/summernote/lang/summernote-' + $(this).attr('data-lang') + '.js"></script>');`

No call for minified files.

Third: that also means, you are using the inoffical file from the maintance (not published yet) release from here:
https://github.com/opencart/opencart/blob/e1b118375c1fa982c4a3a0fc6b2f44fb379fdd57/upload/admin/view/javascript/summernote/opencart.js#L7

And as it seems, there is the bug - thank @webkul-dilip you made this pull.

So don't blame me or OpenCart.
As far as I can see, there are 2 bugs: you and webkul.

**Comment by Elryndel** [comment]
My version is in the 2nd row in my first article, 3.0.3.7 + every GIT update from maintenance repo. As I write, the $_['summernote'] is remowed from the hu-hu.php. I use this site for test and development, thats why is updated from GIT.

"Solution: use the official 3.0.3.7 release." - Realy? This is the solution for a bug report? Nice one.... If the bug appered in the Maintenance repo, no need to fix it?

Ah.. nevermind... i already fixed it, only want to indicate the bug.
