### ISSUE TITLE
WHY!!

### ISSUE THREAD

**Issue by chulcha** [opencart/opencart#9670]
https://github.com/opencart/opencart/blob/cb78604d4265c411d0e1dd46680c9f30da2b7ada/upload/extension/opencart/catalog/controller/module/bestseller.php#L42

https://github.com/opencart/opencart/blob/cb78604d4265c411d0e1dd46680c9f30da2b7ada/upload/extension/opencart/catalog/controller/module/latest.php#L15

ATTENTION!!

https://github.com/opencart/opencart/blob/cb78604d4265c411d0e1dd46680c9f30da2b7ada/upload/extension/opencart/catalog/controller/module/featured.php#L23

**Comment by stalker780** [comment]
I have proposed to move this repeated code to thumb.php
Closed as "Not quite a valuable solution"

https://github.com/opencart/opencart/pull/8010

**Comment by chulcha** [comment]
It cannot be cured.

**Comment by TheCartpenter** [comment]
That's because the product/thumb controller was programmed a different way back then. Daniel did recently re-worked on this controller on the master branch. By comparing the variables above, it does make sense to consider that the array names should be identically named regardless of the foreach statement being used since the $product_data also becomes a parametered array into the product/thumb controller.

**Comment by TheCartpenter** [comment]
@WebkulOpencart: The master branch should be labeled for this for further reviews.

**Comment by chulcha** [comment]
As expected!
no coment.

**Comment by danielkerr** [comment]
It's not an issue.

**Comment by chulcha** [comment]
> 
> 
> It's not an issue.

And what is it?
What can you name the described code that runs in different places, but works according to the same algorithm? 

ISSUE
