### ISSUE TITLE
Bootstrap 5 Multiselect Dropdown with Checkboxes

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9685]
**What version of OpenCart are you reporting this for?**

Master Branch

**Describe the bug**
A clear and concise description of what the bug is
What section does it affect?

Manually select checkbox options checked not working in related forms, that is, json script did not insert "check" mark on checkbox when you clicked the checkbox.

Opencart 3:
![oc-3](https://user-images.githubusercontent.com/14033183/120085710-5818ef80-c0a8-11eb-9e78-6f07d0a17f4f.jpg)

Opencart 4:
![oc-4](https://user-images.githubusercontent.com/14033183/120085719-6a932900-c0a8-11eb-9a00-f3723f0a1773.jpg)
 

Either did not load JQuery and Bootstrap 5 CSS into form twig pages, or missed JavaScript code.

**To Reproduce**

**Expected behavior**

**Screenshots / Screen recordings**
If applicable, add screenshots or recordings to help explain your problem. Please keep these short and if you can, edit them to point out when/where the problem is.
https://www.useloom.com/ is perfect for screen recording with Chrome or with their desktop app

**Server / Test environment (please complete the following information):**
 - Local development? Deployed to a web server?
 - Operating system
 - PHP version
 - Apache version
 - Browser(s) tested with [e.g. chrome, safari - if applicable]

**Additional context**

**Comment by TheCartpenter** [comment]
@WebkulOpencart: This should be tagged for the master branch since this branch now involves using JS with validation forms.

**Comment by mhcwebdesign** [comment]
I am not sure whether it makes sense to report bugs for the master branch yet because it's still all work in progress. 

There are still loads of incomplete features or changes. It may make sense to wait till it reaches a public beta stage. At the moment Daniel appears to be in the middle of upgrading it all to the latest bootstrap 5 and jquery libraries, also might be still working on the json changes for the various forms.
