### ISSUE TITLE
Hot fix “insecure content was loaded over HTTPS, but requested an insecure resource”

### ISSUE THREAD

**Issue by cgcmart** [opencart/opencart#9736]
https://github.com/opencart/opencart/blob/4cfcccf58b2b83f0f8554fa184580c8a904f3faf/upload/catalog/view/template/common/header.twig#L6

before add:
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`

**Comment by mhcwebdesign** [comment]
Well, this directive instructs user agents to treat all of a site's insecure URLs (those served over HTTP) as though they have been replaced with secure URLs (those served over HTTPS).

Rather than using this one, it would be much better to actually sort out any remaining insecure requests in the OpenCart code.

**Comment by danielkerr** [comment]
Another person giving bad advice
